### ISSUE TITLE
get_rpcconfig bug

### ISSUE THREAD

**Issue by justinmoon** [cryptoadvance/specter-desktop#10]
You can specify network-specific parameters in bitcoin.conf in [sections like these](https://github.com/bitcoin/bitcoin/blob/master/share/examples/bitcoin.conf#L164).

The `rpc.get_rpcconfig` function in this project can't parse this options.

**Comment by stepansnigirev** [comment]
Ah, I didn't know about that.
Do you use some kind of ready-to-use bitcoin.conf parser in junction or you wrote one yourself?
