### ISSUE TITLE
Bug when clicking a label when it's in edit mode

### ISSUE THREAD

**Issue by statusquont** [cryptoadvance/specter-desktop#1000]
I clicked the pencil tool next to a transaction to edit a label, and then tried to double-click the default text "Address 42" in order to select-all of the text in the field so that I could overwrite the default, but when clicking on that text when it's in edit mode it tried to open my address explorer at about:blank#blocked. If I cancel out of edit-mode, the correct URL for the address explorer is linked.

**Comment by ben-kaufman** [comment]
Thanks for reporting, I didn't see that at first since I test mostly on Safari where this wasn't happening, but just noticed that with Chrome and fixed it in #1020
