### ISSUE TITLE
"Save wallet to file" escapes double quotes, rendering resulting json unusable

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#1005]
Running the latest from master.

Double quotes are escaped to `&#34;`:

```
{ &#34;label&#34;: &#34;KeepKey-BitcoinCore Hot multisig&#34;, &#34;blockheight&#34;: 671093, ...
```

Needs a `safe` and double quote filtering to yield valid json. Will be fixed alongside #948.

**Comment by kdmukai** [comment]
May address #840 once this one is fixed.

**Comment by ben-kaufman** [comment]
https://github.com/cryptoadvance/specter-desktop/pull/1007/commits/f5f425dd94702e843625a9a7eac2d30f4e16b59f

I believe I fixed it in this commit (which should've been a separate PR in retrospect...), could you please check it solves it for you?

**Comment by k9ert** [comment]
Solved in the pre-releases. Will close here, please reopen if it persists.
