### ISSUE TITLE
invalid addresses generated with nested segwit on signet

### ISSUE THREAD

**Issue by openoms** [cryptoadvance/specter-desktop#1012]
The address: `cMBeq2k7X8GM1zVxBPP1EzoBBzQdfBsoEA` is not valid.
![image](https://user-images.githubusercontent.com/43343391/110435567-141add80-80ab-11eb-8012-887e84115979.png)
![image](https://user-images.githubusercontent.com/43343391/110435610-2137cc80-80ab-11eb-8c4f-a1d4ace188f4.png)

Steps to reproduce:
* connect signet node
* generate hot wallet device
* create nested segwit wallet

**Comment by ben-kaufman** [comment]
Can confirm the issue, will work on it
