### ISSUE TITLE
disablewallet not checked after I added rpcbind and rpcallowip to bitcoind and restarted spected

### ISSUE THREAD

**Issue by oparex** [cryptoadvance/specter-desktop#1014]
I have installed specter desktop and wanted to connect to my node on another hardware server in my local network. I was not able to connect because bitcoind did not have rpcbind and rpcallowip set. 
I closed specter and corrected the bitcoin.conf and restarted bitcoind. 
I then reopened specter and it was already connected to my node indicating version and block height in the top left corner.
Welcome screen showed a checked box for "Connect Specter to your Bitcoin Core node." 
Then I clicked "Add signing devices you wish to use." in the welcome screen and I was able to see the list of all available wallets that I can import.
If however I click "+ Add new wallet" in the left menu, I get the "Configure Bitcoin Core is running with wallets disabled." message.

Clicking "Add signing devices you wish to use." should check disablewallet and produce the same warning screen.

**Comment by k9ert** [comment]
Please check for `disablewallet=0` in your bitcoin.conf. I'll close this issue for now. Please repoen if necessary.
