### ISSUE TITLE
"Addresses" -> "Verify on device" asks to plug in an air-gapped cold card

### ISSUE THREAD

**Issue by alevchuk** [cryptoadvance/specter-desktop#1016]
As a noob I was confused when on Specter Desktop I went to "Addresses" -> "Verify on device" and I was asked by to plug in an air-gapped cold card. Cold card has an Address Explorer where one can do the verification visually. Can you add a clarifying message in the "Detecting..." dialog? For example, "On air-gapped Cold Card use address explorer on the device"

**Comment by alevchuk** [comment]
Screenshot ![Screenshot from 2021-03-13 06-38-40](https://user-images.githubusercontent.com/64738/111033583-c9f56d00-83c6-11eb-825e-f894664af5a1.png)

**Comment by k9ert** [comment]
What about a text like "Only proceed if you're comfortable using USB with your coldcard". This would need to be implemented in `hwi.jinja` adding a div with the text above (hidden) and then check for the `deviceTypes` for coldcard and remove the "hidden" from the classList.

**Comment by alevchuk** [comment]
That would be great!

**Comment by moneymanolis** [comment]
This issue was resolved by #1182.
