### ISSUE TITLE
Internal error: remote error: Long"

### ISSUE THREAD

**Issue by ostermayer** [cryptoadvance/specter-desktop#1027]
This error is generated when signing a transaction with a size that exceeds the max coldcard wire protocol. I believe this is MAX_TXN_LEN of 384kb.

Perhaps the error could be more descriptive to instruct the user to attempt signing via SD card or use another device for signing.

**Comment by k9ert** [comment]
@doc-hex can we have a fix in coldcard for this?

**Comment by doc-hex** [comment]
from `public_constants.py`:

```python
# Max PSBT txn we support (384k bytes as PSBT)
# - the max on the wire for mainnet is 100k
# - but a PSBT might contain a full txn for each input
MAX_TXN_LEN = const(384*1024)
MAX_TXN_LEN_MK4 = const(2*1024*1024)
```

So on the Mk4, the max PSBT size is 2MB. 

I was not able to find "Long" as an error message in our code. We can certainly make that better, but will be hard to trigger to on Mk4.
