### ISSUE TITLE
[Suggestion] Create AUR package

### ISSUE THREAD

**Issue by sTiKyt** [cryptoadvance/specter-desktop#1028]
Are there any Arch users? AUR package would make specter-desktop much easier to install on Arch based distros

**Comment by bitcoinlizard** [comment]
I have created an AUR package:

https://aur.archlinux.org/packages/specter-desktop/

**Comment by sTiKyt** [comment]
Nice

**Comment by bitcoinlizard** [comment]
Let me know if everything works with the AUR package.  Everything seems to work correctly to me but I'm a new Specter user so I might be missing something.
