### ISSUE TITLE
Save Backup PDF for multisig : truncated Master public key

### ISSUE THREAD

**Issue by BitcoinTsunami** [cryptoadvance/specter-desktop#1035]
The PDF backup of a multisig wallet could be unusable when a master public key is truncated.

This split (in wallet_pdf.jinja) for master public key use 40 which is too large :
`.split(/(.{40})/g);`

I see two solutions :
- use a monospace font to get a constant and testable length.
- keep a sans-serif font but calibrate the split value with the widest letter (I ofen use M or W for that purpose).

If you're not aware of the sans-serif character length variance, look here : https://stackoverflow.com/questions/3949422/which-letter-of-the-english-alphabet-takes-up-most-pixels

In the case of my unusuable backup, a split of 38 with the current font should work (two characters are truncated with 40), but in the worst case with only W, it's certainly a smaller number.

**Comment by ben-kaufman** [comment]
Thanks for the suggestions @BitcoinTsunami !
I've updated it to use Roboto Mono now, and adjusted the line breaks. I think it should be fine now but would be great if you could check this too (PR #1095)

**Comment by BitcoinTsunami** [comment]
Thanks @ben-kaufman, your PR#1095 fixed my problem ! I've my backup now :)
