### ISSUE TITLE
Create new wallet crash while in IDB

### ISSUE THREAD

**Issue by torkelrogstad** [cryptoadvance/specter-desktop#1036]
Got a crash: 

<img width="816" alt="bilde" src="https://user-images.githubusercontent.com/16610775/111884716-af715400-89c3-11eb-9d45-7e67f105a3ca.png">

My node is in IBD. Tried to import a wallet from an existing HW wallet.

**Comment by k9ert** [comment]
Thank you. Which version of Specter do you use?

**Comment by torkelrogstad** [comment]
I'm on v1.2.2

**Comment by k9ert** [comment]
This is already fixed in the new upcoming version 1.3.0. Let's keep this issue open nevertheless until release.

**Comment by k9ert** [comment]
1.3.0 released. Please reopen if necessary.
