### ISSUE TITLE
No fee rate in transaction detail (incoming transaction)

### ISSUE THREAD

**Issue by donnlee** [cryptoadvance/specter-desktop#1038]
When I view an outgoing transaction detail, there is the "fee" and "fee rate".  Example: 15.7 sat/vbyte.
However, when I view an incoming transaction detail (in the same way by clicking the transaction id), the fee and fee rate are missing.
If this is easy to add, I would be willing to create a PR.  I just want to confirm it is a known behavior and understand what steps would have to be added (eg. if additional RPC requests about the inputs need to be sent to bitcoind).

My Specter: v1.1 linux .appimage

**Comment by donnlee** [comment]
Hmmm, i see Electrum is the same.  So maybe we just close this issue.  I suspect it is because the wallet knows the input amount for outgoing transactions.  For incoming transactions you don't care about the fee, or you know the fee if you were the sender (sending to yourself).
It would be a nice feature, but users can just use BTC-RPC-Explorer and their full node.

**Comment by instagibbs** [comment]
for incoming you do care if you want to CPFP it, though this would require a package feerate not just the feerate for that txn

**Comment by ben-kaufman** [comment]
The problem I think is that Bitcoin Core doesn't provide the transaction fee of received transactions, only sent, so that would complicate implementing this...

**Comment by instagibbs** [comment]
getmempoolentry has package feerate no?

**Comment by ben-kaufman** [comment]
Oh right, that should actually work for unconfirmed transactions, thanks! I'll see about adding that.
