### ISSUE TITLE
Failed to perform RBF. Error: Cannot RBF a transaction with no change output

### ISSUE THREAD

**Issue by Agnus-Castus** [cryptoadvance/specter-desktop#1039]
I don't understand why this is not possible. I have one UTXO and to safe fees I want to send the whole UTXO minus the fee. And now I want to increase the fee, but this is unfortunately not possibly. It is clear that the receiver will receive a smaller amount but this is OK since I anyway selected "Subtract fees from amount". During my research about RBF I found out it is permitted to change the output. 

Now I post this issue here as a feature request or somebody can explain me why it is not possible.

**Comment by k9ert** [comment]
Ben mentioned in the chat:

> Hi, next version (beta probably in a day or two, release probably in a week) should allow full replace edit options, so you’ll be able to use that

Does that work for you? The problem is imho that "substract from amount" is not working if you do RBF (without change-output). There is not much we can do here other then the proposed resending.

**Comment by Agnus-Castus** [comment]
This sounds really good.
