### ISSUE TITLE
Importing Multisignature transaction from Electrum Fails in Specter

### ISSUE THREAD

**Issue by kaspar-nl** [cryptoadvance/specter-desktop#1046]
I created a multisig wallet (2-of-2), create a tx, and signed the tx in Electrum, and exported the raw PSBT transaction to clipboard.
Next, I pasted the raw PSBT transaction in Specter Desktop (Send > Import) in the dedicated box and clicked on 'import transaction' and get the error "**Exception: 'dict object' has no attribute 'witness_utxo'**" (see below). So this means, I cannot sign the transaction first in Electrum and send it to somebody else so sign in with Specter.

I tried it the other way (first sign with Specter, then export the PSBT tx, and then import it by Electrum and sign) and that works fine, but that means the Specter needs to sign always first, which is not very practical. 

**Setup:**
- Electrum (Testnet) 4.0.9
- Specter Desktop v1.2.2
- Create 2-of-2 Multisign wallet 

[image](https://user-images.githubusercontent.com/40182876/112077628-e1e3a280-8bb7-11eb-9844-7f3ec2208db3.png)

**Comment by k9ert** [comment]
Seems to be related to https://github.com/spesmilo/electrum/issues/6429 which has been fixed in the meantime. Which version of electrum did you use for that? Maybe an upgrade helps?

**Comment by k9ert** [comment]
Please reopen if this is still an issue.
