### ISSUE TITLE
Coldcard from v3.2.1 and above can't sign multisig

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#1052]
Coldcard v3.2.1:
![20210324_092350](https://user-images.githubusercontent.com/934746/112329151-f2ae1a00-8c84-11eb-9371-21aeb1e1df48.jpeg)

Sounds related to #870.

Confirmed that Coldcard v3.1.9 works as expected. Fails from v3.2.1 up to current v4.0.0b4 BETA.

Tried PSBTs generated from Specter v1.2.2 and against current master (v1.3.0-pre3).

---
WORKAROUND: Revert Coldcard to v3.1.9 to sign.

---
@ben-kaufman, @stepansnigirev? This one's beyond my abilities at the moment.

**Comment by ben-kaufman** [comment]
Did you try to delete the multisig setup and re-import it to coldcard. It seems to be necessary to get the coldcard multisig working after the upgrade.

**Comment by kdmukai** [comment]
Ah, that makes sense. I'll give a try when I get the chance in the next day or so.

**Comment by bjarnemagnussen** [comment]
I just ran into a similar issue after upgrading Coldcard to v4.0.0, but with the error message `Failure Invalid PSBT multisig.py 946`.

Exporting the multisig-wallet from the Coldcard, then deleting it and afterwards importing it fixed this issue. Although the fix is straightforward I didn't think of it. Quite annoying to be honest...

**Comment by kdmukai** [comment]
@bjarnemagnussen Yeah, the line number changes depending on which version you're running on the Coldcard. I haven't had a chance to reset mine so thank you for these simple steps!

**Comment by kdmukai** [comment]
Confirmed that reloading the multisig in the Coldcard works.

Back up the multisig first:
```
Settings > Multisig Wallets > (your multisig wallet name) > Coldcard Export
```

Then from the same menu delete your multisig wallet:
```
Delete
```

It'll now display `(none setup yet)` where your multisig wallet name used to be.

Restore the multisig wallet from that screen:
```
Import from SD > (pick multisig wallet file) > (confirm "new" multisig wallet details)
