### ISSUE TITLE
Transactions Not Broadcast

### ISSUE THREAD

**Issue by dtrammell** [cryptoadvance/specter-desktop#1068]
Transactions that Specter is creating are not being broadcast by Bitcoin Core.  I have created multiple transactions using a 2/3 multi-sig wallet.  After signing the transaction with two of the keys, I tell Specter to broadcast the transaction.  I see the transaction get sent to Bitcoin Core with a log entry like this:

2021-03-29T14:49:51Z [specter[somehex]\[wallet_name]] AddToWallet [REDACTED TX ID]  new

The recipient wallet never sees the transaction and the TXID does not show up in any block explorers.  It seems like it's just not being broadcast and never enters the mempool.  I have tried multiple transactions and have waited up to multiple hours to see them show up but they don't.  Any ideas why Bitcoin Core would not be broadcasting the transactions when Specter sends them to it?

**Comment by dtrammell** [comment]
Oh also this installation of Specter, the wallets, and installation of Bitcoin Core have all worked fine in the past.  I have sent and received transactions using this setup before.  This is a new occurance as of today.

**Comment by ben-kaufman** [comment]
Hi, what fee did you put there?

**Comment by dtrammell** [comment]
Whatever fee Specter chose.  I just went to look at the transaction details to tell you exactly what the fee was and now when clicking on the transaction I get the error:

"Failed to load transaction details..."

**Comment by dtrammell** [comment]
I restarted Core thinking that might get it to rebroadcast its unconfirmed transactions.  Maybe that's why Specter can no longer see the transaction details?  I'm going to restart Specter and see if it still sees the transaction.

**Comment by dtrammell** [comment]
Oh wow, now upon restarting Specter, the wallet that I sent from is not loading. Specter says:

"Failed to load some wallets"

Details:

"Request error: Wallet file verification failed: Error loading wallet specter[somehex]\[wallet_name]. Duplicate -wallet filename specified."

**Comment by dtrammell** [comment]
The problem transaction is still listed and now I can get its info.  Fee was 567 sats (3 sat/vbyte).

**Comment by dtrammell** [comment]
The "Speed up" button suggests upping the fee to 5 sat/vbyte.

**Comment by dtrammell** [comment]
Two new log entries in Core related to this transaction:

'''
2021-03-29T15:56:38Z [specter[somehex]\[wallet_name]] Submitting wtx [REDACTED TX ID] to mempool for relay
2021-03-29T15:56:38Z [specter[somehex]\[wallet_name]] AddToWallet [REDACTED TX ID] 
'''

**Comment by dtrammell** [comment]
Transaction still doesn't show up in any block explorers.  I don't currently have access to the recipient wallet to see if it sees the transaction but I'm guessing not if none of the rest of the network sees it.

**Comment by ben-kaufman** [comment]
Fee estimation currently relies on Bitcoin Core which isn't great at it. We changed it to use mempool.space from the next version to improve that. For now Ild recommend to check the fee they suggest there. Very low fee can cause your transactions not to be propagated when fees are high

**Comment by dtrammell** [comment]
mempool.space is currently suggesting 65 sats/vbyte, so I'll try rebroadcasting with that fee rate.

**Comment by dtrammell** [comment]
Yep, that solved the problem.  Transaction was broadcast and block explorers now see it.

Thanks for the assistance and the mempool.space resource, that's useful.
