### ISSUE TITLE
1.3.0 Error: Script failed to execute

### ISSUE THREAD

**Issue by dtrammell** [cryptoadvance/specter-desktop#1070]
After installing 1.3.0 on Windows 10, upon launch, after "Fetching the Specter binary... This might take a minute..." and "Unpacking files", this error is thrown:

'''
Specter Desktop encounter an error:
Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
'''

What/where is the renderer console?

**Comment by ben-kaufman** [comment]
If you're on windows, it's likely that a specter process is running in the background (a bug that was fixed in 1.3.0), if you know how you could try to kill it from the Task Manager, and f not a restart should also work

**Comment by dtrammell** [comment]
I didn't see an icon in the app tray so I didn't think one was running, but looking in task manager there are indeed three separate specterd.exe processes running, possibly from previous instances of the app?  Killed those processes and now Specter starts as expected so that was indeed the problem.  Thanks!
