### ISSUE TITLE
Specter Desktop linux AppImage doesn't start

### ISSUE THREAD

**Issue by bernov** [cryptoadvance/specter-desktop#1071]
Hi Ben

I'm using Specter Desktop app on my linux machine (Ubuntu 18.04), but this time v 1.3 doesn't start, just getting permanent the window with "Fetching the Specter binary... This might take a minute"

**Comment by ben-kaufman** [comment]
Are you connected Tor the internet with decent connection?

**Comment by LaserHodl** [comment]
I'll try and reproduce this on a fresh install this week.

**Comment by LaserHodl** [comment]
Ok, I was able to perform a fresh install of `1.3.0` on the Ubuntu-based distro `elementary OS, 5.1.7 Hera`.

The only problem I ran into was a `Tor is already installed` error, which should probably be handled more gracefully.

Quicksync is running now: so far so good.

**Comment by bernov** [comment]
well, I have a relatively good connection, but why I need the internet connection if I starting the app image?

**Comment by LaserHodl** [comment]
Because the archive the Quicksync requires is downloaded separately from the AppImage.

**Comment by bernov** [comment]
ok guys, I closed my vpn service and tried to start the app. This time it started. Thanks both!
