### ISSUE TITLE
Handle more gracefully: Tor is already installed

### ISSUE THREAD

**Issue by LaserHodl** [cryptoadvance/specter-desktop#1072]
When setting up a brand new `1.3.0` install, Specter accurately detects that I already have Tor installed:

![Screenshot from 2021-03-29 18 47 07](https://user-images.githubusercontent.com/76824110/112922370-3fe51e00-90c1-11eb-8d2b-edd4881a7c51.png)

Instead of forcing the user to hit `Skip` to continue, why not merely continue forward when Tor is detected? That seems like a success state, not a failure state. What does the team think?

**Comment by LaserHodl** [comment]
I'm running on Linux (Ubuntu-based distro `elementary OS, 5.1.7 Hera`), but I assume this issue is present on every OS.

**Comment by ben-kaufman** [comment]
Oh it should've just skipped if installed, but I had a typo... fixing with #1084
