### ISSUE TITLE
Can't read merkle proof 'i' description dialog box

### ISSUE THREAD

**Issue by Bosch-0** [cryptoadvance/specter-desktop#1074]
Tested on windows 10, specter version 1.3.0

I am unable to read the 'more info' dialog popup for merkle proofs as it goes off screen when hovering. When attempting to scroll the dialog box closes and / or starts jittering. Another minor suggestion is to use a different color for the 'BIP 37' link, it is quite hard to read. Screenshot below:

![image](https://user-images.githubusercontent.com/55287964/112969516-e263d680-917f-11eb-929b-151941df0bcd.png)

**Comment by instagibbs** [comment]
yeah ran into this myself
