### ISSUE TITLE
Explain what 'Built in node' and its options are

### ISSUE THREAD

**Issue by Bosch-0** [cryptoadvance/specter-desktop#1075]
Just updated to the new Specter version, amazing work being done!

I'm assuming this new built in node feature is so you don't have to download core and sync it separately from Specter? It would be great if there was a description of some sorts on this screen explaining what the built in node is as well as what the two options are. I actually clicked the Switch to built-in node to see what would happen and realized Specter was no longer connected to my local core node - I received no dialog as to what went on and wasn't entirely sure how to switch back in the moment (it's not exactly hard but these things should be idiot proof, switching back should be more straightforward). 

![image](https://user-images.githubusercontent.com/55287964/112970318-a715d780-9180-11eb-9557-3bdbc130187b.png)

**Comment by ben-kaufman** [comment]
Thanks, makes sense. I guess before you setup the internal node the switch button makes 0 sense lol, so I'll hide it if none is set-up. Will also update with some description
