### ISSUE TITLE
Error: Compiled without sqlite support (required for discriptor wallets)

### ISSUE THREAD

**Issue by sstackmore** [cryptoadvance/specter-desktop#1078]
Tried to create a coldcard wallet from exported generic json as instructed.

Using latest version 1.3.0 for Mac.

Received:

Error: Failed to create wallet. Error: Request Error: Compiled without sqlite support (required for descriptor wallets)

<img width="810" alt="Screen Shot 2021-03-30 at 11 14 51 AM" src="https://user-images.githubusercontent.com/81644748/113033986-22778900-9181-11eb-8198-82ed54a37f79.png">

Unable to proceed.

This is my first attempt to use Specter Desktop.

**Comment by ben-kaufman** [comment]
Where are you running Bitcoin Core?

**Comment by stepansnigirev** [comment]
Looks like you've built Core yourself without sqlite library. You can install it and rebuild.

From Bitcoin Core [build instructions](https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md):

> SQLite is required for the descriptor wallet:
> `sudo apt install libsqlite3-dev`

**Comment by sstackmore** [comment]
Currently my bitcoin core runs on an Umbrel node. I was attempting to use Mac desktop wallet but now I see there is a specter desktop app that can be installed on the node though it is 1.2.2.  I will try that.

**Comment by sstackmore** [comment]
Can confirm that 1.2.2 running on the node itself works.

**Comment by ben-kaufman** [comment]
It was a problem with Umbrel indeed fixed with their last release. Closing this issue for now then.
