### ISSUE TITLE
Unable to retrieve BTC/USD prices over Tor

### ISSUE THREAD

**Issue by LaserHodl** [cryptoadvance/specter-desktop#1082]
With a brand new install of Specter Desktop `1.3.0`, none of the Tor price providers work.

Here is a screenshot containing the error messages stacked up after trying each and every Tor price provider:

![Screenshot from 2021-03-31 11 01 17](https://user-images.githubusercontent.com/76824110/113189996-b17fb200-9210-11eb-9c25-228a3c17c934.png)

I'm running an Ubuntu-flavored Linux `elementary OS 5.1.7 Hera`, but I suspect that is unrelated here.

Are the price providers configured to use the same Tor connection as Core? Feels like it must be a connection issue, since not a single provider is functioning.

**Comment by ben-kaufman** [comment]
If you go to Settings, Tor tab and scroll down and click Test Connection, does this work?

**Comment by LaserHodl** [comment]
No. I get an error code `127` when I run the test:

![Screenshot from 2021-04-01 18 17 27](https://user-images.githubusercontent.com/76824110/113369649-a616ae80-9316-11eb-86a9-9c79c3eb3332.png)

When I uninstall and install again I see that there is also an issue:

![Screenshot from 2021-04-01 18 17 41](https://user-images.githubusercontent.com/76824110/113369672-b62e8e00-9316-11eb-9c14-b5a78683448f.png)

I think what might be happening is Tor is failing to install to begin with, but Specter doesn't seem to catch or report it to the user. The only way I found out is through playing with the Tor prices.

**Comment by ben-kaufman** [comment]
OK I see, if you try to click "Start Tor" what happens?
Also is this version 1.3.0 or a pre-release?

**Comment by LaserHodl** [comment]
On `1.3.0` I get this when trying to start Tor after the above issues: 

```
Enabling Tor hidden service will expose your Specter for remote access.<br>It is therefore required that you set up authentication tab for Specter first to prevent unauthorized access.<br><br>Please go to Settings -> Authentication and set up an authentication method and retry.
```

**Comment by LaserHodl** [comment]
Yes, `1.3.0`, not a pre-release.

When I click "Start Tor" is says "Tor has been started". After that I get the same errors for "Test Tor Connection" and for all the Tor price providers. 

I've verified this on multiple Debian machines.

**Comment by ben-kaufman** [comment]
Maybe you have some existing Tor process running in the background occupying the same port? You can see with the task manager.

**Comment by k9ert** [comment]
> Maybe you have some existing Tor process running in the background occupying the same 
> port? You can see with the task manager.

I'm running ubuntu and for me, the internal tor is also not working when my ubuntu-tor is running.
We also have some better error-management in the newer v1.4.x. Can you upgrade and check whether this still persits?
Closing it for now, feel free to reopen.
