### ISSUE TITLE
Change bitcoin address font

### ISSUE THREAD

**Issue by GreenmanPGI** [cryptoadvance/specter-desktop#1083]
The chosen font is difficult to read. Spector should match the Bitcoin Core font.

**Comment by ben-kaufman** [comment]
Do you know what font exactly?

**Comment by GreenmanPGI** [comment]
Luke Dashjr says it is: Whatever your system defines as its default monospace font.

I think Courier might be a good option.

My concern was that the letter "l" was difficult to interpret in Spector.

Jeffrey J. Gotts
Owner
Gotts Engineering, LLC

“It is curious in how great a degree human progress depends on the individual. Humans, numbered in thousands of millions, seem organized into an ant-like society. Yet this is not so. New ideas, the impetus of all development, come from individual people, not from corporations or states. New ideas, fragile as spring flowers, easily bruised by the tread of the multitude, may yet may be cherished by the solitary wanderer.”

Fred Hoyle - 1957

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by k9ert** [comment]
Can you make that more concrete? I'm not sure what exactly is difficult to read and why and how it could be improved. Maybe some screenshots would be good?

**Comment by GreenmanPGI** [comment]
Just make sure you can tell the difference between "l" (L) and "I"(i)

**Comment by ben-kaufman** [comment]
There can be no confusing letters in bitcoin addresses.
The legacy addresses use base58 encoding, which excludes the confusing letters like lowercase L or uppercase i (and other confusing options). New address type uses bech32 which does not have confusing letters either.

**Comment by GreenmanPGI** [comment]
If that's the case it should not be a problem...but I did have some problem when I wanted to receive to my Spector multi-sig wallet. I was confused by some letter and I thought it was an "l" ... maybe I'm crazy... but on my full node the text was clear and understandable.
