### ISSUE TITLE
Desktop UI Fails to Render

### ISSUE THREAD

**Issue by dtrammell** [cryptoadvance/specter-desktop#1100]
I haven't figured out what is causing this yet but every so often, Specter Desktop will start up and its HTML(?) desktop UI will fail to render properly (see screenshot).  Sometimes restarting Specter Desktop will solve the problem and sometimes it won't...  Problem behavior is very inconsistent.

![Specter HTML Render Fail - Screenshot 2021-04-07 153950](https://user-images.githubusercontent.com/1753512/113931426-0e9ed900-97b8-11eb-98ee-1b9b12b76d20.png)

**Comment by ben-kaufman** [comment]
Hi, which OS are you using?

**Comment by dtrammell** [comment]
This is Windows 10 Pro fully patched.

**Comment by k9ert** [comment]
Interesting, this has been reported in #966 as well. Is this still persisting in newer versions?

**Comment by k9ert** [comment]
I assume that this is now solved. Please reopen if this still persists.
