### ISSUE TITLE
Same device can be imported multiple times

### ISSUE THREAD

**Issue by dzdidi** [cryptoadvance/specter-desktop#1137]
Not really really sure if this is bug or feature.

It is possible to import same device (with same keys) multiple times. It is also possible to use them as cosigners in multi-sig, in such a case:
* consigner's xpubs will be identical in the wallet info
* tx will be completely signed after the first signature

**Comment by k9ert** [comment]
It's questionable whether importing the same one should be created twice. 
Using them in a "Multisig" where effectively you create a singlesig-wallet is imho definitely a bug. We should check that the xpubs are all distinct from one another.
