### ISSUE TITLE
Macos install failing

### ISSUE THREAD

**Issue by Fonta1n3** [cryptoadvance/specter-desktop#114]
I am probably doing it wrong but when I run:
`pip install cryptoadvance.specter`
 
I get:
``` ERROR: Could not find a version that satisfies the requirement cryptoadvance.specter (from versions: none)
ERROR: No matching distribution found for cryptoadvance.specter
```

Any advice for getting it working on mac?

**Comment by ben-kaufman** [comment]
Strange, it works for me on macOS.
What python version (`python --version`) and pip version (`pip --version`) are you using?

**Comment by Fonta1n3** [comment]
python 2.7.16 and python3 3.6.3

pip 19.1.1 and pip3 20.0.2 

When I run `pip3 install cryptoadvance.specter` it installs fine but then will not run the server with python or python3 giving me `no module named crytptoadvance`.

**Comment by Fonta1n3** [comment]
Going to try and follow "what is the right way" instructions [here](https://stackoverflow.com/a/57252632) and maybe it will help my python issues.

**Comment by ben-kaufman** [comment]
Re the installation itself, AFAIK Specter works only with python 3.6 and above. I thought this was in the README but I now see it isn't, so will add it there.

Regarding running, this sounds like the pip3 isn't installed properly with python3.
Try running either:
```
python3 -m pip install --user --upgrade pip
```
Or if that doesn't help.
```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py --force-reinstall
```

And retry to install and run Specter.

**Comment by ben-kaufman** [comment]
@Fonta1n3 yeah that looks like a good guide to try too. It indeed sounds like some python/ pip installation issue.

**Comment by Fonta1n3** [comment]
Same issues after all of that. Are you on Catalina?

**Comment by ben-kaufman** [comment]
Yes I'm on Catalina, though using python 3.7.3.
Another possible thing might be failed installation/ run without `sudo`. I don't think it should be the issue, but worth trying out.

Anyway, another option I think should work is running from source like this:
```
git clone https://github.com/cryptoadvance/specter-desktop.git
cd specter-desktop
virtualenv --python=python3 .env
source .env/bin/activate
pip3 install -r requirements.txt
pip3 install -e .
```
See here: https://github.com/cryptoadvance/specter-desktop/blob/master/DEVELOPMENT.md

**Comment by stepansnigirev** [comment]
@Fonta1n3 are you still facing this problem or you were able to solve it?

**Comment by Fonta1n3** [comment]
Building from source works great :) Thanks
