### ISSUE TITLE
Can't change watching addresses

### ISSUE THREAD

**Issue by OhCrap99** [cryptoadvance/specter-desktop#1153]
When I try and update the currently watching addresses, it wont save. I have some old wallets that I was able to increase the watching address counts but I added a few Cobo devices and added a few more Cold Card Devices and the new wallets I created won't update the address count. The new wallets and multisig wallet are stuck on 20 and I when I change the number and hit "add" the page goes back to the wallet info page and no changes are saved. So right now the balance is wrong because I need a lot more than 20 addresses.

I have Specter on my Mac and it's talking to myNode. I also opened up the Specter app on myNode as well and It also won't update the watching addresses. 

I'm using multiple Cold Cards and Cobo Wallets

Thanks for the help

**Comment by OhCrap99** [comment]
Edited with more info.

Is anyone able to replicate this?

**Comment by ben-kaufman** [comment]
Hi, Specter now supports Bitcoin Core v21 native descriptor wallets, where Bitcoin Core itself is managing the addresses keypool. Does it not find transactions even if you click the rescan option? Also, what is the gap between the last tax it found and the next tax it doesn't find?
