### ISSUE TITLE
Receive/Change Addresses not showing past #19 for my main wallet

### ISSUE THREAD

**Issue by happyluckbox** [cryptoadvance/specter-desktop#1162]
Can't scroll sideways to page 2+ and cant scroll down beyond address 19. No receive or change addresses beyond that. Can generate a new receive address in the receive tab, but it won't show in the list of addresses. Not sure when this bug started happening. 

Tried importing wallet.json to another laptop, and addresses show fine.

**Comment by k9ert** [comment]
If this still persists in the newest version, can you maybe make a video or screenshots to explain better what the issue exactly is?

**Comment by ben-kaufman** [comment]
Closing, please reopen if still relevant with latest version
