### ISSUE TITLE
Label edit sometimes adds unremovable newline to label

### ISSUE THREAD

**Issue by mutatrum** [cryptoadvance/specter-desktop#1164]
Some labels have an added newline character at the end, which cannot be removed by editing the label again.

Unclear on how this happened, but specter-desktop is the only tool I use for labelling.

![image](https://user-images.githubusercontent.com/56344102/118415336-05a00200-b6aa-11eb-9571-1d3a629c8a88.png)
![image](https://user-images.githubusercontent.com/56344102/118415347-16e90e80-b6aa-11eb-8ecb-17aaeed7126c.png)

**Comment by ben-kaufman** [comment]
Hi, is it possible the screen you have is just relatively small and it line breaks because there is no space?

**Comment by mutatrum** [comment]
No, it's a 4K screen. In the inspector, you can see the line break in the data-label field at line 3, which is translated into a <br> in the span class=label further down.

![image](https://user-images.githubusercontent.com/56344102/118453417-7cafb780-b6f7-11eb-8222-434042d30a05.png)

Also, if I query the wallet through bitcoin-cli listunspent, I see the linebreak in the output:

![image](https://user-images.githubusercontent.com/56344102/118454719-f72d0700-b6f8-11eb-9480-07e3210b4a41.png)

**Comment by ben-kaufman** [comment]
Thanks, can confirm the issue, I'll work on fixing it.
