### ISSUE TITLE
MultiSig Wallets with 1 xpub from Unchained-Capital yields wrong addresses

### ISSUE THREAD

**Issue by yunier2002** [cryptoadvance/specter-desktop#1175]
Using the same info (xpub/derivation path) from Caravan backup file yields different addresses in Specter. Unchained doesn't provide the derivation path so I'm leaving that blank, other 2 signers are HW with all same info.

Attempting to create same wallet in Electrum with JUST xpubs, no derivation paths, yields correct addresses as intended from Unchained vaults.

What is different from Unchained/Electrum and Specter in the way wallets are created? Any tricks to get the correct wallet?

**Comment by ben-kaufman** [comment]
Hi, I think Unchained Capital is using legacy addresses, while specter supports only nested or native Segwit addresses

**Comment by privacybuilder** [comment]
@ben-kaufman  - Is there any desire to support legacy addresses?

**Comment by ben-kaufman** [comment]
Hi, currently no, it is not recommended to use legacy addresses at this point.

**Comment by k9ert** [comment]
Closing this as it seems to be about (unsupported) legacy-addresses.
