### ISSUE TITLE
Specter export does not contain hardware wallet type

### ISSUE THREAD

**Issue by craigraw** [cryptoadvance/specter-desktop#1176]
While the export file (created from `Wallets > Settings > Export to Wallet Software` in Specter Desktop) contains sufficient information to reproduce a wallet as a watch only wallet, it does not contain information about the type of devices used to create it.

Practically this means that users need to reimport their hardware wallet after importing this file, since there is no way to tell what kind of interface to present to the user (for example when they want to sign a transaction). This is a common support request for Sparrow users.

As a suggestion, the JSON could contain an extra field which lists the devices in the order they appear in the descriptor:
```
{
  "label": "specter-multisig",
  "blockheight": 646346,
  "descriptor": "wsh(multi(3,[ffffffff/48'/0'/0'/2']xpub...,[eeeeeeee/48'/0'/0'/2']xpub...,[dddddddd/48'/0'/0'/2']xpub...,[cccccccc/48'/0'/0'/2']xpub...))",
  "devices": ["trezor", "ledger", "coldcard", "bitbox02"]
}
```

HWI already has a standard set of names which could be adopted.

**Comment by kdmukai** [comment]
I described a similar approach here:
https://github.com/cryptoadvance/specter-desktop/issues/948#issuecomment-792299094

And implemented it in #1109 but that work is held up by some refactoring that's needed in the UI layer. Maybe I should make that PR less ambitious and at least pull out the device type and name changes into their own PR.

**Comment by craigraw** [comment]
@kdmukai Your suggestion is certainly better than mine - Sparrow could use the labels too. Would be great to see this implemented.

**Comment by ben-kaufman** [comment]
Hi, yes I agree it will be nicer with this format. @kdmukai what is the status with your PR currently?

**Comment by kdmukai** [comment]
@ben-kaufman I'll separate out the backup format changes into a smaller PR. Hopefully in the next few days.

Then I'll see where the wizard UI code is at. If it still needs refactoring, I'll take a stab at that next. That'll be a big lift.

Then it'll be easy to finally incorporate the hot wallet restore flow.

**Comment by craigraw** [comment]
Thanks, I've added support for the `devices` array in Sparrow.
