### ISSUE TITLE
Use of ["addresses"] will be deprecated in Bitcoin Core v22

### ISSUE THREAD

**Issue by Sjors** [cryptoadvance/specter-desktop#1177]
https://github.com/bitcoin/bitcoin/pull/20286

- The following RPCs:  `gettxout`, `getrawtransaction`, `decoderawtransaction`,
  `decodescript`, `gettransaction`, and REST endpoints: `/rest/tx`,
  `/rest/getutxos`, `/rest/block` deprecated the following fields (which are no
  longer returned in the responses by default): `addresses`, `reqSigs`.
  The `-deprecatedrpc=addresses` flag must be passed for these fields to be
  included in the RPC response. This flag/option will be available until v23, at which
  point the deprecation will be removed entirely. Note that these fields are attributes of
  the `scriptPubKey` object returned in the RPC response. However, in the response
  of `decodescript` these fields are top-level attributes, and included again as attributes
  of the `scriptPubKey` object. (#20286)

Replacing `['scriptPubKey']['addresses'][0]` in `wallet_send_sign_psbt.jinja` with `['scriptPubKey']['address']` seems to do the trick.

**Comment by ben-kaufman** [comment]
Thanks for the heads up, I've made this PR to check for this field when the addresses isn't found https://github.com/cryptoadvance/specter-desktop/pull/1180
