### ISSUE TITLE
Tor setup is broken (Ubuntu 20.04, pip installation)

### ISSUE THREAD

**Issue by xphade** [cryptoadvance/specter-desktop#1196]
After installing specter via pip in Ubuntu 20.04, setting up the built-in tor fails with the following error message:

> ERROR in tor_setup_tasks: Failed to install Tor. Error: [Errno 2] No such file or directory: '/home/xphade/.venv/specter/lib/python3.8/site-packages/cryptoadvance/specter/util/../../../../pyinstaller/torbrowser/tor-browser-linux64-10.0.15_en-US.tar.xz'

The whole `pyinstaller` subdirectory is actually missing. I was able to work around the error by simply downloading the archive and putting it into the given path. 

This happened to me on a native Ubuntu 20.04 install as well as on a WSL2 Ubuntu installation in Windows. I don't think it's exclusive to Ubuntu, though, because I see some people complaining about it in the Umbrel forum as well. See here: https://community.getumbrel.com/t/running-tor-on-specter/1139

-----

Another (maybe unrelated) issue: On native Ubuntu, I cannot use the built-in tor at all because after installation I'm getting an error that tor could not be started, due to returning non-zero exit code 127. I think it fails at the following function: https://github.com/cryptoadvance/specter-desktop/blob/fb64940812438601ff177fde0fe8e8910867ad0e/src/cryptoadvance/specter/tor_daemon.py#L58-L61

This only happens on native Ubuntu, however. On Windows, tor is running fine (after the workaround described above). Should I create another issue for this?

**Comment by k9ert** [comment]
Thanks for the report. I'm not sure we should support the internal tor-feature for a pip-installation. Also "distros" like mynode or raspiblitz are usually taking care of the Tor-setup and so we shouldn't.

This is currently definitely a bug but the fix might be to simply handle it more gracefully and make an error-message to suggest to use the electron-binary instead.

At least we have some workaround if people which want to use that feature. Maybe it's a reasonable way to mention that workaround in the error-message.

**Comment by aphex3k** [comment]
The same issue appears on docker based installations of specter desktop

**Comment by PLK2** [comment]
I’m running Ubuntu 20.04 and specter v1.9.4. Getting the error “Command ‘exec “/home/…….” —hash-password …….. returned non-zero exit status 127.”
Is there a fix for this?
