### ISSUE TITLE
Server error - Exception: local variable 'protocol' referenced before assignment

### ISSUE THREAD

**Issue by 03dom** [cryptoadvance/specter-desktop#1198]
Details:
Traceback (most recent call last):
  File "flask/app.py", line 1950, in full_dispatch_request
  File "flask/app.py", line 1936, in dispatch_request
  File "flask_login/utils.py", line 269, in decorated_view
  File "cryptoadvance/specter/server_endpoints/nodes.py", line 134, in node_settings
UnboundLocalError: local variable 'protocol' referenced before assignment

**Comment by zechendorf** [comment]
I am having the same issue trying to connect to a second bitcoin core.

## Summary

Trying to connect to a second bitcoin core the user gets an error when either testing the connection or saving the settings, after entering the connection credentials

## Steps to reproduce

1. Configure the first Bitcoin node
2. Click the node configuration 
3. Select `Connect a new node`
4. Choose `Connect existing node`
5. Unselect `Auto-detect`
6. Enter credentials (I have been using an onion Address for the node host)
7. Click `Test` or `Save`

## What is the current bug behavior?

A `Server Error` Message is thrown:

```
Traceback (most recent call last):
  File "flask/app.py", line 1950, in full_dispatch_request
  File "flask/app.py", line 1936, in dispatch_request
  File "flask_login/utils.py", line 269, in decorated_view
  File "cryptoadvance/specter/server_endpoints/nodes.py", line 134, in node_settings
UnboundLocalError: local variable 'protocol' referenced before assignment
```

## What is the expected correct behavior?

Testing the connection - feedback if the test succeeded or failed.

## Relevant logs and/or screenshots

(Paste any relevant logs - please use code blocks (```) to format console output, logs, and code, as
it's very hard to read otherwise.)

**Comment by ben-kaufman** [comment]
Hi, this means the URL you have entered did not start with `http://` or `https://`, adding that would make it work, but I've fixed the error by making Specter assume the protocol is `http` by default in #1199

**Comment by zechendorf** [comment]
Hey @ben-kaufman - thanks for the clarification and the extremely quick fix. I simply copied the URL my umbrel was providing, not even realizing the protocol was missing (because onion v3 addresses are so long).

I've got everything running prepending `http://` to the tor url.
