### ISSUE TITLE
UTXO and address labels missing during  backup 

### ISSUE THREAD

**Issue by nbourbon** [cryptoadvance/specter-desktop#1207]
Hi 
I created a backup through specter app in Umbrel (I also have specter desktop on my Mac connected). That created a zip file that I later on unpacked as back up

when I tried to restore from my backup folder it did bring up all my wallets and devices but none of the labels that took me a while to record

I did it twice just to be sure and it’s the same problem. Maybe this is because when backups are restored none of my UTXOs or history of transactions are available since it’s forcing me to rescan the blockchain every time and wallet by wallet?

thanks and I hope you can fix this problem that is the only thing preventing me from using Specter as my main wallet manager

**Comment by k9ert** [comment]
The labels are currently (unfortunately) only backed up if you do the backup via 
Settings --> General --> Download Specter Backup files

Did you do it like this? This is a UI/UX issue.

**Comment by k9ert** [comment]
This is no longer true. The labels are part of the individual wallet-backups as well as the backup for all wallets.
Regarding labels in general: There is currently only address labels. We need to improve on that.
Closing this issue for now as it's mainly about labels in backups.
