### ISSUE TITLE
BTC balance in multisig in specter vs electrum

### ISSUE THREAD

**Issue by fiatcentesis21** [cryptoadvance/specter-desktop#1213]
Hi, I opened my watch-only multisig wallet on specter desktop and the BTC balance differs significantly compared to the same multisig wallet on electrum. I use several coldcard devices and inputed the derivation paths and xpubs manually as new devices and then created a new wallet with the appropriate quorum. 

Any help would be appreciated.

Thank you

**Comment by k9ert** [comment]
Apart from the fixes Stepan mentioned, please check [this article](https://github.com/cryptoadvance/specter-desktop/blob/ced040751de6cea77e4943035b3d7e27568126a9/docs/faq.md#i-created-an-existing-wallets-but-even-after-rescanning-specter-couldnt-find-any-or-not-enough-funds) in the FAQ. Hopefully this helps?!

**Comment by k9ert** [comment]
Assume that this is fixed. Please reopen if necessary.
