### ISSUE TITLE
Change descriptor sometimes(?) not imported

### ISSUE THREAD

**Issue by Sjors** [cryptoadvance/specter-desktop#1214]
I just created a fresh (signet) multisig wallet, using Specter v1.4.2. When inspecting it in Bitcoin Core using `listdescriptors` I'm only seeing the receive descriptor. This causes RPC calls like `getaddressinfo` to fail on change addresses (`IsMine` is `false` and it's not inferring the descriptor). It also prevents the user from generating a PSBT (with change) from Bitcoin Core directly.

**Comment by Sjors** [comment]
In addition it causes the `"outputs"` PSBT field to be blank, and missing its `bip32_derivs` field. This makes change on device change detection more difficult.

**Comment by Sjors** [comment]
Perusing the code a bit, I think it should have imported it:

```
            self.keypoolrefill(0, end=self.keypool, change=False)
            self.keypoolrefill(0, end=self.change_keypool, change=
```

I didn't notice an error message though.

For extra robustness, I suggest making the `importdescriptors` RPC call atomically add receive and change, rather than 2 separate calls.

**Comment by stepansnigirev** [comment]
Can you try with current master branch? Should be fixed.

**Comment by k9ert** [comment]
Assume this is fixed. Feel free to reopen if that's not the case.
