### ISSUE TITLE
Begin phasing in multi-language support, especially Spanish

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#1227]
In light of the huge news in El Salvador and the fact that the Bitcoin Beach shared custody wallet uses Specter Desktop, we should start adding multi-language support (specifically Spanish, obviously) to help facilitate further adoption and safe self-custody throughout Latin America.

The rough outline using `Flask-Babel`:
* Wrap jinja template text: `<p>Hello, world!</p>` becomes `<p>{{  _('Hello, world!') }}</p>`
* Wrap python strings: `error="No device was selected."` becomes `error=_("No device was selected.")`
* Extract all wrapped text passages via `pybabel extract`
* Generate initial language file for each language
* Translator submits substitution phrases:
```
#: app/email.py:21
msgid "[Microblog] Reset Your Password"
msgstr "[Microblog] Nueva Contraseña"

#: app/forms.py:12 app/forms.py:19 app/forms.py:50
msgid "Username"
msgstr "Nombre de usuario"

#: app/forms.py:13 app/forms.py:21 app/forms.py:43
msgid "Password"
msgstr "Contraseña"
```
 _note: a blank `msgstr` will just result in the original English being passed to the user. So there's no real downside here, even if translators are slow to fill in these fields._
* The translation files are then compiled into a single resource file via `pybabel compile`.
* Subsequent updates to the English phrases will be automatically picked up by `pybabel update` without overwriting existing translations.

## Scope
It's impractical to fully translate every string in the codebase. But we can take a step-by-step approach that just focuses for now on the initial setup screens and the basic device and wallet creation, sending/receiving. Start with the core features, eventually work our way out from there.

Some example implementations also overlay language code into url structure (e.g. "/en/home" vs "/de/home"). Not sure if this is important enough or makes sense for the initial implementation.

The effort to get this multi-language support in place is largely front-loaded; once the strings are wrapped it's trivially easy for Babel to generate a new translation file for each subsequent language we want to support.

Eventually it might make sense to have two automated hooks. One to run the `pybabel update` on each new commit. Then another to run `pybabel compile` whenever a translator commits an update to a translation file.

## Implementation
I would very much like to take this on and get a basic skeleton up quickly. I don't think we'll have any trouble sourcing Spanish translators to help us fill out the translation file. New code being worked on in parallel need not take any of this into account; we'll just wrap any new text later.

**Comment by kdmukai** [comment]
FYI - work-in-progress branch here:
https://github.com/kdmukai/specter-desktop/tree/babel_integration

I have recruited translators for Spanish and French, eager to add more.

**Comment by fabriciogmatos** [comment]
Hi, I'm working on the Brazilian Portuguese translation file.

**Comment by k9ert** [comment]
Wohooo, great to see all these languages. This is now rolled out with v1.5.0. I'll close this issue.
