### ISSUE TITLE
use satoshi on send pages

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-desktop#123]
*From the Telegram discussion*

Use satoshis, because floats are bad.
To improve the UX we can add a note under the amount that recalculates satoshis to BTC.

Also "Sending 3.856e-05 BTC to bc1....." doesn't look right.

**Comment by ben-kaufman** [comment]
You can assign that to me.
I'm thinking if we should maybe do a radio button option between that, or maybe in the settings allow selecting unit for the entire wallet. What do you think?

**Comment by stepansnigirev** [comment]
I think a radio button between BTC and satoshi makes sense, with default to satoshi. Maybe use two inputs with one of them hidden? Backend should always look at the satoshi input to avoid floating point errors.

I also suggest to put value in another unit below the input as well, something like:

<img width="519" alt="Screenshot 2020-05-09 at 13 01 27" src="https://user-images.githubusercontent.com/1706012/81471976-607c5f00-91f5-11ea-9035-9bfaef45f4d4.png">

**Comment by ben-kaufman** [comment]
I was looking at the code, and since Bitcoin Core expects a BTC denominated amount (not sats) to create PSBT it seems better to keep using that in the backend, as if we'll use sats we'll need to convert it to BTC anyway...
