### ISSUE TITLE
"Encountered an error..." when trying to setup Tor via Umbrel (v1.4.3)

### ISSUE THREAD

**Issue by dxugy** [cryptoadvance/specter-desktop#1233]
<img width="753" alt="Screen Shot 2021-06-14 at 11 34 21 PM" src="https://user-images.githubusercontent.com/85919461/121993429-11deb400-cd69-11eb-8057-3eff59cac91b.png">

**Comment by ben-kaufman** [comment]
Hi, Umbrel already has Tor setup so you don't need from Specter.
