### ISSUE TITLE
Incongruents messages configuring Tor

### ISSUE THREAD

**Issue by antonvier** [cryptoadvance/specter-desktop#1252]
Hi. I was testing the configuration via Tor, when I clicked the "test" button I got three incongruous responses.
  the first (in blue) was:

  Tor requests test completed successfully!

then (in red);

Failed to make test request over Tor. Error: Tor daemon files missing. Make sure Tor is installed within Specter
Tor daemon files missing. Make sure Tor is installed within Specter

My OS is MX-linux, and I have Tor installed, I haven't installed the buit-in, I think that's the reason for the problem, am I correct?

It seems the installation works correctly, wouldn't it be the case to fix these messages if you don't use Specter's built-in Tor?

Grateful for your splendid work!

**Comment by ben-kaufman** [comment]
Hi, I think we had an issue with the Tor test which we now fixed, so next version it should be fine already.

**Comment by antonvier** [comment]
Issue fixed in new release. Thanks!
