### ISSUE TITLE
cobo to keystone update

### ISSUE THREAD

**Issue by riannom** [cryptoadvance/specter-desktop#1257]
Updated my devices from Cobo Vault to Keystone in the 1.4.6 Specter GUI.

It seems that some of my preexisting multisig wallets still show the Cobo icons when viewing the settings for the multisig wallet.  

Additionally when I export my multisig wallet in JSON format, half the devices show "keystone" correctly in the .json file while the other half still show "cobo" even though I have updated all the devices in the specter GUI 'device' sidebar to type "keystone".

**Comment by k9ert** [comment]
Leaving the corresponding PR #1237 here for convenience.
