### ISSUE TITLE
Fatal Error when trying to save a fully signed transaction as pending rather than broadcasting. 

### ISSUE THREAD

**Issue by NyamiDev** [cryptoadvance/specter-desktop#1260]
Hi,

Similair issue found here but closed as Ben K was unable to reproduce:
https://github.com/cryptoadvance/specter-desktop/issues/1063#issue-842849555

I am running Specter as a Webapp on MyNode on Firefox. I love it by the way and thanks for a great product. Cheers!

I like to save fully signed transactions to send when suitable. They still show up as fully signed when you go past the fatal error page, so it works underneath the hood but the error screen is a bit unnerving.

Please see screenshot attached. 

**Running MyNode version 0.2.37
Running Specter version v0.21.1**

![for spec when saving transaction to pend](https://user-images.githubusercontent.com/79112446/124347188-8af05f00-dbe3-11eb-8686-9ee6db351e2b.png)

Not tested on desktop software.

All the best and thank you.

Cheers,

Nyami

**Comment by ben-kaufman** [comment]
Hi, thanks for reporting. I can confirm the issue and have opened a PR that fixes it.

**Comment by NyamiDev** [comment]
Hi,

Thank you, best of luck.

Nyami

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
