### ISSUE TITLE
HWI bridge (miniapp)

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-desktop#131]
Hi fellows!
I started writing a miniapp that works purely with HWI. It is pretty much in progress and I would like to discuss it before I go too deep into that.

Here is the link to the app https://github.com/stepansnigirev/hwibridge

The app is not relying on Bitcoin Core and any Specter logic. It works only with HWI and it is fully stateless. It detects devices, parses PSBT, and allows you to sign transactions with relevant hardware wallets. But I am reusing all `static` files of Specter and HWI code as well. So it makes sense to merge it into specter repo when it's ready. I also started playing with [eel](https://github.com/samuelhwilliams/Eel) there, it might be a good way to pack the app into a single binary.

The idea I have is to make a stand-alone app that can be used in two different use-cases:

- Airgap your USB hardware wallets. You can use it on your air-gapped laptop, scan PSBT from Specter on your online machine, sign with hardware wallets and display signed PSBT as QR code as well. Also should work with files transferred over SD card. So both Ledger and Trezor get airgap properties of Specter or Coldcard if you connect them to a cheap 100$ air-gapped laptop.
- Work as a bridge to HWI on your local machine. If Specter is running in the cloud or node-in-the-box, but you can't connect hardware wallets to that machine, you can run this as a bridge and allow certain domains to access HWI api over localhost. 

The second use case is actually my case - I can't run a full node at home because my internet is very shitty, so I run Specter on a cheap VPS. But then I can't use USB hardware wallets, and that's sad. So this bridge would help me. I know that I can configure Specter to talk to remote Bitcoin Core node, but due to large number of requests it is pretty laggy - so for the best performance Specter should run on the same machine as Core. 

The questions are:
- should it be in a separate repo or in Specter?
- what functionality can we move to the bridge and how to integrate remote bridge in Specter?
- what should the user be able to do in the bridge interface?
- what do you think about eel?

Related to https://github.com/cryptoadvance/specter-desktop/issues/37

**Comment by ben-kaufman** [comment]
The second use case sounds very important, I didn't know it's not working now. I was actually also thinking of another feature which I think would be good to have but apparently would require that too (basically allowing Specter server to have multiple users and accounts - but that's a discussion for a different issue). So in general making it a mini-app sounds great.

- I think if that's a standalone app it deserves a repo of its own :) (though it actually depends on the answer to the next question).
- I'm wondering about that too. One option would be to move all HWI logic from Specet to the mini-app and have Specter run it in the background by default. Then at every HWI call Specter does it will make a popup with an iframe opening the HWIBridge url with its screen and stuff - then if it's on the same machine it'll use the default one, but if it's on a different machine it will get the local one (right?). I'm absolutely not sure if that's good/ feasible/ make sense though.
- I'd say that probably everything the HWI tool is capable of. I think this question mostly depends on the previous one though, so it would make sense to discuss the former first.
- Eel looks really cool! I need to look at it further but seems very handy.

**Comment by stepansnigirev** [comment]
Users and accounts look interesting. The only problem with it is that whoever controls the server knows the balances... On the other hand, Electrum wallet or Blue wallet also know the balances, and people are fine with that :) 
If we have users and accounts we could even run Specter in a cloud for people to try it out!

Coming back to the hwi bridge:
- if it has its own repo we will have a problem with shared files, unless we make ui toolkit with all js, images and css files as a submodule for both. HWI bridge can be an optional dependency for Specter.
- in principle, we don't necessarily need iframes - we could make API calls from javascript to localhost. The idea is to enable CORS in HWI bridge for particular domains / ip addresses, then I can whitelist my Specter domain to access HWI, but other websites will not be able to do it. Iframes don't work because HWI bridge is stateless - it doesn't know about address labels and wallets, so it can't display full information about the transaction, but Specter can.
- Yeah, I looked at HWI-QT and... started writing this app... I think we can wrap all functionality of the HWI into a nice GUI and a bridge for web wallets.
- Eel is nice but requires Chrome to be installed. It also can run with Edge and Firefox, but I didn't test it. Probably the best way is to try all browsers until we find a working one :)

**Comment by ben-kaufman** [comment]
I'll open a new issue to discuss the accounts idea :) In general, I was mainly thinking of it as a way to share your setup with close friends and family, since running a node is not so trivial (for now at least), but sharing with someone you trust seems like a good compromise to me in terms of privacy, security, and usability.

- I don't have a strong opinion right now about opening a new repo for that, so if you think it makes more sense we can start that in the Specter repo and after making some progress reconsider if it makes more sense to leave it in the same repo or not.
- I was just thinking of iframes as a way to connect the HWIBridge GUI with Specter's without having to leave Specter. I don't think that contradicts the approach of making API calls to the HWIBridge as you described. We can at least start without that though and maybe see later...

**Comment by stepansnigirev** [comment]
I agree with you. Many things are still uncertain and we will figure them out during development :)

I will keep working on it and prepare a PR when it has at least minimal functionality that we already use in Specter. Then we can discuss how to integrate them together.

**Comment by stepansnigirev** [comment]
Implemented in #143
