### ISSUE TITLE
Development install fails to find bitcoin core

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1312]
I want to test a modified version of specter and followed  [DEVELOPMENT.md#how-to-run-the-application](https://github.com/cryptoadvance/specter-desktop/blob/master/DEVELOPMENT.md#how-to-run-the-application).
`python3 -m cryptoadvance.specter server --config DevelopmentConfig`

Specter does indeed start. However it is disconnected of BitcoinCore running on the same PC (ubuntu) and cannot find it (`/home/<user>/.bitcoin/.cookie`). 

```INFO in server: Initializing Specter
[2021-07-18 09:11:30,361] ERROR in node: connection of <Node name=Bitcoin Core fullpath=/home/<user>/.specter_dev/nodes/default.json> is None in check_info
[2021-07-18 09:11:30,361] ERROR in node: connection of <Node name=Bitcoin Core fullpath=/home/<user>/.specter_dev/nodes/default.json> is None in check_info
[2021-07-18 09:11:30,361] INFO in wallet_manager: Specter seems to be disconnected from Bitcoin Core. Skipping wallets update.
```

**Comment by k9ert** [comment]
That's quite unusual. However, the developmentConfig also changes the specter-directory to `~/.specter_dev`. This is probably new and should create an initial configuration which does autodetect but in your case this seem to not work. Can you double-check your configuration?
Also i've to admit that the logging is a bit misleading here. We need to imrpve that. Not being connected should imho be no longer considered as `ERROR`.

**Comment by relativisticelectron** [comment]
Thanks for answering. I knew that it would change the directory to `~/.specter_dev`, and my error was to simply copy over the `~/.specter` to `~/.specter_dev`. This led to the error. When I delete `~/.specter_dev` it detects the bitcoin node. 

This leads to the question why simply copying `~/.specter` to `~/.specter_dev` leads to this error.

**Comment by relativisticelectron** [comment]
Ok I managed to port the configuration from `~/.specter` to `~/.specter_dev` by copying over the folders `devices` and `wallets`.

**Comment by k9ert** [comment]
Yeah, that's a good point. Would be cool if that's possible. There are some absolute path-namnes in there i guess. Never did that but also never needed it in the first place.
