### ISSUE TITLE
Install BTC Full Node Data on external Drive

### ISSUE THREAD

**Issue by simon2207** [cryptoadvance/specter-desktop#1313]
Hello Everyone,

would it be possible to add a custom data path for BTC Core within the first run of Specter?

Right now you could choose between pruned and full node on the same machine within the
default data path - but what if you did not have much space on the internal drive and would
like to install das BTC Core Node Data on an external Drive connected to the same Machine?

Would make life so much easier - right now I m downloading Bitcoin Core - and after that I have
to handle JSON RPC Stuff with User and Password Stuff - and I couldn't find good guides for that
as well - so any unexperienced user would stop here and give up...

Many thanks and kind regards
Simon

**Comment by k9ert** [comment]
I'm not sure i get your equest. Can't you do that already?
![image](https://user-images.githubusercontent.com/117085/126144353-a4106d8d-cebb-4f16-83ae-8cd0e5511912.png)

**Comment by simon2207** [comment]
Yeah - I can do that... but I had some issues with that - so I switched to download BTC Core... and now I m stuck with JSON RPC Stuff... and could not connect Specter to my BTC Core Node on the same machine - but on an external drive... I wrote something on your Telegram Channel - but got no feedback yet.

**Comment by simon2207** [comment]
Tried that again - doesn't work - Specter writes everything to my internal drive... Used my external drive in the Bitcoin Core Data directory path - but there seems to be an issue within Specter

**Comment by k9ert** [comment]
Ben just fixed the issue (still needs merge + release). But you also wrote in the chat:

> tried that way again - now Specter Overwrites my Data on the external Drive... 2 Days of BTC Core Sync gone - and the 
> best ... Specter will not write BTC Node Data to the external Drive... it start writting everything to the small internal drive 
> again - thats an issue.

That's a bit contradicting. You should not enter an existing directory into "Bitcoin Core datapath directory" or at least be aware that this folder will be erased (There should be a warning but isn't currently, will make a request on the PR).
However, if that feature didn't work in the first place, how could have deleted it data on the external drive? I'm just asking to clarify, there might be another issue?

**Comment by simon2207** [comment]
Hi - that sounds perfect - many thanks - there is no other issue - the second part was my fault... ;-) Great to hear that Ben fixed it. 
In the meantime I got a new internal SSD with plenty of space and downloaded BTC Core again - and hooked up Specter to it - everything working now. 

Many thanks - and I hope other people will not run into that issue with an external drive after the fix.
