### ISSUE TITLE
I cannot use my trezor by usb with version v1.5.0

### ISSUE THREAD

**Issue by oxhak** [cryptoadvance/specter-desktop#1319]
When I click on 'Get via USB' to get my keys or 'test connection' in usb settings, nothing happen, I had to go back to version v1.4.6 for it to work again. My udev rules are ok, so I don't know how to debug this and help here, I just let you know.

**Comment by Brice123456789** [comment]
Same problem here.

Specter v1.5.0
Ubuntu 21.04 and 20.04.
Trezor and Bitbox02.
I verified the udev rules and the related configuration.
**Nothing** happens when the button "Get via USB" is clicked.

Works with v1.4.6.

**Comment by k9ert** [comment]
I tried to reproduce this with a Dev-setup and an AppImage setup and was not able to. Both, "Test Connection" and "Get via USB" worked for me. You're talking about a Local-USB setup, right? I also did a HWI-based transaction (all with trezor) and also didn't have an issue.

Can you maybe have a look in the logs and maybe also check the console in the developer-tools of your browser while clicking?!

**Comment by oxhak** [comment]
Maybe you can reproduce with the release specter_desktop-v1.5.0-x86_64-linux-gnu.tar.gz, that's what gave me this issue.

**Comment by k9ert** [comment]
> Maybe you can reproduce with the release specter_desktop-v1.5.0-x86_64-linux-gnu.tar.gz, that's what gave me this issue.

Yes, that's what i did. So you're using Linux as well or Mac? Maybe you can use the hwi-cmdline? Please check my other questions. We definitely need more information here. I've seen two people in the the chat complaining as well, so this is definitely worth looking into much further.

**Comment by oxhak** [comment]
Sorry I deleted my previous message because I saw you tried it, anyway, I found these error on the dev tools console:

First line:  when I go to settings tab
Second and Three line: when I click on USB peripherals
Last line: when I click on test connexion

```
hwi:1648 Uncaught SyntaxError: missing ) after argument list
hwi:2010 Uncaught SyntaxError: Unexpected identifier
hwi:2420 Uncaught SyntaxError: missing ) after argument list
hwi:2410 Uncaught ReferenceError: testHWIConnection is not defined
    at HTMLButtonElement.onclick (hwi:2410)
onclick @ hwi:2410
```

**Comment by k9ert** [comment]
Copying from the chat:
```
Ox HaK, [27.08.21 19:09]
First line: when I go to settings tab
Second and Third lines: when I click on USB peripherals
Last line: when I click on test connexion

Stepan Snigirev, [27.08.21 19:13]
Works well for me, also found testHWIConnection in the code...
What version does Specter show at the bottom of the left sidebar?

Ox HaK, [27.08.21 20:36]
[In reply to Stepan Snigirev]
v1.5.0 or v1.5.1, can't remember, will try again with latest version to see
```
Is this still an issue? It might has something to do with the babel-translation. There are some quite ugly lines in `hwi_settings.jinja`. So if it's still an issue, can you compare this screenshot with what you're seeing?
![image](https://user-images.githubusercontent.com/117085/131498774-c1e1f4dd-2e88-4ce2-ae20-c63b2495c884.png)
Have a very close look at the 3 steps at the very bottom!

**Comment by oxhak** [comment]
I updated to version 1.6.0, I had the same problem, I was in French, I had to insist on going back to English, and there I have the detection of the USB that is working , so this occurs when using a language other than English.

**Comment by kdmukai** [comment]
I can confirm that it is a babel + FR issue. Working on a fix now.
