### ISSUE TITLE
bitcoin.conf setup: one setting missing new line character 

### ISSUE THREAD

**Issue by jeffthibault** [cryptoadvance/specter-desktop#1324]
https://github.com/cryptoadvance/specter-desktop/blob/d71e48d18d3aaef6d9af1546464b15566c3dd8e4/src/cryptoadvance/specter/util/bitcoind_setup_tasks.py#L136

I noticed this while looking through the code but not sure if it's an issue. All the others start with a new line character but this doesn't.

**Comment by ben-kaufman** [comment]
Yes this looks like an issue, would you like to open a PR to fix that?

**Comment by jeffthibault** [comment]
Yeah, I'll open one
