### ISSUE TITLE
can't log in to specter desktop 15

### ISSUE THREAD

**Issue by jkariv** [cryptoadvance/specter-desktop#1327]

**Comment by k9ert** [comment]
This might be a duplicate of #1320 which is fixed but not yet released. As a workaround, try to restrict your browser to only use english language.

Alternatively, you can fix it yourself (if you don't use the App) via replicating this fix:
https://github.com/cryptoadvance/specter-desktop/commit/e24a75dbd35342b3c16af72540beb4377bd055a2

**Comment by k9ert** [comment]
Fixed with `v1.5.1`. Closing.
