### ISSUE TITLE
Unable to change Transaction Label on Firefox Kubuntu

### ISSUE THREAD

**Issue by ChineseGeek** [cryptoadvance/specter-desktop#1331]
Using Specter Desktop v1.5.0 im unable to change the label of a transaction, after clicking the pencil, i try to clic on "Address" but nothing happens, so i have to clic Update or Cancel again. Using Chromium on the same machine im able to change the label, so it seems to be a problem with Firefox.

Firefox v90.0
Chromium v92.0.4515.107
Kubuntu 20.04

**Comment by k9ert** [comment]
The edit-mode of labels is not very UX-friendly. I just tested with ubuntu 20.04.2 LTS (Focal Fossa) and firefox 91.0.2 (64-bit) and that seem to work fine.
Maybe you can upgrade your firefox? Another way would be to open the Web developer tools (CTRL-Shift-I) and check whether you see any issues in the console-tab.

**Comment by k9ert** [comment]
I'm closing this for now. Don't hesitate to reopen it, if this issue persists.
