### ISSUE TITLE
Stuck on "Launching Specter Desktop" Windows10

### ISSUE THREAD

**Issue by winney123** [cryptoadvance/specter-desktop#1335]
Trying to install and run Specter Desktop V1.50.
Stuck on constant PacMan-screen showing "Launching Specter Desktop"

Processor	Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz   1.90 GHz
Type systeem	64-bits besturingssysteem, x64-processor
Editie	Windows 10 Pro
Versie	21H1
Build van besturingssysteem	19043.1110
Antivirus: Defender + Malwarebytes

**Comment by k9ert** [comment]
We're aware that the troubleshooting is not very good for these type of issues. Therefore we did some improvements up from v1.6.1. Please try again with this version. Should be released in a couple of days or, if you're doing testing,  you can also use the pre-release:
https://github.com/cryptoadvance/specter-desktop/releases/tag/v1.6.1-pre15

**Comment by bitcoin-eagle** [comment]
Usually when I get stuck on startup in Windows there is a process "specterd" and if I kill it I can start specter successfully.

**Comment by IanMichaelHarper** [comment]
> Usually when I get stuck on startup in Windows there is a process "specterd" and if I kill it I can start specter successfully.

I'm still experiencing this issue but @bitcoin-eagle's solution here fixed it
