### ISSUE TITLE
Restore wallet with label

### ISSUE THREAD

**Issue by enveight** [cryptoadvance/specter-desktop#1336]
Is it possible to restore a wallet (and all labels) created on Specter Desktop on another machine?
In “Settings” -> “Export”, the only option to export wallet is through the descriptors, which do not store the labels.

**Comment by ben-kaufman** [comment]
Hi, if you download everything from the general settings tab (at the top there's a download all wallets option), it should have all the labels there.

**Comment by enveight** [comment]
It worked. Thanks for the quick reply.
