### ISSUE TITLE
We could not check your password, maybe Bitcoin Core is not running or not configured?

### ISSUE THREAD

**Issue by n-i-e-n-o** [cryptoadvance/specter-desktop#1341]
Login with app and browser not possible. 

Error: We could not check your password, maybe Bitcoin Core is not running or not configured?

Specter 1.5.1 
Raspiblitz 1.7.0
macOS 11.5.1

**Comment by ben-kaufman** [comment]
Is Specter running in the RaspiBlitz or just connected to its Bitcoin Core?

**Comment by n-i-e-n-o** [comment]
Specter is running in the RaspiBlitz.

**Comment by behodl** [comment]
I'm having the same issue with Raspiblitz 1.7.0 after updating to Specter 1.5.1.

**Comment by shawnyeager** [comment]
Same here after upgrading to 1.5.1 on Raspiblitz 1.7.0. 

![Screen Shot 2021-08-13 at 5 39 33 PM](https://user-images.githubusercontent.com/980297/129391746-8a88cda5-d8c1-4505-8f65-d322ea6bc58d.png)

Uninstalling Specter, then reinstalling from raspi's menu installs 1.3, which runs, but attempts to upgrade result in the same error.

**Comment by nortwood** [comment]
Same issue after update on Raspiblitz. Should I attempt to roll it back, or?

**Comment by behodl** [comment]
As @shawnyeager said, uninstall then reinstall from the raspi menu and run 1.3

**Comment by nortwood** [comment]
Thanks. I was a bit frantic somehow missed that. Rolled back to 1.3 and have access again.

**Comment by k9ert** [comment]
TBH, not sure what has caused it. Will close this issue, don't hesitate to reopen again.
