### ISSUE TITLE
Scanning QR Codes does not work windows 10 Failed to load module script

### ISSUE THREAD

**Issue by mccolister1017** [cryptoadvance/specter-desktop#1365]
hello the QR code scanner dosen't work on windows 10 what's wrong .

![qr](https://user-images.githubusercontent.com/36525169/130883894-0444fb82-7e7c-4c89-9972-328a2962f978.png)

Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec. 25441/static/qr/qr-scanner.min.js:1 

my camera is ok works perfectly with other software 
﻿
​

**Comment by k9ert** [comment]
Can you check this: https://github.com/cryptoadvance/specter-desktop/issues/705#issuecomment-740413757

**Comment by k9ert** [comment]
I'm closing this for now. Don't hesitate to reopen if necessary.
