### ISSUE TITLE
Cannot sign multisig using coldcard

### ISSUE THREAD

**Issue by dylanseago** [cryptoadvance/specter-desktop#1373]
When trying to sign a 3of5 p2wsh transaction generated by specter and saved to a micro SD to sign on a Coldcard Mk3

```
Failure
XPUBs in PSBT do not match any existing wallet.
```

The PSBT signs successfully using a Trezor but not the Coldcard.

I've verified that the xpubs shown in specter match the xpubs in the json originally exported from the coldcard, and those match the multisig wallet file generated by specter and imported into the coldcard. I can also use the coldcard address explorer to derive the same addresses as I'm seeing on specter. The master xfp in specter and all of the exported files matches the identity shown on the coldcard, including in the psbt itself. All the derivation paths are `m/48'/0'/0'/2'` and are correctly exported, including in the psbt itself.

I've looked for any possible discrepancy that could be causing a mismatch and haven't found any.

Is specter compatible with the latest coldcard firmware for multisig signing?

Specter v1.5.1
Coldcard Mk3 firmware v4.1.2

**Comment by k9ert** [comment]
I can confirm a bug, but not the same one. I tried to sign a 2/4 multisig which works fine with 3.1.9 but not with 4.1.2: 
```
Failure
Invalid PSBT
multisig.py:948
```
Very similiar after downgrading to 4.0.2:
```
Failure
Invalid PSBT
multisig.py:946
```
However, after deleting the multisig and recreating the multisig-wallet again with the very same multisig-file, it worked. It also worked again after upgrading to 4.1.2 again.

Can you try to recreate on your side as well?

**Comment by p-bateman** [comment]
You probably already took a look at this thread but this one helped me with a cold card multi sig problem (although my account number / derivation path wasn't 0): https://github.com/cryptoadvance/specter-desktop/issues/1205

Sorry I'm not super tech savy but thought I'd post this anyway as it fixed my error ;)

**Comment by k9ert** [comment]
I'm closing this issue for now. Feel free to reopen. Would be helpful if you can post here your solution/workaround.
