### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'balance'

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#138]
On behalf of a User in the chat: While creating a new wallet with Core 0.19.1 (Linux Mint) 

```
python3 -m cryptoadvance.specter server
 * Serving Flask app "cryptoadvance.specter.server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:25441/ (Press CTRL+C to quit)
DEBUG=False
127.0.0.1 - - [21/May/2020 08:47:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/May/2020 08:47:18] "GET /static/styles.css?19689060875545653246284764249693 HTTP/1.1" 200 -
DEBUG=False
127.0.0.1 - - [21/May/2020 08:47:20] "GET /new_wallet/ HTTP/1.1" 200 -
127.0.0.1 - - [21/May/2020 08:47:20] "GET /static/img/simple_icon.svg HTTP/1.1" 304 -
127.0.0.1 - - [21/May/2020 08:47:20] "GET /static/img/multisig_icon.svg HTTP/1.1" 304 -
DEBUG=False
127.0.0.1 - - [21/May/2020 08:47:22] "GET /new_wallet/simple/ HTTP/1.1" 200 -
DEBUG=False
127.0.0.1 - - [21/May/2020 08:47:32] "POST /new_wallet/simple/ HTTP/1.1" 200 -
DEBUG=False
127.0.0.1 - - [21/May/2020 08:47:50] "POST /new_wallet/simple/ HTTP/1.1" 200 -
127.0.0.1 - - [21/May/2020 08:47:53] "POST /new_wallet/simple/ HTTP/1.1" 302 -
[2020-05-21 08:47:54,145] ERROR in app: Exception on /wallets/simple_9/ [GET]
Traceback (most recent call last):
  File "/home/corey/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/corey/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/corey/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/corey/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/corey/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/corey/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/corey/.local/lib/python3.6/site-packages/flask_login/utils.py", line 269, in decorated_view
    return func(*args, **kwargs)
  File "/home/corey/.local/lib/python3.6/site-packages/cryptoadvance/specter/controller.py", line 368, in wallet
    if wallet.balance["untrusted_pending"] + wallet.balance["trusted"] == 0:
AttributeError: 'NoneType' object has no attribute 'balance'
127.0.0.1 - - [21/May/2020 08:47:54] "GET /wallets/simple_9/ HTTP/1.1" 500 -
```

**Comment by inpharmaticist** [comment]
My entire bitcoin.conf file (if it helps):

rpcuser=user
rpcpassword=password
server=1
deprecatedrpc=size
peerbloomfilters=1
disablewallet=0

**Comment by k9ert** [comment]
I've created a new PR which contains some improvements on the logging side on #139 . This won't fix it but it should give a better idea what's wrong. Can you install it like this:
`python3 -m pip install --index-url https://test.pypi.org/simple/ --no-deps cryptoadvance.specter`
After you've started up, please also check the (hopefully) green ticks in the settings-menu after clicking the test-button.
![image](https://user-images.githubusercontent.com/117085/82753077-31541900-9dc3-11ea-8cd0-5cb66fd6f6bc.png)

**Comment by inpharmaticist** [comment]
This is what I got

> python3 -m pip install --index-url https://test.pypi.org/simple/ --no-deps cryptoadvance.specter
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://test.pypi.org/simple/
Requirement already satisfied: cryptoadvance.specter in ./.local/lib/python3.6/site-packages (0.3.1)

Now it stops at
>python3 -m cryptoadvance.specter server

**Comment by k9ert** [comment]
I'm not sure why it's no longer starting as the command effectively did nothing (forget another switch but more to that later).
If you say "Now it stops at ...", then it's nevertheless spitting out some log-files, right? Can you please always include the logs? If it really stops there and it's not logging anything, then please in that case press "Ctrl-C" and it should definitely abort AND spit out some logs.

Anyway, please do this (and try again):

> python3 -m pip install --upgrade --index-url https://test.pypi.org/simple/ --pre cryptoadvance.specter

**Comment by inpharmaticist** [comment]
No, there were no log files. It simply said "aborted!"

Tried the first command and got
>python3 -m pip install --upgrade --index-url https://test.pypi.org/simple/ --pre
Defaulting to user installation because normal site-packages is not writeable
ERROR: You must give at least one requirement to install (see "pip help install")

**Comment by k9ert** [comment]
You forgot the "cryptoadvance.specter" at the end of the command.

**Comment by inpharmaticist** [comment]
Oops, pasted as two lines. Did it correctly this time.

![image](https://user-images.githubusercontent.com/49789899/82931134-45228b00-9f3b-11ea-89d6-8260e05b8617.png)

Working slower now. Tried making a wallet. Tried deleting specter wallets and making a new one. Still doesn't work. 
![image](https://user-images.githubusercontent.com/49789899/82931306-95015200-9f3b-11ea-869a-895a139f16dc.png)

Log:
https://pastebin.com/s6RGAQ1f

**Comment by ben-kaufman** [comment]
This seems suspicious. The logs are filled with this error, but it seems like connecting the node itself is working according to the test. 
`[2020-05-26 10:18:33,087] ERROR in logic: can't load wallets: HTTPConnectionPool(host='192.168.0.27', port=8332): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fec5a998080>, 'Connection to 192.168.0.27 timed out. (connect timeout=30)'))`

**Comment by k9ert** [comment]
Also specter created lots of wallets on bitcoin-core which disappeared for some reason. This happens on my dev-env when i'm e.g. resetting my node completely. 
Is your node ok? It's imho worth checking the logs of Bitcoin-Core as probably your node is somehow in trouble.

**Comment by inpharmaticist** [comment]
> This seems suspicious. The logs are filled with this error, but it seems like connecting the node itself is working according to the test.
> `[2020-05-26 10:18:33,087] ERROR in logic: can't load wallets: HTTPConnectionPool(host='192.168.0.27', port=8332): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fec5a998080>, 'Connection to 192.168.0.27 timed out. (connect timeout=30)'))`

That was a mistake on my part. I was trying to connect to my raspiblitz but I reconnected after that to localhost.

**Comment by inpharmaticist** [comment]
> Also specter created lots of wallets on bitcoin-core which disappeared for some reason. This happens on my dev-env when i'm e.g. resetting my node completely.
> Is your node ok? It's imho worth checking the logs of Bitcoin-Core as probably your node is somehow in trouble.

I deleted all the old wallets, as was recommended by someone in the telegram group.

**Comment by k9ert** [comment]
We have a new version v0.4.3. Can you please upgrade and check whether the issue still persists. I'm still puzzled why this is happening for you, so let's maybe start from scratch and you can try to be a bit more verbose on describing what you did exactly and at which point in time it diverges from what you expect to what happened.

**Comment by stepansnigirev** [comment]
Due to inactivity, I am closing this issue.
@inpharmaticist please reopen if the issue is still there.
