### ISSUE TITLE
MultiSig signing one key with Ledger an extra transaction shows up?

### ISSUE THREAD

**Issue by pappyg45** [cryptoadvance/specter-desktop#1382]
Created a small test transaction the trezor key works fine to sign, but when I sign with ledger an extra 2nd transaction pops up to approve that is nowhere to be found? bug?

**Comment by calkob** [comment]
Its probably the change address.  try and send max amount and see if it disappears. Ledger arnt the best for multisig.

**Comment by pappyg45** [comment]
> Its probably the change address. try and send max amount and see if it disappears. Ledger arnt the best for multisig.

Not sure what you mean by max amount? I don't want to approve btc being sent to an address I did not approve? But since my trezor only confirmed the correct transaction will approving the other erroneous 2nd transaction on my ledger prevent it from sending the other amount in a multisig setup?

**Comment by k9ert** [comment]
Please have a look at https://github.com/cryptoadvance/specter-desktop/blob/master/docs/multisig-security-tradeoffs.md and also maybe the linked article which goes into details.
I'm closing this for now.
