### ISSUE TITLE
Passport not reading transaction QR code.

### ISSUE THREAD

**Issue by clayenos** [cryptoadvance/specter-desktop#1390]
Not sure if the problem is with Specter or the Passport (with the latest firmware) but I was only able to sign a transaction with the SD card, not with the Specter-generated QR code. The passport just looked at it and never recognized it. It just said, "scanning." I made it as big as I could on my screen, all to no avail. Anyone else have that issue? I'm running version 1.5.0 on Umbrel.

**Comment by stepansnigirev** [comment]
Support for passport was added in 1.6.0
It shouldn't work with earlier versions

**Comment by clayenos** [comment]
Perfect thank you. Cheers!

C

Clay Enos
+1 212-255-9308
clayenos.com
Join me on Vero | vero.co/clay
