### ISSUE TITLE
Problem in setting up tor connection with specter desktop

### ISSUE THREAD

**Issue by ShoaibZahoor** [cryptoadvance/specter-desktop#1392]
in my specter desktop when i go under tab tor in setting for tor configration and press setup with option built in i get following error message.

Encountered an error:[Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/cryptoadvance/specter/util/../../../../pyinstaller/torbrowser/tor-browser-linux64-10.0.15_en-US.tar.xz
![tor error displayed](https://user-images.githubusercontent.com/89355297/132951769-48497806-7562-41db-8284-bc71322a5f47.jpg)

**Comment by k9ert** [comment]
Can you elaborate a bit more on your setup? Which version are you running? Which OS? Do you use an App or a pip-installation? It's not an umbrel/raspiblitz or the like?

**Comment by k9ert** [comment]
please reopen if you can contribute to this issue.
