### ISSUE TITLE
Modify the multi-signature wallet Co-signer Device Type, but not take effect

### ISSUE THREAD

**Issue by caixiao-QA** [cryptoadvance/specter-desktop#1400]
Specter version: V1.6.0

  In the wallet info of the multi-signature wallet, switch one of the co-signer Device Type from Cobo Vault to Keystone. After the transaction is created, the QR code is still the UR1.0 QR code, which is expected to be the UR2.0 QR code that Keystone can scan.

**Comment by caixiao-QA** [comment]
I recorded the operation screen, maybe it can help you solve the problem.

https://user-images.githubusercontent.com/37337093/133184368-817f68e3-eafa-450a-90d9-1a6fbfc73150.mp4

**Comment by stepansnigirev** [comment]
PR fixing this is open now, will be in the next release.
Currently the workaround is to restart Specter - it will catch up changes on boot.
