### ISSUE TITLE
Wrong datadir stored in .specter/nodes/default.json

### ISSUE THREAD

**Issue by RaulRider** [cryptoadvance/specter-desktop#1407]
the configuration file `.specter/nodes/default.json` gets by default `"datadir": "/home/me/.bitcoin"`

if running spceter connected to a bitcion instance running with a different data directory, the default `"datadir": "/home/me/.bitcoin"`in still stored in the json configuration file.

It does not mean it does not  work. On the contrary the json file stores the correct RPC user and RPC password (probably those user/pass values are taken from the actual `datadir` of the bitcoin instance running.
 
Even if you change that manually in the `.specter/nodes/default.json`, when you restart specter it changes again to the default.

See json file below

```
{
    "name": "Bitcoin-Core",
    "alias": "default",
    "autodetect": false,
  ****** "datadir": "/home/me/.bitcoin",******* WRONG
  ****** "user": "useruseruser",*************** RIGHT
  ****** "password": "passpasspass",*********** RIGHT
    "port": "8332",
    "host": "localhost",
    "protocol": "http",
    "external_node": true,
    "fullpath": "/home/me/.specter/nodes/default.json"
}
```

**Comment by k9ert** [comment]
The key here is, that this is an external-node. The datadir is only relevant if you autodetect the credentials. This only works with the default-directory. 
If you configure your node explicitly, the datadir is no longer relevant, even though it might not make that much sense.
However, maybe i'm also overlooking something. Is there something to worry about?

**Comment by RaulRider** [comment]
I don' t think it is an external node (As I understand) 
My bitcoin node runs from a different datadir (external drive not the default .bitcion folder). The HDD is attached to the same computer where the Bitcoin node and specter instance are running. It is just the bitcoin-node-datadir which is in a external HDD. 

When I did the first setup of specter, I think that I had the autodetec ON and I don´t remeber having configured the bitcion core instance explicitly (first setup done quite a while ago).

But, everything seems to work just fine, Specter seems to recognize the node running with this `-datadir = /media/me/HDD `, (it gets RPC password and RPC username right or maybe I enter those during my first set up). Specter seems to store the specter's files (wallets) in the right place in the bitcion-node-datadir at the external drive. 

It is just that the json keeps stating the default datadir.

**Comment by k9ert** [comment]
I think it's an implementation detail which shouldn't bother you. I'm closing this for now.
