### ISSUE TITLE
Remove active prefilled 0 in Send -> Amount

### ISSUE THREAD

**Issue by Bosch-0** [cryptoadvance/specter-desktop#1413]
Currently there is an active prefilled '0' in the amount form. When a user clicks on this that zero becomes part of the input unless they backspace it. It would be better UX to have a non-active prefilled 0 that is just a placeholder, using a lower opacity looks nice too :) 

See before / after below:

![image](https://user-images.githubusercontent.com/55287964/135582400-ed02145e-fa5b-4c94-8774-410787da429f.png)

**Comment by VCBhatawadekar** [comment]
I have tried to do this by changing `value = "${amount}"` to `placeholder = "0"`
