### ISSUE TITLE
Add CSV Address (and txn) Label Imports

### ISSUE THREAD

**Issue by GoofyAF** [cryptoadvance/specter-desktop#1419]
I have had issues keeping address labels across Specter instances (i.e. the labels disappear when I import the wallet into a new specter-desktop instance). However, I had the specter-desktop CSV label file that can be exported by the wallet: `${WALLET_NAME}_addr.csv`

In the Settings -> Advanced tab, the first option is `Import Electrum address labels` but these require a json format of 

```
{"8aasd324..": "some utxo label",
...,
"12asdu34q5...": "some txn label"}
```

I was able to import my CSV by doing a CSV to JSON conversion using the python pandas library, but I think this would be a waste of resources to use this approach in specter.

Instead I suggest using the following code as a guide and adding in a CSV to JSON parser so that specter can consume it's own label export CSVs.

Example code taken from (https://pythonexamples.org/python-csv-to-json/) :

```
import csv 
import json 

def csv_to_json(csvFilePath, jsonFilePath):
    jsonArray = []
      
    #read csv file
    with open(csvFilePath, encoding='utf-8') as csvf: 
        #load csv file data using csv library's dictionary reader
        csvReader = csv.DictReader(csvf) 

        #convert each csv row into python dict
        for row in csvReader: 
            #add this python dict to json array
            jsonArray.append(row)
  
    #convert python jsonArray to JSON String and write to file
    with open(jsonFilePath, 'w', encoding='utf-8') as jsonf: 
        jsonString = json.dumps(jsonArray, indent=4)
        jsonf.write(jsonString)
          
csvFilePath = r'data.csv'
jsonFilePath = r'data.json'
csv_to_json(csvFilePath, jsonFilePath)

```

**Comment by moneymanolis** [comment]
OK, on it. With autodetection you mean to detect whether the electrum_label_export is in json or in csv format I guess?

**Comment by k9ert** [comment]
> OK, on it. With autodetection you mean to detect whether the electrum_label_export is
> in json or in csv format I guess?
yes, exactly.

**Comment by moneymanolis** [comment]
Not done yet :-)
