### ISSUE TITLE
Auto-hide sensitive info requires POST, can have problems activating on certain pages

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#1449]
The POST to auto-enable Hide Sensitive Info mode can fail due to csrf timeout or other POST-related issues.

Would be simpler if this mode could be enabled with GET, even though that slightly goes against GET vs POST convention (GET for read-only, POST to change state).

**Comment by k9ert** [comment]
I think this is already solved in one of:
* https://github.com/cryptoadvance/specter-desktop/pull/1478
* https://github.com/cryptoadvance/specter-desktop/pull/1468
Let's close this.
