### ISSUE TITLE
"Send" tab and transactions slow to load

### ISSUE THREAD

**Issue by PLK2** [cryptoadvance/specter-desktop#1451]
Specter Desktop v1.7.0 
M1 Macbook Pro 2020 MacOS 11.5.2
Bitcoin Core 0.21.1

Bitcoin Core updates blocks; then Specter opens; then I select the "Send" tab and have to wait about ~60 seconds for it to open.

After inputting send transaction data I have to wait another ~60 seconds for the signature page to come up.

**Comment by k9ert** [comment]
I did some tests and figured out that mempool fee calculation seem to be slow as hell. Do you use that (Check in the general settings) ? It's unfortunately the default right now.
Please try to switch to Bitcoin-core!

**Comment by k9ert** [comment]
We have significant improvements apart from the mempool-issue in the send-dialog coming in https://github.com/cryptoadvance/specter-desktop/pull/1454
So hopefully this will come into the next release!

**Comment by k9ert** [comment]
This is now solved in `v1.8.0`.
