### ISSUE TITLE
Avira blocking Specter

### ISSUE THREAD

**Issue by fernandosesim** [cryptoadvance/specter-desktop#1455]
I am trying to initialize the Specter Wallet on Mac Os, but Avira is sending `specterd` to quaratine.

> File name: specterd
> Threat name: PUA/OSX.CoinMiner.jplfa
> Action taken: The threat was moved to quarantine

**Comment by k9ert** [comment]
Does it make sense to use this:
https://support.avira.com/hc/en-us/articles/360008803558-How-do-I-configure-the-white-black-user-list-

**Comment by fernandosesim** [comment]
Yes, I can easily bypass the verification, but this in parallel to issue #1458 made me question if this was correct. Anyway, it would be better in the future do not have this false positive by Avira.

**Comment by k9ert** [comment]
Yes, good point. I'm not sure what we can do on our end with this. I can't imagine that Avira is so clever to download hashes from github and flag files if they don't match.

BTW, the specterd is downloaded from the app at first start. Before internally launching the specterd, it'll check automatically the sha256-sum against a build-in value. That value was correct allmost all the time. 

I'm closing this for now. Feel free to reopen if you see some potential action on the project side.
