### ISSUE TITLE
After updating to version 1.7 my balances, txid, addresses, labels, amounts, time, and confirmations are all just ######

### ISSUE THREAD

**Issue by freddiemacd** [cryptoadvance/specter-desktop#1456]
I updated to 1.7. I was using Ubuntu 18.04. I had an error and saw that I needed to update to ubuntu 20.04. I now can start up specter desktop but everything just displays ########## instead of showing the amount of bitcoin, the TxID, etc.

Bitcoin core 22 is showing the correct balances for the wallet
![Screenshot from 2021-10-31 20-01-07](https://user-images.githubusercontent.com/39029241/139616035-56277c92-e433-4f4e-a385-b637fb2319de.png)
.

**Comment by calkob** [comment]
I think that is the evil maid protection set to on, you know to stop someone looking over your shoulder and seeing your balance.  It should be easy enough to turn off i think its an icon in top right corner, you just click it.

**Comment by freddiemacd** [comment]
I see (pun intended). Thanks that was it.
