### ISSUE TITLE
Trezor Wallet Error

### ISSUE THREAD

**Issue by jeanmazc** [cryptoadvance/specter-desktop#1460]
I cant connect my trezor wallet with specter after put pin and the passphrase the specter try many times connect with the passphrase but no success

**Comment by k9ert** [comment]
Can you create a screenshot and maybe also have a look in the logs? Do you use HWI-bridge or local only? Did you imported the udev-rules?

**Comment by k9ert** [comment]
Please reopen if you can provide more information.
