### ISSUE TITLE
Specter desktop can't launch, Specter Desktop encounter an error

### ISSUE THREAD

**Issue by caixiao-QA** [cryptoadvance/specter-desktop#1461]
Specter Version: v1.7.0
mac os: 10.15.7

`Error：script failed to execute， this normally means an error was thrown.Check the render console for thr wrror `
![image](https://user-images.githubusercontent.com/37337093/140480520-9cd856d9-8f46-40db-86ef-662649cdf3cf.png)

Tried to restart the computer ,but still can't work.

and tried to open Specter many times, sometimes I get another error:

`Erroe:end of central directory record signature not found`
![image](https://user-images.githubusercontent.com/37337093/140480577-96018145-d4fe-4e1f-911e-670f5702f683.png)

**Comment by k9ert** [comment]
Since v1.7.0, there is an option to access the logs in the Specter-menu. Can you please have a look at the logs and copy them here?

**Comment by caixiao-QA** [comment]
> Since v1.7.0, there is an option to access the logs in the Specter-menu. Can you please have a look at the logs and copy them here?
[specterApp.log](https://github.com/cryptoadvance/specter-desktop/files/7567164/specterApp.log)

**Comment by ashjkl159** [comment]
yes i am getting exactly the same error here too after upgrade

**Comment by ashjkl159** [comment]
i will try to find log sec

**Comment by ashjkl159** [comment]
[](url
[specterApp.log](https://github.com/cryptoadvance/specter-desktop/files/7600988/specterApp.log)
)

**Comment by ashjkl159** [comment]
ok, i am now OK, my bitcoin core was not connected, once bitcoin core internet connection has been established, specter desktop did start with no errors
