### ISSUE TITLE
"Wallet already being loading." - grammar is inccorect

### ISSUE THREAD

**Issue by Zimbakin** [cryptoadvance/specter-desktop#1471]
`Request error: Wallet already being loading.`
"being loading" is incorrect english grammar.

...already loading
or being loaded is proper english.

Cheers.

**Comment by k9ert** [comment]
I'm having trouble finding that string. Where did you get that? Can you maybe create a screenshot?

**Comment by Zimbakin** [comment]
After changing my LAN IP subnet and subsequently updating to 1.7.1 , I received this message (below).
I had to open Specter in order to change the RPC config to the new LAN IP for MyNode. After changing the RPC config, I received the message 4 times before it finally worked. I think the restart helped. MAC OS 12.0.1, Specter 1.7.1

```
2021-11-14T05:02:59.948Z [info] : stderr-SPECTERD: WARNING in wallet_manager: Couldn't load wallet xxxx into core. Silently ignored! RPC error: Request error: Wallet already being loading.
SPECTERD: INFO in wallet_manager: Loading xxxxxx to Bitcoin Core
```

**Comment by k9ert** [comment]
I assume this is solved. Closing. Feel free to reopen for the UIUX issue but please consider to open a new issue if you have something else to report.

**Comment by djpnewton** [comment]
It is a message from bitcoin core RPC (see also https://github.com/bitcoin/bitcoin/pull/19300)

I am getting it now with bitcoin core 0.21 when trying to sign a tx

I will try updating to the latest bitcoin core

**Comment by djpnewton** [comment]
Updating to bitcoin core 23 seems to have solved the issue for me
