### ISSUE TITLE
Can't sign L-BTC spending transaction with Jade

### ISSUE THREAD

**Issue by 84adam** [cryptoadvance/specter-desktop#1486]
Trying to sign a Liquid spending transaction over HWI Bridge. HWI Bridge does allow for proper detection of Jade HWW connected to local machine. During signing, I get this error every time:

`TypeError: an integer is required (got type NoneType)`

I am running v1.7.1 in both places (with Bitcoin Core v22.0 and Liquid v0.21.0 on the remote server).

Traceback:

![traceback](https://user-images.githubusercontent.com/13172004/142694207-0b0a962c-e950-4f83-924b-a0e995f36b85.png)

For this transaction, the (single) input amount shows up as `Amount: 0 ???`. (However, this transaction would spend the whole input in this case, around 10,000 L-SATS.)

Transaction Details:

![LBTC-tx-details](https://user-images.githubusercontent.com/13172004/142694719-5965c8ee-41c5-44cf-adb8-ff62e9294b73.png)

NOTE: I _am_ able to sign and spend with inputs that are non-zero in amount at this time under otherwise identical conditions with the same Jade HWW.

**Comment by 84adam** [comment]
Issue remains in version 1.7.2. Error upon signing attempt: `TypeError: an integer is required (got type NoneType)`.

**Comment by stepansnigirev** [comment]
Looks like Specter failed to unblind the transaction. Is it a pegin output?

**Comment by 84adam** [comment]
No, but its parent output was a pegin output:

The output I'm trying to spend: `ex1###############################xq` `0.0001####` LBTC

Its parent (PEGIN OUTPUT): `ex1###############################7h` `0.0001####` LBTC ; Transaction fees `0.000000##` LBTC

Its grandparent (BTC): `3H################################CN` `0.0001####` BTC

**Comment by stepansnigirev** [comment]
I see. Is this input confidential or unconfidential? Is the output confidential?

**Comment by 84adam** [comment]
The input is unconfidential. The output is confidential.

**Comment by stepansnigirev** [comment]
I see, thanks. I think I didn't test this case with Jade properly, so I'll work on the fix.

**Comment by stepansnigirev** [comment]
Fix in Specter-Desktop: https://github.com/cryptoadvance/specter-desktop/pull/1528

Fix in Jade firmware:
https://github.com/Blockstream/Jade/commit/508afa102eaac614116eabef26e439bcd19a88df

So looks like you need a new release of both...

**Comment by 84adam** [comment]
I've updated to latest stable release, v1.8.1 and updated Jade FW to 1.32 (latest also).

I am still unable to sign successfully using this UTXO that is a "child of a peg-in output" (its parent was a peg-in). Just to reiterate: This input is unconfidential, and the output is confidential.

However, I am able to see more information now in the error message. And I can tell you I was able to sign and send a separate "confidential input to confidential output" transaction, and as a result, I know where it's failing now: right before it would take you to the Fee Summary screen in the Jade.

During signing it shows the following error, as seen in the screenshot below.

- Error: `BAD_PARAMETERS = -32602` / "Failed to extract value commitment from parameters."
- source: https://github.com/cryptoadvance/specter-desktop/blob/master/src/cryptoadvance/specter/devices/hwi/jadepy/jade_error.py

NOTE: Nothing is logged regarding the error even in debug mode in the specter.log file. Nothing in elements/liquidv1 debug.log either.

Error: 

![Jade-LBTC-sign-error-021522](https://user-images.githubusercontent.com/13172004/154181356-9523fd5a-32d3-437d-a714-99c7505b7043.png)

Transaction details for above:

![Jade-LBTC-sign-TX-details](https://user-images.githubusercontent.com/13172004/154181401-8dc393c4-b25d-496f-a70b-d1a4351b3ba8.png)

By the way, I also tried spending to another unconfidential address in my same wallet (under the same Jade's control). The error I get in that case is "Internal error: Nothing to blind."

Please advise.

**Comment by stepansnigirev** [comment]
AFAIK firmware update with the fix is not released yet on Jade. They say it will be released soon.
Regarding "Nothing to blind" error - I'll take a look, could be a problem on our side.

**Comment by 84adam** [comment]
I tried with the new Jade FW version 0.1.33 today and it works. Problem solved! Thanks for your help.
