### ISSUE TITLE
Tor Not connecting and keeps showing error when testing connection.

### ISSUE THREAD

**Issue by LStergianis** [cryptoadvance/specter-desktop#1487]
Failed to make test request over Tor. Error: SOCKSHTTPConnectionPool(host='2gzyxa5ihm7nsggfxnu52rck2vv4rvmdlkiu3zzui5du4xyclen53wid.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x0000021051192220>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

Any idea how to fix this  ?

**Comment by k9ert** [comment]
Looks like an issue with your Tor-Setup or a temporal glitch in the network. I just tried myself and it works. Can you reproduce this?
