### ISSUE TITLE
Cannot get Specter Desktop to work properly, bit core configuration issues persist

### ISSUE THREAD

**Issue by RandalGraves** [cryptoadvance/specter-desktop#1488]
Hi, I install Specter Desktop with no problems and eventually get to the "conratulations" window with a successful install but over on the left hand side of the window , it's all bad news on the bit core side of things
![Screenshot 2021-11-24 at 17 25 01](https://user-images.githubusercontent.com/94986890/143287291-4b5cec35-0fdc-4233-8941-557dfdb0eb53.png)
.

So I click on the lh side, specter bitcoin, click to configure and get this:
![Screenshot 2021-11-24 at 17 25 33](https://user-images.githubusercontent.com/94986890/143287599-69a2e3a3-21cd-465c-9456-ca7c0e4b1b96.png)
 
The bitcoin node info box remains there for ages , nothing happens. Next I try the "configure node" option within the grey box warning wallets are not available and get this:

![Screenshot 2021-11-24 at 17 26 09](https://user-images.githubusercontent.com/94986890/143287861-e4c39149-ff06-4f86-93ca-ce62dc153e39.png)

And this is the result:

![Screenshot 2021-11-24 at 17 26 27](https://user-images.githubusercontent.com/94986890/143287904-f6e70586-5d10-4096-b1e2-2612c4d0438d.png)

I've tried several installs, 3 without quick sync, one with, all ended in the same result, an issue with the node, I installed the pruning option due to disk storage constraints. 

So I am currenly stuck and cannot get the node to run or configure.

Regards,

RG

**Comment by k9ert** [comment]
I can't imagine that this is not due to some corruption in the `~/.specter` folder. As you probably don't have any sensitive data in there, can you zip that folder and attach it here?
So it's high likely that it'll work again if you simply delete the whole folder and restart the procedure. Can you do that?

**Comment by RandalGraves** [comment]
Hi, I can do that later, in the meantime I've deleted the app and reinstalled it several times and the issue remains.

Regards

RG

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by k9ert** [comment]
I'm closing this issue for now. Please reopen if it doesn't help what i'm suggesting here.
