### ISSUE TITLE
Please change "Unconfirmed" string in spanish version

### ISSUE THREAD

**Issue by wchancao** [cryptoadvance/specter-desktop#1502]
Please change "Unconfirmed" string in the Spanish version of Specter Desktop, now it shows "Inconfirmado" and i dont think that word exist. "No confirmado" or "Sin confirmaciones" would be better.

CC @2a3dex

**Comment by 2a3dex** [comment]
Thanks !!! Already did the PR. Thank your !!!

**Comment by k9ert** [comment]
Is that already merged? If yes, i'd like to close this issue but can't find the PR.

**Comment by 2a3dex** [comment]
Yes, already merged.

**Comment by k9ert** [comment]
Yes, i think it was this one.
https://github.com/cryptoadvance/specter-desktop/pull/1507
Closing this issue.
