### ISSUE TITLE
Export with historical price data does not work

### ISSUE THREAD

**Issue by dennisreimann** [cryptoadvance/specter-desktop#1512]
Specter Version: v1.7.2 (macOS)

The CSV export works in general, but the toggle for including historical price data does not seem to have an effect: The rate and value columns in the export are empty. For me this works with none of the price providers – though the general price feature in the app works and prices can be fetched.

**Comment by k9ert** [comment]
I just tested this on Linux master and it worked for the Bitstamp-price-provider. I know that it doesn't work for all of them. E.g. coindesk does not have historic data and we're not explicitely stating that, Ahem, We should definitely make that more explicit. 

I can't currently test on MacOS, maybe can you choose the Bitstamp one and check the logs? We should see an exception:
https://github.com/cryptoadvance/specter-desktop/blob/994501d3591fec69e2b08407cf0c99c84f2628ae/src/cryptoadvance/specter/util/price_providers.py#L77

**Comment by dennisreimann** [comment]
Specter Log:

```
WARNING in price_providers: Failed to get price data from: bitstamp_eur. Exception: Could not find a suitable TLS CA certificate bundle, invalid path: /var/folders/cr/wr00rr_d77q9xh0ht13tcjrc0000gn/T/_MEIuOKK2Q/certifi/cacert.pem
```

App Log:

```
stderr-SPECTERD: WARNING in price_providers: Failed to get price data from: bitstamp_eur. Exception: Expecting value: line 1 column 1 (char 0)
```

**Comment by moneymanolis** [comment]
I'll check on MacOS, I vaguely remember having certificate issues like that before on MacOS.

**Comment by moneymanolis** [comment]
Works on MacOS Monterey with Bitstamp using Specter via pip. Perhaps this is the reason for the issue: https://www.albertyw.com/note/pyinstaller-requests

@dennisreimann could you run Specter via pip and try again? The weird thing is, though, that for me it also works with the MacOS Specter app.
Also could you check whether you have this env variable: REQUESTS_CA_BUNDLE? Apparently, if this is pointing to a wrong location, it can generate your error.

**Comment by dennisreimann** [comment]
I'm also running macOS Monterey. 

It works neither with the Specter Desktop macOS app, nor with the pip version.

My `REQUESTS_CA_BUNDLE` is unset. I installed `certifi` and used its certificate location, but that didn't help either:

```sh
~ ➜ python3 -m certifi                
/usr/local/lib/python3.9/site-packages/certifi/cacert.pem

~ ➜ export REQUESTS_CA_BUNDLE=/usr/local/lib/python3.9/site-packages/certifi/cacert.pem
```

The error remains:

`WARNING in price_providers: Failed to get price data from: bitstamp_eur. Exception: Expecting value: line 1 column 1 (char 0)`

It also always seems to be using Bitstamp, no matter what I've selected as price provider in the app settings.

**Comment by k9ert** [comment]
I'm a bit confused from the error-message. Especially in the last comment. Maybe this is more than one issue. I've created a PR. @moneymanolis  let's discuss this and merge and then create an artifact for Dennis to test. Obviously this is a bit tricky if we can't reproduce.

**Comment by dennisreimann** [comment]
DM'ing with @k9ert he sorted it out and for me it is now working with `v1.9.4-pre2`. 

Thanks a lot, Kim!
