### ISSUE TITLE
when on testnet unable to import wallets - Invalid wallet descriptor

### ISSUE THREAD

**Issue by dennislevens** [cryptoadvance/specter-desktop#1518]
When trying to import wallets that were exported from sparrow in specter desktop format you get this error "Invalid wallet descriptor: Descriptor key has wrong derivation, only /0/* derivation is supported."

I am able to export and then import specter exports of wallets on testnet
I get the import error when importing sparrow exports of wallets

To recreate:
Create a wallet in specter or sparrow
If created in specter, export wallet and import to sparrow and delete wallet in specter
export wallet from sparrow in specter desktop format
import wallet to specter

Attached is a json export from sparrow that will show the error when importing to specter
[test1223-specterdesktop.json.zip](https://github.com/cryptoadvance/specter-desktop/files/7771213/test1223-specterdesktop.json.zip)

**Comment by stepansnigirev** [comment]
#1519 should fix it. For now you can add /0/* derivation to the descriptor keys:
```
{
  "label": "test1223",
  "blockheight": 0,
  "descriptor": "wpkh([6d3bbb91/84h/1h/0h]tpubDDaEFrcf24FqgyyQJfbPTtexNxy7j1AmNavZSYkYdnX1xtXpRdwsuogCoWVn6JHpAWyEbig3NK5wHFUMttB17adyHU4WVE2DbzVdUDjtyYU/0/*)"
}
```

**Comment by k9ert** [comment]
Is this something which should be fixed on Sparrow-side (as well) ? If yes, i'm happy to create an issue there?

**Comment by stepansnigirev** [comment]
I am not sure what would be the best way to resolve this - to specify exactly the descriptor format we support, or to release the constraints such that it's easier to construct import descriptor by hand.

In particular, open questions:
- Should we check that checksum in the descriptor is present and valid?
- Should we check that `/0/*` is always present in the descriptor? What if we find `/15/*` or `/*/22` instead? What if no wildcard suffix is provided (append `/0/*` or treat as a single address wallet)?
- How should we derive change descriptor from the receiving descriptor present in the json? Just replace `/0/*` with `/1/*`?
- What if some of the keys contain wildcard and some does not?

**Comment by k9ert** [comment]
@craigraw what do you think about this?

**Comment by craigraw** [comment]
Good question. For the purposes of the Specter Desktop export format, I'm happy to follow whatever you'd like. 

In terms of the path forward, I believe a concise output descriptor to completely describe a wallet is generally useful and something we should strive towards, particularly wrt multisig backups. To this end, Sparrow has started generating multipath output descriptors as per https://github.com/bitcoin/bitcoin/pull/22838 (note also the linked issue https://github.com/bitcoin/bitcoin/issues/17190). Unfortunately it's not clear that will be merged into Bitcoin Core, but my hope is that if other wallets like Sparrow or Specter Desktop adopt it, it will gain general acceptance.
