### ISSUE TITLE
Issue connecting tor from docker to docker on the same network

### ISSUE THREAD

**Issue by aphex3k** [cryptoadvance/specter-desktop#1525]
In Umbrel, the specter desktop app runs in a docker container. I would like to connect it to any of the 3 app tor container umbrel provides with its installation.

10.21.21.47-49 is the IP address range for the app tor container but specter desktop can't seem to be using any of them as socks proxy because the connection test fails on the settings page with the error:

> Failed to make test request over Tor. Error: SOCKSHTTPConnectionPool(host='2gzyxa5ihm7nsggfxnu52rck2vv4rvmdlkiu3zzui5du4xyclen53wid.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fadb4838280>: Failed to establish a new connection: [Errno 111] Connection refused'))

All umbrel containers are part of the same docker network: In my case the specter desktop app is hosted at 10.21.21.18.

![image](https://user-images.githubusercontent.com/433270/148592274-5bf9b9fa-7bf3-4dbd-b9ce-f46ee9d7c8e0.png)

**Comment by k9ert** [comment]
@aarondewes , @nolim1t can you maybe help with that?

**Comment by AaronDewes** [comment]
I'm not an Umbrel User, I'm using @runcitadel, my own, better Umbrel fork, but on Umbrel, the apps tor is the wrong container, it only hosts hidden services, not a proxy. Umbrel's tor proxy is at 10.21.21.11

**Comment by nolim1t** [comment]
Yep it Looks like a Misconfiguration on umbrels part.

**Comment by AaronDewes** [comment]
> Yep it Looks like a Misconfiguration on umbrels part.

I'm pretty sure it's intentional, but not sure.

**Comment by aphex3k** [comment]
Can confirm. Everything is working as expected, it is just the UI behaving a little weird.
