### ISSUE TITLE
Fail upgrading to 1.8

### ISSUE THREAD

**Issue by antonvier** [cryptoadvance/specter-desktop#1530]
Hi. My system is mxlinux 21. 
My previous specter running is 1.4.6 , after upgrading i receive this error message:

https://pastebin.com/fzb3bdsb

thanks

**Comment by k9ert** [comment]
Thank you very much. I can reproduce the issue. This is a still a pre-release (and i forgot to mark it as such). So please wait until the final release.

**Comment by antonvier** [comment]
thanks so much!

**Comment by k9ert** [comment]
Ok, should be fixed now. Release is done!
