### ISSUE TITLE
implement QR-code based message signing in Specter

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#1550]
The current state of [message-signing](https://docs.specter.solutions/desktop/sign-message/) is quite bad in Specter. We have at least two issues:
* The user has to navigate to the underlying device and manually insert the derivation path for that address
* A specter-DIY could potentially sign via QR code but it's not implemented on the Specter Desktop side.

Some hints on how to solve both issues:
- Avoid user input of derivation path
- The QR code that Specter DIY can handle looks like this:
```
signmessage m/1h/2h/3 ascii:hello world
```
TODOs
- [x] Create an example QR code that can be read with the DIY
- [x] Change user input to address and derive the derivation from it

### To be discussed
- Where does the user start the signing flow, at the device and/or at the wallet level? 
- What happens to addresses that were used for signing? Special tag etc.?

**Comment by moneymanolis** [comment]
I think the first point could simply be solved by prompting for the address instead and deriving the derivation path in the background here. Would be nice to perhaps have some functionality to set the address involved to used or some new property, after all the hash protection of the pubkey of this address is no longer available when transmitting the signature (the pubkey can be inferered from the signature).

<img width="421" alt="image" src="https://user-images.githubusercontent.com/70536101/152386305-06797bd0-5ac9-4a6c-b3fe-b50e8500cf1c.png">
