### ISSUE TITLE
Wrong Transaction-date for csv-exports

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#1552]
As reported by @dennisreimann , transactions have a date when they got first discoivered in the mempool but not when they got confirmed in a block. This is not so good as conversion-rates need to be based on the confirmation-date, not the mempool-date.

**Comment by dennisreimann** [comment]
Whoohoo, thanks for fixing this!

**Comment by k9ert** [comment]
Just for the reference: I also learned that the time which is shown on the transaction (`blocktime` from core) is NOT the time the block got confirmed.

https://twitter.com/PhilippWa2/status/1496792021813579781
https://github.com/bitcoinbook/bitcoinbook/blob/a3229bbbc0c929dc53ec11365051a6782695cb52/ch07.asciidoc#median-time-past
https://github.com/bitcoin/bips/blob/master/bip-0113.mediawiki
