### ISSUE TITLE
Please Be Advised [WINDOW'S USER'S ONLY] 

### ISSUE THREAD

**Issue by LucasStergianis** [cryptoadvance/specter-desktop#1555]
If you are running Specter on windows 10 or 11 the latest release that will work is v1.7.2, if you try downloading a release any higher then that you will be left with 

![specter error](https://user-images.githubusercontent.com/97878567/152448190-b36f238d-492b-4320-9b30-1bb19cf51669.png)

It looks like this user that posted issue #1553 is having the same problem as me and I pulled the picture from there to show you what pops up when you try installing the updated versions on windows. There is no current work around other then staying on v.1.7.2

**Comment by k9ert** [comment]
Yes, seem so. Sorry for the bad experience. I'll close this issue here and please follow #1553 for a resolution.
