### ISSUE TITLE
UX: Inconsistent behavior for "Create unsigned transaction"

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1562]
I tested the following use case:

- Create the same unsigned transaction multiple times at different fee rates.  (This is useful for future transaction in an unknown fee environment)

There the following confusing and inconsistent behavior occurred:

1. If the tx spends more than what is unspent/unlocked in the wallet, I will be prevented from doing my use case 
    https://github.com/cryptoadvance/specter-desktop/blob/a55764ca3529cf64ca229e78f6dba74e2c04dcf3/src/cryptoadvance/specter/templates/wallet/send/new/wallet_send.jinja#L449
2. If the tx spends less than what is unspent/unlocked in the wallet, I can create the tx.  

This is inconsistent in the following way:

- It prevents double spending the same utxo only in certain cases.

My current workaround:

- Export transaction to file and delete it in specter. 

Possible ideas how to resolve this UX inconsistency:

1. Hide the locked utxos or grey their checkbox out.    This behavior would be consistent with electrum (electrum completely hides utxos which are in a saved tx).
2. Allow double spending utxos when using the coin selector. This is significant work, because all calculations are currently done with summing up utxo values -  and not unique utxos. It might also be difficult to understand for new users.

Do you think option 1 should be done? Then I would do that.

**Comment by k9ert** [comment]
I don't understand why this should be inconsistent? In which cases should double-spending be allowed? I mean, we have RBF and you can modify any (non-confirmed) transaction you have sent out if RBF was enabled. 
However, new transactions should be prevented from creation, no?
Maybe i'm missing something, i'm not the expert here.

**Comment by k9ert** [comment]
Please have a look @moneymanolis

**Comment by moneymanolis** [comment]
I checked, it is indeed very inconsistent. There is already a styling (using "frozen" style) going on, when a UTXO is used in a unsigned transaction. 

<img width="487" alt="image" src="https://user-images.githubusercontent.com/70536101/153383980-4f312c96-1623-44a4-a011-414ebd910b94.png">



I'd take that a step further and prevent the selection of those UTXOs when using coin selection (so, I guess the "Electrum way" as described by @relativisticelectron). I've done quite a bit recently in this jinja file, so I can implement that.

**Comment by relativisticelectron** [comment]
Ok. Great! Thanks.

**Comment by moneymanolis** [comment]
There is also another related issue: Currently, frozen UTXOs can be used via coin selection as long as their amount is below "Available funds" (from which the frozen UTXOs are deducted).
