### ISSUE TITLE
Correct spelling of GitHub

### ISSUE THREAD

**Issue by fulldecent** [cryptoadvance/specter-desktop#1570]
Typo on homepage
<img width="1436" alt="Screen Shot 2022-02-10 at 11 54 43" src="https://user-images.githubusercontent.com/382183/153456976-823ab81e-4f3e-4ea0-9c80-dbad27e4b2af.png">

**Comment by GoofyAF** [comment]
I can't find this page in the specter-desktop repo or the cryptoadvance/docs repository. Is this site not in the cryptoadvance organization?

**Comment by k9ert** [comment]
No, it's not. Fixed it.
