### ISSUE TITLE
UI: Transaction creation possible with unconfirmed UTXO

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/specter-desktop#1581]
Should it be possible to create transactions with unconfirmed UTXO?

![image](https://user-images.githubusercontent.com/70536101/153923753-d2127e98-263b-48f1-860e-afa268130a54.png)

**Comment by relativisticelectron** [comment]
For me, creating tx with unconfirmed parents,   is an essential feature.

**Comment by moneymanolis** [comment]
@relativisticelectron very good point, so we'll leave it as it is. For everyone wondering what CPFP is: 

_Child Pays For Parent (CPFP) is a fee bumping technique where a user spends an output from a low-feerate unconfirmed transaction in a child transaction with a high feerate in order to encourage miners to include both transactions in a block._ (source: [https://bitcoinops.org/en/topics/cpfp/](url)
