### ISSUE TITLE
Requested wallet does not exist or is not loaded

### ISSUE THREAD

**Issue by mcsnubbs** [cryptoadvance/specter-desktop#159]
Im getting the following error when trying to bring up the main Specter page after starting the server - it previously worked fine. Any suggestions? Thank you

cryptoadvance.specter.rpc.RpcError
cryptoadvance.specter.rpc.RpcError: Server responded with error code 500: {"result":null,"error":{"code":-18,"message":"Requested wallet does not exist or is not loaded"},"id":0}

**Comment by stepansnigirev** [comment]
Can you give us a bit more information?
What has changed from the time when it was running fine? Did you upgrade specter? Or switched to another bitcoin core node?

Can you check if your wallet is in the list when you call?
```
bitcoin-cli listwalletdir
```

Should be with a name like `specter<some_random_number>/your_wallet`

**Comment by stepansnigirev** [comment]
Could you upgrade to the latest release and check if the issue remains?
