### ISSUE TITLE
UI Feature request: Global search

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1593]
**Problem**:  I wanted to search an address in specter and found no easy way of doing it.   
**Counter example**: I see friends using gmail. You can search globally all mailboxes for anything and gives a very user friendly experience.

**Feature request**:  A global (all wallets) search over 

- Addresses 
- transactions, id, label, time (date), amount
- device names, wallet names, service/plugin names
- (optionally) settings.  So you could search for "export" or "label import", and you would quickly find the menu where it is hidden

**Mockup**  (and yes this is regtest.... )
![Untitled](https://user-images.githubusercontent.com/60378539/154636741-47e56762-aa84-453f-b497-dad69ebde7b7.png)

**Some design elements:**

- Visual highlighting of the menu buttons under which search results where found, and how many in this sub-category
- Filtering of the tx, utxo, or address list to show only hits

**Replaces**  the current search for the transactions/utxos

**Comment by moneymanolis** [comment]
@agg-pranav want to give it a shot?

**Comment by relativisticelectron** [comment]
I am working on a branch on this https://github.com/relativisticelectron/specter-desktop/tree/20220710_search
![image](https://user-images.githubusercontent.com/60378539/178160421-01b8746c-d03a-4ddf-8b46-20bd26b9e086.png)

**Comment by relativisticelectron** [comment]
PR exists : https://github.com/cryptoadvance/specter-desktop/pull/1832
