### ISSUE TITLE
Flask not autoreloading changed files

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#16]
When running specter-desktop as specified in the README Flask is not auto-reloading when python, html, or css files change.

**Comment by stepansnigirev** [comment]
I accidentally changed the `debug` to `False` in the `server.py` - that's why...

https://github.com/cryptoadvance/specter-desktop/pull/17 implements the recommended way to run flask, but I would like to keep an option to run it via `python3 server.py`.

**Comment by kdmukai** [comment]
Right. I'm just learning more about Flask and didn't realize that autoreload is tied to the `debug` flag.

With that cleared up there's no need for #17. Also #19 depends on running via `python3 server.py` anyway.
