### ISSUE TITLE
UI: Improve scroll bar

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/specter-desktop#1605]
The addition of a scrollbar to the table-holder class (#1598) also affects other elements using this class, for example the key table:

<img width="861" alt="image" src="https://user-images.githubusercontent.com/70536101/155579352-f3e88635-baca-42c0-80cb-38322894349c.png">

 At least, we should set a min-height for the scrollbar. @VCBhatawadekar perhaps this is something for you?

**Comment by relativisticelectron** [comment]
Thanks for pointing that out. Sorry, I missed that.

**Comment by moneymanolis** [comment]
@relativisticelectron I am already working on it, should be able to push it later today, so you can have a look.
