### ISSUE TITLE
Pre-releases shouldn't be marked as "Latest"

### ISSUE THREAD

**Issue by BTCBellyButton** [cryptoadvance/specter-desktop#1609]
Usually the "Latest" release shouldn't be a pre-release:
![Screenshot from 2022-02-26 09-33-31](https://user-images.githubusercontent.com/68573637/155848998-b0272cd0-a77c-4fa2-853c-b5cc35f676fe.png)

**Comment by k9ert** [comment]
Fully agree. It's not automated yet that pre-releases are marked as such. Would be a great idea, though.
