### ISSUE TITLE
Instructions for setting up the dev environment could be improved

### ISSUE THREAD

**Issue by cypherhoodlum** [cryptoadvance/specter-desktop#1613]
New devs might wonder why their code changes don't show in the browser after following the instructions in [development.md](docs/development.md). I'd like to add the following line to avoid future headaches for new devs.

```sh
python3 setup.py develop # will track code changes during development
```

**Comment by k9ert** [comment]
I never did that and i'm not aware that it's necessary. the `pip setup -e .` should do the trick as well,no? At least that's what i'm doing and it does it for me.

**Comment by k9ert** [comment]
Ok, then i'd close this PR. Reopen it anytime if we have more information here. @kdmukai also had sometimes issues to that regard. We just don't know yet under which circumstances and i'd like to rather have clarity than confusing a documentation with doing things which "probably makes it more likely" that it works.

**Comment by k9ert** [comment]
BTW, at least i'm happy if you only create a PR without an extra-issue. Separating it usually makes sense if the one spotting the issue and the one fixing it are either seperated people or separated in time but it's imho not necessary if you spot it and just fix it right away.
