### ISSUE TITLE
UI/UX: Not all icons in the settings bar have titles

### ISSUE THREAD

**Issue by cypherhoodlum** [cryptoadvance/specter-desktop#1617]
When a user hovers over the icons in the settings bar some of them have a title and some don't. This is not great from a new user's perspective.

![Screenshot from 2022-03-02 16-54-54](https://user-images.githubusercontent.com/82510823/156386259-ddc7c221-4faf-4ca9-9af2-951e3f63d416.png)

**Comment by relativisticelectron** [comment]
Thanks for the issue.  Fixing in https://github.com/cryptoadvance/specter-desktop/pull/1621
