### ISSUE TITLE
UI/Design proposal: The main page could be improved

### ISSUE THREAD

**Issue by cypherhoodlum** [cryptoadvance/specter-desktop#1619]
The main/landing page could be improved. Here's my suggestion:

| Before (1920x1080 / iPad / iPhone) | After (1920x1080 / iPad / iPhone) |
| --------- | ------ |
| <img src="https://user-images.githubusercontent.com/82510823/156415559-859ce9c2-9d80-4da2-a426-6299945c81ff.png" width=500 /> | <img src="https://user-images.githubusercontent.com/82510823/156415642-80977e6a-537c-4504-8c28-55dea2d3b889.png" width=500 /> |
| <img src="https://user-images.githubusercontent.com/82510823/156415595-7f943c39-70f1-4806-bbb2-bc4b84352ba7.png" width=500 /> | <img src="https://user-images.githubusercontent.com/82510823/156415656-5908aa31-1730-4d06-a2be-8d3e1379dc16.png" width=500 /> |
| <img src="https://user-images.githubusercontent.com/82510823/156415612-9c89b078-305a-4508-9dcc-feaeca84296e.png" width=500 /> | <img src="https://user-images.githubusercontent.com/82510823/156415672-df248a6f-39ba-4c72-8202-1c6cb73f27e2.png" width=500 /> |

**Comment by k9ert** [comment]
Nice! LGTM!

**Comment by moritzwietersheim** [comment]
Hi @cypherhoodlum - this is a very nice proposal with the flexboxes. I really like how makes the ui/ux clearer.

Also I like your suggestion to take the two little Specter Logos away before and after the "Welcome to Specter Desktop".

However the Specter-Logo as a watermark in the background I would like to take out as it confuses my vision here :)
