### ISSUE TITLE
Core dats and legacy inquiry

### ISSUE THREAD

**Issue by mikejnpc** [cryptoadvance/specter-desktop#1625]
Hi nice pre , still checking it out but love node and quick sync functions.. 
just wanted to ask - i can i load my core dats into this,.. and can we use legacy ?

Thanks!
Mike

**Comment by jonathancross** [comment]
This is not the correct place to ask for support, please use the Telegram channel: https://t.me/spectersupport

**Comment by k9ert** [comment]
... but the answer is: What are core dats? And no, sorry, legacy is not supported.

**Comment by mikejnpc** [comment]
Ah apologies misread that... thank you for the  clarification.....
Kind regards.
