### ISSUE TITLE
 new with specter...would appreciate some advice with an error

### ISSUE THREAD

**Issue by Campanada1130** [cryptoadvance/specter-desktop#1629]
Server error!
Exception: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

[Back to the main page](http://localhost:25441/)

Details:
Traceback (most recent call last):
  File "flask/app.py", line 2447, in wsgi_app
  File "flask/app.py", line 1953, in full_dispatch_request
  File "flask/app.py", line 1970, in finalize_request
  File "flask/app.py", line 2267, in process_response
  File "cryptoadvance/specter/server_endpoints/controller.py", line 171, in after_request
  File "werkzeug/local.py", line 347, in __getattr__
AttributeError: '_AppCtxGlobals' object has no attribute 'start'

Please let us know! Create an [issue](https://github.com/cryptoadvance/specter-desktop/issues) or ping us on [Telegram](https://t.me/spectersupport) to fix it.

**Comment by Campanada1130** [comment]
We have installed the bitcoin core and run bitcoind and can see the core running. We encounter a problem when trying to connect Specter to the core. We don't seen to have the correct path because every time we test the connection, it says "Test failed: connection to node failed".

I have tried getting the path through the terminal two different ways. When I type echo $PATH the terminal gives this as the path:
Screenshot from 2022-03-16 11-57-10.png

But this is the other path that I see:

Screenshot from 2022-03-16 11-53-47.png

Neither path seems to work. Do we need to be running bitcoind while running specter?

**Comment by Campanada1130** [comment]
Sorry the screenshots did not translate over so here goes:
FIRST PATH

ghost@ghost-HP-Laptop-15-ef1xxx:~/Core/bitcoin$ echo $PATH/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/sbin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

THE SECOND PATH IS 
ghost@ghost-HP-Laptop-15-ef1xxx:~/Core/bitcoin$ 

Question 2: 
Do we need to be running bitcoind whenever we run the specter desktop node?

**Comment by Campanada1130** [comment]
We are working on Linux OS (Mint Cinnamon).
Thank you for your help.

**Comment by k9ert** [comment]
I'm a bit confused what your issue is. I think you could greatly profit from reading a bit more documentation. Here is one which might be fitting to your issue:
https://docs.specter.solutions/desktop/connect-your-node/

**Comment by Campanada1130** [comment]
Thank you so much for responding... I am trying to use a linux mint cinnamon platform on an HP dedicated computer. Both linux and specter are new to me... so I have suffered a bit with all the new tech and language, but my son gave me a hand and we have loaded the program successfully.

We have installed the bitcoin core and run bitcoind and can see the core running. We encounter a problem when trying to connect Specter to the core. We don't seen to have the correct path because every time we test the connection, it says "Test failed: connection to node failed".

I have tried getting the path through the terminal two different ways. When I type echo $PATH the terminal gives this as the path:
[Screenshot from 2022-03-16 11-57-10.png]

But this is the other path that I see:

[Screenshot from 2022-03-16 11-53-47.png]

Neither path seems to work. Do we need to be running bitcoind while running specter?

thank you,
All the best,
Jess

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by k9ert** [comment]
Unfortunately i can't see the screenshots as they are not attached.

> Do we need to be running bitcoind while running specter?

Definitely yes. But that's only currently the case. We're working on a version of specter where you don't need anymore a node. Maybe it's worth for you waiting for that version?

**Comment by Campanada1130** [comment]
Thank you that probably is a proton mail thing!!! All that privacy can cause problems.. Can't wait till your new version. What are you planning to do about compatibility with lightning or will stay with liquid?

All the best,
Jess

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
