### ISSUE TITLE
Failed building wheel for hidapi 18.04.6 LTS Ubuntu

### ISSUE THREAD

**Issue by wild-kard** [cryptoadvance/specter-desktop#1631]
First of all I have tried running

`sudo apt install libusb-1.0-0-dev libudev-dev python3-dev`

as described [here](https://github.com/cryptoadvance/specter-desktop/issues/902)

and 

`sudo apt-get update`

after the fact.

when I try to install specter desktop with pip I get the following error

`Building wheels for collected packages: hidapi
  Building wheel for hidapi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-its5nioc/hidapi_0f5fe8cfa6ee47418ffd0259514b7dd0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-its5nioc/hidapi_0f5fe8cfa6ee47418ffd0259514b7dd0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_ep5f_os
       cwd: /tmp/pip-install-its5nioc/hidapi_0f5fe8cfa6ee47418ffd0259514b7dd0/
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_ext
  Compiling hid.pyx because it changed.
  [1/1] Cythonizing hid.pyx
  /tmp/pip-install-its5nioc/hidapi_0f5fe8cfa6ee47418ffd0259514b7dd0/.eggs/Cython-3.0.0a10-py3.6.egg/Cython/Compiler/Main.py:346: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-its5nioc/hidapi_0f5fe8cfa6ee47418ffd0259514b7dd0/hid.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'hid' extension
  error: unknown file type '.pxd' (from 'chid.pxd')`
  ----------------------------------------
  `ERROR: Failed building wheel for hidapi`

 `Running setup.py clean for hidapi
Failed to build hidapi
Installing collected packages: hidapi, ecdsa, click, base58, zipp, urllib3, pyaes, mnemonic, libusb1, idna, flask, certifi, bitbox02, stem, requests, python-dotenv, pysocks, pyserial, importlib-metadata, hwi, flask-login, flask-cors, daemonize, cryptoadvance.specter
    Running setup.py install for hidapi ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-its5nioc/hidapi_0f5fe8cfa6ee47418ffd0259514b7dd0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-its5nioc/hidapi_0f5fe8cfa6ee47418ffd0259514b7dd0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gmzwwal9/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/collin/.local/include/python3.6m/hidapi
         cwd: /tmp/pip-install-its5nioc/hidapi_0f5fe8cfa6ee47418ffd0259514b7dd0/
    Complete output (5 lines):
    running install
    running build
    running build_ext
    building 'hid' extension
    error: unknown file type '.pxd' (from 'chid.pxd')`
    ----------------------------------------
`ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-its5nioc/hidapi_0f5fe8cfa6ee47418ffd0259514b7dd0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-its5nioc/hidapi_0f5fe8cfa6ee47418ffd0259514b7dd0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gmzwwal9/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/collin/.local/include/python3.6m/hidapi Check the logs for full command output.`

I have tried simply using the appimage but I get the 255 error describe [here ](https://github.com/cryptoadvance/specter-desktop/issues/1484)

**Comment by k9ert** [comment]
Is there any reason you're not using 20.04LTS ? I don't think we can afford such old platforms.

**Comment by wild-kard** [comment]
That's fair. No reason in particular actually, I should probably upgrade.
