### ISSUE TITLE
After version 1.7.2 can't edit labels

### ISSUE THREAD

**Issue by BTCBellyButton** [cryptoadvance/specter-desktop#1645]
The edit pencil isn't there since 1.7.2.
See screenshots:

![Screenshot from 2022-03-31 16-48-24](https://user-images.githubusercontent.com/68573637/161155122-870a5b69-df34-4e56-9122-35f2de06ac15.png)

1.7.2:
![Screenshot from 2022-03-31 17-00-18](https://user-images.githubusercontent.com/68573637/161156394-029afc9f-6ad2-4300-bfea-6c8aaa66d628.png)

**Comment by k9ert** [comment]
Yes, i can confirm that. It seems to be a specific problem occuring while migrating from a specific version to the newest. Stay tuned.

**Comment by BTCBellyButton** [comment]
Works again in 1.9.1,
Thanks!
