### ISSUE TITLE
Pagination: right arrow does not work

### ISSUE THREAD

**Issue by BTCBellyButton** [cryptoadvance/specter-desktop#1655]
The right arrow doesn't bring you to the next page:
![Screenshot from 2022-04-05 10-46-31](https://user-images.githubusercontent.com/68573637/161793798-dd38064f-0cab-4836-9c89-93f1a2651282.png)

The left works fine instead.

**Comment by moneymanolis** [comment]
Another bug that will be fixed in #1580
