### ISSUE TITLE
Pagination: Scroll bar should act only on the table content

### ISSUE THREAD

**Issue by BTCBellyButton** [cryptoadvance/specter-desktop#1656]
It'd be better **not** to scroll this part:

![Screenshot from 2022-04-05 10-52-58](https://user-images.githubusercontent.com/68573637/161795110-5c0f76dc-3a9f-46b5-bc0e-355905566385.png)

But only the actual TX/UTXO

**Comment by k9ert** [comment]
@moneymanolis can you please qualify? However, i can't see the issue from the screenshot.
