### ISSUE TITLE
Error adding Bitcoin Core (hot wallet) Device Type

### ISSUE THREAD

**Issue by sponge-b0b** [cryptoadvance/specter-desktop#1658]
```
Traceback (most recent call last):
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "flask_login\utils.py", line 269, in decorated_view
  File "cryptoadvance\specter\server_endpoints\devices.py", line 207, in new_device_mnemonic
  File "cryptoadvance\specter\util\mnemonic.py", line 42, in validate_mnemonic
  File "mnemonic\mnemonic.py", line 115, in detect_language
mnemonic.mnemonic.ConfigurationError: Language not detected
```

**Comment by k9ert** [comment]
Which browser are you using on which operating system? Seems like your language-setup is somehow screwed?

**Comment by sponge-b0b** [comment]
OS: Windows 10 Home 64-Bit
Version: 10.0.19043 Build 19043

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
Build ID: 20220330194208

**Comment by k9ert** [comment]
Sorry, my fault. This has nothing to do with the browser but with the seed-words. [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md) allows the seed words to be in different languages. You don't specify the language when you write in the seed words. So the algorithm gets the first word from your list and tries to find them in the different lists. That's the way the language is detected.

So in you case it could not find the first word in any of these lists. Please double-check!

**Comment by k9ert** [comment]
Just saw that you used the english language. So i just tried to reproduce on the master branch with 
```
ghost ghost ghost ghost ghost ghost ghost ghost ghost ghost ghost machine
```
That worked without an issue. Can you test that?!
