### ISSUE TITLE
Send max with multiple recepients

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-desktop#1663]
When I send money to several addresses and click "Send max" not on the first one, Specter subtracts fee from the first output.

Expected behaviour: fee should be subtracted from the output where I clicked "Send max".
Previously we had an input that was specifying which output to subtract from, not sure why it was removed.

![image](https://user-images.githubusercontent.com/1706012/162437670-9cea157b-0a81-436c-9598-724b26b76195.png)

![image](https://user-images.githubusercontent.com/1706012/162437701-967c395c-36fb-42f6-ad3f-d30ea7726eda.png)

**Comment by moneymanolis** [comment]
The additional input field probably "got lost" during refactoring. 
This could be a good issue for the current Summer of Bitcoin students.

**Comment by Sahaj-Srivastava24** [comment]
I'm interested in working on this issue.

**Comment by devesh-002** [comment]
Hey @moneymanolis  I am an SoB applicant and went though the issue, in this basically under the if statement of line Number 585 of file mentioned we need to set the visibility true by 
```
FeeSelectionComponent.showSubtractFrom(true)
```
 and when it becomes to text then to
```
FeeSelectionComponent.showSubtractFrom(false)
```
This might resolve the issue.

**Comment by ahv15** [comment]
I'd like to work on this issue.

**Comment by ahv15** [comment]
![image](https://user-images.githubusercontent.com/52852877/171211615-07e97aaa-9c07-4b87-808b-b5deb474409e.png)
![image](https://user-images.githubusercontent.com/52852877/171211679-c95db2fa-a57e-4e6b-9962-a504c6313094.png)

**Comment by moneymanolis** [comment]
There is slight JS bug in the send max function. If you go about it in the exact order that Stepan describes, the `Subtract from recipient number ` field is not automatically appearing despite the `Subtract fees from amount `checkbox being checked:

https://user-images.githubusercontent.com/70536101/171625114-a9bdf51f-d1e1-428f-b526-c1d50197bd8f.mov
