### ISSUE TITLE
scanning QR codes doesn't work

### ISSUE THREAD

**Issue by stefanwouldgo** [cryptoadvance/specter-desktop#167]
When I click scan on the send page, I get asked for camera permissions, I give them, I see the camera picture, but QR codes are not recognized. I tried bech32 bitcoin addresses from both Samourai and Phoenix wallet.

**Comment by stepansnigirev** [comment]
Are you using the latest specter-desktop release? What browser?
Maybe try updating specter with `pip3 install cryptoadvance.specter --upgrade`

I just checked on the latest release that we have - scanning fine on Chrome and Firefox.
It doesn't verify what it is scanning on the send page, so any content of the qr code should be placed into the address field.

**Comment by stefanwouldgo** [comment]
Thank you for the instant reply!

I installed specter via pip3 yesterday. Unfortunately, the upgrade command
you recommended crashes on my Ubuntu 18.04 (segfault). I used Chrome 66.
Just doesn't seem to recognize any QR codes.

Am Fr., 19. Juni 2020 um 15:25 Uhr schrieb Stepan Snigirev <
notifications@github.com>:

**Comment by stepansnigirev** [comment]
I don't have an ubuntu machine with me at the moment, but I will try tonight when I get back home.

**Comment by stepansnigirev** [comment]
I tried on Ubuntu and Chrome, didn't have any problems.
I can't test on Chrome 66 as current version is 83 and I have no idea how to downgrade.

I would suggest to upgrade your browser, also you can check the developer console and see if there are any JavaScript errors.

**Comment by stefanwouldgo** [comment]
Thank you, updating Chrome did the trick. Unfortunately, now there is a new
issue: https://github.com/cryptoadvance/specter-desktop/issues/168


Am So., 21. Juni 2020 um 10:37 Uhr schrieb Stepan Snigirev <
notifications@github.com>:

**Comment by dtrammell** [comment]
I am also having this problem when trying to read QR codes from wallet backup PDF files to add the account to a new Specter instance.  Putting a QR code infront of the camera doesn't seem to trigger a read of the QR code.  I've tried different lighting, the QR code seems fairly well focused in the image, and I am running the most recent version of Specter (1.2.2) for Windows 10.  This is using the built-in camera on my laptop.

**Comment by Camilojdl** [comment]
> I am also having this problem when trying to read QR codes from wallet backup PDF files to add the account to a new Specter instance. Putting a QR code infront of the camera doesn't seem to trigger a read of the QR code. I've tried different lighting, the QR code seems fairly well focused in the image, and I am running the most recent version of Specter (1.2.2) for Windows 10. This is using the built-in camera on my laptop.

Same problem on my side, using windows 10 and Specter Version: v1.5.1

**Comment by stepansnigirev** [comment]
I reopened the issue and will do some checks on Windows.

**Comment by k9ert** [comment]
Closing this issue as it is to unspecific. There are a lot of reports about issues scanning QR-codes. Details usually vary a lot:
* from paper or from screen (tap the qr-code in specter-DIY on order to get a white background which makes it much easier)
* internal or external cameras (specificall also relevant: fixed focus or variable focus)
* lightning (usually natural light improves it)

Most people need to figure it out on there own and most people also get it working one way or another. Please reopen if necessary.
