### ISSUE TITLE
Recreating wallets from .dat and .dat-journal files

### ISSUE THREAD

**Issue by Quenos** [cryptoadvance/specter-desktop#1677]
I've had some issues with my SSDs resulting in a loss of the Specter wallets.
I'm able to recreate the wallets, but lost the comments I attached to the UTXOs that show the origin or destination of the coins.
The .dat and .dat-journal files still exist in a back-up and I had hoped that those contain the comments.

However I'm not able to persuade Specter to load these files, and also copying them into the re-created wallets is not working.
Is there a way to get the comments back?

**Comment by k9ert** [comment]
First of all: Check the json-backups of your wallet. If you did the right backup, the labels should be in there. Are they?
Recovering the labels out of the dat-files might be possible via the bitcoin-core-rpc but is definitely out of scope for this repo here.

**Comment by Quenos** [comment]
Hi, yes it worked with the JSON updates, but I created a new wallet half a year ago which I failed to back-up.

**Comment by k9ert** [comment]
Sorry for your loss but closing the ticket here. I'd suggest you copy the dat-file in a newly created node (i don't think it needs to be synced at all) and try to load the wallets and receive the labels via the bitcoin-cli.
https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line
