### ISSUE TITLE
New Idea

### ISSUE THREAD

**Issue by gusantoscode** [cryptoadvance/specter-desktop#1678]
Hi, I have an idea that maybe I can contribute to the project.

**Note before starting to explain: I don't know if this already exists or if it would be possible, however, I believe that if it were possible, it would be something very useful for the community in general.**

Explanation:
  - Well, I thought that if the specter desktop had a kind of "Operating System" of its own, it would be something lighter to host a node, for computers with little memory or for users who simply don't want to install another OS. For example, currently (to my knowledge), it is only possible to create a node with spectre by installing it on an already existing operating system, such as linux, windows, mac (which already take up some space on the HD), however, if specter were it an OS, with basic functions, in addition to the wallet, like a terminal for administrative functions and a connection to the tor network (it wouldn't necessarily need a browser) it would be much lighter than any linux or other OS.

**If I'm being silly, I'm sorry.**

**Comment by k9ert** [comment]
What's the difference to a raspiblitz? Specter is quite flexible regarding its deployment possibilities and therefor has been integrated in a lot of other projects but we can't provide that ourself.
So feel free to do it or encourage others to do it (e.g. your favorite OS to provide packages ...).
