### ISSUE TITLE
confirmed tx stays "locked in pending"

### ISSUE THREAD

**Issue by stefanwouldgo** [cryptoadvance/specter-desktop#168]
I have received a tx that took some time to confirm. Now it has been confirmed about 200 blocks deep (specter says so), but I still cannot send funds:  "- BTC, Available: 0;  Locked in pending transactions: xxxx".

**Comment by stepansnigirev** [comment]
Go to the pending tab, you will probably see there a draft of the transaction. Specter locks funds for this transaction.
You can delete it and then it will unlock the funds.

It is done to prevent spending the same inputs in several partially signed transactions.

**Comment by stepansnigirev** [comment]
Here what it looks like:

<img width="815" alt="Screenshot 2020-06-21 at 11 21 38" src="https://user-images.githubusercontent.com/1706012/85221106-7616a400-b3b1-11ea-8f07-48ab53b6a5bd.png">

**Comment by stefanwouldgo** [comment]
Ah, thank you. That is a little surprising, since pending is often used for unconfirmed txs. Maybe there is a clearer way of phrasing it in the UI, something like "unsigned txs".

**Comment by ben-kaufman** [comment]
Yeah I see how this terminology could be confusing here. I opened a PR #171 with slightly modified wording, please let me know if that's clear enough that way.

**Comment by stefanwouldgo** [comment]
That's much better, thank you.
