### ISSUE TITLE
Wallet balance

### ISSUE THREAD

**Issue by romfordpele** [cryptoadvance/specter-desktop#1703]
OK this might be an easy one.

My balance shown when I sign into Specter is more coins than I actually have. This shows the total balance of all wallets.

My 'zpub' wallet has my actual correct balance, and my 'main' has a smaller amount but the addresses appear to be just duplicates from my zpub. It makes sense that the 'total' balance has added these wallets together to get the total but what I don't understand is why both wallets don't show the exact same balance.

Perhaps I'm being a dummy here but it's just a bit confusing. Not sure is anyone has any idea how this could happen, perhaps it was something in how I set the wallets up?

**Comment by moneymanolis** [comment]
So, in a nutshell the question here is why your main wallet has less amount. 
Check your key pool below and perhaps make a UTXO rescan again. In general, though, I don't fully understand why you have two wallets with the exact same xpub.

![image](https://user-images.githubusercontent.com/70536101/167100856-0f7b8280-34fb-452e-9899-55a837d7fa1d.png)

**Comment by k9ert** [comment]
Having two wallets with the same xpub really doesn't make sense. We addressed some of that in https://github.com/cryptoadvance/specter-desktop/pull/1500 but it may still be possible to do it.

**Comment by k9ert** [comment]
Ups, accidentally closed it. I assume you can't create the same wallet twice in the meantime. You can reopen the issue if that's still possible.
