### ISSUE TITLE
Stuck on "Launching Specter-Desktop" Win 10

### ISSUE THREAD

**Issue by Funman2** [cryptoadvance/specter-desktop#1709]
Specter Desktop running on Windows 10 Home after initial installation is always stuck on the endless pacman with "Launching Specter Desktop" ...no matter what version of Specter i am using. Killing multiple tasks in task manager named "Specter" and Specterd (2 Instances) did not resolve the issue.

![image](https://user-images.githubusercontent.com/105175715/167316425-3a06d8d1-bd2a-48bc-86ef-87738919be11.png)

**Comment by k9ert** [comment]
Sorry for the late reply. Do you have anything from the logs? 
Maybe something in here helps:
https://docs.specter.solutions/desktop/endless-pacman/

Also make sure to unplug all your sophisticated usb-hardware (including hardwarewallets) if you have any.

**Comment by Funman2** [comment]
Thank you so much for your reply! We already talked in the telegram group.
I solved the issue by reinstalling  windows (clean install) specter works like a true charm now!
I love the app!

Best regards
Alexander



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Kim Neunert ***@***.***>
Datum: 18.05.22 11:11 (GMT+01:00)
An: cryptoadvance/specter-desktop ***@***.***>
Cc: Funman2 ***@***.***>, Author ***@***.***>
Betreff: Re: [cryptoadvance/specter-desktop] Stuck on "Launching Specter-Desktop" Win 10 (Issue #1709)


Sorry for the late reply. Do you have anything from the logs?
Maybe something in here helps:
https://docs.specter.solutions/desktop/endless-pacman/

Also make sure to unplug all your sophisticated usb-hardware (including hardwarewallets) if you have any.

**Comment by k9ert** [comment]
That was caused by a broken USB-driver. Reinstallation helped.

**Comment by Funman2** [comment]
I finally found out specter was blocked by some 'protective' features by acronis true image software, after uninstalling acronis I could just start up specter normally without any issues!
