### ISSUE TITLE
build-unix.sh  failes in Ubuntu 22.04

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1710]
**Describe the bug**
Running `cd pyinstaller` and `./build-unix.sh`  gives the error message:
```
Traceback (most recent call last):
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 464, in assemble
    ctypes_binaries = scan_code_for_ctypes(co)
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/site-packages/PyInstaller/depend/utils.py", line 110, in scan_code_for_ctypes
    binaries = __recursively_scan_code_objects_for_ctypes(co)
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/site-packages/PyInstaller/depend/utils.py", line 172, in __recursively_scan_code_objects_for_ctypes
    libname = ctypes.util.find_library(libname)
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/ctypes/util.py", line 351, in find_library
    _get_soname(_findLib_gcc(name) or _findLib_ld(name))
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/ctypes/util.py", line 148, in _findLib_gcc
    if not _is_elf(file):
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/ctypes/util.py", line 100, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibsecp256k1.a'

```

**Expected behavior**
It should find the library and continue with building a binary.  **In Ubuntu 20.04 it builds fine.**  

If I go into "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/ctypes/util.py" and catch the library name and change it to b'libsecp256k1.a' it can find it and continues flawlessly with the built.

_Could this be a Pyinstaller bug?  Or embit?_

**Desktop (please complete the following information):**
 - Ubuntu 22.04, Pyinstaller 4.9
 - Specter Version: current master

**Comment by relativisticelectron** [comment]
In Ubuntu 20.04  
![image](https://user-images.githubusercontent.com/60378539/169772257-eb8c1c1f-0623-4889-a2ae-eb9e7594388a.png)
in https://github.com/pyinstaller/pyinstaller/blob/dc093332c49da0a1693384e0f2fd7e37ad2324d4/PyInstaller/depend/utils.py#L162  gets me
![image](https://user-images.githubusercontent.com/60378539/169772167-0b87897a-75ac-4280-99dd-e4ab1969299f.png)


In Ubuntu 22.04 I get the error mentioned above.... really strange....

**Comment by relativisticelectron** [comment]
Hmm... `./build-unix.sh` was removed... ok.   Trying https://github.com/cryptoadvance/specter-desktop/blob/master/docs/build-instructions.md

**Comment by relativisticelectron** [comment]
https://github.com/cryptoadvance/specter-desktop/blob/v1.9.4/pyinstaller/build-unix.sh  was deleted.

**Comment by relativisticelectron** [comment]
The issue arises too when I do locally
https://github.com/cryptoadvance/specter-desktop/blob/2f0f743ccd17128993289eba57abcb34b05b62ff/.gitlab-ci.yml#L172

**Comment by relativisticelectron** [comment]
The cpython bug is being taken care of in https://github.com/pyinstaller/pyinstaller/pull/6864 
So we could migrate to the coming pyinstaller version.

**Comment by k9ert** [comment]
If i get this right, than we need to upgrade pyinstaller from 4.9 to 5.2 in order to fix this issue. That's not too bad.
I've created a branch on my fork and created a pre-release here:
https://github.com/k9ert/specter-desktop/releases/tag/v1.10.4-pre3
