### ISSUE TITLE
unncecessary scrolling

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#1722]
**Describe the bug**
Currently, the list of transactions is only 6 TX long. You have to scroll even though you might have lots of space on your screen.
![scrolling](https://user-images.githubusercontent.com/117085/168476060-e5c58601-af98-44a6-8633-6b75893f13c3.gif)

**Comment by ankur12-1610** [comment]
I would like to work on it😅

**Comment by ankur12-1610** [comment]
@k9ert I was planning to it this way - 

https://user-images.githubusercontent.com/76884959/168595187-f3ca5c94-2d8b-4445-8905-7e4ef12c77dd.mp4

Or do we need a scrollable table?

**Comment by moneymanolis** [comment]
@ankur12-1610
It was a user request to implement a scrollable table, mainly to keep this part of the table (`<div class="search-container">`) visible when scrolling down:
<img width="835" alt="image" src="https://user-images.githubusercontent.com/70536101/168836873-bd162d58-5fcb-4472-a058-fbedd7e95ad3.png">

For now, the requirement would be to keep that functionality.
I think one way to make the height of the table-container more adaptive would be by setting the height of the table container using the viewport's (visible page area) height (using a percentage of the viewport height). See here: https://stackoverflow.com/questions/39190742/css-fill-height-of-screen-when-window-is-zoomed-100

**Comment by ankur12-1610** [comment]
> @ankur12-1610 It was a user request to implement a scrollable table, mainly to keep this part of the table (`<div class="search-container">`) visible when scrolling down: <img alt="image" width="835" src="https://user-images.githubusercontent.com/70536101/168836873-bd162d58-5fcb-4472-a058-fbedd7e95ad3.png">
> 
> For now, the requirement would be to keep that functionality. I think one way to make the height of the table-container more adaptive would be by setting the height of the table container using the viewport's (visible page area) height (using a percentage of the viewport height). See here: https://stackoverflow.com/questions/39190742/css-fill-height-of-screen-when-window-is-zoomed-100
> 
> As a side note, I would also think about changing the default page limit from 50 to sth. lower.

Sure, working on it :)

I was thinking to set the default page limit to 25, does that sound right?
