### ISSUE TITLE
Incorrect linkings in `development.md`

### ISSUE THREAD

**Issue by ankur12-1610** [cryptoadvance/specter-desktop#1726]
**Describe the bug**
The current `developement.md` has an incorrect link to `cypress-testing.md`, `
artifacts-session` and `archblog`.
**To Reproduce**
Visit:
https://github.com/cryptoadvance/specter-desktop/blob/master/docs/development.md#cypress-ui-testing

**Expected behavior**
The link should be corrected.

- For `cypress-testing.md`:
Correct link: https://github.com/cryptoadvance/specter-desktop/blob/master/docs/cypress-testing.md
Current link: https://github.com/cryptoadvance/specter-desktop/blob/master/docs/docs/cypress-testing.md

- For `archblog`:
Correct link: https://github.com/cryptoadvance/specter-desktop/blob/master/docs/archblog.md
Current link: https://github.com/cryptoadvance/specter-desktop/blob/master/docs/docs/archblog.md

- For `arctifacts-session`:
Correct link: https://github.com/cryptoadvance/specter-desktop/blob/master/.gitlab-ci.yml
Current link: https://github.com/k9ert/specter-desktop/blob/cypress/.gitlab-ci.yml#L53-L58

**Screenshots**
![Screenshot from 2022-05-19 13-56-40](https://user-images.githubusercontent.com/76884959/169248698-c468ab67-7050-47c3-83d9-99bf42239b07.png)

**Desktop (please complete the following information):**
 - Where is your node running: local(internal)
 - Where is your specter running: Node
 - If you're running a binary, which OS: Linux
 - Browser: chrome
 - Specter Version [custom]

**Comment by ahv15** [comment]
There seems to be an incorrect link to `archblog` and `artifacts-section` too.
