### ISSUE TITLE
Error setting up Tor on Ubuntu 20.04 “non-zero exit status 127.”

### ISSUE THREAD

**Issue by PLK2** [cryptoadvance/specter-desktop#1727]
I’m running Ubuntu 20.04 and specter v1.9.4. Getting the error “Command ‘exec “/home/…….” —hash-password …….. returned non-zero exit status 127.”
Is there a fix for this?

_Originally posted by @PLK2 in https://github.com/cryptoadvance/specter-desktop/issues/1196#issuecomment-1133756656_

**Comment by k9ert** [comment]
Can you be more precise here? I recently created an issue template which can give you better guidance on how to report an issue. Mainly: 
* What's the exact error-message?
* What's your deployment-method?
* What did you do which caused the error-message?

**Comment by PLK2** [comment]
Error message: “Command ‘exec “/home/…….” —hash-password …….. returned non-zero exit status 127.”

deployment method: not sure what this means.

Action caused error: fresh install Specter v2.9.4 on Ubuntu 20.04. In Specter, go to Settings / setup Tor. Using Specter locally only. Auto setup of tor failed with the error message above.

**Comment by k9ert** [comment]
I tried to reproduce this but couldn't with the exact same setup an a pre-release version.
The Error-message is still incomplete to me. Why are there so many dots in there? Where is it coming from? Is it from the log-file or did you copy it from a message in the UI?
I assume you have downloaded a binary for linux, right? That's what's meant by Deployment-method.
