### ISSUE TITLE
Multisig beginner guide missing in specter

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1728]
For beginners or even people familiar with single-sig, multisig is quite intimidating.   While specter is designed to make this easy, there is no step-by-step guide in specter.  And the first google/duckduckgo results lead to many altcoins, good ressources are hard to find.

On the welcome page (and or on the Create wallet --> Multisig) page we add a link to a new "Multisig Introduction" page.  There could be
a) A self written overview and step-by-step guide
b) or simply links to guides like  
- Overviews like:  https://multisigtools.com/  or  https://coinguides.org/multisig-multi-signature-wallet/
- Step-by-step with specter: https://btcguide.github.io/setup-wallets/coordinate-multisig  or  https://shiftcrypto.ch/blog/specter-multisig-guide/
- Or even videos:  https://www.youtube.com/watch?v=ZQvCncdFMPo

Questions:
- Do you agree that this would be useful? 
- Could this "Multisig Introduction" be designed differently?
- Are there better guides out there?  Should we write an own step-by-step-guide?

**Comment by k9ert** [comment]
I think that would be a very good idea. @moneymanolis @moritzwietersheim your thoughts?

**Comment by moritzwietersheim** [comment]
Fantastic - yes, this would be very useful. 
There is also https://bitcoiner.guide/multisig/  - as a pretty good guide from BitcoinQnA.
Probably it would be good to do an own guide, by taking the best from the other guides from the community.

**Comment by relativisticelectron** [comment]
Thanks for the positive feedback.   The guide could be placed in [project-docs](https://docs.specter.solutions/desktop/) , and the welcome page (or  Create wallet --> Multisig) link to it.

**Comment by relativisticelectron** [comment]
I would offer to write a draft of guide (though I have never written a guide). I was thinking of

- keep it as short as possible (and link to more comprehensive guides, and videos like https://bitcoiner.guide/multisig/), but do not neglect crucial points like: 
  - Backing up ALL the xpus (and derivation paths)  
  - Where to put the seeds/backups and devices to make a geographically distributed setup?
  - Set up a watch-only wallet with specter
  - Test sending it out with small amounts first 
- Stick to the most common 2 of 3  setup for long term cold storage

Should I do that, or has anyone else experience in writing guides?

**Comment by moneymanolis** [comment]
Would be great if you could start off with a guide, and the agenda sounds good. I'd offer to help integrate it nicely in the front end.

**Comment by relativisticelectron** [comment]
Ok. I'll do that.

**Comment by djpnewton** [comment]
at the moment there is a link to https://github.com/cryptoadvance/specter-desktop/blob/master/docs/multisig-security-tradeoffs.md on the create wallet (multisig) page. It would be good to have a more comprehensive guide

**Comment by relativisticelectron** [comment]
> at the moment there is a link to https://github.com/cryptoadvance/specter-desktop/blob/master/docs/multisig-security-tradeoffs.md on the create wallet (multisig) page. It would be good to have a more comprehensive guide

Right. I am on it: https://github.com/relativisticelectron/specter-desktop/blob/20220523_multisig_doc/docs/multisig-guide.md

**Comment by relativisticelectron** [comment]
Solved with https://github.com/cryptoadvance/specter-desktop/pull/1731
