### ISSUE TITLE
Export wallet's PDF backup doesn't open in current `master` branch

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#1738]
**Describe the bug**
Cannot open a wallet's backup PDF file.

**To Reproduce**
1. Navigate to a wallet (multisig in my case)
2. Click on its Settings tab
3. Click on the Export sub tab
4. Click on "Open backup PDF"

Nothing happens. If you open a console window, there's no error. Viewing the source I don't see anything wired up to the button `id="pdf-wallet-download"`. So I think the button is literally doing nothing when clicked.

**Expected behavior**
Should open the wallet's backup PDF file.

**Desktop (please complete the following information):**
 - Where is your node running: local regtest
 - Where is your specter running: local from current (2022-05-28) `master` branch
 - If you're running a binary, which OS: Not a binary, but on macOS
 - Browser: Chrome 101.0.4951.64
 - Specter Version: n/a (current `master`)

**Comment by moneymanolis** [comment]
I could reproduce the bug, looks like it is only not working with multisig wallets, with singlesig wallets it works for me.
