### ISSUE TITLE
Error trying to rescan UTXO

### ISSUE THREAD

**Issue by frankcastro** [cryptoadvance/specter-desktop#1756]
Hi I recently reinstalled Specter Desktop and I am trying to Rescan UTXO and I am getting this error: 

Traceback (most recent call last):
  File "flask/app.py", line 1523, in full_dispatch_request
  File "flask/app.py", line 1509, in dispatch_request
  File "flask_login/utils.py", line 269, in decorated_view
  File "cryptoadvance/specter/server_endpoints/wallets.py", line 785, in settings
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by relativisticelectron** [comment]
The line is https://github.com/cryptoadvance/specter-desktop/blob/b83c26afcf3a9f945c040d06e200229bbcd0c169/src/cryptoadvance/specter/server_endpoints/wallets.py#L785

And I interpret that that the blockchain explorer is not reachable

**Comment by frankcastro** [comment]
Hi thank you, I checked in Preferences and in Block explorer URL (main):
is set to 
   Mempool.space Tor hidden service

The wallet is working correctly it has all the BTC, I really don't need to run Rescan UTXO

Thank you

**Comment by relativisticelectron** [comment]
> Hi thank you, I checked in Preferences and in Block explorer URL (main): is set to Mempool.space Tor hidden service
> 
> The wallet is working correctly it has all the BTC, I really don't need to run Rescan UTXO
> 
> Thank you

Great to hear specter is working for you. If the issue arises again please write here. I still am unclear how this could have occurred.

**Comment by k9ert** [comment]
This might have to do with Users. Do you use multiple-users? Can you check whether the Admin-User has a explorer set? And if he does not, does it disappear if it's set?

**Comment by minioff** [comment]
I'm experiencing the same issue as OP. Using latest version.

Have tried to set different block explorers, no change in behavior.

I do not have multiple users (everything default).
