### ISSUE TITLE
UI issues with French translation special characters

### ISSUE THREAD

**Issue by oxhak** [cryptoadvance/specter-desktop#1791]
**Describe the bug**
At start, french language is still used even if english is set and saved in the settings, french translation special caracters are causing troubles with interface buttons becoming unusable.

Possible solution: use \\' instead of ' for the translation, same for \\" instead of ".

**To Reproduce**
Start Specter, change language to French, enable developpers tools to watch the errors, click on a wallet, create or import a transaction, try to click on the button to scan the signed transaction, nothing will happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/2832152/178032161-273faca4-e48f-48ad-88e5-a53f08abaa23.png)
![image](https://user-images.githubusercontent.com/2832152/178033120-01b18c32-6ee9-44d6-8e79-8bab6abe6bf9.png)

**Desktop (please complete the following information):**
 - Specter Version V1.10.3

**Comment by relativisticelectron** [comment]
https://github.com/cryptoadvance/specter-desktop/blob/4d2abc75f518ff2d2901b002772a3d97ec53e79a/src/cryptoadvance/specter/templates/wallet/components/wallet_pdf.jinja#L94

So jinja2 is not handling strings in a safe way....  that is not great. How can we make jinja2 replace strings safely?

**Comment by oxhak** [comment]
I think your code is ok but not the translation file, the french one, you need to replace special character like this: 

Type d'appareil ---> Type d\\'appareil
(only one \\, github require two to be displayed here)

**Comment by relativisticelectron** [comment]
I disagree. The translation file should not be needed to be trusted. The code itself must handle unsafe translations.

**Comment by relativisticelectron** [comment]
Opened PR: https://github.com/cryptoadvance/specter-desktop/pull/1793

**Comment by relativisticelectron** [comment]
@oxhak : https://github.com/cryptoadvance/specter-desktop/pull/1793 was merged. Can you close the issue?
