### ISSUE TITLE
UI Bug: The Address table header isn't rendered correctly

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1794]
**Describe the bug**
The table header looks like this
![image](https://user-images.githubusercontent.com/60378539/178193042-a3c61b68-2047-40b9-b33a-1125e208d8f2.png)

There is the filter missing (is that intended?), and the "Page Limit:" is lonely on the left, while the actual page Limit selector is on the right...

**To Reproduce**
1. Go to `/wallets/wallet/<wallet>/addresses/` 
 
**Expected**
![image](https://user-images.githubusercontent.com/60378539/178193379-8ee168c9-98cb-4a63-acce-dbb9032b7319.png)

**Desktop (please complete the following information):**
 - Linux, local, current master

Tagging @moneymanolis

**Comment by moneymanolis** [comment]
There was no filter / search bar on the address list so far, which "makes sense" since it is not implemented as a web component as of yet so it was not some easy `{% include ... %}`.

I've fixed the alignment bug in a PR (#1779) that I will finalise soon.

**Comment by relativisticelectron** [comment]
> There was no filter / search bar on the address list so far, which "makes sense" since it is not implemented as a web component as of yet so it was not some easy `{% include ... %}`.
> 
> I've fixed the alignment bug in a PR (#1779) that I will finalise soon.

Ok, I didn't know that there is no address filter. That might me a good feature in the future.  Thanks for fixing the alignment.
