### ISSUE TITLE
Transactions in "unsigned" can be signed, just unbroadcast.

### ISSUE THREAD

**Issue by BitcoinMechanic** [cryptoadvance/specter-desktop#1803]
The text here should probably read "Transactions Awaiting Signing/Not Yet Broadcast To The Network"

![image](https://user-images.githubusercontent.com/45926711/179061258-0924d345-d93a-4c47-8344-cd713808b8e7.png)

**Comment by k9ert** [comment]
So a reasonable (not too long) text would be "Transactions Awaiting Signing/Broadcasting" ?

**Comment by BitcoinMechanic** [comment]
Yes

**Comment by BitcoinMechanic** [comment]
Or a whole new tab - "Signed (unbroadcast)

**Comment by PaarthAgarwal** [comment]
I feel this issue has been solved by #1972 and can be closed now.
