### ISSUE TITLE
UI: Sorting in the tx-table

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1805]
The UI is confusing, suggesting there is column sorting available:
![sorting](https://user-images.githubusercontent.com/60378539/179070812-b268a976-a2eb-4ff6-8635-6b8d659975bd.gif)

**Comment by k9ert** [comment]
Agree. That's indeed a stupid thing. I'd even recommend to remove these useless errors as a good_first_issue rather than having that confusion.

**Comment by PaarthAgarwal** [comment]
I think this issue has been solved by #1973 and can be closed.

**Comment by k9ert** [comment]
Thank you @PaarthAgarwal . Reviewing issues like that is very much appreciated!
