### ISSUE TITLE
UI: Messed up HTML in create unsigned transaction button and other places

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/specter-desktop#1809]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/70536101/179350574-d2772a2a-a6f5-478c-a33d-5e725ef5f730.png">

Seems like this only popped up after #1793. I have no idea why this InnerText was used like it is used here. Just having {{ _('Create unsigned transaction') }} should fix it.

Update: Looks like there are more HTML quirks. Apparently, everywhere where there are Babel jinja tags with HTML elements inside, those elements are now intepreted as strings / text. See for example the br tags here:
<img width="577" alt="image" src="https://user-images.githubusercontent.com/70536101/179352517-e69fed10-046e-4a25-8a29-b9a349bb9626.png">

@relativisticelectron can you have a look?

**Comment by relativisticelectron** [comment]
I guess we have to break the babel strings apart.  Translations should only be applied to text and not to html code....

**Comment by moneymanolis** [comment]
Thanks so much for this. 
Yes, the approach looks great. I also just double-checked this approach and it seems to fix the problem.

**Comment by relativisticelectron** [comment]
I can not finish now, I will do it this evening.

**Comment by moneymanolis** [comment]
No problem, it will take some time. Tedious work. It is finished when it is finished :-).

**Comment by relativisticelectron** [comment]
Ok, added the PR: https://github.com/cryptoadvance/specter-desktop/pull/1810
