### ISSUE TITLE
Error message when Bitcoin Core not connected

### ISSUE THREAD

**Issue by FrancisPouliot** [cryptoadvance/specter-desktop#182]
Upon my first install, connection to Bitcoin Core didn't work because of datapath.

On the specter UI, it just said on top left "Bitcoin" "none, none" which was not very explicit. Perhaps replace this with an error message more detailed with instructions or something. Not sure what though. Or maybe a Bitcoin Core: connected status ?

**Comment by stepansnigirev** [comment]
Good point! I created a PR to fix it: #184
