### ISSUE TITLE
UI Bug Mobile: Some elements are not viewable/accessible  , due to height issues

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1826]
On mobile (not the browser emulated mobile screen, but a real mobile phone, firefox), it shows that the last entry of the tx-table is not viewable. 
![Screenshot_20220728_220411_org mozilla firefox](https://user-images.githubusercontent.com/60378539/181682704-995e4ff4-d185-4d10-a0a2-33f0f329e670.jpg)

This is however not a problem due the tx-table, but occurs on every page. It is explained here: https://css-tricks.com/the-trick-to-viewport-units-on-mobile/
On mobile I get `window.innerHeight = 600, window.outerHeight = 656`

**Comment by moneymanolis** [comment]
This currently creates huge additional space at the bottom of the tx table for me:

<img width="1066" alt="grafik" src="https://user-images.githubusercontent.com/70536101/183256525-76f60690-9cae-4552-bc91-e2db14ff1e23.png">

I think it would be good to use media queries to restrict the extra spacing to mobile devices, have a look here for example: 
https://wpbuffs.com/media-query-for-mobile/

I could not reproduce the issue in the first place using Firefox but this depends on so much stuff besides the browser.

**Comment by relativisticelectron** [comment]
Fixed by https://github.com/cryptoadvance/specter-desktop/pull/1827
