### ISSUE TITLE
derivation path m/45h

### ISSUE THREAD

**Issue by bitcoin-beekeeper** [cryptoadvance/specter-desktop#1846]
**Describe the bug**
I have a few UTXOs with this derivation path but surely this isnt correct? Aren't there a few steps missing?

I want to sign a txt file on my coldcard and i need the derivation path to individual addresses

Thanks

**Comment by relativisticelectron** [comment]
When you click on an address you should see something like:
![image](https://user-images.githubusercontent.com/60378539/186644865-4ee8c746-0de6-413a-8c16-5850e6235f6e.png)

Here I have the 3. address of this wallet, and the derivation path is `m/84h/1h/0h/0h/3h`

**Comment by moneymanolis** [comment]
This was answered in the community chat. It is the multisig format of Coldcard. If you reading this, join the group and search for `m/45h` if you are interested in more. Closing this now.

**Comment by relativisticelectron** [comment]
@moneymanolis : Could you copy & paste the relevant answer here?  It would help future readers to quickly understand the solution.

**Comment by moneymanolis** [comment]
- This is a valid BIP32 based path, even though it is so short.
- 45 is the coldcard specific derivation path for multisig. The inofficial standard is 48, even though there has never been an official BIP for it.
- The relevant BIP for the "coldcard standard": https://github.com/bitcoin/bips/blob/master/bip-0043.mediawiki
