### ISSUE TITLE
Liquid: Adding L-sats

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/specter-desktop#1853]
Currently, switching to sats here:
<img width="569" alt="grafik" src="https://user-images.githubusercontent.com/70536101/186702988-a5718f26-72cb-4a38-9792-09d5f2f4c3a5.png">
does not change the units from LBTC to L-sats, for example in the address overview:
![grafik](https://user-images.githubusercontent.com/70536101/186703229-2f1818fd-8e0d-47f7-882e-497e54d7e4b9.png)

The amounts, as you can see, are changed, though.

**Comment by PaarthAgarwal** [comment]
Can you point me to relevant files and functions to fix this issue?

**Comment by moneymanolis** [comment]
I think I am closing this since we don't really support Liquid in Specter v2
