### ISSUE TITLE
Improve message when adding Ledger device

### ISSUE THREAD

**Issue by wombat6** [cryptoadvance/specter-desktop#1863]
When adding a new Ledger device, the current message says something like "Connect your Ledger". Then Specter doesn't find the device over USB. The problem I had was I didn't realize I had to activate the Bitcoin app on my Ledger before Specter would see it. My suggestion is to change the message to something like "Connect your Ledger. Be sure to activate the Bitcoin app on your Ledger so Specter can see the device."

**Comment by moneymanolis** [comment]
I am on it. I think we also need to add a device check when setting up a new device (at the` new_device_keys.` endpoint). Seems like this is not done for HWI / USB devices.
