### ISSUE TITLE
slider for fees not working in dynamic mode

### ISSUE THREAD

**Issue by topuli** [cryptoadvance/specter-desktop#1865]
**Describe the bug**
It is not possible to change the fees amount usind the slider in dynamic mode.
Opening the advanced section immediately after clicking send, the slider ist in the middle position. After a few seconds it moves to the left (very low). From here on i am not able to change the fees using the slider

**To Reproduce**
1. Go to send
2. Click on advanced
3. Watch the slider

**Expected behavior**
Ability to change the fees amount using the slider

**Screenshots**
![image](https://user-images.githubusercontent.com/48984696/187247942-5461b5d1-53cb-401d-8328-8473fc9fa944.png)

**Desktop (please complete the following information):**
 - Where is your node running: local (internal)
 - Where is your specter running: binary
 - If you're running a binary, which OS: Linux
 - Browser Firefox
 - Specter Version 1.10.5

**Comment by relativisticelectron** [comment]
I can confirm this bug.  In the beginning the slider works as expected, but then the slider gets stuck at minimum and can't move any more.

**Comment by relativisticelectron** [comment]
I guess the cause is a currently low fee environment and then https://github.com/cryptoadvance/specter-desktop/blob/9dfb6c3a775b18ccc0734795e7b878f0a42331b3/src/cryptoadvance/specter/templates/includes/fee-selection.html#L241  sets the minimum fee rate....

**Comment by relativisticelectron** [comment]
Was solved in  https://github.com/cryptoadvance/specter-desktop/pull/1878
