### ISSUE TITLE
Error in libusb1 during installation. 

### ISSUE THREAD

**Issue by StijnBTC** [cryptoadvance/specter-desktop#1874]
**Describe the bug**
While installing through pip3 I get the error message: 
```
Collecting libusb1==1.7.1
  Using cached libusb1-1.7.1.tar.gz (78 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in libusb1 setup command: use_2to3 is invalid.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
**To Reproduce**
run `pip3 install cryptoadvance.specter`

**Expected behavior**
No error messages during installation.

**Comment by relativisticelectron** [comment]
- Which OS are you on?
- which python version `python --version` are you using?

**Comment by StijnBTC** [comment]
uname -a:
`Linux ubuntu 5.15.0-1013-raspi #15-Ubuntu SMP PREEMPT Mon Aug 8 06:33:06 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`

Python 3.10.4

**Comment by relativisticelectron** [comment]
The pip installation does not work yet with python 3.10. We are however working on it to upgrade specter to be compatible with python 3.10: https://github.com/cryptoadvance/specter-desktop/pull/1688

**Comment by k9ert** [comment]
We're almost done with #1688 and there is already a publicly available pip-package. So install it like this:
```
pip3 install cryptoadvance.specter --pre
```
This should install [v1.13.0-pre1](https://github.com/cryptoadvance/specter-desktop/releases/tag/v1.13.0-pre1) which should solve this!

**Comment by StijnBTC** [comment]
Fixed it, thank you!
