### ISSUE TITLE
Add time series chart for wallet balances

### ISSUE THREAD

**Issue by wombat6** [cryptoadvance/specter-desktop#1876]
Some other wallet managers, like Ledger Live and Trezor Suite, have a time series chart that shows wallet balances over time in sats and fiat. For me this is a valuable feature.

One drawback for those HWW-specific UIs is that they don't handle wallets that span multiple HWWs, whether multisig or just multiple single sig wallets being managed on different HWWs. Something great about Specter is that it has a wallet overview page where you can see transactions across all wallets. Having a way to visualize UTXOs evolution over time would make this aggregation even more compelling.

This issue proposes to implement the time series chart feature using Specter's extension/plugin capability. The chart would appear for each individual wallet as well as for the aggregate view. I actually believe that the charts are sufficiently fundamental that they should be part of the core (that is, not a plugin), but I can appreciate that it's more careful to try it out as a plugin and let it prove its value there first.

For now, there is no need for fiat tracking. Just sats. We can treat fiat as an enhancement at a later time.

**Comment by wombat6** [comment]
I'll take this one. I have a repo at https://github.com/wombat6/specterext-stacktrack.

**Comment by moneymanolis** [comment]
Just throwing this in here: @ahv15 works on the Spotbit extension in Specter which will provide historical fiat prices if one wanted to add fiat tracking at some later stage as well.

**Comment by k9ert** [comment]
This is not yet released but stacktrack is in master since some time. Closing this.
