### ISSUE TITLE
Transaction history not appearing on the plugin transactions page

### ISSUE THREAD

**Issue by wombat6** [cryptoadvance/specter-desktop#1880]
I'm creating a new plugin, and I used the plugin generator to generate the boilerplate. Transaction history is not showing up on the plugin transactions page.

**To Reproduce**
1. Use the plugin generator to create a new plugin.
2. Add a device that's managing a seed with transactions and UTXOs. (I am using a Ledger. I don't know whether that matters.)
3. Create a single sig wallet for the new device.
4. Scan the blockchain for the transactions.
5. Go to the plugin page. 
6. Go to the Transactions tab.
7. Below you will see that the History tab is selected by default, and that it has no transactions.
8. Click the UTXO tab. You will see your UTXOs.

Note that behind the scenes, the Wallet data structure (obtained via `service.getAssociatedWallet()`) does actually include the transactions. I am able to see the transactions by calling `wallet.txlist()` and iterating over them. I can also see the transaction history on the core (non-plugin) transaction history tab. The history  just don't show up on the plugin UI for whatever reason.

**Expected behavior**
I expect the transaction history to appear on the plugin's transaction history tab.

**Screenshots**

<img width="1123" alt="missing_history" src="https://user-images.githubusercontent.com/112285082/189543658-6ee2ee74-2470-49d9-abeb-b5335c781b37.png">

In the screenshot above, note that there's an option to do a blockchain rescan. I clicked that (even though I already scanned the transactions when creating the wallet). But I get an error:

![wallet_settings](https://user-images.githubusercontent.com/112285082/189543642-c56bccc9-c122-4203-bb47-4b0344e82c11.png)

(This seems like a separate error.)

**Desktop (please complete the following information):**
 - I'm running against a MyNode on a separate Raspberry Pi.
 - My Specter is running on my MacOS laptop.
 - Browser is Safari.
 - Specter version is 1.12.0.

**Additional context**
- @moneymanolis suggested that the issue may be a fetch API call.
- I tried with a separate Ledger device and also a Trezor device, and got the same result (including the "Wallet settings does not exist" when I attempt to rescan the blockchain).

**Comment by k9ert** [comment]
I've created a note in the transaction-page to make that better transparent.
https://github.com/cryptoadvance/specterext-dummy/commit/0c2028a1287e4d44f0d25c9edd0414d58bbe1ee7

I'm closing this for now, please reopen if necessary.

**Comment by wombat6** [comment]
Thanks @k9ert. I was able to view the transactions by disabling the service ID in the way you describe. The additional explanation you added should help.

**Comment by wombat6** [comment]
For my own understanding -- can you give an example of what sort of use case the service/address binding feature might support? I think I get the mechanics involved, but don't understand what I'd use this for.
