### ISSUE TITLE
404 on static/img/expand-more.svg

### ISSUE THREAD

**Issue by wombat6** [cryptoadvance/specter-desktop#1881]
**Describe the bug**
I'm seeing

```
[2022-09-11 12:21:22,961] ERROR in controller: Could not find Resource (404): http://127.0.0.1:25441/static/img/expand-more.svg
[2022-09-11 12:21:22,962] INFO in _internal: 127.0.0.1 - - [11/Sep/2022 12:21:22] "GET /static/img/expand-more.svg HTTP/1.1" 404 -
```

on my console log when running Specter while developing a plugin.

**To Reproduce**
1. Generate a plugin with the plugin generator.
2. Configure it to show up in the menu.
3. Click the plugin in the menu.
4. You should see the 404 above.

**Expected behavior**
Don't expect to see any 404s.

**Desktop (please complete the following information):**
- Running Specter Desktop 1.12.0.

**Additional context**
The request originates with the menu Jinja template:

![Screen Shot 2022-09-11 at 12 25 49 PM](https://user-images.githubusercontent.com/112285082/189545493-2a3be998-749a-4c38-b543-8ed9e1579d2f.png)

**Comment by k9ert** [comment]
Yes confirmed. I searched for it with this:
https://stackoverflow.com/questions/953481/how-do-i-find-and-restore-a-deleted-file-in-a-git-repository

![expand-more](https://user-images.githubusercontent.com/117085/189838549-c8555d34-65c1-4821-99da-63a8a5a4e5ed.svg)

Maybe someone can add it again.

**Comment by PaarthAgarwal** [comment]
> Yes confirmed. I searched for it with this: https://stackoverflow.com/questions/953481/how-do-i-find-and-restore-a-deleted-file-in-a-git-repository
> 
> ![expand-more](https://user-images.githubusercontent.com/117085/189838549-c8555d34-65c1-4821-99da-63a8a5a4e5ed.svg)
> 
> Maybe someone can add it again.

I searched for it in all previous commits but couldn't find it. Opening a PR to add it manually.

**Comment by k9ert** [comment]
![expand-less](https://user-images.githubusercontent.com/117085/212909218-876c4817-427d-415a-b86a-59fad38b6e7d.svg)

Here is expand-less.svg

**Comment by PaarthAgarwal** [comment]
> ![expand-less](https://user-images.githubusercontent.com/117085/212909218-876c4817-427d-415a-b86a-59fad38b6e7d.svg)
> 
> Here is expand-less.svg

Found it just now using the commands on StackOverflow. I was doing it wrong that's why it didn't work yesterday. It's a great way of restoring deleted files!
