### ISSUE TITLE
UX improvement: maintain nav state

### ISSUE THREAD

**Issue by wombat6** [cryptoadvance/specter-desktop#1882]
This is an UX enhancement request.

When navigating around the app, Specter Desktop should remember which menus are open and closed. Specifically, Specter always expands the wallet menu, and always collapses the devices menu. I understand that wallets are probably more important than devices for normal usage, but it's atypical and disorienting for the menus to change on the user.

**Comment by otkstdio** [comment]
This is fixed in v2.0.0
