### ISSUE TITLE
Docs: Deployment Decision Guide

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#1884]
It's often enough confusing how specter can get installed. It would be great to have a structured guide which possibilities exist and which dis-/advantages each of them have. This should be an abstract article in the `User Guide` of the [Specter Desktop Documentation](https://docs.specter.solutions/desktop) and can/should reuse the content from [this presentation](https://www.slideshare.net/k9ert/deploying-specter-desktop-mechanism-not-policy).

Additionally, it should contain some kind of decision-matrix, flow-chart or at least some kind of heuristics which can help the user to make a decision for his deployment-choice.

Some resources which might help here:
* [25 mins video introduction to Markdown in Visual Studio Code with Markdown worksheet](https://www.youtube.com/watch?v=pTCROLZLhDM), a good editor to deal with markdown
* [7 mins Video Using Git with Visual Studio Code (Official Beginner Tutorial)](https://www.youtube.com/watch?v=i_23KUAEtUM)
* [5 mins tutorial howto make changes to projects in github with PRs (and forks)](https://www.youtube.com/watch?v=4ZlK55_44II)

This issue is part of the [Nodesignal Bounty Program](https://nodesignal.space/spenden-bitcoin-bounties/)

**Comment by relativisticelectron** [comment]
While I think documentation is good, I expect 99% of users will just try to install, run it and expect the UI to make it intuitive for them what options exist (like with an install/setup wizard). I really like what sparrow did here when first setting it up (it is short and clear and no further documentation is needed):
![image](https://user-images.githubusercontent.com/60378539/190580648-9f3cff89-a9de-41af-9b4b-a8f647bc1e7b.png)
![image](https://user-images.githubusercontent.com/60378539/190580726-15571a61-2f79-49ea-92aa-0a5d97425832.png)
![image](https://user-images.githubusercontent.com/60378539/190580775-4321827b-9777-45b4-94b2-82cd0a537542.png)
![image](https://user-images.githubusercontent.com/60378539/190580804-d836ead9-9fa8-4617-aeae-40649714ecbc.png)

**Comment by k9ert** [comment]
Sparrow has a lot less possibilities than specter has. People who don't have sophisticated requirements should probably simply use Specter on their own computer with a downloaded binary and a pruned node.
This is for more sophisticated use-cases, maybe even in enterprise scenarios.

**Comment by j0sh21** [comment]
I think we can close this issue now.
