### ISSUE TITLE
Add QR support for Blockstream Jade

### ISSUE THREAD

**Issue by bitcoinhelp** [cryptoadvance/specter-desktop#1940]
Blockstream Jade will support QR communications in the next firmware release.

In order for this to work with Specter successfully:

1. The "Scan QR Code" option will need to be added for Jade in the "Add new device" flow. Jade will display a `ur:crypto-account` for the user's selected path (m/84', m/49', m/48h/0h/0h/1h, m/48h/0h/0h/2h). **This is already working with Specter fine when scanning Jade as an 'Other' device** - just need the option added to Jade.

2. When displaying a PSBT for Jade to scan, Specter will need to show a `ur:crypto-psbt`. This appears to be similar to how Keystone is treated, as Specter will display that format when Keystone is a device linked to the wallet

**Comment by moneymanolis** [comment]
Thanks, I think that should be quite straight forward to implement. Can you tag me here once the release is out?

**Comment by bitcoinhelp** [comment]
Excellent - yes will do

**Comment by moneymanolis** [comment]
I think that will be just a one line change, adding `qr_code_support = True` to` jade.py`.

**Comment by bitcoinhelp** [comment]
Great. Will this also require an additional change to display PSBTs QR for Jade as `ur:crypto-psbt`?

I've noticed that if the device for the wallet is not a Keystone - it will simply display a raw PSBT base64 string. Seems like we may also need change this for Jade too unless that is the new default. Jade will only read `ur:crypto-psbt` for now

**Comment by moneymanolis** [comment]
I think we'll need to add this method to` jade.py`, similar to `keystone.py`, to prepend "crypto-psbt:" for the qr-code web component. 
```

    def create_psbts(self, base64_psbt, wallet):
        psbts = super().create_psbts(base64_psbt, wallet)
        # make sure nonwitness and xpubs are not there
        qr_psbt = wallet.fill_psbt(base64_psbt, non_witness=False, xpubs=False)
        # add a hint to <qr-code> tag that this should be encoded as crypto-psbt
        psbts["qrcode"] = f"crypto-psbt:{qr_psbt}"
        return psbts
```
@stepansnigirev wouldn't be easier to add an attribute regarding the qr code format to the devices (which format they can read) and then also add an attribute to the qr-code web component? So, similar to` animate="{{device.qr_code_animate}}"`.

**Comment by moneymanolis** [comment]
Looking at `qr-scanner.html`, scanning ur:crypto-psbt is implemented no changes needed IMO.

**Comment by stepansnigirev** [comment]
@moneymanolis you are correct, QR protocol is the same as in keystone, so we only need to enable QR codes for jade.

I think having QR format as an attribute makes more sense, would be nice to refactor qrcode component using that instead of the prefix

**Comment by moneymanolis** [comment]
OK, let's do it like this then. I will already start with the QR code component refactoring then and then add QR codes for Jade later when they release.

**Comment by bitcoinhelp** [comment]
@moneymanolis would it be possible to have the QR code option added to Jade now as well? The alpha is already available to users who know how to access the beta channel.

Would also help us start creating some documentation and tutorial resources with the proper screenshots

**Comment by bitcoinhelp** [comment]
@moneymanolis I'm using v 1.14.2 right now and I'm not seeing the QR options for Jade, either for PBST or xpub scanning. I know it was there when I tested for you a while ago, any idea on this?

**Comment by moneymanolis** [comment]
Couldn't reproduce so far, neither on the MacOS app nor on master.

**Comment by bitcoinhelp** [comment]
Thanks for checking, looks like something wrong on my end - appreciate the investigation
