### ISSUE TITLE
error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by aphex3k** [cryptoadvance/specter-desktop#1963]
> # oops! something went wrong
> ``` 
> error: redirect_uri_mismatch
> error_description: redirect_uri did not match any of the client's registered redirect_uris
> state: kjkmdskdmsmmsmdslmdlsm
> ```

OAuth with Swan is not working and throws a `redirect_uri_mismatch` error instead.

**Steps To Reproduce**

1. Log in to specter desktop, e.g. 'http://umbrel.local:25441'
2. Click on '+ Choose plugins'
3. Click on 'Swan'
4. Click on 'Existing Swan users'
5. Click on 'Link your account'
6. New tab opens presenting the error shown in the screenshot
`https://api.swanbitcoin.com/oidc/auth?client_id=specter&redirect_uri=http://umbrel.local:25441/svc/swan/oauth2/callback&response_type=code&response_mode=query&code_challenge=<redacted>&code_challenge_method=S256&state=kjkmdskdmsmmsmdslmdlsm&scope=offline_access%20v1%20write:vendor_wallet%20read:vendor_wallet%20write:automatic_withdrawal%20read:automatic_withdrawal&prompt=consent`

**Expected behavior**
This has worked at least once at some point in a version of specter desktop prior to updating to 1.13.1. I don't know exactly in which version this regression was introduced though. Auto-withdrawals from Swan to Specter had been working for this account for quite some time. Eventually the auto-withdrawal stopped working which is why I attempted to re-connect the plugin.

**Screenshots**
![Fg09NavUcAENSGK](https://user-images.githubusercontent.com/433270/200470109-90747c51-72f6-4054-b373-90a6bf8a54b1.png)

 - Where is your node running: **umbrel**
 - Where is your specter running: **umbrel**
 - If you're running a binary, which OS: I don't think it matters, but I'm also running specterd hwibridge on **macOS** since I access specter remotely
 - Browser: any, I tried Chrome, Brave, Safari and Edge
 - Specter Version: **1.13.1**

**Comment by moneymanolis** [comment]
Just tested the integration on master and all worked fine.

**Comment by aphex3k** [comment]
Is this an issue?
![spc](https://user-images.githubusercontent.com/433270/200642402-c8a00ecf-588d-4459-98a6-2c28b38d2656.jpg)
![svc](https://user-images.githubusercontent.com/433270/200642404-f4cd48c5-6ba3-4da6-8beb-eea074a9d1d4.jpg)

**Comment by aphex3k** [comment]
> Just tested the integration on master and with [v1.13.2-pre7](https://github.com/cryptoadvance/specter-desktop/releases/tag/v1.13.2-pre7) and all worked fine.

v1.13.1 is the latest release...

**Comment by ReedWommack** [comment]
I think this might be because the associated wallet was deleted on Swan Bitcoin itself. Could that be the issue?

**Comment by aphex3k** [comment]
I wanted to add that auto-withdrawals definitely happened 20 times so the first batch of addresses definitely used up and it failed to acquire the next batch?

**Comment by k9ert** [comment]
@moneymanolis `/svc` is correct. We want to change it to `/ext` but we're not there, yet.

@aphex3k Those configurations might be helpful for people hosting specter customised but as you already discovered, they are "deactivated" by default.

@ReedWommack i don't think this has anything to do with the selected wallet.

This is about the URLs configured on the swan-side: https://github.com/cryptoadvance/specter-desktop/blob/v1.13.1/src/cryptoadvance/specter/services/swan/config.py#L15
Maybe something got scrambled on that side. At least, i can't imagine that this has been working on umbrel for pre `v1.13.1` releases.

If the integration is no longer working (otherwise you wouldn't get this issue), no more addresses can be reported to Swan and so the automatic withdrawals stops. But you can do manual withdrawals. Hopefully we'll solve that soon. Manolis will check on the server side. Sorry for the bad experience.

**Comment by moneymanolis** [comment]
Just in addition: We could reproduce the issue by "simulating" the hostname to `umbrel.local`. This makes it very likely that the server side is causing this.

**Comment by moneymanolis** [comment]
@aphex3k we've identified the issue, it is on the Swan server side. I will tag you here, once it is resolved. Thanks for your patience and for bringing it to our attention!

**Comment by aphex3k** [comment]
Thank you

**Comment by aphex3k** [comment]
> Just a quick update, we are still working on making the right changes on the API backend. For now, the integration only works properly with localhost as redirect URI.

I can not confirm localhost to be working. 

I was able to get past the oAuth issue outline above but when selecting a wallet I receive the following error:
```
TypeError: string indices must be integers
```

<img width="1582" alt="image" src="https://user-images.githubusercontent.com/433270/202087673-a9bfc437-6ba9-4873-8da2-1821a62daa1b.png">

**Comment by moneymanolis** [comment]
OK, I could reproduce the issue @aphex3k - working on it.

**Comment by moneymanolis** [comment]
@aphex3k https://github.com/cryptoadvance/specter-desktop/pull/1981 should fix it.

**Comment by k9ert** [comment]
Just a general note: You cannot expect to setup the integration on one specter and then use it on another instance. It's difficult for me to understand this issue as IMHO, it should never have worked on an umbrel.

**Comment by aphex3k** [comment]
> Just a general note: You cannot expect to setup the integration on one specter and then use it on another instance. It's difficult for me to understand this issue as IMHO, it should never have worked on an umbrel.

I've been using the same specter desktop version on my umbrel. I've not moved it or anything. I just updated the docker containers to whatever was latest at the time and set up the Swan extension on the first version that it had available in a non-pre version.
