### ISSUE TITLE
Bug: Node details are lost

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1968]
**Describe the bug**
After switching from [4aa5858](https://github.com/cryptoadvance/specter-desktop/pull/1901/commits/4aa585893e3649afd52fb06fe25a8e294a6f1b46) (of https://github.com/cryptoadvance/specter-desktop/pull/1901 )  to  current master   a739a062 the node details are not loaded (or are lost): 
![image](https://user-images.githubusercontent.com/60378539/201314369-8b259370-a465-451c-b881-bcacad9bdfd3.png)

- When entering the node details, it can find the node, but doesn't load the wallets
- After restarting specter again the node details are lost again.

**Cause**
My suspicion is that one of these merges on master in the meantime caused this:

- de8f5af619d06fdb8b508dae1c5e54d36f5b3bd3
- 55e2a5fb761b8a48c53f699724580a22fcbb00a2
- 65bb7d2309845270e123718b9ab17bf1d94077d5
- ba5873d23be308c67c9446c928880bd9c4b1067b
- 1d2fea976ac06823cbbfc43b46f6b26ed342bab7
- bef9cf69f88db10f8aec4ded8c8fc73355ef8e7f
- a739a062ca44005a1613f072f8f99def3c71c6c0

**Desktop (please complete the following information):**
 -  local(external) , regtest
 - Linux

**Comment by moneymanolis** [comment]
Can confirm, there a gazillion node jsons created:
![grafik](https://user-images.githubusercontent.com/70536101/201761116-453236bf-d4d9-40cb-8645-c77576bcc487.png)
