### ISSUE TITLE
notify_upgrade() error

### ISSUE THREAD

**Issue by gorazdko** [cryptoadvance/specter-desktop#198]
## Abstract

* my Specter doesnt start unless commenting out notify_upgrade() call
* ubuntu

![image](https://user-images.githubusercontent.com/25270775/86855380-7d7cc380-c0ba-11ea-918a-3726e5398865.png)

**Comment by stepansnigirev** [comment]
What is version of python you are using?

**Comment by gorazdko** [comment]
yeah 3.6.9
