### ISSUE TITLE
This error is thrown if you are using the internal node (which means Specter is managing bitcoind) and can't find the bitcoind binaries. Can you check whether there are any files in (I suppose in your case:) `"/Users/YOURUSERNAME/.specter/bitcoin-binaries/bin/bitcoind"`.

### ISSUE THREAD

**Issue by Baronz1** [cryptoadvance/specter-desktop#1983]
This error is thrown if you are using the internal node (which means Specter is managing bitcoind) and can't find the bitcoind binaries. Can you check whether there are any files in (I suppose in your case:) `"/Users/YOURUSERNAME/.specter/bitcoin-binaries/bin/bitcoind"`. 

You will also need to sync your node first, which can take a day or two. If you need  the wallet "asap" I'd recoomend this approach which is also maintained by the Specter team: https://prunednode.today/

_Originally posted by @moneymanolis in https://github.com/cryptoadvance/specter-desktop/issues/1982#issuecomment-1321836582_

**Comment by moneymanolis** [comment]
Duplicate.
