### ISSUE TITLE
This error is thrown if you are using the internal node (which means Specter is managing bitcoind) and can't find the bitcoind binaries. Can you check whether there are any files in (I suppose in your case:) `"/Users/YOURUSERNAME/.specter/bitcoin-binaries/bin/bitcoind"`.

### ISSUE THREAD

**Issue by Baronz1** [cryptoadvance/specter-desktop#1984]
<img width="366" alt="截屏2022-11-23 04 12 31" src="https://user-images.githubusercontent.com/118652726/203467998-92e69112-4d3c-440b-a6d6-e387af6462b1.png">
        This error is thrown if you are using the internal node (which means Specter is managing bitcoind) and can't find the bitcoind binaries. Can you check whether there are any files in (I suppose in your case:) `"/Users/YOURUSERNAME/.specter/bitcoin-binaries/bin/bitcoind"`. 

You will also need to sync your node first, which can take a day or two. If you need  the wallet "asap" I'd recoomend this approach which is also maintained by the Specter team: https://prunednode.today/

@moneymanolis 
'Can you check whether there are any files in (I suppose in your case:) "/Users/YOURUSERNAME/.specter/bitcoin-binaries/bin/bitcoind". '
I use Macbook, is it also this location? I can't even find the 'bitcoind' folder.
My Specter App doesn't show in the 'Applications', I can only open it from the 'Location' section in 'Finder'. Why is this? What should I do?

Shall I re-inistall it? If I uninstall the App the install it again will I lose my BTC? Will I have to do that 2-3 days synchronize again?(I have a back up'.pdf' and recovery phrases)

_Originally posted by @moneymanolis in https://github.com/cryptoadvance/specter-desktop/issues/1982#issuecomment-1321836582_

**Comment by moneymanolis** [comment]
Can you please stop the spamming with duplicate issues?

**Comment by k9ert** [comment]
@moneymanolis maybe you can refer the duplicate issue here before closing.

**Comment by k9ert** [comment]
I think this is an unnecessary followup on #1982 . Let's continue there. I can't see a reason (or a benefit) why there should be a new issue. The context is all in the other issue and so we'll definitely can give you better support in the other issue.

**Comment by Baronz1** [comment]
Ok

通过 Proton Mail 移动端发送

--------原始邮件--------
2022年11月23日 23:36，k9ert 来信：

**Comment by Baronz1** [comment]
> Can you please stop the spamming with duplicate issues?

fuck you rude cunt
