### ISSUE TITLE
(replaced because of unfriendly language)

### ISSUE THREAD

**Issue by Baronz1** [cryptoadvance/specter-desktop#1985]
Can you please stop the spamming with duplicate issues?

_Originally posted by @moneymanolis in https://github.com/cryptoadvance/specter-desktop/issues/1984#issuecomment-1325260893_
      
It is a new question and you didn't answer it, it is not fucking spamming

**Comment by k9ert** [comment]
Sorry for your experience and i can understand that you're frustrated. However, please mind your language and be friendly.
You can also still post on closed issues if you think that it's not a duplicate.

Closing this and continuing in the other issues. I've reopened #1984. We should refer to the duplicate issue before closing.
