### ISSUE TITLE
cant import a wallet

### ISSUE THREAD

**Issue by gorazdko** [cryptoadvance/specter-desktop#199]
## Abstract

* idk a bunch of problems for me, meybe i'm missing something
* did a fresh clone, installation, before that deleted .specter, registered new hwws, created a multisig wallet, but no qr code shown
* device.exportable_to_wallet evaulates to false
* ubuntu, firefox

![image](https://user-images.githubusercontent.com/25270775/86855603-fda32900-c0ba-11ea-8250-405a5f22dafc.png)

**Comment by stepansnigirev** [comment]
Looks like device type is not recognized. When you are importing the device to Specter there is a selector what is the device type. Usually it should detect the type automatically, but looks like something went wrong. I see that both ledger and specter-diy were not recognized...
You can change the device type in corresponding jsonrpc file in .specter/devices.

@ben-kaufman do we have an option to change device type in settings already?

**Comment by ben-kaufman** [comment]
Not yet... but I could probably add that later today.

**Comment by gorazdko** [comment]
yes, both device types unrecognized ("other"). Manually fixing the type works.

**Comment by ben-kaufman** [comment]
Ok good, I'll also try to add some warning when saving the device with `type = Other` to remind the user to make sure to select the type.
