### ISSUE TITLE
Total balance zero

### ISSUE THREAD

**Issue by gorazdko** [cryptoadvance/specter-desktop#200]
## Abstract

This used to work for me. I refreshed the page after generating blocks, but amount is still zero.

![image](https://user-images.githubusercontent.com/25270775/86914034-e5b1c080-c11f-11ea-8ba0-be286341036f.png)

![image](https://user-images.githubusercontent.com/25270775/86913648-3c6aca80-c11f-11ea-8c37-27148295ef32.png)

**Comment by ben-kaufman** [comment]
What’s the chain’s height? If you’ve used the same regtest for many blocks you might have reached the final block subsidy, which if I remember correctly halves every 150 blocks for regtest (so <5100 height has 0 subsidy).
If that’s not the issue, which python version are you using? And which Specter version? (from master?)

**Comment by gorazdko** [comment]
Good point. That's probably it
