### ISSUE TITLE
Ui: Specter icon in menubar is broken (or not shown) - v1.14.1

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#2013]
Bug: Specter icon in menubar is broken, when using the Electron desktop app.
There is no icon in menubar, when switching to  Chrome browser or other app on top. 

To Reproduce: Running Specter v1.14.1 on a Macbook Pro M1, with local Bitcoin 10GB pruned node as BitcoinQT running next to Specter.

Expected behavior: Should be displayed as the usual small Blinky from Pacman.

Screenshot - Specter through Electron desktop app
![image](https://user-images.githubusercontent.com/47259243/206463789-b3dcea7d-c5ba-4201-ab7d-06bcd55f333c.png)

Screenshot - Specter through chrome browser
![image](https://user-images.githubusercontent.com/47259243/206465229-e3ee909e-4ccc-42f5-8e94-0a7e490219df.png)

**Desktop (please complete the following information):**
 - Where is your node running: Local machine as Bitcoin qt
 - Where is your specter running: Local machine 
 - If you're running a binary, which OS: macOS 13.0.1 (22A400) on Macbook M1 Pro, 14inch 2021
 - Browser: Chrome browser & Electron App
 - Specter Version: v1.14.1

**Comment by moritzwietersheim** [comment]
Hey @moneymanolis, could you reproduce this icon problem?

**Comment by otkstdio** [comment]
Fixed in v2.0.0
