### ISSUE TITLE
Labeling an address changes the colour in the tx info

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/specter-desktop#2019]
Before:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/70536101/207931169-c2f92aa7-5205-4950-ba53-6dd3c56ead76.png">

Now, giving a label to `bcrt1qe6acutvg5w8zssl7nrg252xc9f2zagcjqd5dct`, it changes the colour to blue (which indicates an address belonging to the wallet):

<img width="600" alt="image" src="https://user-images.githubusercontent.com/70536101/207931419-fa2e5413-f9f0-469c-92a7-6ff50ae7aa27.png">

**Comment by relativisticelectron** [comment]
Can you test if the bug is solved with https://github.com/cryptoadvance/specter-desktop/pull/1901 ?

**Comment by moneymanolis** [comment]
I can try, sure, but, would also like to know why :-)

**Comment by relativisticelectron** [comment]
> I can try, sure, but, would also like to know why :-)

Sorry, no testing necessary.  https://github.com/cryptoadvance/specter-desktop/pull/1901 touched the coloring, however ONLY the coloring, not the logic.

**Comment by otkstdio** [comment]
This is no longer the case in the v2.0.0, so closing for now.
