### ISSUE TITLE
Better error handling of HWI issues on start-up

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/specter-desktop#2035]
For example: If there is an issue with a signing device plugged in you get sth. like this:

<img width="694" alt="grafik" src="https://user-images.githubusercontent.com/70536101/210416238-d82b8fa5-d509-48cb-b5d9-bf9a357fde18.png">

Would be good if we could already be more specific here, sth. like "try to start Specter without your signing device plugged in and consider upgrading its firmware"

**Comment by k9ert** [comment]
For the reference: Already discussed in #818 and we tried to fix it in #1748

**Comment by k9ert** [comment]
Closed it as it can be seen as duplicate of #818
