### ISSUE TITLE
whitepaper functionality is broken with spectrum

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#2065]
getrawtransaction is not implemented in spectrum. Therefore the whitepaper functionality is broken.
#2056 tries to fix it by deactivating but that would be a pity, no?!

So waiting on https://github.com/cryptoadvance/spectrum/issues/33

**Comment by k9ert** [comment]
@Aditi-Singh16 or @PaarthAgarwal or @Aditi-Singh16 or @Omkar0803
Maybe you can get that working!

**Comment by PaarthAgarwal** [comment]
> @Aditi-Singh16 or @PaarthAgarwal or @Aditi-Singh16 or @Omkar0803 Maybe you can get that working!

I have a PR up for it https://github.com/cryptoadvance/spectrum/pull/39
Can you take a look at it? I feel it's really close
