### ISSUE TITLE
Log file name flowing out of Tool-tip box

### ISSUE THREAD

**Issue by PaarthAgarwal** [cryptoadvance/specter-desktop#2075]
**Describe the bug**
The log file name is flowing out of the tool-tip box because it's a large text without spaces.

**To Reproduce**
1. Open specter desktop and go to settings.
2. Go to General tab
3. Scroll down to the Logging level
4. Hover over the lit bulb icon.

**Screenshots**
![Screenshot from 2023-01-24 03-51-58](https://user-images.githubusercontent.com/86092410/214164380-641f04e8-cccf-4b9e-9414-407be7c39007.png)

**Desktop (please complete the following information):**
 - Where is your node running: [e.g. raspiblitz, MyNode, umbrel, local(internal), local(external)]
 - Where is your specter running: [e.g. Raspiblitz, Node, umbrel, binary]
 - If you're running a binary, which OS: [e.g. Linux, MacOs, Windows]
 - Browser : Edge for Ubuntu
 - Specter Version [e.g. 1.9.4]: Latest development version

**Additional context**
A simple CSS fix can solve the issue. Creating a PR for the same.

**Comment by moneymanolis** [comment]
It's already looking OK in the revamp branch, which we will hopefully merge soon:

<img width="686" alt="grafik" src="https://user-images.githubusercontent.com/70536101/214246025-da089c46-7b69-418e-a927-af71a7f99a5d.png">

@PaarthAgarwal I'd suggest to either wait with UI fixes or make PRs to the revamp branch until we have merged it:
https://github.com/cryptoadvance/specter-desktop/pull/1991

**Comment by PaarthAgarwal** [comment]
I see. Thanks for the heads up 👍🏻

**Comment by moneymanolis** [comment]
It would be a great help if you could check out this branch and search for UI bugs. Tailwinds CSS is pretty easy to learn, especially with ChatGPT.

**Comment by PaarthAgarwal** [comment]
I'm familiar with Tailwind. Will check out the new branch soon. Trying to fix the whitepaper issue. It seems like the getrawtransactionapi is passing 4 arguments instead of 3 which is failing the whitepaper.
