### ISSUE TITLE
Tooltip is not overlaying

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/specter-desktop#2113]
The tooltip should overlay (have a higher z-index) than the floating-wrapper element. This is for some reason not the case despite the relevant tool-tip element having a z-index of 2000 ...

![grafik](https://user-images.githubusercontent.com/70536101/215857133-7df2dbe9-6737-43de-b8bf-7299f888419e.png)

**Comment by moneymanolis** [comment]
@Aditi-Singh16 perhaps you wanna give this a go

**Comment by Omkar0803** [comment]
Hey @moneymanolis, can you give me this chance to contribute?

**Comment by PaarthAgarwal** [comment]
> @Aditi-Singh16 or @PaarthAgarwal perhaps you wanna give this a go

Okay. I'll take it on

**Comment by Aditi-Singh16** [comment]
I missed it :(
@moneymanolis could you pls tag in some more issues suitable for a new comer.
I will also browse some

Thanks!

**Comment by moneymanolis** [comment]
@Aditi-Singh16 I will. There is always more than enough to fix :-)
