### ISSUE TITLE
Allow exports to other wallets

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-desktop#212]
At the moment if Specter fails people don't have an easy way to regain access to their money.
We are still in development so crashes and failures may happen pretty often.
Would be nice to have an option to export wallet to another wallet.
Candidates:
- [ ] sequence of Bitcoin Core and HWI commands
- [x] [Electrum](https://electrum.org/)
- [ ] [Caravan](https://unchained-capital.github.io/caravan/#/)
- [x] [Fully Noded](https://apps.apple.com/us/app/fully-noded/id1436425586)
- [x] [Fully Noded 2](https://github.com/BlockchainCommons/FullyNoded-2)
- [ ] [Sparrow](https://sparrowwallet.com/)
- [ ] JoinMarket
- [ ] Wasabi

**Comment by Fonta1n3** [comment]
I think it’s worth adding Fully Noded to the list as it is capable of spending any watch-only wallet that exists on a users node simply by loading it and adding bip39 mnemonics as signers. The signers are stored locally to the device and act as psbt signers independently of bitcoind.

**Comment by stepansnigirev** [comment]
> I think it’s worth adding Fully Noded to the list as it is capable of spending any watch-only wallet that exists on a users node simply by loading it and adding bip39 mnemonics as signers. The signers are stored locally to the device and act as psbt signers independently of bitcoind.

Added :)

**Comment by Fonta1n3** [comment]
Just to continue the conversation with @ben-kaufman here. To import the wallet all we need is the receive descriptor, and ideally the block-height the wallet was created at to automate rescanning. 

I know json is not ideal for QR codes but it is what we are using in FN2 for now and it gets the job done. We call them "Account Maps" and they include the receive descriptor (Bitcoin Core format) with full path and checksum, a user defined label, and a blockheight. When we scan an Account Map we know it includes the receive descriptor so we simply replace `/0/*` with `/1/*`, and carry out two importmulti commands to derive all the receive and change keys.

An example:
```
{"label":"2 of 3","blockheight":1746106,"descriptor":"wsh(sortedmulti(2,[48148d15\/48'\/1'\/0'\/2']tpubDE7m94o4wm4dgvqKPeMv8WH67HLrQ3MxhdwfTASSRpBt5nsAfREi3447nsE3mtbr3wUwr8Z8KuGvTxAnTZGBqALk3bWuNn12cbTJq98MfGf\/0\/*,[116e058f\/48'\/1'\/0'\/2']tpubDEshoRXj3yC5SA1eUgwgHVp91Q9zZfX95H2tSQkrNC7PcVq3Pyq6tWncLMxDN7P8EnnwCvRzgGQZEhnYAvQ6WsfKRyqdsEkoH4HDkmTJzDS\/0\/*,[e37d5a62\/48'\/1'\/0'\/2']tpubDERYqh9L4atPmBGzsw2EzExPgqVDqwRDDpTfSEFaUwU3m9aW14oue1xrtMPpAXhpnhUEhJQjK63WwUxZgheVeCMr8tgMad7DUgkMGBohKVk\/0\/*))#e5vxd3ks"}
```

Perhaps we can share this approach? Or at least allow the user to export the receive descriptor in Bitcoin Core format as plain text or QR. 

The only issue I see is if a user utilizes a random derivation that does not conform to BIP44/49/84/48, in which case we can not be certain on how to derive change keys. 

Fully Noded/FN2 both work in very similar ways as to what you described with separating the signer from the node's wallet. I myself am using the same multisig watch-only wallet on my node between Specter, FN2, Fully Noded, Coldcard and Electrum. Having the ability to *easily* import/export the wallet to other apps/devices is really nice, especially if you can designate each as an optional signer.

**Comment by ben-kaufman** [comment]
I think that sounds good. Besides wallet creation block height, we already have the information available, and showing it for export should be very easy. I think adding the block height shouldn't be a problem either, so saving it for new wallets or checking the first transaction block height for existing/ imported wallets (and then saving it) is not complicated either.
Importing from that format might be more complicated, but also doable. If for every pubkey in the descriptor there is a device object with it in Specter, I think importing won't be so complicated, but if there isn't then we will need to figure out what to do (maybe reject the wallet/ create a new device specifically for that key/ something else...).

So what I suggest is to start with supporting export with the "Account Maps" format you described, then also adding support to import wallets if all devices for a wallet exist, and as a last step maybe supporting importing wallets even if signers data doesn't exist (either disabling some functionality or creating the data while importing the wallet).
Regarding random derivations, I think at least until we get all the above implemented we shouldn't worry about it, maybe just warn the user stuff might not function properly and so not to use it unless he is very technical and knows what he's doing.

What do you think @Fonta1n3 @stepansnigirev? If that sounds good I think I could start by adding the export option later today/ tomorrow.

**Comment by Fonta1n3** [comment]
Sounds good to me, my opinion is if a user is messing with custom derivs they are an expert and on their own :-) A simple warning can suffice.

**Comment by stepansnigirev** [comment]
Let's start with exporting, and meanwhile discuss how to import wallets.
I think for all keys in the descriptor we can try to find matching device, and if there is no or more than one we can show a table (similar to when we choose keys when create a wallet) and ask what to do - create a new device, import key to one of known devices or something else.
It also will be useful for cooperative signing when another person shares xpub with me and I don't have any device assigned to it. But I probably still want to create a device called "Another person's name" to keep track of who is my cosigner.

**Comment by mflaxman** [comment]
I've been playing with Electrum and this appears for watch-only:
```
{
    "wallet_type": "1of2",
    "x1/": {
        "derivation": "m/48'/0'/0'/2'",
        "pw_hash_version": 1,
        "root_fingerprint": null,
        "type": "bip32",
        "xprv": null,
        "xpub": "Zpub74h4HCSddD3n8wX1JMQjfb12fQeLAeFAbtN3zVqyTSj387zTdnYR4GpuA2giJMEvp5nJ7L48uGmVawyfV3pkHY5d6rMVtXFCk6J3Aw81r5c"
    },
    "x2/": {
        "derivation": null,
        "pw_hash_version": 1,
        "root_fingerprint": null,
        "type": "bip32",
        "xprv": null,
        "xpub": "Zpub74sb5KB3Ak1RwabGr8SHQnMTkd2mC3boVDgPf1jBFNxcXh7Nx4KV3XakPDtWLN5RpszdM7qcBN4wm7xreh8Ys2xYUBqQ9GtkTN8h5kRVecc"
    }
}
```

The good news is that this should be a trivial PR.

The bad news is that upgrading to a cosigning wallet is really hard; I don't think Electrum has a way add a seed/xprv and instead users have to manually go through the new wallet creation steps (which are *very* difficult and full of gotchas for multisig).

I think it's still worth adding the functionality for watch-only, no? Can be extra useful for an offline address verification (especially for multisig).

**Comment by ben-kaufman** [comment]
Update: with #721 we should have Electrum support too. `"sequence of Bitcoin Core and HWI commands"` would be great but is more of a documentation thing right? And for Caravan, this might be problematic unless they change their format to include fingerprints...

**Comment by k9ert** [comment]
We won't track the export to more wallets. We did some work and more export-functions are welcome but closing this issue.
