### ISSUE TITLE
Import wallet screen not properly styled

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/specter-desktop#2123]
![grafik](https://user-images.githubusercontent.com/70536101/216089144-8a5f4d95-9847-48c0-a298-d482aaeb3bd4.png)

**Comment by indra7777** [comment]
sir, can i try to align "import wallet screen"
This is the sample of ux design


<img width="1156" alt="Screenshot 2023-02-01 at 10 08 46 PM" src="https://user-images.githubusercontent.com/98700452/216105875-cc42a254-7df2-45be-a4a6-dc4f52f0997b.png">

**Comment by PaarthAgarwal** [comment]
I can take this on but I want to know what do you mean by not properly styled? Do you want to fix spacing and alignment or you want other changes?

**Comment by moneymanolis** [comment]
Best to compare with other screens, especially the send screen.

**Comment by indra7777** [comment]
Sir , I mean to contribute to open source
If you want sir, i can change the ui
Please help me how to do and how to contribute

**Comment by indra7777** [comment]
If it is not styled my ui not properly,
Then I will try to change ui better
Please help me...

**Comment by moneymanolis** [comment]
It has to fit into the existing styling.
