### ISSUE TITLE
QR code slider is not working properly

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/specter-desktop#2126]
As you can see in the screencast it is only getting smaller (in both directions). The container of the QR code should also not change dynamically IMO:

https://user-images.githubusercontent.com/70536101/216110268-91c1e607-ef53-40c9-9013-00b6ff4a95e5.mov

**Comment by moneymanolis** [comment]
On master the slider's display is set to None btw.

<img width="584" alt="grafik" src="https://user-images.githubusercontent.com/70536101/216111428-356ea286-79bf-4849-9ce8-f41538334e7a.png">

I think it would still be a nice feature and there seems to be some JS code already there. 
I will however, as a first step and for the next release, just hide the slider until it is working.

**Comment by PaarthAgarwal** [comment]
I'll take it up

**Comment by moneymanolis** [comment]
@PaarthAgarwal fyi: I made a PR [here](https://github.com/cryptoadvance/specter-desktop/pull/2129) to just hide the slider. You can remove the `hidden` class again once the slider is working.

**Comment by PaarthAgarwal** [comment]
Tested the behaviour
It's not as broken as it looks. You won't need to hide it at all for the next release.
It's at its maximum size initially, but the slider is in the middle. After you move it a bit in any direction, it gets small, but then the slider works as expected. Goes small on the left and more prominent on the right.
Can you tell me where the js code is present for it?

**Comment by moneymanolis** [comment]
It is in `qr-code.html `(web component).

**Comment by moneymanolis** [comment]
@PaarthAgarwal can you create a new issue / or make a new PR with a working slider? I am closing this issue now.
