### ISSUE TITLE
Weird scroll bar appearance on edge browser

### ISSUE THREAD

**Issue by PaarthAgarwal** [cryptoadvance/specter-desktop#2127]
**Describe the bug**
Weird scroll bar appears when I open specter on edge ubuntu. Works fine on firefox

**Screenshots**
On firefox:

![Screenshot from 2023-02-01 23-50-16](https://user-images.githubusercontent.com/86092410/216129919-7b391ca5-8c97-4588-95cf-8f4775455a98.png)

On edge:

![Screenshot from 2023-02-01 23-50-49](https://user-images.githubusercontent.com/86092410/216129926-6a43a4be-3334-40c0-a41c-3992cb01023b.png)

**Comment by moneymanolis** [comment]
We don't support Edge, only Firefox and Chrome. Closing this.
