### ISSUE TITLE
v2.0.0-pre6: Scrolling bars appear white

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#2131]
- Scroll bars appear white 
- Should we do blue drawers with black background? 
- Tested on MacBook M1 Pro, macos Ventura 13.0.1

https://user-images.githubusercontent.com/47259243/216158873-2765ea23-2913-4680-8461-6954bf81c129.mov

**Comment by PaarthAgarwal** [comment]
Which browser are you using?
Faced same issue here https://github.com/cryptoadvance/specter-desktop/issues/2127

**Comment by moneymanolis** [comment]
That is really interesting now. @PaarthAgarwal he is using a binary (MacOS app), which is based on Electron.

**Comment by moneymanolis** [comment]
Perhaps this will be fixed by the Electron upgrade? @k9ert

**Comment by moritzwietersheim** [comment]
Ah, yes I'm using with Electron app.
(Otherwise I'm using Chrome Browser)
And a BitcoinQT node, pruned to 10GB.

**Comment by moritzwietersheim** [comment]
And issue also appears in my Chrome browser.
(Chrome Version 109.0.5414.119 (Official Build) (arm64))

![image](https://user-images.githubusercontent.com/47259243/216163458-ec023400-712c-4a0e-812c-e535de1ed4d4.png)

**Comment by k9ert** [comment]
> Perhaps this will be fixed by the Electron upgrade? @k9ert

I don't think so as the current electron build already has the electron update.

**Comment by moritzwietersheim** [comment]
- Hey @otkstdio, somehow still these sidebars on Electrum. 
- ...same on Chrome.

https://user-images.githubusercontent.com/47259243/217149873-f1c3efaf-2bfb-49d8-808e-2d0852a7c28f.mov
