### ISSUE TITLE
v2.0.0-pre6: Swan Plugin Screen - all text underlined 

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#2133]
When clicking on the Swan Plugin Screen, all the text is underlined in the screen.

(Tested on MacBook M1 Pro, macos Ventura 13.0.1, 10GB pruned node same machine)

https://user-images.githubusercontent.com/47259243/216163076-8a5c5906-73d8-409b-9254-858d41474e70.mov

**Comment by moneymanolis** [comment]
I had this weird issue on Firefox from time to time, too.
