### ISSUE TITLE
v2.0.0-pre6: Setup-Helper/Wizard still visible.

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#2139]
- Setting up from scratch, the setup-helper/wizard is still visible.
- Setup-helper is offering to "Get Started" on the "About Bitcoin" screen (Start Screen).
-  I understand we want to hide the setup-helper to avoid new users to set up with packaged node and packaged TOR.

![image](https://user-images.githubusercontent.com/47259243/216220560-05eb67ee-3421-4adb-bae6-80d91bd292c0.png)

**Comment by moneymanolis** [comment]
<img width="749" alt="grafik" src="https://user-images.githubusercontent.com/70536101/216264758-46394f6a-e2f7-46b5-9e91-a432816eab71.png">

This screen (about screen without Spectrum) redirects to the old setup flow.
