### ISSUE TITLE
Properly handle cancel events in HWI (js side)

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-desktop#215]
In #213 we refactored JS part, but it can be improved further.
[Signals](https://ckeditor.com/blog/Aborting-a-signal-how-to-cancel-an-asynchronous-task-in-JavaScript/) can be used to cancel requests.

Some other improvements that we may consider:
- return an error from HWI controller when HWI is busy processing another request (currently it will just wait using a thread lock).
- add a json-rpc command that cancels current HWI operation

**Comment by k9ert** [comment]
Sorry, won't come to that. Feel free for anyone to implement any time
