### ISSUE TITLE
v2.0.0-pre6: Forget the Device button quits Specter

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#2154]
- "Forget the Device" button quits Specter
- But Device seems deleted in the files.

- @moneymanolis, this could be a larger bug? Probably prio/later?

(Tested on MacBook M1 Pro, macos Ventura 13.0.1)

https://user-images.githubusercontent.com/47259243/216436276-a6333c70-4265-45f1-96a4-adcc0b97c425.mov

**Comment by moneymanolis** [comment]
I think you meant `prio/now`, would be fitting.

**Comment by moritzwietersheim** [comment]
Super. Is gefixt. Danke ;)

**Comment by moneymanolis** [comment]
OK, then I close.
