### ISSUE TITLE
v2.0.0-pre6: When Spectrum loads tx history and data, there is weird wallet behaviour.

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#2155]
- When an old wallet is recovered and Spectrum loads its tx history and data, there is weird wallet behaviour.
- When the wallet, Transactions or Refresh List are clicked, then Specter jumps back to About Specter start-page. 
- Also error message showing.
- Probably not a good UX, could we stop the user from clicking on wallet? 
- And show a "Loading wallet history" message or similar message?
- Or is this a larger bug, which we should do later, @k9ert ?

https://user-images.githubusercontent.com/47259243/216439379-6c6d0fef-1643-48d2-be04-ba703c5864b0.mov

(Tested on MacBook M1 Pro, macos Ventura 13.0.1)

**Comment by k9ert** [comment]
Probably easy to fix. The "Refresh List" is probably just doing a reload, right?

**Comment by moneymanolis** [comment]
@k9ert look closer at the error messages, that is exactly the issue that we hopefull fixed with the thread lock in https://github.com/cryptoadvance/specter-desktop/pull/2161

**Comment by moneymanolis** [comment]
I am closing this for now. @moritzwietersheim but pay attention in your next test whether this was really resolved. I am pretty sure, though.

**Comment by moritzwietersheim** [comment]
While Spectrum is getting the address info, we could have a small updating counter somewhere saying: "Scanned 126 of 200 addresses" with a small rotating icon. 
To communicate the process in the background, and progress.

**Comment by k9ert** [comment]
Agree, should be tracked in https://github.com/cryptoadvance/spectrum/issues/38
