### ISSUE TITLE
v2.0.0-pre6: Spectrum: Default fee estimate set to Bitcoin Core

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#2158]
- Default fee estimate when using Spectrum is set to Bitcoin Core
- When using Spectrum, probably better set to Mempool.Space?
- Also "Data Sources" better to Blockstream.info? 
- What is Data Source exactly referring to?

(Tested on MacBook M1 Pro, macos Ventura 13.0.1)

Spectrum Default setting: Bitcoin Core
![image](https://user-images.githubusercontent.com/47259243/216443949-0fac2402-e5b6-48cf-88d4-e7be641ee6bf.png)

Better default setting for Spectrum - Blockstream.info, Mempool.space ?
![image](https://user-images.githubusercontent.com/47259243/216444005-c5d06eb1-1e33-488b-b002-0fbe56cfcde8.png)

**Comment by moritzwietersheim** [comment]
When connected to Spectrum, Specter uses Electrum (essentially Bitcoin Core) for fee estimation.
Maybe change the test from "Bitcoin Core" to "Bitcoin Core (or Bitcoin Core via Electrum Server)".

Maybe @moneymanolis, you can change this?
Not a blocker for v2.0 release though.

**Comment by moneymanolis** [comment]
@moritzwietersheim can I take it out of the milestone then?

**Comment by moneymanolis** [comment]
Bitcoin Core is the default value in Specter in general. 
TODO
- [ ] Check how the fee estimation using Core in implemented in Spectrum
