### ISSUE TITLE
v2.0.0-pre6: Broadcasting tx after signing with Ledger Nano S Plus seems broken

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#2174]
- After signing a singlesig tx with Ledger Nano S Plus, I could not broadcast.
- Error message: Server failed to broadcast transactions! SyntaxError: Unexpected token '<' "
- I could broadcast via "Send via block explorer"
(Tested on MacBook M1 Pro, macos Ventura 13.0.1)

https://user-images.githubusercontent.com/47259243/216726387-0cb04f99-4eb8-4c0b-bc61-84d93b802106.mov

**Comment by moritzwietersheim** [comment]
Tried again. 
Now worked. No Problem.

**Comment by moneymanolis** [comment]
But it looks like you couldn't broadcast it with your own node, no? And this happens only with Ledger Nano S Plus?

**Comment by moritzwietersheim** [comment]
Happened only with Ledger Nano S plus. Let's close this.
