### ISSUE TITLE
2.0.0-pre9: Setting up UIUX at Beginning

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#2179]
- When the user starts, he sees the Welcome screen with option to connect to Electrum server or own node.
- If he for some reason clicks on "Disconnected" or “+Add Connection”, he comes to the "Configure New Connection" screen which has only the option to connect to own Node. 
- Maybe if still disconnected the user should jump to Welcome screen when clicking "Disconnected" or “+Add Connection”, to choose between Electrum or Node.

- This is not absolutely necessary for the v2, but something to clean up later imho.

https://user-images.githubusercontent.com/47259243/217145754-2e8871b6-55cf-4529-9587-a8c434d1dc69.mov

**Comment by k9ert** [comment]
Related: https://github.com/cryptoadvance/specter-desktop/pull/2169 
Please qualify that PR

**Comment by moritzwietersheim** [comment]
I think the current format for choosing between Electrum or Node is fine.
