### ISSUE TITLE
Old design for errors and exception box is too small 

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#2191]
A potential screenshot should show it completely:
![image](https://user-images.githubusercontent.com/117085/218100246-c4b75943-fa55-4b1e-aab1-d78a591d82f4.png)

**Comment by moneymanolis** [comment]
This also has the old styling, probably makes sense to fix this in one go.

**Comment by k9ert** [comment]
Currently it looks like this:
![image](https://user-images.githubusercontent.com/117085/220691442-88349df7-7f2c-43d1-a0b5-6e89de06f37b.png)

Reopening this issue ...
