### ISSUE TITLE
v2.0.0-pre11: USB HWW signing problem

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#2202]
- I could sign with Bitbox (MultiSig + SingleSig) and Trezor 1 (Multisig (SingleSig not tested)).

- I could not sign with Ledger Nano S (MS + SS), Ledger Nano S+ (MS + SS), Trezor T (MS + SS), Jade (MS+SS). I could enter pin and hww seems to get recognized by Specter, but signing process does not start. 

- Using MacBook M1 Pro, 16GB, 2021, macos Ventura 13.0.1

*Edit: Tested this with the Spectrum connection.

**Comment by k9ert** [comment]
Can you check whether this is related to #1946 ?

**Comment by moritzwietersheim** [comment]
Regarding #1946, i did not receive the Error: "the selected device does not have a matching signing key"

**Comment by moritzwietersheim** [comment]
New testing run

Pre11 from blank - with new Bitcoin Core node
- All USB HWWs could be set up as devices, and extract xpubs.
- But I could sign only with Trezor T (Multisig & SingleSig), Ledger NS (MS), Trezor1 (MS).
- I could not sign with Jade, Bitbox, LedgerNS+

- Then I shut down node and specter, and restarted both. 
- This time Specter didn't load the MS & the SSig wallet, I created before. (Error Details: Request error for method loadwallet(specteredd4ffca4c0f30c7/ms__kot,): Wallet file verification failed. Failed to load database path /Users/moritzwietersheim/Library/Application Support/Bitcoin/wallets/specteredd4ffca4c0f30c7/ms__kot. Path does not exist.) 
- The wallets were originally created under path specter8db47efe19276c52 and there was no path specteredd4ffca4c0f30c7
- I recreated the wallets then through the Specter interface, and Specter recreated the wallets under the new path specteredd4ffca4c0f30c7

![image](https://user-images.githubusercontent.com/47259243/218912852-67e511c5-f875-491c-a284-ab40cf871bf6.png)

- With these recreated wallets, i could then sign with all USB HWWs. 
- (Also no performance issue after a break of 2-3 hours)


Test with Spectrum - Pre11 from blank:
- All USB HWWs could be set up as devices, and extract xpubs.
- Could sign with LedgerNS, and Jade, then the devices feature got stuck on Jade. But not in the devices UI. I could switch the device, but in the signing process it still was asking for Jade device and would not recognize the TrezorT or the Bitbox.
- So I restarted the Specter, and same problem with wallets as above. The Specter would not find the wallets, and ask to recreate them. 
![image](https://user-images.githubusercontent.com/47259243/218927907-0c2d0401-4905-42a9-a028-c05dc596f28d.png)

- I recreated the wallets and I could sign with all the USB HWWs. 
- Then I restarted the Specter and it reloaded the two wallets without problems.


(Sidenote: And i was observing that the Spectrum setup seemed to have problems with the very full mempool.)

![image](https://user-images.githubusercontent.com/47259243/218928471-bc0a19e1-7184-45f0-9aeb-672e49d1180a.png)

**Comment by moneymanolis** [comment]
Closing this after offline debugging with @moritzwietersheim - please create a separate issue for the UID thingy.
