### ISSUE TITLE
UIUX: Notification is close to not drawing any attention

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#2230]
See this screenshot:
![image](https://user-images.githubusercontent.com/117085/220112650-4e055a8e-8edd-4521-a808-caf82cfc245b.png)

Would like to see a much higher contrast, maybe some neutral color and i don't understand why this notification is showing in the lower right instead of upper center.
Maybe that's because it's only a notification but error-messages also come up there. Shouldn't they be placed more prominent?

If that makes sense from a UIUX perspective, can we have a rationale, here?

**Comment by otkstdio** [comment]
Now fixed in #2237
