### ISSUE TITLE
Change favicon in Specter 2.0

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/specter-desktop#2233]
Should look like sth. like this (this is not optimal yet, though, too pixely and too small):

<img width="483" alt="grafik" src="https://user-images.githubusercontent.com/70536101/220130000-af9bf419-ef20-44b1-b678-cdee7e119468.png">

**Comment by otkstdio** [comment]
Note, i chose to go with dark as more users use light mode. It's also what I see other majors go with, ergo Github. The sizing and pixelation is now fixed in #2237.
