### ISSUE TITLE
Timeout too short for wallet import

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/specter-desktop#2235]
I even hit the default timeout of 10 seconds with a larger regtest wallet. The timeout for (re-) creating an existing wallet should be higher.

`Failed to create wallet: Timeout after 10 secs while BitcoinRPC call(wallet/specterb89971bf662437c6/trezor_test_3). Check the logs for more details. (check logs for details)`

@k9ert what do you think?

**Comment by k9ert** [comment]
Creating a wallet is definitely something which might cost a bit more time. We have the ability to specify different timeouts per call so i'd suggest to tweak the timeout for that call!
