### ISSUE TITLE
Improve popup after adding device

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/specter-desktop#2239]
<img width="475" alt="grafik" src="https://user-images.githubusercontent.com/70536101/220363302-c124fb19-c053-469c-9092-ad8f86459f5e.png">

- More contrast between pop-up and the main screen
- Align the three options in the pop-up.

**Comment by otkstdio** [comment]
@moneymanolis I can't reproduce this locally and think the design is too small we when we use a 3x3 grid.
