### ISSUE TITLE
add support for faster wallet rescan with local explorer

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-desktop#224]
Bitcoin core is nice, but rescan is pretty slow. Some people have large storage with not just Bitcoin Core, but also electrs server. We could use it for rescan.

We can use `importprunedfunds "rawtransaction" "txoutproof"` to import transactions we got from local explorer.

> Imports funds without rescan. Corresponding address or script must previously be included in wallet. Aimed towards pruned wallets. The end-user is responsible to import additional transactions that subsequently spend the imported outputs or rescan after the point in the blockchain the transaction is included.
>
> Arguments:
> 1. rawtransaction    (string, required) A raw transaction in hex funding an already-existing address in wallet
> 2. txoutproof        (string, required) The hex output from gettxoutproof that contains the transaction

**Comment by k9ert** [comment]
This is at least related to #344 or can we even close this issue?

**Comment by k9ert** [comment]
> Some people have large storage with not just Bitcoin Core, but also electrs server.

Sounds very likely that this might be solved with spectrum as well. Closing it for now, please reopen if i'm missing a point.
