### ISSUE TITLE
Some quirks on Transactions Details

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/specter-desktop#2240]
- `cursor-pointer `classes are missing for tx ids (you can copy and paste those).
- Typo in first line

<img width="700" alt="grafik" src="https://user-images.githubusercontent.com/70536101/220370475-dcd2fb35-745e-4cab-a7d3-5d3b73a9fc03.png">

**Comment by otkstdio** [comment]
Now fixed in #2237
