### ISSUE TITLE
Multiple outputs in a single transaction are smashed into one UTXO

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#2253]
- I found a bit of an exotic bug when a singlesig wallet receives to multiple addresses in one transaction. 
- These UTXOs are not displayed separately in the UI, but as only one large UTXO. And I could not send these UTXOs.
- This happened bc i send funds between my singlesig and my multisig back & forth, and i tried to do 2 batched transactions from multisig to multiple addresses of the singlesig wallet.
- Tx Multiple UTXOs 01:
 https://mempool.space/tx/30230e3cc5aa6508f80bec50aca95d5424b864ea4730a910025e912303490683#flow=&vout=0 
- Tx Multiple UTXOs 02: https://mempool.space/tx/295596865396117a22fa979bec08285b7ba2128a6fad77f469590c3302c45889

![Screenshot 2023-02-23 at 11 41 07 PM](https://user-images.githubusercontent.com/47259243/221096847-fd93e575-a8ff-4484-bb2b-337708e721dd.png)

![Screenshot 2023-02-23 at 11 41 47 PM](https://user-images.githubusercontent.com/47259243/221096896-e7912183-2ed5-4fbe-8350-ab78ab2c6b90.png)

**Comment by moneymanolis** [comment]
@k9ert so it seems, this isn't fixed yet.

>  I could not send these UTXOs.

This is bad, but somehow expected.
I will try to replicate this on regtest, first.

**Comment by moneymanolis** [comment]
Reproduced on Regtest.

**Comment by moneymanolis** [comment]
Further testing:

You can spend the "merged UTXO" but only one of, say, 2 UTXO is then selected.
Example:
If you made a tx with 50k sats to two different addresses in one tx, you can select the merged UTXO but you will get an error if you want to spend more than 50k sats.
`Selected coins do not cover full amount. Please select more coins!`

**Comment by moritzwietersheim** [comment]
- UTXOs apparently not getting split up over different addresses in screen "Receive Addresses"
- Example tx:  https://mempool.space/tx/295596865396117a22fa979bec08285b7ba2128a6fad77f469590c3302c45889

![image](https://user-images.githubusercontent.com/47259243/225342290-a405c1a2-a605-4ff3-94b8-c26d01dc564a.png)

**Comment by moneymanolis** [comment]
> * Specter could load the wallet.
> 
>     * But gave error message "Failed to load utxos, KeyError: 'amount' ✕" when a tx was prepared and pending.
> 
> 
> Logs:
> 
> ```
> 2023-03-15T14:09:47.590Z [info] : stderr-SPECTERD: INFO in wallet_manager: starting update of wallet_manager (threading: True , comment: via server_specter_error)
> 
> 2023-03-15T14:09:47.591Z [info] : stderr-SPECTERD: INFO in controller: GET, /wallets/wallet/singlesig_know/history/ , 302, took,  167, ms
> 
> 2023-03-15T14:09:47.599Z [info] : stderr-SPECTERD: INFO in controller: GET, /welcome/about                          , 200, took,    4, ms
> 
> 2023-03-15T14:09:47.660Z [info] : stderr-SPECTERD: INFO in controller: GET, /wallets/wallets_loading/               , 200, took,    0, ms
> 
> 2023-03-15T14:09:47.666Z [info] : stderr-SPECTERD: INFO in controller: GET, /nodes/sync_status/                     , 200, took,    9, ms
> 
> 2023-03-15T14:09:47.813Z [info] : stderr-SPECTERD: ERROR in wallet: 'amount'
> Traceback (most recent call last):
>   File "cryptoadvance/specter/wallet.py", line 918, in check_utxo
> KeyError: 'amount'
> SPECTERD: INFO in wallet_manager: Updating wallet manager done in   222ms. Result:
> SPECTERD: INFO in wallet_manager:   * loaded_wallets: 1
> SPECTERD: INFO in wallet_manager:   * failed_load_wallets: 0
> 
> 2023-03-15T14:09:47.813Z [info] : stderr-Exception in thread Thread-1103 (_update):
> Traceback (most recent call last):
>   File "cryptoadvance/specter/wallet.py", line 918, in check_utxo
> KeyError: 'amount'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "threading.py", line 1009, in _bootstrap_inner
>   File "cryptoadvance/specter/util/flask.py", line 32, in run
>   File "threading.py", line 946, in run
>   File "cryptoadvance/specter/managers/wallet_manager.py", line 243, in _update
>   File "cryptoadvance/specter/wallet.py", line 655, in update
>   File "cryptoadvance/specter/wallet.py", line 937, in getdata
>   File "cryptoadvance/specter/wallet.py", line 933, in check_utxo
> cryptoadvance.specter.specter_error.SpecterError: Failed to load utxos, KeyError: 'amount'
> 
> 2023-03-15T14:09:48.673Z [info] : stderr-SPECTERD: INFO in controller: GET, /wallets/wallets_loading/               , 200, took,    0, ms
> 
> 2023-03-15T14:09:53.873Z [info] : Quitting ...
> 2023-03-15T14:09:53.919Z [info] : stderr-SPECTERD: INFO in specter: Closing Specter after cleanup
> 
> 2023-03-15T14:09:53.919Z [info] : stdout-[{'unit': 'sat', 'amount': 36340, 'btc_amount': 0.0003634, 'recipient_id': 0, 'label': 'Test', 'address': 'bc1qdg3wm4g70mw8mznyv6sqfvak89q5ta4mlz066etlg8m9ezcxa04sq7yzx5'}]
> ```

What UTXO where you trying to spend here exactly?

**Comment by k9ert** [comment]
Regarding the "split-up" issue: This is caused in [this loop](https://github.com/cryptoadvance/specter-desktop/blob/master/src/cryptoadvance/specter/wallet.py#L2076-L2077) which tries to split up the utxo-values towards the address which is currently itterated. A `utxo` is of type `WalletAwareTxItem` and the assumption is, that only one output belongs to wallet. In that case all 4 outputs belong to the wallet spread over more than one address.
So it would need to iterate over the `utxo.tx.vout` and only add the sums where the corresponding `utxo.tx.vout[x].script_pubkey` belongs to the address.
