### ISSUE TITLE
Warn the user if he is signing with a wrong device

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-desktop#226]
Related to this:
https://github.com/cryptoadvance/specter-desktop/issues/203

If fingerprint doesn't match we should show a warning. Or filter devices by fingerprint (devices with not-matching fingerprints should have "disabled" state but still visible)

**Comment by ben-kaufman** [comment]
I could implement that if you haven't started yet.

**Comment by stepansnigirev** [comment]
I didn't, so feel free to implement that.
Don't forget that if passphrase is required we don't know the fingerprint ;)

**Comment by ben-kaufman** [comment]
Fixed in #240
