### ISSUE TITLE
Exception thrown when selecting device settings without a node connection

### ISSUE THREAD

**Issue by otkstdio** [cryptoadvance/specter-desktop#2260]
An exception is thrown when attempting to add a device or change an existing device if you have no node connection.

To reproduce, remove your node / delete spectrum connection so it says "Disconnected" (also the state for a new user), click "Add device" and click on any signing device.

<img width="1329" alt="shot" src="https://user-images.githubusercontent.com/85369328/221285928-736a53ca-0dfc-4f85-a1b2-4e67212ae8c5.png">

**Comment by alluringambiguous** [comment]
Hi, I am looking at the issue, I reproduced it.
I traced the error and found that there is no check written in the `/new_device_keys/<device_type>/` route. 
I can think of 2 possible solutions,
1. One could be to pop up error when ever user clicks on a device (when the node is not connected).
2.  Other could be to not allow user to add device by showing an warning (similar to how it is handled in case of wallets)

![66ca1e7e-6dff-4cff-b754-73a81eb97408](https://user-images.githubusercontent.com/67975841/221363702-ac5947c9-f806-4242-8183-879e64459b00.jpg)



Please let me know your feedback. :) 
@moneymanolis
