### ISSUE TITLE
"Run the numbers" button not syncing and displaying info

### ISSUE THREAD

**Issue by igrsw** [cryptoadvance/specter-desktop#2305]
**Describe the bug**
When I clicked "Run the numbers" button while syncing full node got the error "Uncaught exception:'NonType' object has no attribute 'getblockchaininfo'

**Expected behavior**
Thought it will update me like it did first time when I opened panel.

**Screenshots**
![22](https://user-images.githubusercontent.com/125664329/225313639-41cfcc22-7bd4-404d-b631-c36652058df2.jpg)

**Desktop (please complete the following information):**
 - Where is your node running: pi4, ubuntu 20.04
 - Where is your specter running: binary
 - If you're running a binary, which OS: windows
 - Browser 
 - Specter Version Specter-Setup-v2.0.0-pre35.exe

**Comment by igoratswan** [comment]
Yes that would be the issue. When the full node is synced its working well.
