### ISSUE TITLE
Specter-v2.0.1-pre3: Not all wallets loaded

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#2312]
- On Spectrum instance during 1st sync the MultiSig wallet stopped loading.
- Upon relaunch the Specter did not find the MultiSig wallet: "Not all Wallets loaded"
- Log File: [specterApp.log](https://github.com/cryptoadvance/specter-desktop/files/11035560/specterApp.log)

![image](https://user-images.githubusercontent.com/47259243/226784164-82f5c5a2-9917-4e21-b5d1-0411ed8b8ec4.png)

**Comment by k9ert** [comment]
This is most probably not due to the new version but a serious issue in spectrum. We're currently working on it.

**Comment by moritzwietersheim** [comment]
- Error persists on v2.0.1-pre4 - on Spectrum instance during 1st sync the MultiSig wallet stopped loading.
- Error message: "Failed to load utxos, RpcError: ('Method not found (getaddressinfo)', -32601) ✕"
- Upon restart i get the same message:  "Not all Wallets loaded"
- Logs: [specterApp.log](https://github.com/cryptoadvance/specter-desktop/files/11066245/specterApp.log)

![image](https://user-images.githubusercontent.com/47259243/227628268-b3cda78c-41c3-4cc5-8d2a-cbe6019b10c3.png)
