### ISSUE TITLE
Transactions export as CSV is broken

### ISSUE THREAD

**Issue by dennisreimann** [cryptoadvance/specter-desktop#2319]
**Describe the bug**

Transactions export as CSV is broken.

**To Reproduce**
1. Go to 'Wallets Overview'
2. Click on 'Export'
3. 'Export transactions to CSV'
4. An empty HTML file named 'full_transactions.html' gets exported

It's the same for a single wallet, the only difference being the filename 'transactions.html' in that case.

**Expected behavior**
A CSV file containing the transactions data is exported.

**Desktop (please complete the following information):**
 - Where is your node running: Raspiblitz
 - Where is your specter running: Desktop, binary
 - If you're running a binary, which OS: Linux
 - Specter Version: v2.0.1

**Additional context**

The only log entry:

```
[info] : stderr-SPECTERD: INFO in controller: GET, /wallets/wallets_overview/full_transactions.csvexportPrices=false&search=&sortby=time&sortdir=desc, 200, took,  408, ms
```

**Comment by 4b10t1c** [comment]
Experiencing the same issue on MacOS 13.2.1 w/ Specter Version: v2.0.2.dev0+g6202c06a.d20230327

Log entry: 
2023-05-04T02:34:03.483Z [info] : stderr-SPECTERD: INFO in controller: GET, /wallets/wallets_overview/full_transactions.csvexportPrices=false&search=&sortby=time&sortdir=desc, 200, took,  932, ms

Appears the file system attempts to create the CSV file, but disappears shortly thereafter.
