### ISSUE TITLE
[specter.solutions] duplicated PGP public key on the website

### ISSUE THREAD

**Issue by nymkappa** [cryptoadvance/specter-desktop#2324]
Hi.

I'm not sure if that's the appropriate place to report this but on https://specter.solutions/downloads/, in `Verify signature` modal, the `PGP Public key of "Specter Signer"` seems to have a "copy/paste" issue 😄.

The page shows: `The fingerprint for this key is 785A 2269 EE3A 9736 AC1A 4F4C 864B 7CF9 A811 FEF7785A 2269 EE3A 9736 AC1A 4F4C 864B 7CF9 A811 FEF7.`

Seems to me it should just be `The fingerprint for this key is 785A 2269 EE3A 9736 AC1A 4F4C 864B 7CF9 A811 FEF7`.

Thanks for your amazing wallet. Cheers.

**Comment by k9ert** [comment]
Thank you. Very good point. Just fixed it.
