### ISSUE TITLE
Key Error when trying to set up wallet

### ISSUE THREAD

**Issue by Funman2** [cryptoadvance/specter-desktop#2334]
**Describe the bug**
Every time i try to import my main wallet i gat an utxo key error, the wallet fails to load, wther its imported or the key is freshly imported from hww...
i had to go back to version 1.14.5

**To Reproduce**
install new version, wallets fail to load

**Expected behavior**
it should have imported old wallets automatically

**Screenshots**

**Desktop (please complete the following information):**
 - Where is your node running: umbrel
 - Where is your specter running: local windows machine
 - If you're running a binary, which OS:windows 10
 - Browser [chrome
 - Specter Version2.0.1 and 2.0.2 pre

could not resolve

**Comment by kostadinstoilov** [comment]
I get a similar error when trying to load a wallet:

`Failed to load utxos, IndexError: list index out of range`

The only thing that works is to delete the wallet and recreate it.

**Comment by Funman2** [comment]
Still get this error when loading the particular wallet :" Failed to load utxos, KeyError: '462c34dc7f7029cdcd3f571cb183537162b3806c551c7b17ededb30d6991639f' "
Loading wallet fails. Deleting and reimport does not fix, delete wallet and import keys from multiple devices fail ( seedsigner, airgapped or trezor, same wallet...)

**Comment by oren-z0** [comment]
Could be related? https://github.com/cryptoadvance/specter-desktop/issues/2475

**Comment by Funman2** [comment]
My Problem went away after switching to specter 2.0.5 and more powerful umbrel home bitcoin node hardware.
So I might close this now even though due to new issue #2473 Specter does not function at all anymore.
