### ISSUE TITLE
Restoring multi-sig wallet - Wallet name exists after deleting

### ISSUE THREAD

**Issue by steveocrypto** [cryptoadvance/specter-desktop#2363]
**Describe the bug**
After deleting a multi-sig wallet and restoring, Specter gives you an error that the wallet already exists even after deleting it previously.  Changing the name of the imported wallet fixes the issue, but it shouldn't require this.

**To Reproduce**
1. Create Multisig Wallet - Give it "Test Wallet"
2. Save copy of backup PDF to restore the wallet
3. Delete "Test Wallet"
4. Restore using backup PDF
5. The error pops up that the wallet already exists

**Expected behavior**
After deleting a wallet, you should be able to restore said wallet even with the same wallet name.

**Screenshots**
<img width="571" alt="CleanShot 2023-08-07 at 16 42 45@2x" src="https://github.com/cryptoadvance/specter-desktop/assets/171488/1aa23c8c-85d2-4515-b928-834c6aeba9dc">

**Desktop (please complete the following information):**
 - Where is your node running: Local
 - Where is your specter running: Local
 - If you're running a binary, which OS: MacOS
 - Browser: Chrome
 - Specter Version: 2.0.2

**Comment by k9ert** [comment]
This is a limitation of the bitcoin core wallet as it doesn't have an API to delete a wallet. Really difficult to explain the solution as it meants to use the cli and manually delete files.
I'd recommend to switch to electrum in your case.
Closing this issue for now.
