### ISSUE TITLE
Wallet tab won't open

### ISSUE THREAD

**Issue by berrybenry** [cryptoadvance/specter-desktop#2365]
I have opened Specter to manage a transaction, and for some reason the tab for my wallet won't open. I click on it a few times and it's unresponsive.

**Comment by k9ert** [comment]
Sorry for the late reply. Please fill out the form for reposrting an issue. We need much more information here and ideally a screenshot. I'm not sure what's meant by "wallet tab" and what you have clicked exactly.

Please don't hesitate to reopen this issue but i'm closing it for now.
