### ISSUE TITLE
Recent transactions not appearing in "recent transactions"

### ISSUE THREAD

**Issue by Fonta1n3** [cryptoadvance/specter-desktop#239]
My most recent (many confs) transactions are not showing up for my multisig wallet in the latest update (0.5.5 macos). The balance is correct though.

**Comment by ben-kaufman** [comment]
@Fonta1n3 we removed the full Addresses view and left just the UTXO view part of it. Could you please try to pull master and check if now data is displayed correctly?

**Comment by Fonta1n3** [comment]
It is there now, thanks!
