### ISSUE TITLE
PGP Key Specter Signer is expired

### ISSUE THREAD

**Issue by izzqz** [cryptoadvance/specter-desktop#2396]
Valid until: `17-Oct-23`
Fingerprint: `785A2269EE3A9736AC1A4F4C864B7CF9A811FEF7`

[From keyserver](http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x785a2269ee3a9736ac1a4f4c864b7cf9a811fef7)

**Comment by k9ert** [comment]
Thanks. It's fixed now. See #2397
