### ISSUE TITLE
PGP key is expired

### ISSUE THREAD

**Issue by haeniya** [cryptoadvance/specter-desktop#2397]
**Describe the bug**
When trying to verify the signature of Specter Desktop I get the following. The PGP key seems to be expired.
![image](https://github.com/cryptoadvance/specter-desktop/assets/12571550/0d21592d-db32-436b-85b8-6795bf653071)
Am I doing something wrong?

**To Reproduce**
1. Follow instructions to verify signature of Specter Desktop (Windows)
2. Download PGP key
3. Import into Kleopatra

**Comment by k9ert** [comment]
Should be fixed!
https://keyserver.ubuntu.com/pks/lookup?search=785A2269EE3A9736AC1A4F4C864B7CF9A811FEF7&fingerprint=on&op=index

<img width="1067" alt="Screenshot 2023-11-16 at 13 50 03" src="https://github.com/cryptoadvance/specter-desktop/assets/117085/9f4ae8e2-7c57-4ce0-a50f-5cf0ecbb81f2">
