### ISSUE TITLE
Not able to add previously added (and deleted) wallet

### ISSUE THREAD

**Issue by TrbnH** [cryptoadvance/specter-desktop#2415]
**Describe the bug**
It is not possible to recreate a wallet. I wanted to check my setup. So I created a wallet send funds to it. Then deleted the wallet. Afterwards I wanted to recreate the wallet with my device and the error occures: "Failed to create wallet. Error: ('Wallet already exists', -4)"

**To Reproduce**
1. Create a wallet
2. Delete this wallet
3. Try to create the same wallet again
4. See error "ailed to create wallet. Error: ('Wallet already exists', -4) "

**Expected behavior**
I expect that I should be able to recreate the wallet.

 - Specter Version [2.0.2]

**Comment by TrbnH** [comment]
There is a solution: Just rename the wallet after you load the .json file or scanned the QR code etc. So it seems that the problem is not the xpub but only the wallet name...

**Comment by JamesKuzilni** [comment]
> **Describe the bug**
> It is not possible to recreate a wallet. I wanted to check my setup. So I created a wallet send funds to it. Then deleted the wallet. Afterwards I wanted to recreate the wallet with my device and the error occures: "Failed to create wallet. Error: ('Wallet already exists', -4)"
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Create a wallet
> 2. Delete this wallet
> 3. Try to create the same wallet again
> 4. See error "ailed to create wallet. Error: ('Wallet already exists', -4) "
> 
> **Expected behavior**
> I expect that I should be able to recreate the wallet.
> 
>  - Specter Version [2.0.2]

Change the name of your wallet when you recreate it. Under Bitcoin Core you have a Wallets directory and you previously created a wallet called Vault, now you are trying to create the same wallet with the same name and getting the error "it already exists".
