### ISSUE TITLE
Specter Test Suit

### ISSUE THREAD

**Issue by ben-kaufman** [cryptoadvance/specter-desktop#244]
Our current test suit is quite small and does not cover much of the code, which results in potential bugs and issues going unnoticed. We should make sure to add some decent test coverage, both for the code on the server-side and the front end integration with it. For the UI testing, we could explore addin a new framework like https://www.cypress.io/ to help us with that. In addition, now that we have a hot wallet, it should be possible to do full transactions testing without setting up an HWW simulator (which seems complicated to automate for tests). This will help us cover also signing and transaction sending etc. in our test suit.

**Comment by stepansnigirev** [comment]
Makes perfect sense.
I was also thinking about raw API for specter (like json-rpc we have for HWI). Maybe to have separate endpoints / blueprints for device, wallet and Core status.
This would help with testing post/get requests and in the future allow javascript to update content dynamically and get notifications.
