### ISSUE TITLE
Feature request: sendmany

### ISSUE THREAD

**Issue by stefanwouldgo** [cryptoadvance/specter-desktop#246]
It would be really useful to be able to send to multiple addresses in one tx. Maybe it's even already possible, but I couldn't find the documentation for it.

**Comment by stepansnigirev** [comment]
It is a very good idea, currently it's not possible with Specter, but Core supports it, so we should do it.

This would require some changes in how we represent transactions in the history tab - to allow multiple addresses there. But certainly possible and nice feature to have!

**Comment by ben-kaufman** [comment]
I actually think that with the recent change to history from yesterday, it might be working out of the box. Just need a way to pass multiple addresses, labels, and amounts in send and I think we could support that fairly easily :)

**Comment by stepansnigirev** [comment]
And change the way we save pending transactions - there should be not one address but a list.

**Comment by ben-kaufman** [comment]
Right, we'll need to modify the pending and signing screens a bit, but not by much I think.

**Comment by ben-kaufman** [comment]
Added in #252
