### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by kosuodhmwa** [cryptoadvance/specter-desktop#2465]
server ip is pingable and telnet-able via its port. so why that message? 
![image](https://github.com/user-attachments/assets/40fca28f-9797-447c-b423-1d195306960e)
![image](https://github.com/user-attachments/assets/48284f3e-3c09-4d7d-adb5-33fb902e9647)

thx for feedback.

bitcoin stack i use is Satoshi:27.99.0 

regards, jan

**Comment by kosuodhmwa** [comment]
i also added disablewallet=0, does not solve problem

**Comment by kosuodhmwa** [comment]
When i enter https instead of http and port 8333 instead of 8332, the spinner animation runs infinitely wtf

**Comment by kosuodhmwa** [comment]
<
When i enter https instead of http and port 8333 instead of 8332, the spinner animation runs infinitely wtf

>

UPDATE: No, same message after a long time

**Comment by kosuodhmwa** [comment]
maybe problem is that it runs via tor? but miro bitcoin manager web gui also runs without tor... (???)

**Comment by kosuodhmwa** [comment]
and no i don't use electum, just a plain bitcoind node with compiled-in wallet support 
https://github.com/cryptoadvance/specter-desktop?tab=readme-ov-file#select-how-to-connect-to-bitcoin-network

**Comment by kosuodhmwa** [comment]
Don't know what the problem is! 
![image](https://github.com/user-attachments/assets/e294d2fc-5de9-4f0e-987b-a390212b8c68)

**Comment by annemarieshev** [comment]
Hello @kosuodhmwa 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID BTC07638
Please see the link below to our dedicated support line:
[Bitcoin Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by kosuodhmwa** [comment]
Reported

**Comment by kosuodhmwa** [comment]
will try it with another product now https://github.com/sparrowwallet/sparrow/issues/1471

**Comment by kosuodhmwa** [comment]
Nearly 100% sure that bitcoins rpc params etc. are NOT the problem https://community.umbrel.com/t/fixed-issue-configuring-specter-with-bitcoin-core-node/15997

**Comment by kosuodhmwa** [comment]
IP is pingable, port is telnet-able too...

**Comment by kosuodhmwa** [comment]
"miro bitcoin" manager (but on 127.0.0.1) is also currectly authenticated (with data in bitcoin.conf) and that works too

**Comment by kosuodhmwa** [comment]
yes, and "sparrow" works not. your product not...
https://github.com/sparrowwallet/sparrow/

**Comment by kosuodhmwa** [comment]
thank you for your feedback

**Comment by kosuodhmwa** [comment]
solved by not-using specter
