### ISSUE TITLE
Freezing with "Launching Specter Desktop..."

### ISSUE THREAD

**Issue by etkaar** [cryptoadvance/specter-desktop#2477]
Unfortunately Specter Desktop 2.0.5 is unusable on Linux (Ubuntu 22.04), because Specter very often freezes with "Launching Specter Desktop...":

![Screenshot from 2024-11-15 16-24-12](https://github.com/user-attachments/assets/b879134f-fb2f-46ba-8b49-8d0bdaf2f019)

Also, Spectrum is suddenly loading forever:

![image](https://github.com/user-attachments/assets/ef4b27c1-ccec-4f9d-9e0a-b7bb1964192e)

**Comment by moneymanolis** [comment]
takes time for Spectrum to sync, can't identify a concrete bug here, closing...
