### ISSUE TITLE
Server error when downloading  zip backup file through browser

### ISSUE THREAD

**Issue by SebastianKnigge** [cryptoadvance/specter-desktop#2478]
#Description
When downloading the zip backup file from the browser in the v1.11.2, I get a server error
<img width="953" alt="image" src="https://github.com/user-attachments/assets/894ebdae-0307-4dd1-b867-c1609b4fc552">

**Comment by entone** [comment]
same issue here

**Comment by entone** [comment]
looks like it's probably related to a deprecation in Flask https://github.com/pallets/flask/issues/4753

**Comment by entone** [comment]
Appears a fix has been merged https://github.com/cryptoadvance/specter-desktop/pull/2456

**Comment by moneymanolis** [comment]
closing this, please use the latest version of Specter

**Comment by entone** [comment]
I'm running specterd, and the "latest" is v2.1.0-pre3, and doesn't appear to provide the full release artifacts. Any timeline on publishing a full release?

**Comment by moneymanolis** [comment]
> I'm running specterd, and the "latest" is v2.1.0-pre3, and doesn't appear to provide the full release artifacts. Any timeline on publishing a full release?

unfortunately, no, no timeline.
