### ISSUE TITLE
Unable to create wallet: "Failed to create wallet. Error: Request error: Wallet already exists"

### ISSUE THREAD

**Issue by etkaar** [cryptoadvance/specter-desktop#2479]
Seems that Specter doesn't really delete wallets if deleted, as it keeps the name of the wallet, so it can't be created again under the same name after removal.

![image](https://github.com/user-attachments/assets/c1ac8aed-2b04-454b-9f3e-497ae350d7cf)
![image](https://github.com/user-attachments/assets/6ce84a2d-c242-4cf2-99ee-2ea7f7a7fdba)

**Comment by moneymanolis** [comment]
depends on your setting, if you run Specter and Bitcoin Core on the same machine it does, if not, not (and then it can't). There is already an [open issue](https://github.com/cryptoadvance/spectrum/issues/47) to delete a wallet with Spectrum so I am closing this.
