### ISSUE TITLE
Improve Usage of trezor in remote-usecases

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#253]
Currently, we have the hwi-bridge which enables the use of trezor in a scenario where specter is running on a different server then where the trezor is connected. But isn't that improvable? Maybe we can leverage https://github.com/trezor/trezord-go or other projects in order to make that easier for the end-user?

**Comment by stepansnigirev** [comment]
This one to connect to Trezor from the browser directly:
https://github.com/trezor/connect
Ledger javascript libs:
https://github.com/LedgerHQ/ledgerjs

I think we can communicate to Specter backend to convert PSBT to device-specific commands using hwilib, and then from JS side communicate to the wallets.

**Comment by k9ert** [comment]
hwi-bridge works ok. So why changing that. Closing for now.
