### ISSUE TITLE
Dynamic backup of the whole wallet

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#255]
Creating backups is not yet in the scope, yet. How about giving the user the maximum flexibility to make backups? So e.g. if you would be able to configure a specific backup-script which gets triggered whenever a change in the .specter-directory happened? This way, "node-packagers" like nodl, mynode or raspiblitz can easily integrate the backup in their own setup.

**Comment by stepansnigirev** [comment]
Good idea! It will also help Specter to keep track if wallet or device files have changed and reload them only when necessary.
At the moment wallet and device files are reloaded on every request that is not optimal.

I think we can have a separate thread that is looking at the `os.stat` of the files in the folder and notifies Specter (and extensions in the future) about changes in the file.
