### ISSUE TITLE
Flexible Core-configuration via environment-variables

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#256]
In certain scenarios, that might make a lot of sense.

**Comment by stepansnigirev** [comment]
One of them - if Bitcoin Core directory is not at default path, autodetect will fail.
We could do env variables like BITCOINDIR, SPECTERDIR, TORPASSWD, SSL_KEY and others. I think it's cleaner than passing these as parameters to specter main script (even though we should still be able to parse cmdline arguments as well)

**Comment by k9ert** [comment]
Usually both possibilities have their usecases. So let's keep command-line-params and let them override the env-vars (if they exist).

**Comment by k9ert** [comment]
I did a focus on the RPC-configuration. So no other env-vars so far in scope of this ticket. Check 
ca09562 for my proposal.

**Comment by stepansnigirev** [comment]
Looks good, I just don't understand why https by default - it will break autodetect for local node...

**Comment by k9ert** [comment]
> Looks good, I just don't understand why https by default - it will break autodetect for local nodes...
Not sure i understand your concern. If the env-vars are specified, local-autodetection is no longer used anyway.
Note that the env-solution will only work if all 4 env-vars are defined. Otherwise i hope everything else works as before.
At least that was my intention. So shouldn't break the autodetection?
