### ISSUE TITLE
Improvement: mobile-friendly UI

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#26]
* Collapse the left nav into a burger menu
* Change the QR code displays to use the includes/overlay.html popups to maximize display without clipping?

**Comment by Fonta1n3** [comment]
How can I run Specter on my mobile device? Sorry for the newb question.

**Comment by stepansnigirev** [comment]
As it's a web interface to your node you can get access to Specter from mobile - over Tor or if you are using VPS like me.
You can't sign with USB hardware wallets in this case, but still you can monitor funds, use Specter-DIY, Cobo, Electrum and hot wallet from mobile.
At the moment web interface looks pretty bad on phones, but hopefully we will get it decent as well.

**Comment by Fonta1n3** [comment]
So create a hidden service for the specter port and open in a tor browser? That is really very cool.

**Comment by stepansnigirev** [comment]
Yes, you already can do it: https://github.com/cryptoadvance/specter-desktop/blob/master/docs/tor.md
There will be problems with the camera access if you don't use self-signed certificates, but otherwise works :)

**Comment by ben-kaufman** [comment]
Closing for now as solved with #731 
We could still improve on mobile friendly-ness but for now, I think it's good enough. Please reopen/ make a new issue if you see a need.
