### ISSUE TITLE
Launch issue with v0.5.5

### ISSUE THREAD

**Issue by tehelsper** [cryptoadvance/specter-desktop#262]
Hey, I'm getting a launch issue on aarch64 platforms and was wondering if you had run into it.

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/__main__.py", line 12, in <module>
>     from .bitcoind import (BitcoindDockerController,
>   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/bitcoind.py", line 15, in <module>
>     from .server import DATA_FOLDER
>   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/server.py", line 11, in <module>
>     from .specter import Specter
>   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/specter.py", line 5, in <module>
>     from .device_manager import DeviceManager
>   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/device_manager.py", line 11, in <module>
>     from .devices.bitcoin_core import BitcoinCore
>   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/devices/bitcoin_core.py", line 2, in <module>
>     from bip32 import BIP32
>   File "/opt/mynode/specter/env/lib/python3.7/site-packages/bip32/__init__.py", line 1, in <module>
>     from .bip32 import BIP32
>   File "/opt/mynode/specter/env/lib/python3.7/site-packages/bip32/bip32.py", line 5, in <module>
>     from .utils import (
>   File "/opt/mynode/specter/env/lib/python3.7/site-packages/bip32/utils.py", line 1, in <module>
>     import coincurve
>   File "/opt/mynode/specter/env/lib/python3.7/site-packages/coincurve/__init__.py", line 1, in <module>
>     from coincurve.context import GLOBAL_CONTEXT, Context
>   File "/opt/mynode/specter/env/lib/python3.7/site-packages/coincurve/context.py", line 4, in <module>
>     from coincurve.flags import CONTEXT_ALL, CONTEXT_FLAGS
>   File "/opt/mynode/specter/env/lib/python3.7/site-packages/coincurve/flags.py", line 1, in <module>
>     from ._libsecp256k1 import lib
> ImportError: /opt/mynode/specter/env/lib/python3.7/site-packages/coincurve/_libsecp256k1.cpython-37m-aarch64-linux-gnu.so: undefined symbol: secp256k1_ecdh

This issue is not present if I install the last version used by myNode, v0.5.2.

Thanks.

**Comment by ben-kaufman** [comment]
Hi @tehelsper, I believe the issue is with a dependency we added in version v0.5.5. We have already removed the dependency from master so it will not be in the next version, which will hopefully solve this issue.

**Comment by tehelsper** [comment]
Awesome, thanks

**Comment by ben-kaufman** [comment]
@tehelsper we included the fix in the last release ([v0.6.0](https://github.com/cryptoadvance/specter-desktop/releases/tag/v0.6.0)) Can you please just check to make sure it solves the issue for you?

**Comment by tehelsper** [comment]
Yes, it appears to be resolved in v0.6.0. Thanks!
