### ISSUE TITLE
New Feature: multiple settings configs: mainnet, regtest, etc

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#28]
Provide an option in the Settings UI to quickly switch back-and-forth between previously saved settings for mainnet, regtest, etc.

**Comment by stepansnigirev** [comment]
Maybe we should add a `known_nodes` list to `.specter/config.json` and build a simple selector widget.
It might be an arrow ▾ next to Bitcoin Core config menu so if you click on it you can choose one of known nodes.

**Comment by kdmukai** [comment]
Could maybe also probe the `known_nodes` list on `specter.check()` if it doesn't introduce delays.

**Comment by ben-kaufman** [comment]
Implemented with the new node manager.
