### ISSUE TITLE
mynodebtc - Upgraded to specter 0.6.0 - Wallet not creating

### ISSUE THREAD

**Issue by imacfan** [cryptoadvance/specter-desktop#284]
Upgraded to v0.6.0 from v0.5 via mynodebtc

It showed existing devices.
However, Wallets were missing. I could see them in directory /.specter though, but not visible in UI
I tried to create both SingleSing and MultiSig both gave error.
I re-installed Specter 
Still same error. See screenshot
![image](https://user-images.githubusercontent.com/54225190/90337569-ef70f280-e000-11ea-9d55-f92518b0180d.png)

**Comment by stepansnigirev** [comment]
Can you update to the latest version 0.7.1 and try? I think this issue was solved in #305

**Comment by ben-kaufman** [comment]
Closing this for now, please reopen if this is still an issue with version 0.8.0 or above.
