### ISSUE TITLE
Extremely slow pageloads

### ISSUE THREAD

**Issue by mflaxman** [cryptoadvance/specter-desktop#289]
Loading the "homepage" of this app takes ~6s:
![Screen Shot 2020-08-17 at 3 21 58 PM](https://user-images.githubusercontent.com/448644/90440938-ade25500-e09d-11ea-85e8-6700f8e6dd58.png)

Loading /devices/coldcard takes ~12s:
![Screen Shot 2020-08-17 at 3 23 42 PM](https://user-images.githubusercontent.com/448644/90440934-acb12800-e09d-11ea-9a6a-ebc9682c4af7.png)

This is not the highest performance machine (and I am syncing bitcoin core node in the background), but I would still expect this to be at least an order of magnitude faster:
![Screen Shot 2020-08-17 at 3 25 03 PM](https://user-images.githubusercontent.com/448644/90441724-141ba780-e09f-11ea-922a-dd7d0e4fa5fa.png)

Using my machine while this node syncs (writing code, browsing websites, sending email, etc) is all very fast. Only Specter is slow.

Screenshots were taken with firefox, but using Chromium has a negligible impact on speeds.

**Comment by stepansnigirev** [comment]
It's because your node is syncing. We make a few rpc calls on every page load, if bitcoin core is syncing it can take a few seconds per call.
We are working on that, making rpc calls independent from page requests, so response time should get better in the next releases.

**Comment by mflaxman** [comment]
@stepansnigirev have you considered [sanic](https://github.com/huge-success/sanic)? It's a popular asyncio framework that should be a drop-in replacement for flask. Might be really useful for these types of background tasks, not to mention generally much better performance. ElectrumX is built on asyncio for example.

Here are some blog posts I've written on the topic IYC:
* https://eng.paxos.com/python-3s-killer-feature-asyncio
* https://eng.paxos.com/should-i-migrate-to-an-async-framework

**Comment by mflaxman** [comment]
Update: performance is now great on a fully synchronized node.

Unfortunately, I made the mistake of running a pruned node (not a lot of SSD space on this laptop). I will connect to a remote node where I can rescan from recent (pruned nodes must be reindexed and not rescanned).

**Comment by stepansnigirev** [comment]
Solved with a significant reduction of the number of RPC calls in https://github.com/cryptoadvance/specter-desktop/pull/588 and https://github.com/cryptoadvance/specter-desktop/pull/631
