### ISSUE TITLE
New Feature: Restrict access w/password

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#29]
Implement access restrictions so that other machines on the local network can't get in. Also ensures that if your Tor onion address were to ever get leaked, a password prompt would still inhibit external access.

**Comment by stepansnigirev** [comment]
I was solving it by using simple httpauth in nginx, but it might make sense to implement authentication in the web ui.

My nginx config:
```
server {
    # server config stuff

    auth_basic "Private Property";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        proxy_pass http://127.0.0.1:25441;
    }
}
```

**Comment by kdmukai** [comment]
Also consider the possibility of remote signers directly accessing the UI (or via Ajax calls) over Tor (see #37). A more limited access layer (sign-only, limited to specific wallet(s)) for those remote signers might be useful.

A remote signer could have two possible flows, depending on signing device:
* Directly log into the UI over Tor and sign via Coldcard or QR.
* Install and launch the signing mini app (#37) locally and enter the server's onion addr. Log in and the mini app automatically retrieves the pending psbt for the wallet(s) the signer is authorized to access. Sign with usb wallet. Mini app transmits signed psbt back to the server to combine.

**Comment by stepansnigirev** [comment]
We have two modes for authentication now:
using rpcpassword: https://github.com/cryptoadvance/specter-desktop/pull/75
multiuser support, or just username & password: https://github.com/cryptoadvance/specter-desktop/pull/172
