### ISSUE TITLE
Tooltip when restoring a backup needs to be more clear or should accept zip files

### ISSUE THREAD

**Issue by nolim1t** [cryptoadvance/specter-desktop#293]
![Screen Shot 2020-08-20 at 00 17 05](https://user-images.githubusercontent.com/83470/90668623-90b6ad80-e27a-11ea-9643-bda9de7516ab.png)

This tooltip needs to either mention you need to extract the zipfile to restore the wallet to avoid some confusion

**Comment by stepansnigirev** [comment]
Good point. Uploading zip files would be convenient.
