### ISSUE TITLE
cannot create wallet-- Specter 0.6.1

### ISSUE THREAD

**Issue by caixiao-1123** [cryptoadvance/specter-desktop#295]
when i create Signal key wallet,Specter throw an exception.
When do you expect to fix the bug？

![image](https://user-images.githubusercontent.com/37337093/90743869-6a3c5500-e302-11ea-85b5-f3b227740558.png)

**Comment by stepansnigirev** [comment]
Can you update to the latest version 0.7.1 and try? I think this issue was solved in #305

**Comment by k9ert** [comment]
Assuming this is resolved. Please don't hesitate to reopen if this is still an issue for you.
