### ISSUE TITLE
Any plans to support light clients in the future?

### ISSUE THREAD

**Issue by mflaxman** [cryptoadvance/specter-desktop#297]
Bitcoin core is the most secure way to interact with the bitcoin blockchain, but having to sync a full node before creating a wallet (to receive funds) *massively* increases the difficulty/overhead of using spectre-desktop for non-expert users.

I'm not asking you to change anything in the short-term, just wondering what the medium-to-long term plan is?

Thanks!

**Comment by k9ert** [comment]
Have a look in the https://github.com/cryptoadvance/spectrum/ repo . The spectrum component currently gets build into specter via a specter-extension. After this is done, you'll be able to connect your own (or public) electrum-server.

I'll close this issue if that's done.

**Comment by k9ert** [comment]
Spectrum has been released in alpha on the [v1.14.5](https://github.com/cryptoadvance/specter-desktop/releases/tag/v1.14.5)  version and will soon be released with prod-level maturity on the [upcoming](https://github.com/cryptoadvance/specter-desktop/releases/tag/v2.0.0-pre10) `v2`. 
So i'll close this issue for now.
