### ISSUE TITLE
Balance not correct for prunded node and "Rescan UTXO"

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#298]
I connected spectre to a pruned node, and (re)created a wallet in spectre. Most transactions in this wallet were prunded by core, because they happened some time ago. However also "Rescan UTXO" (with a large address space) did not show any funds/balance beyond the non-pruned transactions.

**Comment by stepansnigirev** [comment]
>  I guess one would have to get the peer info and connect manually to this peer?
Yes, looks like we would need to connect to a random peer and ask for a block. RPC doesn't have such a command.

Without the block we could create the PSBT transaction ourselves, but without full raw transaction we can't provide non-witness-utxo that is required by Trezor. Other wallets can live without full previous transaction, but Trezor will refuse to sign. So we need to get full raw transaction somewhere.

At the moment I see three options:
- download a block from a random peer, calculate the proof and import the transaction to the wallet
- get the full block from the explorer (like blockstream.info)
- get the proof for the tx from explorer (maybe over Tor?) 

The first one is the best in sense of privacy but also the hardest. We could connect to peers at random and fetch one block from every peer, but it's pretty hard to implement.
The third one is the easiest but exposes information about transactions we are interested in to the block explorer.

**Comment by stepansnigirev** [comment]
And a very ugly way - run bitcoin core with -reindex flag, so it will start syncing blockchain from the very beginning... But it's too much I think.

**Comment by k9ert** [comment]
Isn't this issue now fixed with #344 ? In that case we could close it.

**Comment by ben-kaufman** [comment]
Closed with #344

**Comment by relativisticelectron** [comment]
> In principle it is possible. I was thinking about storing the result of utxo rescan in Specter and adding these utxos to coin selection.
> Another option is to get full blocks we are interested in from other nodes and calculate the proof. Or use a block explorer.
> Anyways I think support of pruned nodes is very important and we will do it one way or another.

This code https://github.com/Start9Labs/btc-rpc-proxy-wrapper  (though in another language) is able to fetch pruned nodes from other peers.
