### ISSUE TITLE
Fails to communicate with Ledger on MyNode

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-desktop#302]
Just to keep track of the issue discussed on Telegram.
MyNode + Ledger - can't open Ledger device.

**Comment by felipeucc** [comment]
I was also unsuccessful in connecting ledger nano S directly to MyNode / raspberry Pi
Any news about that?

**Comment by stepansnigirev** [comment]
Might be fixed now, can you check?

> I was also unsuccessful in connecting ledger nano S directly to MyNode / raspberry Pi
> Any news about that?

**Comment by ben-kaufman** [comment]
Closing as I have seen multiple people report this is already fixed for them. Please reopen if this still doesn't work.
