### ISSUE TITLE
Extra decimal on conversion from BTC to sats on Send screen

### ISSUE THREAD

**Issue by bitcoinheiro** [cryptoadvance/specter-desktop#313]
Hi guys,

There's an extra decimal when converting from BTC on the Send screen display.
See attached screenshot.

![image](https://user-images.githubusercontent.com/50273260/91357358-ca972f00-e7f9-11ea-9993-38671759372e.png)

**Comment by ben-kaufman** [comment]
Hi, good catch, thanks for reporting!
I've fixed it here #314 , just that at the conversion there was an extra 0 after the decimal point...
