### ISSUE TITLE
Add configuration for tor control ip:port

### ISSUE THREAD

**Issue by seth586** [cryptoadvance/specter-desktop#317]
I have tor running on a different device on my local network. It would be nice to specify the tor control ip:port!

**Comment by k9ert** [comment]
The control port can be specified in this method:
https://stem.torproject.org/api/control.html#stem.control.Controller.from_port
... which is called here: https://github.com/cryptoadvance/specter-desktop/blob/master/src/cryptoadvance/specter/cli.py#L122

Other then that, one need to add a new click-option here:
https://github.com/cryptoadvance/specter-desktop/blob/master/src/cryptoadvance/specter/cli.py#L22-L36

Maybe something like --tor-control-address --tor-control-port ?!
