### ISSUE TITLE
Automate Binary Upload for release

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#323]
Doing them manually is a waste of time. Might get difficult for MacOS and Windows, though.

**Comment by stepansnigirev** [comment]
Maybe we can look into how HWI does it, AFAIK they build binaries for mac and windows as well

**Comment by k9ert** [comment]
HWI is using travis which do not allow private runners. Also hwi has a lot less releases than we have. 
They had 10 releases in 1,5 years. We have 26 releases since in 3-4 month! That's legit as we 're much more customer-facing than HWI is. My guess is that Andrew is creating the release by hand with some scripts on his machines.

Imho we should try to automate as much as possible. Today i'll create another PR for a windows-binary.

**Comment by ben-kaufman** [comment]
Closing for now since we have it on Gitlab for Linux and Windows but probably no intention to add macOS there right?
Anyway please reopen if you think it should stay open.
