### ISSUE TITLE
[Feature request] facilitate batch channel opens with LND

### ISSUE THREAD

**Issue by openoms** [cryptoadvance/specter-desktop#338]
Specter has the tools already to be able to create a batch channel open PSBT, but the 
process can be streamlined.
Workflow in Electrum explained with screenshots using the Balance of Satoshis helper tool (https://github.com/alexbosworth/balanceofsatoshis):
http://satbase.org/bos-open/

Needed in Specter:
* paste the addresses and amounts in the format:
```
<ADDRESS>, <AMOUNT>
<ADDRESS2>, <AMOUNT2>
<ADDRESS3>, <AMOUNT3>
```
* accurate fee estimation in advance to be able to create transaction without change (or to be able to choose the best sized utxo)
LN channel opens need to be negotiated as an exact amount so the `Subtract fees from amount` would be dangerous there.

Some notes:
* RBF is not needed for this usecase: https://twitter.com/gugol/status/1298743145782538240
CPFP is the way to go when fees are too low and there is a change output.
* there is a 10 minutes limit to get the signed PSBT to LND: https://github.com/lightningnetwork/lnd/blob/master/docs/psbt.md
* should avoid publishing the signed PSBT accidentally

`

**Comment by ben-kaufman** [comment]
Added in #350
