### ISSUE TITLE
Grammar and Spelling in Info tabs

### ISSUE THREAD

**Issue by manbyt** [cryptoadvance/specter-desktop#341]
Backing up Your Specter Data Info 

Change: 
It is recommended to keep your backup files _privately_ as sharing them _with_ result in privacy leaks.

Backups are recommended to ensure access to funds _remains_ even in case a device from a multisig wallet is lost.

To:
It is recommended to keep your backup files private as sharing them will result in privacy leaks.

Backups are recommended to ensure access to funds remain, in case a device from a multisig wallet is lost.

**Comment by manbyt** [comment]
Found another:
Restoring Specter from backup
Change:
Here you can restore your wallets and devices from an existing _Secter_ backup.
Please make sure to unzip the backup file first, then to select the extracted folder for upload.
Note: Loading devices/ wallets with names identical to existing ones may overwrite the existing ones.

To
Here you can restore your wallets and devices from an existing Specter backup.
Please make sure to unzip the backup file first, then to select the extracted folder for upload.
Note: Loading devices/ wallets with names identical to existing ones may overwrite the existing ones.

**Comment by manbyt** [comment]
If this is annoying let me know. 
In White List Settings info tab: 
Change: 
HWI Bridge: Connect USB devices with Specter

This page is loaded from HWI bridge server you defined above.

To communicate with hardware wallets on your computer you need to make sure Specter domain is whitelisted.

Add whitelist Specter domain to this whitelist.

If the page is not loading - something is wrong with your configuration. Maybe wrong url?

to:
HWI Bridge: Connect USB devices with Specter

This page is loaded from the HWI bridge server you defined above.

To communicate with hardware wallets on your computer you need to make sure the Specter domain is whitelisted.

Add whitelist Specter domain to this whitelist.

If the page is not loading - something is wrong with your configuration. Maybe wrong url?

**Comment by k9ert** [comment]
@webdiverblue

**Comment by PaarthAgarwal** [comment]
Is this issue still open?

**Comment by PaarthAgarwal** [comment]
> Yes, i guess would be cool to fix it @PaarthAgarwal

I searched for typos but didn't find any. All the above-mentioned points have been fixed in https://github.com/cryptoadvance/specter-desktop/commit/d7733a19c68c4934bb4ded4f37796d0f25d8d9be.
Is there anything else you want to be corrected?
