### ISSUE TITLE
Amount for manual coin selection will not validate

### ISSUE THREAD

**Issue by luclefleur** [cryptoadvance/specter-desktop#347]
When manually selecting a UTXO to spend with x BTC on it, and entering x in the Amount field, selecting 'subtract fees', and setting a manual fee of 5 sat/b (for a total fee well under the value of the coin), there is an invalid amount error when clicking 'create unsigned transaction.'

Error in latest Binary for OS X (edited to remove accidental bitcoin core version number).

**Comment by ben-kaufman** [comment]
Hi, can you please check if that still happens with the master branch? Should be fine after #350

**Comment by luclefleur** [comment]
It works when running the most recent version installed from pip. The problem is just in the binary I got from Stephan on telgram.

**Comment by stepansnigirev** [comment]
how about binaries from the release page?
https://github.com/cryptoadvance/specter-desktop/releases/tag/v0.7.2

**Comment by ben-kaufman** [comment]
Closed by #350 
Please reopen if still an issue.
