### ISSUE TITLE
New Feature: Privacy-first block explorer option in tx list

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#35]
Rather than linking txs out to blockstream, pull tx and block info directly from the attached node (provided it isn't pruned) to avoid leaking any privacy info during tx lookups.

Or alternatively (and less work), allow users to point to an existing local block explorer UI (e.g. if they're running btc-rpc-explorer).

**Comment by k9ert** [comment]
I guess an easy fix would be to provide a template-snippet in the App-settings so that the link is created from that template?

**Comment by kdmukai** [comment]
Or a custom template tag? It could check from a list of supported block explorers which one was configured in settings and then render the proper url.

Something like:
```
{% load explorer_urls %}

<a href="{% tx_explorer_url|txid %}">{{ txid }}</a>
<a href="{% block_explorer_url|block_id %}">{{ block_id }}</a>
<a href="{% addr_explorer_url|addr %}">{{ addr }}</a>
```

**Comment by stepansnigirev** [comment]
My initial thoughts were that if I paid someone I want to send him a link to the block explorer with the transaction. I never looked into tx details myself.
With the local block explorer we can fetch some information about the transaction but we can't share this link.
I think fetching transaction information from the local block explorer is nice, but I would also like to keep ability to share the link to online block explorer with someone. 
How should we do both? Add a "copy link to blockexplorer" button?

**Comment by kdmukai** [comment]
For pending txs the recipient's wallet will find the tx in the mempool. But makes sense as a way to refer back to a confirmed tx long after the fact. I think some UI "view vs share" distinction shouldn't be too hard to work out. Like the tx hash is a link to the private viewer but there's also that box w/arrow out icon to indicate an external link.

**Comment by stepansnigirev** [comment]
We have an explorer url that the user can define in settings (empty by default).
If explorer is not set clicking on the txid copies txid into the buffer.
https://github.com/cryptoadvance/specter-desktop/pull/89
https://github.com/cryptoadvance/specter-desktop/pull/144
