### ISSUE TITLE
Ledger keys 'Get over USB' only gets first account

### ISSUE THREAD

**Issue by joostjager** [cryptoadvance/specter-desktop#353]
It finds the account `m/84'/0'/0'`, but not for example `m/84'/0'/1'`. 

Adding it manually is not so easy, because it seems the xpub cannot be retrieved in Specter. Also the fingerprint is only shown when connecting the device and after `Get over USB`.

**Comment by stepansnigirev** [comment]
Good point, we should add account support...

**Comment by ben-kaufman** [comment]
Added in #360

**Comment by joostjager** [comment]
Tested in 0.8.0 and works as expected. Great, thank you!
