### ISSUE TITLE
Add support for connecting to a remote node over Tor

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-desktop#363]
Connecting to a bitcoin core over Tor would be nice to have.
Same for block explorer url.
Probably can be done with requests sessions.
See for example https://stackoverflow.com/questions/42971622/fetching-a-onion-domain-with-requests

**Comment by ChristopherA** [comment]
We have a new tutorial on Tor in “Learning Bitcoin from the Command Line”: https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/14_0_Using_Tor.md

I also recommend you support QuickConnect https://github.com/BlockchainCommons/Gordian/blob/master/Docs/Quick-Connect-API.md and some initial thoughts on QuickConnect 2.0 https://github.com/BlockchainCommons/Gordian/issues/66 cc: @fonta1ne

**Comment by stepansnigirev** [comment]
Looks good, thanks!
Do you know if there is a way to install Tor service on Windows?

**Comment by Fonta1n3** [comment]
> Looks good, thanks!
> 
> Do you know if there is a way to install Tor service on Windows? Linux and MacOS work nicely, but I didn't figure out how to do it on Windows...


https://github.com/Fonta1n3/FullyNoded/blob/master/Docs/Tor/Tor.md#Windows-10

**Comment by stepansnigirev** [comment]
That's awesome! Thanks a lot for the link!

**Comment by vindard** [comment]
> That's awesome! Thanks a lot for the link!

I'm still having problems connecting to my remote node's Bitcoin RPC via Tor on Windows (on remote node I've already setup a Hidden Service that I can successfully connect to from an Ubuntu box using Specter Desktop)

I've gotten as far as the following **_on Windows_**:
- edit `torrc` to add the line `ControlPort 9051`
- go to `control panel -> network & internet -> internet options -> connection -> lan setting` and tick `Use a proxy...` and then use the address and port as `127.0.0.1` and `9051` ([see here](https://stackoverflow.com/a/61306130))


This gets me as far as this on Specter Desktop now when I test the connection but I can't seem to move ahead any further:

![image](https://user-images.githubusercontent.com/17693119/98472479-bb553a00-21c9-11eb-8dc2-06ab8b297119.png)
