### ISSUE TITLE
Value being displayed in exponent instead of full sats

### ISSUE THREAD

**Issue by bitcoinheiro** [cryptoadvance/specter-desktop#365]
Noticed this at the MoN's (k3tan) video.

At the review transaction info screen after the tx has been prepared and is ready to sign.
He's running Windows on a VM (Ubuntu) - maybe this is something only this machine will experience.

![image](https://user-images.githubusercontent.com/50273260/92386348-52473c80-f11c-11ea-9b3e-49eae3f904dc.png)

**Comment by ben-kaufman** [comment]
Fixed in #367
