### ISSUE TITLE
[Feature request] Create wallets for all keys in a device

### ISSUE THREAD

**Issue by openoms** [cryptoadvance/specter-desktop#369]
Proposing a workflow improvement for importing multiple derivation paths from one device.
For example the 5 mixdepths of the JoinMarket wallet (https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/USAGE.md#funding-wallet-and-displaying-balance):
```
m/49'/0'/0'
m/49'/0'/1'
m/49'/0'/2'
m/49'/0'/3'
m/49'/0'/4
```
Samourai Wallet:
```
Deposit: m/44'|49'|84'|47'/0'/0'
Bad Bank: m/84'/0'/2147483644'
Pre Mix: m/84'/0'/2147483645'
Post Mix: m/84'/0'/2147483646'
Ricochet: m/44'|49'|84'/0'/2147483647'
```
Other examples at: https://walletsrecovery.org/

The `Master Public Keys` can be exported from the wallets themselves or by importing the seed to SpecterDIY or ColdCard.
Suggestion:
when all the `Master Public Keys` have been imported under a `Device` in SpecterDesktop there could be a button to automatically create a wallet for each key (with some batch naming option) instead of going through the process of wallet creation one by one.

**Comment by k9ert** [comment]
I think this is easily solvable via a specter-extension. Check the docs here:
https://docs.specter.solutions/desktop/extensions/

Have to close this as we won't work on that anytime soon.
