### ISSUE TITLE
Adding a slide bar to adjust the actual size of the QR code for better compatibility with Cobo Vault

### ISSUE THREAD

**Issue by BitcoinLixin** [cryptoadvance/specter-desktop#374]
Cobo Vault is using a fixed focal length camera to scan the QR code. 

We use a fixed focal length camera because the scanning speed is more than twice faster than auto focus length camera - a auto focus camera will redo focus procedure when it sees a new QR code and in the scenario of animated QR code, it takes much more time than fixed focal length camera.

But the fixed focal length cause another problem - it can only read the QR code in a specific range of actual size. This is not a big problem if the user is using mobile companion app. But if the user is using a desktop software wallet like Specter, as the PPI varies a lot between different monitors, it better to add a slide bar on Specter for user to manually adjust the actual size of the QR code.

It would be better if the size can be memorized so the users don't need to adjust every time.

Thanks Ben & Stepan!

**Comment by ChristopherA** [comment]
Can you also post this at https://github.com/BlockchainCommons/AirgappedSigning/discussions ?

**Comment by BitcoinLixin** [comment]
> Can you also post this at https://github.com/BlockchainCommons/AirgappedSigning/discussions ?

https://github.com/BlockchainCommons/AirgappedSigning/discussions/15
