### ISSUE TITLE
Used other coins to create tx even with coin selection activated

### ISSUE THREAD

**Issue by bitcoinheiro** [cryptoadvance/specter-desktop#377]
Hi, maybe this was already fixed, but I used the coin selection when testing the wallet and it failed me.
It used the input that was not selected to compose a transaction instead of  accusing invalid amount.

Forgot to report this before, remembered now that this is inside this video that was recorded a while ago and still was not published:

https://youtu.be/FYxE0Pr3EUk?t=573 

Let me know when you see this so I can reschedule the video for publishing next week.

**Comment by bitcoinheiro** [comment]
Also, why I cannot set the fee to a uneven number? Only from steps of 0.5 sats per byte allowed?

**Comment by stepansnigirev** [comment]
Regarding the coin selection, in your video you send the whole utxo amount, but Core needs to take fees from somewhere, so it adds another input just to get the fees.
Either check the "subtract from amount" checkbox, then the fees will be subtracted from this utxo, or add another input, or reduce the amount.

Fee rate - agree, the step should be arbitrary. We will fix it.

**Comment by stepansnigirev** [comment]
Yes, I think it is a good idea.

**Comment by bitcoinheiro** [comment]
Could also be part of the check made when user uses coin selection and also clicks on "max" or "send all" (because this issue only happens when user sweeps all funds from an address). Maybe force the "subtract fees from amount" in those cases

**Comment by ben-kaufman** [comment]
I think this is fixed now with the current send max button and coin control options. Please reopen if this still happens.
