### ISSUE TITLE
Windows version 0.7.2 classified as virus by Avira

### ISSUE THREAD

**Issue by akc2020** [cryptoadvance/specter-desktop#382]
Avira https://www.avira.com/ has classified Specter Desktop for Windows version 0.7.2 as a virus on my Win 10 PC. The tool identified the pattern "HEUR/APC (Cloud)" and moved it to quarantine. I have contacted the software company and reported it as a "false positive".

**Comment by stepansnigirev** [comment]
It's an issue of pyinstaller packaging, hopefully will be fixed in the next release. We slightly changed how we package the binary in #370

**Comment by akc2020** [comment]
Thank you. Once released I will try again. - I have just tried v0.7.3-pre1 but there were three errors during installation, renaming of files failed. "MoveFile failed; code 5".

**Comment by akc2020** [comment]
I have just tried today's 0.8.0 release. Avira no longer flags Specter Desktop, the installation went through well. Thank you!
