### ISSUE TITLE
Add the category 'Date' to wallet history and UTXOs.

### ISSUE THREAD

**Issue by kolmansoifer** [cryptoadvance/specter-desktop#385]
Adding the calendar date for txs to the wallet history and UTXO screen would be nice for reference purposes.
Being able to sort tx by Date would also be useful.

**Comment by ben-kaufman** [comment]
The date should already be visible as part of the Status column, for the moment, it's only sorted as latest -> oldest, but yes would be nice to be able to reverse the order also. Though isn't it already part of #384 ?

**Comment by kolmansoifer** [comment]
Hi Ben,
Yes, the date is visible via the Status column but would be nice if it were broken out into its own sortable category.

When i submitted #384, i didn’t mention ‘Date’ as a category.  I wan’t sure if I could edit a submitted issue, so i just made an additional submission (#385).
Sorry if that was redundant or messy…..  

Thanks again, KS

**Comment by ben-kaufman** [comment]
Exists in v1.0.0
