### ISSUE TITLE
New feature: utxo selection on sends

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#40]
Continuing with privacy-focused utxo improvements.

Select exactly which utxos will be involved in a particular transaction. In conjunction with #39 we would get much closer to Electrum, Wasabi, etc. level of utxo privacy management.

**Comment by stepansnigirev** [comment]
I think we can add a "choose inputs" button on the send screen and when it is clicked we can display a pop-up with all available utxos with lables and checkboxes to select them.

**Comment by stepansnigirev** [comment]
#96 fixed this
