### ISSUE TITLE
docker-compose support for specter+bitcoind+tor

### ISSUE THREAD

**Issue by pox** [cryptoadvance/specter-desktop#413]
- [ ] Add a `docker-compose.yml` file that can build & launch Specter Desktop, along with bitcoind and using tor.
- [ ] Add documentation 

### Open Questions

- How to specify the volume location for the bitcoind data dir, as the default might not be ideal for lots of setups

**Comment by k9ert** [comment]
Doesn't seem to be anyone working on this.
