### ISSUE TITLE
Using passphrase with Trezor Model One does not work anymore after latest firmware update

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/specter-desktop#417]
Passphrase feature worked fine before latest firmware update form Trezor (Model T: version 2.3.3 and  Model One: version 1.9.3, see for details: https://bit.ly/32KQx7i) which brought a new passphrase feature ("on-device confirmation") which apparently broke the functionality in Specter Desktop. @stepansnigirev

**Comment by ben-kaufman** [comment]
Just tested with Trezor One on the 1.9.3 firmware. Everything works fine for me except with the new wizard, where for some reason it ignores the passphrase. Is that where you had an issue?

**Comment by ben-kaufman** [comment]
Closed by #420 
Please feel free to reopen though if this still seems to be happening.

**Comment by moneymanolis** [comment]
Yes, you can't input the passphrase.

**Comment by ben-kaufman** [comment]
Are you sure you have the passphrase enabled on the device? You can try from the device screen to toggle the passphrase and see if it says if it's already enabled or not.

**Comment by moneymanolis** [comment]
Yes.

**Comment by moneymanolis** [comment]
Can you enter a passphrase with the latest Trezor firmware?

**Comment by ben-kaufman** [comment]
Ok, I'll reopen the issue the. But it doesn't seem related to the Trezor firmware update as I tested also with the new firmware.

**Comment by ben-kaufman** [comment]
Yes I tested and works for me. So doesn't seem like it's issue with the latest firmware.

**Comment by moneymanolis** [comment]
That's really strange, because it works with a One with the older firmware but not with the newest one.

**Comment by ben-kaufman** [comment]
Hmm but just to be completely sure, did you verify that with toggle passphrase the passphrase is already enabled? A firmware update could possibly toggle this off (to default) so even if it was on it might got switched off.

**Comment by moneymanolis** [comment]
I'll rerun tomorrow to be 100% sure.

**Comment by moneymanolis** [comment]
Okay, it "works", but you need to confirm the passphrase on the One multiple times, at least 8 times.

**Comment by stepansnigirev** [comment]
The flow is improved with the device wizard https://github.com/cryptoadvance/specter-desktop/pull/598, so now at least you will see that xpubs are added one by one after each confirmation click.
