### ISSUE TITLE
Make it more clear which are the download links

### ISSUE THREAD

**Issue by mflaxman** [cryptoadvance/specter-desktop#428]
Normies are confused:
https://twitter.com/TheRealFreddyF4/status/1308437883078942722

A dedicated static website (i.e. specter-desktop.github.io) would be great, but more simply I think just changing the copy [here](https://github.com/cryptoadvance/specter-desktop/releases/tag/v0.8.0) to put big download links for Specter-Desktop at the top would solve most of the problem (I assume specterd is for advanced users who can dig through all the text/links and figure it out).

I'd submit a PR but I think only @stepansnigirev can edit the text on the releases page?

**Comment by stepansnigirev** [comment]
I agree, it's a problem. We'll make a web page for Specter-Desktop soon-ish.

**Comment by mflaxman** [comment]
github pages (jekyll) is pretty great if you're not familiar. Example here:

**Comment by ben-kaufman** [comment]
We now have the https://specter.solutions/downloads/ page
