### ISSUE TITLE
Change the project/repo name?

### ISSUE THREAD

**Issue by mflaxman** [cryptoadvance/specter-desktop#433]
I'm getting confusion from people that there are two specters: `Specter-Desktop` and `Specter-DIY`. Would it be possible to change the name of one of them (and then the other could just be `Specter`)?

I know this is an annoying request, creates work, and doesn't add functionality. I have no opinion on which project should have which name and what the other should be, only that I think the confusion is harming *both*.

As another anecdote, I wasn't initially that excited about contributing to `Desktop` because I assumed `Desktop` was a project specifically/only for `DIY`. Separating the two names counter-intuitively makes `Desktop` **more** useful. The current full name `Specter-Desktop` is also quite the mouthful.

To be totally clear: I'm not proposing any change in maintainers, who has commit access, project direction, etc. It's just confusing that these two different projects have almost the same name.

**Comment by bitcoinheiro** [comment]
Specter Device? Specter Hardware?
I guess just changing DIY would be enough.

It cannot be only "Specter" - that would be too broad and not SEO friendly

**Comment by xraid** [comment]
Specter handheld

Specter handy

Specter signer

**Comment by stepansnigirev** [comment]
I think the most confusion is because both the software wallet and the hardware wallet have the name Specter in it.
On the other hand, they are related, Specter Desktop started as a software wallet for Specter-DIY, but became more than that.

**Comment by calkob** [comment]
I think Specter Desktop sounds good and has been getting some hype on popular podcasts need to be careful that changing the name dosnt add to more confusion at this point.  If anything i think it would be best to change the DIY to something else, if at all. 

Specter Desktop wallet & Specter HW Device? not great but just me 2cents

**Comment by k9ert** [comment]
I've tried to crowdsource naming suggestions here: https://twitter.com/k9ert/status/1309037848411209740
Here is the list:
* Specter Device
* Specter Hardware
* Ghost, spook, wraith and the like even Ecto short for [Ectoplasm](https://en.wikipedia.org/wiki/Ectoplasm_(paranormal)) :-D
* specter Offline <-- my favorite
* Specter Delorean (because of [some UX similarities](https://twitter.com/_pretyflaco/status/1309044992468451333) ;-) )
* Specterware
* Pac-Bit

**Comment by stepansnigirev** [comment]
We discussed it a bit and decided to keep the names for now. We may rethink the name for Specter-DIY when we release a fully-assembled manufactured version of the hardware
