### ISSUE TITLE
Coldcard save transaction dialog (suggestion)

### ISSUE THREAD

**Issue by oduspace** [cryptoadvance/specter-desktop#439]
I was a bit confused by the Coldcard upload/download dialog option descriptions when saving a PSBT to SD card. The two options are 'Download transaction' and 'Upload signed transaction'. 'Download' suggests (to me anyway) that a file or some other data will be pulled into Specter from somewhere else, when in fact it is the opposite. For clarity, some alternative dialog descriptions might instead be 'Write unsigned transaction to file' and 'Read signed transaction from file', respectively.

**Comment by k9ert** [comment]
I think this is indeed a result from server vs- desktop software. I think your proposal is indeed a good one.

**Comment by figgyfigs** [comment]
Found the file for this issue. Are we okay with the rewording that @oduspace provided?

"Download transaction" to "Write unsigned transaction to file" and "Upload signed transaction" to "Read signed transaction from file". If yes I'll make these changes.

**Comment by stepansnigirev** [comment]
Maybe just "Save to file" and "Load from file" ?

**Comment by stepansnigirev** [comment]
Thanks for reminding about this issue, and sorry for taking an opportunity from you to contribute, we are releasing today and I thought it would be nice to have it merged before the release.

**Comment by figgyfigs** [comment]
No worries, I'll work on another issue!
