### ISSUE TITLE
Linux Binary fails on Linux-Mint 20 (Virtualbox)

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#441]
> Unable to run the v0.8.0 Specter desktop binary in my LinuxMint 20 Virtualbox session. It's kicking out a bunch of error/warning 
> messages before dumping. I've been running v0.7.2 without any problems. Are there additional dependencies on v0.8.0?

The error-message is not very fruitful, though. We need to make a way to provide more insights here.
![image](https://user-images.githubusercontent.com/117085/94343420-61812200-0018-11eb-9d19-303678c8ccc2.png)

First step here is to integrate a way how users can report the used dependency easily similiar to what's explained in #373 and what's currently commented in the source-code:
https://github.com/cryptoadvance/specter-desktop/blob/master/pyinstaller/specter_desktop.py#L388-L394

**Comment by stepansnigirev** [comment]
Should work fine now as we switched to Electron.
