### ISSUE TITLE
Connect to Bitcoin Node not on the Specter Computer

### ISSUE THREAD

**Issue by fhoenyx** [cryptoadvance/specter-desktop#443]
I've downloaded Specter 0.7.2 and am trying to connect it to a Full Node not connected to this computer. It says it can do it, but I can't find instruction on how to point Specter to it.

**Comment by ben-kaufman** [comment]
Hi, you can check this explanation for example of connecting to a remote Bitcoin Core running on a myNode: https://twitter.com/zndtoshi/status/1291737252419207171?s=20

**Comment by k9ert** [comment]
Documentation is definitely not where we'd like it to see. Did it helped you?
If not, please click the "test-button" and let us know if you have something different then green checks:
![image](https://user-images.githubusercontent.com/117085/94672775-0603ac80-0316-11eb-84b7-c656f8bcb7c6.png)

**Comment by fhoenyx** [comment]
It didn't work but I don't think I added the right data into the fields. Is the username, password, and host the username and password of the computer I'm accessing that has the blockchain and the IP address.of the computer I'm connecting to?

**Comment by fhoenyx** [comment]
![image](https://user-images.githubusercontent.com/48840777/95096506-f6a7a900-06f1-11eb-8f68-c6c7ec23a9c1.png)

**Comment by k9ert** [comment]
I've created this document to support troubleshooting efforts with connecting to full-nodes. Can you check whether anything in there helped? If you've solved your issue, it would be interesting to know whether anything in there would have helped you?
https://github.com/k9ert/specter-desktop/blob/improve_errorhandling/docs/connect-your-node.md

**Comment by fhoenyx** [comment]
That's very thorough! Thank you! My bitcoin.conf file only has 3 lines in
it and none of them speak to RPC at all. I added those lines setting a
username and password. Ill see if that solves the problems. The section im
referencing is below. If that solves the issue, it may be a good starting
point to add in the middle of that section. Something like "if you dont
have the "rpcuser=bitcoin" or rpcpassword=aVerySecretPassword lines, add
them.

[image: image.png]

**Comment by fhoenyx** [comment]
That didnt seem to work. Now Im having issues connecting to my node on that
computer. Yikes.

**Comment by fhoenyx** [comment]
Notice back up and running again. Is it possible that there is hidden text
in the Bitcoin.conf file?

**Comment by k9ert** [comment]
You also have to restart the bitcoin-service. Watch the logs es they will tell you if the bitcoin.conf is not readable or has issues.
If in doubt, paste suspicious lines from the log-files in here!

**Comment by fhoenyx** [comment]
To be honest, I think the majority of the issue is the computer I loaded
Linux on to. I've had a laundry list of troubles trying to get the node up
and running.  I'm working on my second remote node on a windows so I'll see
if I can get that working remotely.  Can I run Specter on computer A,
reference a full node on the se computer, AND run Specter on Computer B and
reference that se node on Computer A? ie two instances of specter
referencing the se full node.

**Comment by k9ert** [comment]
Yes, you can run two different specters referencing the same fullnode.

**Comment by fhoenyx** [comment]
Wonderful! I'll let you know how the remote connection goes with that one.
Your instructions seem pretty clear, I just don't have that info in my conf
file. It was completely blank when I set up the first one. Followed K3tan's
guide and added the 3 lines that are in there. Thank you for helping
though, I really appreciate it!

**Comment by k9ert** [comment]
Assume that this is solved.
