### ISSUE TITLE
Show an explanation if wallet functionality is disabled

### ISSUE THREAD

**Issue by leshik** [cryptoadvance/specter-desktop#444]
Right now it throws an exception if the node is started with `-disablewallet=1`. Might be better to show some nice explanation that the node wallet should be on as it's used to store exported keys, etc.

**Comment by ben-kaufman** [comment]
Hi, thanks for reporting, we have a check for that when clicking on Test on the Bitcoin Core tab on Settings, but seems like that was broken. I fixed it in #461 and also added better error handling for this case when trying to create wallet.
