### ISSUE TITLE
Unable to load wallet folder on both app and browser. 

### ISSUE THREAD

**Issue by calkob** [cryptoadvance/specter-desktop#445]
was able to upload files via browser originally but deleted wallets to test recovery and now continually getting the server error below.

The browser does find the files but error show when you tey to load them. 

![server error specter wallet](https://user-images.githubusercontent.com/16057802/94372544-84820380-00f6-11eb-928c-45037185741d.png)

Windows 10
Core 0.20.1
specter 0.8.0

**Comment by calkob** [comment]
So been playing about with this and found that loading both devices and wallets together works.  

Noticed that when i totally uninstalled specter from the laptop and reinstalled it remembered my devices, where is that information cached? and wouldnt it be better for privacy if it was deleted?

**Comment by stepansnigirev** [comment]
Specter stores all its data in the `.specter` folder in your home directory. So if you want to delete everything delete this folder as well.
In Bitcoin Core it creates wallets in a separate folder as well, so in your Bitcoin directory you will see `wallets/specter<randomid>` folder where Specter creates wallets.
You may want to delete this folder as well (requires unloading all corresponding wallets from bitcoin core, or just stopping it)

**Comment by ben-kaufman** [comment]
The issue is actually fixed here: https://github.com/cryptoadvance/specter-desktop/pull/430/files#diff-a386d70e20c16c989ef22377f5ca3398R354

The PR doesn't say anything about it because I discovered the bug while testing the PR and fixed it on the way and forgot to mention that, I'll write there that it handles this issue too.
