### ISSUE TITLE
Wallet with existing balance shows tx sorted randomly

### ISSUE THREAD

**Issue by ChineseGeek** [cryptoadvance/specter-desktop#447]
A wallet imported from Coldcard with existing balance, shows tx sorted randomly, instead of sorting them by date or confirmations on the Status column. Rescaning the whole blockchain didn't solve the issue.

**Comment by calkob** [comment]
i think specter sorts them in derivation path for example m/84'/0'/0'/1,  m/84'/0'/0'/2,  m/84'/0'/0'/3 for example.  you may have been randomly selecting on previous software.

**Comment by ben-kaufman** [comment]
I think this is solved now with #738
Please reopen if this is still happening.
