### ISSUE TITLE
QR codes don't show up with Tor browser

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-desktop#448]
<img width="501" alt="Screenshot 2020-09-28 at 15 40 24" src="https://user-images.githubusercontent.com/1706012/94439685-062e6b80-01a1-11eb-8ecd-53b805bfee9b.png">

**Comment by ben-kaufman** [comment]
I just tried myself and looks like you only need to grant permission for the URL to use HTML5 canvas. After clicking like in the picture and approving I refreshed and the QR codes worked fine. Not sure if we have a way around this permission thing really...

<img width="672" alt="Screen Shot 2020-09-30 at 8 26 51" src="https://user-images.githubusercontent.com/10667901/94646463-f32daf80-02f6-11eb-9d6d-3b25ca1ce180.png">

**Comment by HassMc** [comment]
Can confirm the same error. Wallet import/export QR codes are working, but QR codes for transaction signing isn't working (just a blank image)

Running MyNode with Specter 0.8.1 on RasPi 4 - run it in Chrome, Brave and Edge (Windows 10), all with the same issue

**Comment by ben-kaufman** [comment]
Closing, please reopen if still relevant
