### ISSUE TITLE
Wont start after download/install

### ISSUE THREAD

**Issue by btcjake** [cryptoadvance/specter-desktop#450]
Downloaded the link for Mac. Installed and when I click to start nothing happens. I read in the troubleshooting to right click and "open" but still wont work.

**Comment by ben-kaufman** [comment]
Hi, which macOS version are you using?

**Comment by btcjake** [comment]
version 10.12.6

**Comment by ben-kaufman** [comment]
Thanks, we currently don't have support for most of the old macOS versions with the packaged desktop app, so to use it on such older OS you'll need to install directly from `pip` like this: https://github.com/cryptoadvance/specter-desktop#installing-specter-from-pip

**Comment by k9ert** [comment]
Sorry for not being able to better support you. Hope the workaround helps you. I'm closing this issue for now.
