### ISSUE TITLE
Allow import of binary psbt file

### ISSUE THREAD

**Issue by jimmysong** [cryptoadvance/specter-desktop#452]
Currently, you have to paste the base64-encoded psbt to upload a signature. Allow a file upload of a binary psbt.

**Comment by stepansnigirev** [comment]
If you set your device type to "Other" then you will lose an option to use USB for signing, but you will get two other options - to scan QR code with base64-encoded psbt or download/upload psbt transaction as a file.
File format is either binary or base64.
You can change device type any time.

<img width="909" alt="Screenshot 2020-10-01 at 01 13 56" src="https://user-images.githubusercontent.com/1706012/94749199-8dd3d000-0383-11eb-9853-630429d5a646.png">

But I think it's a good idea to extend "Paste PSBT transaction" to have more options - files and QR codes.

**Comment by ben-kaufman** [comment]
Closed by #469
