### ISSUE TITLE
'Method Not Allowed' error when connecting to remote bitcoin node

### ISSUE THREAD

**Issue by cbeams** [cryptoadvance/specter-desktop#453]
I am able to connect to my remote bitcoin node via bitcoin-cli as follows:

```
$ bitcoin-cli -rpcconnect=192.168.0.199 -rpcuser=mynode -rpcpassword=redacted getblockcount
650497
```

However, when attempting to connect to the same remote node from specter desktop, I get `405: Method Not Allowed` as follows:

<img width="956" alt="image" src="https://user-images.githubusercontent.com/301810/94547241-4f3cf900-024f-11eb-85af-b8dd68da6ff8.png">

Specter Desktop version: 0.8.0.
Bitcoin Core version: 0.20.1

**Comment by stepansnigirev** [comment]
Can you try setting port to `8332`?

**Comment by cbeams** [comment]
I did so and it works, thanks. I left in blank because I thought it would default to 8332. The "Default ports..." language below the field is obviously just a helpful reminder about the different values, but I read it hastily and assumed it meant that it would actually automatically use the default mainnet port value. My bad, but perhaps others would make the same mistake. Perhaps you could validate the form field and explicitly indicating to the user that it's required when they leave it blank.

**Comment by stepansnigirev** [comment]
I agree, we should default to 8332 if nothing is in the port field, I will open a separate issue on that.

**Comment by stepansnigirev** [comment]
This one
https://github.com/cryptoadvance/specter-desktop/issues/456
