### ISSUE TITLE
Specter version "unknown"

### ISSUE THREAD

**Issue by cbeams** [cryptoadvance/specter-desktop#454]
I've installed Specter Desktop 0.8.0 via the .dmg on the GitHub releases page, and the version reads 'unknown' as follows:

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/301810/94548225-af806a80-0250-11eb-8cad-fdcbda89ba0f.png">

By contrast, Specter Desktop 0.6.0 running on a mynode installation displays the version properly.

**Comment by stepansnigirev** [comment]
Yes, binary installations don't support versions yet.
It is already implemented and merged into master, so should be available in 0.8.1

**Comment by ben-kaufman** [comment]
Yes, fixed with #421

**Comment by cbeams** [comment]
Thanks. Closing as a duplicate of #421.
