### ISSUE TITLE
HWI Bridge doesn't detect Ledger (macOS connected to myNode)

### ISSUE THREAD

**Issue by ben-kaufman** [cryptoadvance/specter-desktop#477]
I couldn't reproduce this myself, but got a report on issue where running Specter on myNode and connecting to it from macOS (Chrome), with HWI Bridge set up and running. Specter just seems to not detect the Ledger (firmware 1.4.6) connected there.

**Comment by andytipton** [comment]
I'm having a similar issue of Ledger not being detected in MacOS.  However I am running on the core GUI not by the bridge.

**Comment by ben-kaufman** [comment]
Hi, I believe the issue is related to a change we made in packaging the app and should be solved with #473 

Meanwhile, I think the v0.8.2-pre1 pre-release should work as well. Can you please try that and see if that works for you?
https://github.com/cryptoadvance/specter-desktop/releases/tag/v0.8.2-pre1

**Comment by bektar** [comment]
I have the same issue and v0.8.2-pre1 did not help. Coldcard works fine though.

**Comment by bektar** [comment]
Update on my end: On a completely fresh install of macOS (no brew, no cli tools… nothing after setting up a new user) my ledger works using v0.8.2-pre1 (getting warnings about being malware when starting it the first time though)
