### ISSUE TITLE
Desktop App doesn't start on OSX

### ISSUE THREAD

**Issue by jgustave** [cryptoadvance/specter-desktop#478]
OSX 10.13.6.
v0.8.1
App doesn't start.
'ps -ef | grep specter' shows nothing, no icon in tray.

I also tried v0.8.0:
Gives me the usual OSX security warnings which I clicked through as well as allowing the app in 'Security and Privacy'.

Don't know how to debug further.

**Comment by stepansnigirev** [comment]
We were compiling the binary on 10.15, so I am not sure about backward compatibility on MacOS.

I can suggest installing specter with pip:
https://github.com/cryptoadvance/specter-desktop#installing-specter-from-pip

**Comment by k9ert** [comment]
Does that solves the issue for you? As a very small project, it's quite difficult to support that many OSes. So if you can update or use the pip-version, i'd be happy to close this issue.

**Comment by stepansnigirev** [comment]
Should be solved as we codesign mac binaries now. If the issue is not resolved with v9 please reopen.
