### ISSUE TITLE
Unfriendly error message when scanning a QR Code without https

### ISSUE THREAD

**Issue by nioncode** [cryptoadvance/specter-desktop#482]
The basic specter setup is with plain http. When trying to scan a QR Code (in Firefox), I get an error: `TypeError: navigator.mediaDevices is undefined`

This most likely happens because of the camera access requiring https as written in the readme, but it would be great if specter could display a helpful error message instead of this cryptic error message to make it clear to users what the actual problem is, something like: `Camera access not allowed. Specter must be run over https to enable QR code scanning.`

**Comment by stepansnigirev** [comment]
Thanks, https://github.com/cryptoadvance/specter-desktop/pull/533 should fix it!
