### ISSUE TITLE
"Electrum was unable to parse your transaction"

### ISSUE THREAD

**Issue by mcsnubbs** [cryptoadvance/specter-desktop#484]
In Specter 0.7.2 I've created a multisig wallet using multiple types of wallets. If I create a PSBT in Specter and bring it over to an electrum wallet for the first signature I get the following error:

"Electrum was unable to parse your transaction: SerializationError('PSBT input cannot have both PSBT_IN_NON_WITNESS_UTXO and PSBT_IN_WITNESS_UTXO')"

Oddly enough, if I sign the PSBT with another wallet (eg Cobo Vault), then bring the PSBT to electrum, electrum handles the PSBT without error. Im assuming that Specter is incorrectly constructing the PSBTs for electrum?

**Comment by stepansnigirev** [comment]
Looks like Electrum doesn't like when both witness utxo and full previous tx are present in the psbt transaction.
Both are included by default in Core 0.20.1, so looks like we need to remove full prevtx.
Thanks for reporting!

**Comment by Fonta1n3** [comment]
> Looks like Electrum doesn't like when both witness utxo and full previous tx are present in the psbt transaction.
> Both are included by default in Core 0.20.1, so looks like we need to remove full prevtx.
> Thanks for reporting!

@mcsnubbs just needs to update Electrum to the latest beta release and it will work, I had the same issues and can confirm latest beta electrum fixes it.

**Comment by mcsnubbs** [comment]
Thank you both!

**Comment by k9ert** [comment]
Assuming that @Fonta1n3 is right, i'm closing this issue. Feel free to open again if this doesn't solve it. Thank you @Fonta1n3  for the hint.
