### ISSUE TITLE
PSBT's not exported as BIP174

### ISSUE THREAD

**Issue by Fonta1n3** [cryptoadvance/specter-desktop#486]
I think it would be nice to export the psbt file as the raw binary `.psbt` type as defined in BIP174 [here](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki#encoding) when the user exports a file. This would be compatible with Coldcard SD card, Electrum file import and Fully Noded file upload.

**Comment by Fonta1n3** [comment]
The raw text as base64 seems to get some odd formatting/styling, when I print the clipboard contents directly it shows as Chinese:

挀䠀一椀搀倀㠀䈀䄀䤀欀䌀䄀䄀䄀䄀䄀吀匀㈀稀漀䬀戀愀㔀䜀挀昀䨀㘀　䴀瘀䴀㔀䰀夀伀䜀挀䬀焀搀⬀䘀猀㈀甀搀昀嘀䤀䰀甀娀㌀嘀氀瘀䄀儀䄀䄀䄀䄀䐀⬀⼀⼀⼀⼀䄀猀䘀渀䘀眀䄀䄀䄀䄀䄀䄀䤀最䄀最㄀最眀⼀儀礀琀椀栀㄀礀䜀㌀堀䘀砀眀渀　⬀㌀䴀嘀䜀伀匀戀䘀刀䬀昀瘀䰀戀⬀　氀倀眀䈀圀戀㘀最栀最䔀䄀䄀䄀䄀䄀䄀䌀䤀䄀䤀䄀䈀最㜀戀唀䬀一䈀㌀戀嘀䌀刀焀刀圀渀瀀漀礀欀瀀㘀䔀娀搀䤀爀䬀伀氀㈀䌀最唀䜀㠀瘀稀䄀㜀䤀䄀䄀䄀䄀䄀䄀䄀䈀䄀倀猀䌀䄀䄀䄀䄀䈀一漀䬀䬀㤀䨀䠀䜀椀攀伀䤀娀䈀砀攀攀唀刀稀䘀焀䌀爀焀䤀䐀䴀㤀䨀椀戀⼀甀琀洀㤀⼀㐀瀀㜀焀娀䔀最䄀䄀䄀䄀䐀㤀⼀⼀⼀⼀一䨀㌀䤀樀㈀戀　猀㌀䌀戀渀圀䠀㠀唀㔀栀搀愀猀䘀匀䨀礀稀匀挀刀夀猀攀䜀㜀礀渀礀吀椀㐀搀䴀䄀䄀䄀䄀䄀䄀倀㌀⼀⼀⼀⬀渀䘀一刀猀焀戀一䌀稀渀䰀稀稀㘀䠀㜀琀昀㤀嘀嘀䄀㄀猀氀昀爀氀唀琀倀一䰀㘀渀稀䰀夀最匀㤀最䄀䄀䄀䄀䄀䄀⼀昀⼀⼀⼀㈀椀䬀刀㄀㠀圀䴀　樀洀刀瀀儀圀儀挀一䐀眀㘀䰀儀砀䨀䬀娀爀礀䰀匀㐀猀䈀琀洀樀䤀嘀攀䤀甀匀䄀儀䄀䄀䄀䄀䐀㤀⼀⼀⼀⼀䄀瀀瀀䈀瘀儀䤀䄀䄀䄀䄀䄀䜀堀愀瀀䘀䜀洀圀刀猀猀㘀琀搀一㘀㐀欀䴀⬀砀⼀栀堀礀刀匀眀㠀一猀䠀椀䬀礀一⼀䈀最䄀䄀䄀䄀䄀䄀䌀䤀䄀䤀䔀堀稀堀㐀洀䘀㐀堀猀儀䴀稀⬀甀㤀漀㈀樀甀㤀搀栀㜀䨀䤀洀䨀樀洀䘀漀儀戀㤀㔀爀夀娀䤀攀挀䌀䄀䄀䄀䄀䄀䄀䔀䈀䬀㐀㌀㠀䜀䄀䄀䄀䄀䄀䄀䄀䤀最䄀最刀昀一昀椀夀堀栀攀砀䄀稀倀㘀㜀㈀樀愀伀㜀㄀㈀䠀猀欀椀夀洀伀夀圀栀䈀瘀㌀洀琀栀欀栀㔀眀䤀䈀䈀圀氀匀䤀儀䨀㜀娀㘀㔀㠀䔀稀　䜀㤀栀昀漀氀䌀夀䐀㜀甀倀吀匀猀吀匀愀琀一稀㔀戀娀⬀㐀猀㄀䜀䜀䔀吀漀⼀䌀䔀䐀䨀娀㘀儀㌀㄀㌀㜀搀䠀娀䰀㤀刀猀圀㜀嘀⼀夀䈀琀稀䨀樀戀䐀䴀㈀㜀甀嘀儀栀䌀刀䌀昀嘀䠀瘀倀漀栀䄀㤀䰀漀爀㤀最猀欀刀嘀㔀椀眀㐀䜀瘀䔀氀礀琀䠀㌀㄀挀稀稀戀㠀挀娀吀最甀娀䘀䨀樀娀椀礀䄀䄀刀唀㘀㐀椀䈀最䨀㜀娀㘀㔀㠀䔀稀　䜀㤀栀昀漀氀䌀夀䐀㜀甀倀吀匀猀吀匀愀琀一稀㔀戀娀⬀㐀猀㄀䜀䜀䔀吀漀⼀䈀稀㔀㤀椀䜀唀䴀䄀䄀䄀最䄀䄀䄀䄀䤀䄀䄀䄀䄀䌀䄀䄀最䄀䄀最䄀䔀䄀䄀䄀䌀洀䄀䄀䄀䄀䤀最夀䐀䨀娀㘀儀㌀㄀㌀㜀搀䠀娀䰀㤀刀猀圀㜀嘀⼀夀䈀琀稀䨀樀戀䐀䴀㈀㜀甀嘀儀栀䌀刀䌀昀嘀䠀瘀倀漀挀礀夀猀嘀一吀䄀䄀䄀䤀䄀䄀䄀䄀䌀䄀䄀䄀䄀䄀最䄀䤀䄀䄀䤀䄀䈀䄀䄀䄀䄀瀀最䄀䄀䄀䌀䤀䜀䄀㤀䰀漀爀㤀最猀欀刀嘀㔀椀眀㐀䜀瘀䔀氀礀琀䠀㌀㄀挀稀稀戀㠀挀娀吀最甀娀䘀䨀樀娀椀礀䄀䄀刀䠀䠀一㄀戀䠀㠀眀䄀䄀䌀䄀䄀䄀䄀䄀最䄀䄀䄀䄀䤀䄀䌀䄀䄀䌀䄀䄀儀䄀䄀䄀䬀夀䄀䄀䄀䄀䄀䄀儀䘀瀀唀椀䔀䌀渀㤀栀爀䴀㐀㜀䨀䰀挀㈀唀䔀䴀夀䠀䔀㠀洀樀䬀㤀㜀漀䘀爀㠀礀栀稀㠀䨀䰀圀㄀　䰀稀⼀㘀⼀眀㐀栀䄀㄀䨀愀嘀砀䜀娀攀渀吀攀焀　椀夀氀吀匀䌀琀⼀㔀䘀昀㜀匀一瘀㠀琀樀焀䠀娀唀堀㄀氀嘀儀䌀㌀㠀䤀儀倀最㘀䜀㜀㐀唀䈀嘀瘀䨀稀䴀刀䰀琀儀䰀樀䠀䐀愀渀匀䈀瘀堀爀㤀伀渀䔀娀瀀焀洀渀洀䨀欀䔀䨀砀氀伀甀䤀最䤀䌀渀㤀栀爀䴀㐀㜀䨀䰀挀㈀唀䔀䴀夀䠀䔀㠀洀樀䬀㤀㜀漀䘀爀㠀礀栀稀㠀䨀䰀圀㄀　䰀稀⼀㘀⼀眀㐀挀礀夀猀嘀一吀䄀䄀䄀䤀䄀䄀䄀䄀䌀䄀䄀䄀䄀䄀最䄀䤀䄀䄀䤀䄀䈀䄀䄀䄀䄀䈀䄀䄀䄀䄀䌀䤀䌀䄀㄀䨀愀嘀砀䜀娀攀渀吀攀焀　椀夀氀吀匀䌀琀⼀㔀䘀昀㜀匀一瘀㠀琀樀焀䠀娀唀堀㄀氀嘀儀䌀㌀㠀䠀倀渀㈀䤀娀儀眀䄀䄀䌀䄀䄀䄀䄀䄀最䄀䄀䄀䄀䤀䄀䌀䄀䄀䌀䄀䄀儀䄀䄀䄀䄀儀䄀䄀䄀䄀椀䄀最倀最㘀䜀㜀㐀唀䈀嘀瘀䨀稀䴀刀䰀琀儀䰀樀䠀䐀愀渀匀䈀瘀堀爀㤀伀渀䔀娀瀀焀洀渀洀䨀欀䔀䨀砀栀砀稀搀圀砀⼀䴀䄀䄀䄀最䄀䄀䄀䄀䤀䄀䄀䄀䄀䌀䄀䄀最䄀䄀最䄀䔀䄀䄀䄀䄀䔀䄀䄀䄀䄀䄀䄀䔀䈀愀嘀䤀栀䄀栀伀䜀唀䰀㌀洀䌀猀䜀礀娀愀猀㄀攀猀䴀爀欀䄀樀㄀䐀樀圀圀⬀欀欀琀㄀刀吀伀䔀猀㔀䐀䤀瀀㔀攀䤀儀䴀攀㘀䴀⼀　䄀䰀伀⼀伀䜀琀氀唀礀㤀䘀圀焀戀匀㌀㐀䰀樀䤀欀䬀㘀夀甀瀀㐀瘀㌀挀樀夀㔀㐀䨀洀匀䔀䐀䨀戀氀䴀䜀㐀儀椀㔀㄀圀稀䰀㈀洀吀䄀愀䤀渀琀匀圀挀搀䈀堀稀䤀㘀䔀戀夀琀䐀最挀洀椀䐀㤀洀嘀吀爀椀䤀䌀䄀栀伀䜀唀䰀㌀洀䌀猀䜀礀娀愀猀㄀攀猀䴀爀欀䄀樀㄀䐀樀圀圀⬀欀欀琀㄀刀吀伀䔀猀㔀䐀䤀瀀㔀攀䠀倀渀㈀䤀娀儀眀䄀䄀䌀䄀䄀䄀䄀䄀最䄀䄀䄀䄀䤀䄀䌀䄀䄀䌀䄀䄀䄀䄀䄀䄀䬀欀䄀䄀䄀䄀椀䄀最䴀攀㘀䴀⼀　䄀䰀伀⼀伀䜀琀氀唀礀㤀䘀圀焀戀匀㌀㐀䰀樀䤀欀䬀㘀夀甀瀀㐀瘀㌀挀樀夀㔀㐀䨀洀刀稀䨀椀砀唀㄀䴀䄀䄀䄀最䄀䄀䄀䄀䤀䄀䄀䄀䄀䌀䄀䄀最䄀䄀最䄀䄀䄀䄀䄀䌀瀀䄀䄀䄀䄀䤀最䤀䐀䨀戀氀䴀䜀㐀儀椀㔀㄀圀稀䰀㈀洀吀䄀愀䤀渀琀匀圀挀搀䈀堀稀䤀㘀䔀戀夀琀䐀最挀洀椀䐀㤀洀唀挀挀㌀嘀猀昀稀䄀䄀䄀䤀䄀䄀䄀䄀䌀䄀䄀䄀䄀䄀最䄀䤀䄀䄀䤀䄀䄀䄀䄀䄀䄀焀儀䄀䄀䄀䄀䄀㴀

**Comment by Fonta1n3** [comment]
Removing the styling manually from the text and then pasting it works fine, not sure how to do that programmatically.

**Comment by Fonta1n3** [comment]
Just an update, I must have exported the original file as an Electrum signer, I see when I export as a file under the "other" type it exports the plain base64 text.

I think it would be nice to export the file as the raw binary `.psbt` type as defined in BIP174 [here](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki#encoding) when the user exports a file. This would be compatible with Coldcard SD card, Electrum file import and Fully Noded file upload.

**Comment by stepansnigirev** [comment]
What is the benefit over base64? Don't you support base64 encoding on Fully Noded?
I think using base64-encoded file to move psbt to an airgapped computer and then sign it with Bitcoin Core is also a valid use-case and binary format will break it.

**Comment by Fonta1n3** [comment]
Well its the officially supported format as per BIP174 and what Coldcard, BlueWallet, Electrum, Fully Noded and Gordian all support. Of course we support base64 but as text not as a file upload.

**Comment by stepansnigirev** [comment]
Ok, makes sense. Fine with implementing it.
