### ISSUE TITLE
Download of wallet after finishing wizard

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#487]
via Stephan Livera:

> btw i'm thinking one good feature or UX to build in to the wizard would be: when the user 
> goes thru multi sig wizard set up, at the end, they're actually prompted to save the JSON 
> backup file and keep copy of it with each HWW. This will probably save a lot of future grief

**Comment by k9ert** [comment]
This is a simple UX issue which needs just to combine things which are already there. It has a potential quite high impact, though.
Good first issue!

**Comment by stepansnigirev** [comment]
https://github.com/cryptoadvance/specter-desktop/pull/614 allows to download backup pdf at the end of the creation process
