### ISSUE TITLE
Encryption password not working on Bitcoin Core (hot wallet) device

### ISSUE THREAD

**Issue by pedromvpg** [cryptoadvance/specter-desktop#490]
Is the encryption password field on the **New Device > Device Type > Bitcoin Core** screen refer to a BIP38-encrypt Passphrase?

If so, leaving the field blank or adding a password returns exactly the same zpub. This makes it impossible to import BIP32 protected wallets.

Am I missing something?

See test below:

```
labor better pink common fashion unit strategy swift depend resemble street win lab opera ozone fee cancel doctor design bleak dish odor bachelor escape
↓
[57c6d2be/84h/0h/0h]zpub6qgcH99CzfwsYujyHnGQKA7ZoUWWAxWBX6CcMGQJDutyAyA3EkJjhdptynYTAEU5h92jpbp6X2x9XNRxcCPh8C24dt4RfFzSmFEDd4ZPDAb
```

```
labor better pink common fashion unit strategy swift depend resemble street win lab opera ozone fee cancel doctor design bleak dish odor bachelor escape
+
gLkEZy44[zA;xA{Z
↓
[57c6d2be/84h/0h/0h]zpub6qgcH99CzfwsYujyHnGQKA7ZoUWWAxWBX6CcMGQJDutyAyA3EkJjhdptynYTAEU5h92jpbp6X2x9XNRxcCPh8C24dt4RfFzSmFEDd4ZPDAb
```

![Frame 16](https://user-images.githubusercontent.com/807505/95273425-0f5ab080-0811-11eb-913e-8a2d441a4158.png)

**Comment by ben-kaufman** [comment]
Hi, no, the encryption password on the Bitcoin Core device type refers to the Bitcoin Core wallet encryption mechanism:
https://bitcoincore.org/en/doc/0.20.0/rpc/wallet/encryptwallet/

I see why this seems confusing though, and would be happy to hear if you have suggestions on how to better explain this in the UI and make it clearer that the encryption is for the wallet storage on the machine, not for the seed itself.

**Comment by pedromvpg** [comment]
Now that it's explained it seem pretty obvious. Is there a way to also include a bip38 passphrase?

I guess the language on the field label could change to "Encrypt Wallet File" and the placeholder could read just "password". It reads more direct and like an action.

**Comment by ben-kaufman** [comment]
Makes sense, I've just opened a PR (#514) which will both change the terminology and add support for BIP39 passphrase for the hot wallet. So once that's merged you'll be able to use a BIP39 passphrase with Specter's hot wallet functionality.
