### ISSUE TITLE
Improvements for reverse-proxy setups

### ISSUE THREAD

**Issue by max302** [cryptoadvance/specter-desktop#492]
Hello, 

I've been trying my hand at integrating specterd into BTCPayServer, I'm almost there but I've run into a bind with regards to the reverse proxy setup. 

The is probably a very hacky way of working this out with a complex setup of URI rewrites within NGINX, but I'm guessing that as adoption increases, other people will run into my problem. 

The problem itself is that linking to external resources (images, stylesheets) seems to be inconsistent, which breaks proxy actions; some are linked with trailing slashes, some are not. Here's an example:

icon.png in div `footer` (does not work): 
`<img src="/static/img/icon.png" style="width: 35px;">`

icon.png in div `messages` (works):
`<img src="static/img/icon.png" width="40px" style="vertical-align: top; margin-right: 20px;">`

I see a few ways of fixing this, but since I'm not familiar with Workzeug, I thought I'd run it by you guys. 

1. Fix the markup to use relative links for all resources
2. Configure Workzeug to serve the application at a specific base URI, which would reflect what I'm trying to use in BTCPayServer. (domain.com/specter -> 0.0.0.0:/specter/)
3. Document a full list of endpoints and asset locations to help people with their proxy setups. 

My docker image is [https://github.com/max302/specter-docker](url). I'm using the specterd binaries. 

Let me know what sounds like the simplest/best, hopefully I can help out and propose a PR.

**Comment by k9ert** [comment]
Can you please have a look here:
https://github.com/cryptoadvance/specter-desktop/pull/504

Would that help here as well?

**Comment by max302** [comment]
This is exactly what I need, @kexkey's use case is almost identical to mine!
