### ISSUE TITLE
Crash when clicking "Scan" ( for QR, when sending)

### ISSUE THREAD

**Issue by JayOceans** [cryptoadvance/specter-desktop#493]
when trying to send a TX from wallet, 
App crashes when i click "Scan"....
many times, i tried again & crash

**Comment by ben-kaufman** [comment]
The issue is something with PyQt WebEngine, so a workaround would be to use Specter directly from the browser instead for scanning (either click open in browser on the menu icon or just go to http://127.0.0.1:25441/)

I'll keep looking for a solution to make it work on the packaged app to though

**Comment by JayOceans** [comment]
in the browser, the app does Not crash, when click "Scan"
But, after i click "Allow" the camera doesn't work...
it just does nothing...
But, it might just be My camera, i had issues before...

**Comment by ben-kaufman** [comment]
I'm not sure, for me that does work from the browser so I guess the camera might be the issue...
