### ISSUE TITLE
Doesn't run on systems with GCC version < 2.25

### ISSUE THREAD

**Issue by bitcoinoplomo** [cryptoadvance/specter-desktop#495]
Downloaded the binaries and they didn't work
```
$ ./specterd 
[324] Error loading Python lib '/tmp/_MEIpXOxpr/libpython3.8.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIpXOxpr/libpython3.8.so.1.0)
```

Because I have  GCC 2.23 on my Slackware 64 14.2
```
$ ldd --version
ldd (GNU libc) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

Also cloned the git and tried to build and install with no success.
It doesn't work in systems with GCC < 2.25 ?

**Comment by k9ert** [comment]
> It doesn't work in systems with GCC < 2.25 ?

Unfortunately, no. We decided to build on Ubuntu bionic. See #373 for details.
I'm sorry but we can't support these old versions.
A reasonable workaround would be to [intsall from pip](https://github.com/cryptoadvance/specter-desktop#installing-specter-from-pip).
