### ISSUE TITLE
hot wallets don't support custom derivation paths

### ISSUE THREAD

**Issue by jlopp** [cryptoadvance/specter-desktop#498]
Unlike when adding a hardware device, viewing a hot wallet does not provide the "add more keys" option for custom derivation paths. Is this a Bitcoin Core limitation or just something that hasn't been added to the UI yet?

**Comment by ben-kaufman** [comment]
The limitation is just on the UI side of Specter. We use Bitcoin Core's descriptor wallet functionality which allows custom derivation, so it shouldn't be difficult to allow this on Specter's side.

**Comment by jlopp** [comment]
Gotcha; this is a blocker for several different potential wallet recovery paths for Casa users (depending upon their setup) so it would be great if this could be prioritized since it sounds like it shouldn't be much work to add.

**Comment by ben-kaufman** [comment]
I've just opened a PR (#514) which adds support for custom derivations for Bitcoin Core hot wallet (among other things. You can try out that branch and see if that handles the use cases you have in mind. Let me know if there's something you need and is not covered by that.
