### ISSUE TITLE
Missing PyQt dependencies for specter_desktop tray app

### ISSUE THREAD

**Issue by ZeroPointEnergy** [cryptoadvance/specter-desktop#501]
without `PyQt5`

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/specter_desktop", line 2, in <module>
    from PyQt5.QtGui import QIcon, QCursor, QDesktopServices
ModuleNotFoundError: No module named 'PyQt5'
```

without `PyQtWebEngine`

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/specter_desktop", line 30, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
```

**Comment by ZeroPointEnergy** [comment]
Well, I just realized that they are in `pyinstaller/requirements.txt` and that this scripts are not installed with the pypi version. I just looked at the top level `requirements.txt`.

Is this something that will be in the pypi version in the future or only in the binary version?

I'm currently working on an ebuild that will hopefully in the future end up in Gentoo GURU (some dependencies need to be worked on). This is the work in progress ebuild: https://github.com/ZeroPointEnergy/portage-overlay/blob/master/net-p2p/specter-desktop/specter-desktop-0.8.1.ebuild

It does not use pyinstall, but the scripts are working fine with some minor adjustment, like the shebang and some small patch to get the icon from `static/img/` instead of wherever pyinstall places the `icons` folder. You can see that patch here: https://github.com/ZeroPointEnergy/portage-overlay/blob/master/net-p2p/specter-desktop/files/load-tray-image-from-static-resource-dir.patch .

I guess there is a possibility this scripts could work with the pypi version as well.

**Comment by k9ert** [comment]
I don't have much idea about gentoo-builds. The [binary/pyinstaller build](https://github.com/cryptoadvance/specter-desktop/blob/master/pyinstaller/build-unix.sh) significantly differs from the pip-base build and there is other stuff in the [pyinstaller-dir](https://github.com/cryptoadvance/specter-desktop/tree/master/pyinstaller) which contributes to the specificality of the binary build.

> Is this something that will be in the pypi version in the future or only in the binary version?

I think it's definitely worth separating the two things. I really hate that build-process of the binary  and it's imho woth questioning that OS-specific packages replicate that. There is still the possibility to make it much simpler by running it simply on port 25441 but then it's not really multiuser ... Aaahhh ... i hope there is some project out there which allows the user to use the browser on localhost via https but also to run the server-client-side.

**Comment by ZeroPointEnergy** [comment]
> I think it's definitely worth separating the two things. I really hate that build-process of the binary and it's imho woth questioning that OS-specific packages replicate that.

Well the scripts are worcking nicely and they don't seem to rely on anything pyinstall specific. So I will just keep it the way it is now. The tray application that starts the web view is pretty awesome. Let me know if you are interested in a patch for the icon resources. This would prevent you from having to put them into two separate directories. But maybe that was deliberate.

Yeah those local web applications binding to a specific port aren't really multi user. On Linux there may be the possibility to use a network namespace. I think the user should be able to create their own without needing any privileges. But have not looked into that yet.

**Comment by stepansnigirev** [comment]
Closing as we switched to Electron for the app.
