### ISSUE TITLE
Two tiny issues/typos

### ISSUE THREAD

**Issue by s-5Q2X8mgeGR** [cryptoadvance/specter-desktop#503]
**1. "unsigned" typo**
- /wallet/send/new/wallet_send.jinja
line 40 & line 45 

"usigned" → "unsigned"

**2. UTXO page, label title width hardfixed/not adequate**

The label title width seems to have its width fixed. For a label of this length, "自己的，11/10/2020, 从小的", only  "自己的，11/10/2020" is shown. There's plenty of space for the width to be larger. Ideal solution probably make twice larger in width and add line breaks, but given not that important a quick fix to double the width should probably be enough for most. 

See video: ![SpecterDesktop_-two-tiny-issues](https://user-images.githubusercontent.com/71570725/95687340-4828ca00-0c03-11eb-9c48-8d8d5008bb58.gif)

**Comment by Bayernatoor** [comment]
Got the typo fixed

haven't worked much with jinja, trying to see how to fix issue 2

**Comment by stepansnigirev** [comment]
Thanks for noticing and sorry for a long time without any reaction.
#532 should fix it :)
