### ISSUE TITLE
Signing failed on ColdCardWallet  and Ledger Nano S. 2 of 2 multisig

### ISSUE THREAD

**Issue by cryptocliffy** [cryptoadvance/specter-desktop#509]
Hi

I created a multisig with ledger nano s and CCW MK3. Used a mynode on network device as full node and win64 exe for specter

Steps:
1) Added device Ledger Nano S
2) Added device CCW3 
3) Imported cold card public keys as per faq

While signing a send transaction with CCW3, I get an error Invalid PSBT on both airgapped and usb method

![image](https://user-images.githubusercontent.com/70041260/95798182-fedc9580-0d3c-11eb-90a2-823565febe7f.png)

While signing with Ledger Nano S, The Ledger asks to confirm outputs and inputs. but after confirmation on the device.
Nothing happens and the specter does not display acquired. It stays at Acquired 0 of 2 signatures. 

Both devices has a custom passphrase set along with 24 word seed. 

I have tried this on specter specterd-0.7.2-win64 and specterd-v0.8.1-win64. Both give same errors.

**Comment by cryptocliffy** [comment]
On checking the Multisig.json. Both xpubs are from coldcard so a multisig is created with 2 devices but both devices are CCW. 

Not sure why or how this happened.

**Comment by cryptocliffy** [comment]
I managed to withdraw my funds using the ledger nano by setting up the seed from ccw... had to sign just once to send it. looks like ccw has some validation for duplicate xpub due to which it throws error.. I think i had deleted some keys that were imported into specter as i wanted to keep only multisig segwit keys to avoid confusion. i might have done some mistake there. surely specter has a bug somewhere it created a multi sig wallet with 2 cold card wallet xpubs. and same id. 

CCW was cranky and did not allow signing but setting the CCW seed in ledger allowed me to sign transaction and withdraw my coins.. although it wasnt a lot its still a relief as it could be lot in future. 

Love the specter wallet hope this issue gets fixed for other who might mess up like i did..

**Comment by ben-kaufman** [comment]
I believe the issue is now solved with v0.9.2. Please reopen the issue if still facing it.
