### ISSUE TITLE
You cannot send more than XXX BTC!

### ISSUE THREAD

**Issue by bobjones0** [cryptoadvance/specter-desktop#512]
I get this error when trying to create a transaction with 3 or more outputs even when the total amount spent is much less than my available funds. The only way around it is to have less outputs. I'm running Specter Desktop on Windows. It is connected to my full node. Great program otherwise. Thanks to the devs on this project!

**Comment by ben-kaufman** [comment]
Hi, I've just checked and the amount validation worked fine for me. Did you maybe have existing unsigned transactions (in the unsigned tab) while trying to do that?

Also which version of Specter are you using?

**Comment by bobjones0** [comment]
There were no unsigned transactions. My version is v0.8.1. I was sending from a nested-segwit wallet to a segwit wallet. Perhaps that will help you reproduce the error? Four inputs and four outputs caused the error one time. I reduced both by one, which then worked. Then another time it gave the same error with three inputs and three outputs, so I had to reduce to two and two for it to work. Also, it would have worked with the greater number of outputs if I reduced the amount being sent below a certain amount, however I had more than enough funds for the larger amount, so there's a bug somewhere in there. Thanks.

**Comment by bobjones0** [comment]
I continue to have this problem, and now it seems it is not related to multiple outputs but rather exceeding a certain spending amount (via one output or more). I continue to get the "You cannot send more than XXX BTC!" error when trying to create a transaction, even though I am sending less (far less) than my total available funds from a wallet. For privacy reasons I don't want to write the amounts I am trying to send, but this bug is there. There are no unsigned transactions. There are not pending funds.

**Comment by ben-kaufman** [comment]
Hi, I'll retry to check that. Just need to know, were you using coin control when that happens? Also does this issue happens consistently with the same amount or only sometimes and with different limits?
Just last question is if the amount shown in the error is matching your total balance in the wallet or is it the much lower amount it limits you to?

**Comment by bobjones0** [comment]
This happens with or without coin control. It happens with different amounts and seems to be related to the first digit of the amount I type to send. It will reject a *lower* amount that starts with a higher digit but not a higher amount starting with lower digit. For example (and these are obviously not the numbers I am using, but just to illustrate the point), if I had 1,000 BTC available, it would not reject me sending 1000 but would reject 200. I hope that makes sense. Also the first digit is always rejected if it is greater than the first digit of the total available balance. For example if the available balance were 2,000, it would reject 30 but allow 2000, 1900, etc. If the available balance were 3,000, it would reject any number starting with a 4 or greater. And yes the error matches the total available balance. Also, nothing in fact needs to be entered in the Send->New page besides the amount to cause the error.

**Comment by ben-kaufman** [comment]
Thanks for the detailed info! I was now able to reproduce this thanks to the note on the first number being large. Will check and work to fix this ASAP.

**Comment by ben-kaufman** [comment]
@bobjones0 thanks a lot for reporting and helping me find out the issue! Seems like some of the amount validation code was broken since it was comparing between strings instead of numbers.
I found and fixed the issue in #516 so it will be working properly with the next version.

**Comment by bobjones0** [comment]
Awesome. Thanks for all the great work you do!
