### ISSUE TITLE
Support UR crypto-psbt animated QR codes

### ISSUE THREAD

**Issue by Fonta1n3** [cryptoadvance/specter-desktop#513]
Was wondering if by any chance you guys would be interested to support this standard for animated QR codes: https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-006-urtypes.md#partially-signed-bitcoin-transaction-psbt-crypto-psbt

Fully Noded, Sparrow, Gordian Wallet and Gordian Signer have implemented it. Looks like you guys are just splitting up the base64 which of course we can add support for too, hopefully BlueWallet and Cobo will also update to `crypto-psbt`. Just gets messy having to add checks for every possible standard.

**Comment by stepansnigirev** [comment]
Good that we are getting a common standard.
Ok to implement both for DIY and desktop.

**Comment by stepansnigirev** [comment]
Implemented with Keystone integration
