### ISSUE TITLE
Submit partially signed transaction to Specter via QR code

### ISSUE THREAD

**Issue by Transisto** [cryptoadvance/specter-desktop#518]
Multisig flow, 

Create transaction in specter web-browser
Scan that transaction QR code via electrum mobile
Sign that transaction on mobile, Then we're shown a PSBT Qr-code
Now the only way to submit that transaction is to paste the signed transaction, Would like the browser to scan the PSBT from the phone.

(at this step)
![image](https://user-images.githubusercontent.com/388716/96197462-28094b80-0f20-11eb-8e87-cb8080219c12.png)

**Comment by stepansnigirev** [comment]
If you use Electrum as a signer why don't you use Electrum device type? It provides an interface to scan or upload psbt when you click on "sign with xxx" button. What do you see when you click on 222 and other device buttons?

**Comment by Transisto** [comment]
> If you use Electrum as a signer why don't you use Electrum device type? It provides an interface to scan or upload psbt when you click on "sign with xxx" button. What do you see when you click on 222 and other device buttons?

The keys are all electrum type, I have no problem scanning and signing the the transaction but once signed I had to find a way to send the copy/past from mobile to desktop. Instead of having the browser scan the 1/2 signed transaction.

**Comment by stepansnigirev** [comment]
When you are signing a transaction with Electrum there is a button specifically for this purpose, don't you have one?

<img width="633" alt="Screenshot 2020-10-17 at 18 06 45" src="https://user-images.githubusercontent.com/1706012/96347689-a9d5b200-10a3-11eb-88cb-d9762d4548cf.png">

**Comment by Transisto** [comment]
> When you are signing a transaction with Electrum there is a button specifically for this purpose, don't you have one?
> 
> <img alt="Screenshot 2020-10-17 at 18 06 45" width="633" src="https://user-images.githubusercontent.com/1706012/96347689-a9d5b200-10a3-11eb-88cb-d9762d4548cf.png">

Yes, thank you, I didn't see it there and must have closed this window, 

Would it be a good idea to also have it right next to "Paste signed transaction" in the transaction's page?

**Comment by stepansnigirev** [comment]
The qr code format is different depending on the device type, so common scan qr button is a bit problematic.
Also if you are using usb wallet this button will be useless. "Paste psbt" is there for exceptional cases when you receive a signed transaction from your cosigner over email etc.
