### ISSUE TITLE
Unable to connect to remote node via Tor

### ISSUE THREAD

**Issue by cbeams** [cryptoadvance/specter-desktop#519]
I am able to connect to my remote node on my local network via IP address, but am unable to connect via Tor onion address. I am able to connect via Tor using other wallets and apps, so I know my server-side configuration is fine. I assumed that I should be able to enter the onion address of my node in the `Host` field and that connecting should just work. Instead I get the following error when attempting to test the connection:

> Process finished with code -1Error message: Failed to connect

I noticed that the Tor icon it the upper right corner of the Specter app was grayed out. I attempted to start it, assuming this is necessary for connecting via Tor to work, and got the following error:

> Failed to start Tor hidden service.Make sure you have Tor running with ControlPort configured and try again.Error returned: 'NoneType' object has no attribute 'reconnect'

I already had `tor` running locally, but I stopped it and re-ran it with `ControlPort auto` set in my `.torrc`. This made no difference. The Tor icon in Specter remains grayed out, and clicking 'Start Tor' returns the same error. Restarting Specter makes no difference. Likewise, if I stop my local manually-started `tor` process and try to let Specter start it for me (by clicking `Start Tor`), I get the same error as above.

What am I missing? I'm running 0.8.1. See also #363.

**Comment by stepansnigirev** [comment]
Sorry for a late reply...
Can you check with this instruction, maybe something missing in your setup?
https://github.com/cryptoadvance/specter-desktop/blob/master/docs/tor.md#configure-tor-port

**Comment by ben-kaufman** [comment]
Hi, is this still an issue with version v0.10.2?

**Comment by ben-kaufman** [comment]
Closing for now due to inactivity. Please reopen if this is still active.
Anyway, from the next version, you'll be able to set Specter to just use the Tor Browser for Tor communications which would hopefully make stuff simpler.
