### ISSUE TITLE
Label import from electrum

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#528]
Is there any way to import labels from electrum?  This would make a migration a lot easier.

**Comment by stepansnigirev** [comment]
I think this is possible when we get to importing electrum wallet files.
Not sure when we will do it, but importing wallets from other software including electrum is definitely on the roadmap.

**Comment by relativisticelectron** [comment]
I started experimenting with how to import it: https://github.com/relativisticelectron/specter-desktop/commit/997ed683921505df469b91269c57e15b2b022e14

**Comment by relativisticelectron** [comment]
Done in https://github.com/cryptoadvance/specter-desktop/pull/1314
