### ISSUE TITLE
add rescan buttons from tx history screen if history is empty

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-desktop#539]
If the user forgot to rescan during wallet creation he may be confused that his transactions are not there.
If the transaction history is empty we don't need to show the table, and we can suggest to rescan the wallet if the user forgot to do it during creation.
Maybe also a note, something like:
"Missing transactions here? Rescan the blockchain to find your coins."

**Comment by figgyfigs** [comment]
I'll attempt to work on this issue

**Comment by k9ert** [comment]
I think that there are two main reasons for the list to be empty:
* A fresh wallet might not have any TXs
* an existing wallet is missing a proper rescan

So a reload-button might make a lot of sense for the first case (even when the tx-list is not-empty) and a link to the rescan functionality might be good in the second case.

**Comment by VCBhatawadekar** [comment]
I'll attempt to work on this issue

**Comment by moneymanolis** [comment]
Great!
