### ISSUE TITLE
Display fiat equivalents next to BTC amounts

### ISSUE THREAD

**Issue by s-5Q2X8mgeGR** [cryptoadvance/specter-desktop#546]
Any time a BTC amount is displayed (Total balance, confirmed+pending; amount in History tab; amount in UTXO tab; amount in Send New + Unsigned tab; etc, etc), it would be neat to have the fiat value right after, eg: 

"0.1 ($130)"

The exchange rate could be a setting on the Settings general tab, much like block explorer is. 

Top right corner of the screen where Tor icon + Settings icon is, perhaps could display full exchange rate there as well, eg ($13000). 

Additionally, it'd be neat to allow the user to manually set a exchange rate value. eg., if click the Fiat-value (or placeholder "Set fiat value") button just (eg) left hand side of Tor icon, the user can manually enter a value. This'd remove the reliance on third party source as an optionality to the user. For setting value manually, could have a currency ticker dropdown too, so user's could both manually enter (exchangeRate) + (currencyTicker) to display in their currency of choice. 

Below some quick examples of how it might look in some of the places (excuse the incorrect proportions on the Set value/exchange rate left hand side of Tor icon; done via browser devtools)

![SpecterD, 1](https://user-images.githubusercontent.com/71570725/97083175-b65f8a80-160e-11eb-9cbd-98448322a9ec.png)
![SpecterD ](https://user-images.githubusercontent.com/71570725/97083174-b5c6f400-160e-11eb-87e4-b0558794dd61.png)
![SpecterD, 3](https://user-images.githubusercontent.com/71570725/97083176-b6f82100-160e-11eb-9c19-f3bc84a3950c.png)
![SpecterD,4](https://user-images.githubusercontent.com/71570725/97083177-b6f82100-160e-11eb-95eb-fbe8b7c4419e.png)

**Comment by nolim1t** [comment]
Maybe an optional thing so bitcoin amount information does not get leaked unintentionally to external services

**Comment by s-5Q2X8mgeGR** [comment]
Yes, optional indeed, set source in settings, and additionally give ability to manually set the value as I write, thus a no third party involved at all option.

**Comment by ben-kaufman** [comment]
Added in #622 

Thanks for the suggestion and the images, I added it in the bar there as you suggested.
