### ISSUE TITLE
Error When Adding Ledger Keys on 0.8.2-pre1

### ISSUE THREAD

**Issue by crawfordleeds** [cryptoadvance/specter-desktop#547]
OS: macOS 10.15.7
Device: Ledger Nano S
Specter: v0.8.2-pre1

I'm receiving an attribute error when attempting to add new keys on `v0.8.2-pre1`. For context, I added my Ledger and my segwit and legacy keys yesterday using account #0 on the derivation path. Today I wanted to add keys with account 1, 2 etc. and importing keys from a USB scan when I ran into this error:

```python
AttributeError: 'Ledger' object has no attribute 'hot_wallet'
```

Screenshot:

![Screen Shot 2020-10-24 at 10 53 13 AM](https://user-images.githubusercontent.com/25166339/97087526-14c54280-15e8-11eb-932c-3af670816c94.png)

I did also test with Account 0 again just to rule out an issue related to the derivation path and received the same error.

In looking at line 1703 of `controller.py` on the commit hash for `0.8.2-pre1` it's not obvious to me the source of the issue.

https://github.com/cryptoadvance/specter-desktop/blob/b6bb2e4967d9a45366cc91debc49704a8f0c2d3b/src/cryptoadvance/specter/controller.py#L1703

Does the `Ledger` device class need a `hot_wallet` attribute, presumably set to `False`?

**Comment by stepansnigirev** [comment]
Should be fixed here:
https://github.com/cryptoadvance/specter-desktop/pull/544
This change:
https://github.com/cryptoadvance/specter-desktop/pull/544/files#diff-a67a0051c2b3a6fa1915e01816594f821413632767c56e829439a08140003618R21

**Comment by crawfordleeds** [comment]
Cool, thanks!
