### ISSUE TITLE
Crash on Ubuntu when exporting wallet

### ISSUE THREAD

**Issue by b1tc01n3r** [cryptoadvance/specter-desktop#549]
Just created a multi sig wallet following the video by BTCSessions on YT. The last step is to export the wallet file, so that I can re-create the wallet without needing all the devices. When I click the download button Specter just crashes. I've tried a few more times, but a crash every time.

I'm running Ubuntu Mate 20.04.1 (Focal Fossa) on a minimal installation. Added the Udev rules. Besides this crash everything was working just fine.

Looked through the open issues and didn't see this one, apologies if it is already there.

Edit: I've managed to export / import the wallet through the browser. In the meantime also noticed the 'Open in browser' option on the tray icon doesn't work either. Tried importing the exported wallet in the app as well, but whenever I choose the option the app crashes again.

**Comment by ben-kaufman** [comment]
Hi, I believe this should be resolved with #473 

Meanwhile, you can try out the pre-release of it and see if that works for you: https://github.com/cryptoadvance/specter-desktop/releases/tag/v0.8.2-pre1

**Comment by b1tc01n3r** [comment]
The issue is indeed solved when I use the 0.8.2-pre1 version. 

Not getting a tray icon on the 0.8.2-pre1 version though. So when I close it, it doesn't close to tray but instead just closes the entire application. New version starts a bit faster for me as well. Using an old celeron dual core laptop, so perhaps not noticable for people with more modern hardware.

**Comment by ben-kaufman** [comment]
Closed with v0.9.2 (also has a tray icon which 0.8.2-pre1 didn't have).
