### ISSUE TITLE
Unable to connect to umbrel

### ISSUE THREAD

**Issue by dermichal** [cryptoadvance/specter-desktop#565]
When follwing the instructions from your tweet:
[https://twitter.com/getumbrel/status/1313472541776846853](https://twitter.com/getumbrel/status/1313472541776846853)

The follwing error message shows up:
![Screenshot 2020-10-30 at 15 59 29](https://user-images.githubusercontent.com/688962/97720758-ef917200-1ac8-11eb-9fdd-9e1db1a04dec.png)

Specter: 0.8.1
Umbrel: 0.2.13
MacOS: 10.15.7

**Comment by k9ert** [comment]
Did you worked through that document?
https://github.com/cryptoadvance/specter-desktop/blob/master/docs/tor.md

So tor is working on your mac?

**Comment by dermichal** [comment]
Thanks Ben. 

A detail I forgot: 
- Umbrel is running on an raspberry pi 4b.
- FullyNoded on iOS is able to connect to it and to query the bitcoin cli.
- I installed Specter using SpecterDesktop-v0.8.1.dmg

Is there a more noob-friendly way to get it to run as I planned to do it for several members of my family/friends?

**Comment by dermichal** [comment]
Installed tor over terminal. Seems to work now. Thanks

**Comment by phenomeus** [comment]
there should be a hint on the screen, that "if you want to connect to an .onion address you should have tor installed and running." 

I missed that somehow in my thinking. but of course its just logic to do so.
