### ISSUE TITLE
MacOS Crash on Adding Specter-DIY Wallet

### ISSUE THREAD

**Issue by noobtester21** [cryptoadvance/specter-desktop#566]
macOS 10.15.5
1.6 GHz Dual-Core Intel Core i5
8 GB RAM
Specter 0.8.1
Bitcoin Core 0.20.1 on MyNode RasPi 4

Crash occurs when:
- Add new wallet
- Choose Specter-DIY
- Choose Scan QR Code
- Program Disappears

Also having significant delays when navigating in the app.

Please let me know if there is additional information I can provide.

Thanks for all of your work, love this concept.

**Comment by stepansnigirev** [comment]
Can you check if it happens with pre-release as well?
https://github.com/cryptoadvance/specter-desktop/releases/tag/v0.8.2-pre1

**Comment by noobtester21** [comment]
Issue resolved in the pre-released. Based on timing of previous crash might have been related to getting access to the system's camera. Thanks much.
