### ISSUE TITLE
New device type - this computer

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-desktop#58]
I am thinking about including a hot storage functionality into the app by implementing a new device type - call it a "Hot storage" or "This computer".
### Motivation:
I really like using Specter-desktop for my cold storage, but for small transactions I don't want to use my hardware wallet — my laptop is always with me, but I don't take my hardware wallets with me all the time.
At the moment I have to use another app for these small transactions without a hardware wallet - I would prefer to use Specter-desktop for this as well.
### Future bonuses
If we have hot storage functionality we could later add CoinJoin and Lightning to the app.
Implementing hot storage as a device type also allows us to add the computer to the multisig setup. Or maybe even run Specter on an airgapped computer or raspberry pi purely for signing.

I think this signing functionality can be implemented as a new miniapp that can be included in Specter as an addon. But I don't know yet what would be the best architecture for a plugin system.
In principle future extensions like CoinJoin and Lightning can be also implemented as plugins.

@k9ert , @kdmukai , what do you think? Makes sense or totally insane?

**Comment by k9ert** [comment]
I like the idea! A hotwallet functionality is a good thing to have for several reasons: Mixing, better testability, UI/UX same for smaller and bigger amounts.

But i'm not sure we need a plugin architecture (yet!) for that. Sure, we should do stuff modularily but what would be the idea of the plugin-system? Which would be the benefits doing that as plugins? How do we envision the software-lifecycle for plugins? Different repos?! 
I think we should have clear answers to these questions before we think about a plugin-system.

**Comment by kdmukai** [comment]
Concept ACK for the hot wallet. Though it would have to come along with something like #29. And should that password be overall, per-wallet...?

A "plugin" concept is probably mostly already supported via typical python project/app structure and Flask blueprints. Could probably make it pip installable (`pip install specter-coinjoin`) with minimal other configuration.

**Comment by FrancisPouliot** [comment]
really want this feature!

**Comment by ben-kaufman** [comment]
Yeah that will be a nice feature, I will start working to implement that.
