### ISSUE TITLE
Coin Control & Send Max

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#585]
When I select two small utxos of about 25k sats each and then select "send max", with a very small fee, I get the following error message:

"ERROR: Selected coins does not cover Full amount! Please select more coins!"

Anyone else had this issue?

**Comment by ben-kaufman** [comment]
Is this still happening with the latest version?

**Comment by ben-kaufman** [comment]
Closing for now due to inactivity. Please reopen if this is still active.
