### ISSUE TITLE
incorrect address is displayed in tx inputs details

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-desktop#591]
From Telegram group:

> I created a 4xINPUT/3xOUTPUT unsigned tx and the 4th input seems to be an Output#0(different owner) instead of Output#1(mine) value from a previous tx. I created the same tx in another wallet to compare and the correct Output#1 shows. Perhaps I'm missing something.

I think we may display wrong address in the tx details, we need to check.

**Comment by ben-kaufman** [comment]
I couldn't replicate this issue so far. Any update on that or maybe we should close this for now?

**Comment by ben-kaufman** [comment]
Closing for now due to inactivity. Please reopen if this is still active.
