### ISSUE TITLE
Consolidated UTXO -> TX not shown in Transaction/History

### ISSUE THREAD

**Issue by janrothen** [cryptoadvance/specter-desktop#597]
Specter Version: v0.9.2

I've manually consolidated a couple of transactions and sent the consolidated amount to the same wallet but to a new receiving address. The transaction confirmed and my balance is the same minus the transaction fee.
In the UTXO view the consolidated UTXO is also visible.

Bug: In the transaction history the received transaction is not visible.

**Comment by stepansnigirev** [comment]
Thanks for reporting. We are refactoring the transaction history and hopefully will fix this issue in the next release.
