### ISSUE TITLE
Incorrect blocks count

### ISSUE THREAD

**Issue by BTCBellyButton** [cryptoadvance/specter-desktop#600]
![image](https://user-images.githubusercontent.com/68573637/99014464-4e6ad880-2518-11eb-8d06-b1499fc7040b.png)

The current block count does not update. You've to stop and restart the daemon to get it up to date.
Specter desktop 0.9.2 on Windows. Daemon on Ubuntu 20.04.1.

**Comment by stepansnigirev** [comment]
Thanks! Currently we check for blocks every 10 minutes that's probably not enough if the node is still syncing. We will do it more often in this case.

**Comment by BTCBellyButton** [comment]
You're welcome!
In my case the node was already synced. It's been on for quite some months
now.

**Comment by stepansnigirev** [comment]
And what if you just navigate to another page in Specter? We don't update the block count dynamically, only on a page load.

**Comment by BTCBellyButton** [comment]
I tried to reload the page. No changes. If I stop and restart the server
daemon it updates but then it doesn't update any more.

**Comment by stepansnigirev** [comment]
I see. What about other functionality of Specter, does it detect incoming transactions? Does it generate a fresh address when the current one is used?

**Comment by BTCBellyButton** [comment]
I didn't have time to test much but I imported e 3 of 4 musig electrum
wallet with no problems, transactions and utxo look fine. As soon as I am
back home I'll do a few more checks.
I was planning to play around on the weekend.
I'll let you know if something else comes up.

**Comment by BTCBellyButton** [comment]
Hi,
I did few more tests.
It seems that the blocks count works only if you don't start Specter as a daemon with the --daemon option.
I simplify my setup in order to run everything on the same Ubuntu machine, uninstalled, removed ~/.specter/ and installed it again.

If I run it with:
`python3 -m cryptoadvance.specter server`
The blocks are updated but they are 1 block behind what the node says.

If I run it with:
`python3 -m cryptoadvance.specter server --daemon`
then the blocks never update.

I also noticed that without the --daemon it connects to the hw wallets with no problems while in daemon mode it does not connect to the them.

**Comment by stepansnigirev** [comment]
Looks like the daemon mode is buggy...
I would recommend setting up Specter as a systemctl service or init.d script for now.
I will look into the daemon but not sure if I will be able to easily fix that - it may require some time.

**Comment by BTCBellyButton** [comment]
Is there a specter.service file to be used as a starting point? I couldn't find it.

**Comment by stepansnigirev** [comment]
Just tried, for me the following flow worked (edit in systemd folder requires `sudo`):
1. Create a file `/lib/systemd/system/specter.service` with the following content (replace `User=stepan` to your username):
```
[Unit]
Description=Specter Desktop Service
After=multi-user.target
Conflicts=getty@tty1.service

[Service]
User=stepan
Type=simple
ExecStart=/usr/bin/python3 -m cryptoadvance.specter server
StandardInput=tty-force

[Install]
WantedBy=multi-user.target
```
2. Reload systemd with `sudo systemctl daemon-reload`
3. Enable service with `sudo systemctl enable specter.service`
4. Start service with `sudo systemctl start specter.service`

To stop run `sudo systemctl stop specter.service`, to restart `sudo systemctl restart specter.service`

**Comment by stepansnigirev** [comment]
I opened a PR with docs on that
https://github.com/cryptoadvance/specter-desktop/pull/621

**Comment by BTCBellyButton** [comment]
Cool. Thanks! I'll put it at work ASAP.

**Comment by BTCBellyButton** [comment]
Just tested. It works for me as well.
Is it worth it to fix the daemon mode? I guess this way (as a systemctl service) is more consistent with all the other bitcoin sw configurations.
Looking forward to the upcoming release!
Great job!

**Comment by stepansnigirev** [comment]
I think we could remove the daemon mode and just direct people to the document with instructions.
I don't know how to do similar thing on Mac though...

**Comment by BTCBellyButton** [comment]
I've no idea about Mac...but probably most of the people running their own
node use some Linux flavor.

**Comment by BTCBellyButton** [comment]
Does this help?

https://support.apple.com/guide/mac-help/use-services-in-apps-mchlp1012/mac#:~:text=On%20your%20Mac%2C%20select%20an,Services%2C%20then%20choose%20a%20service
.

**Comment by nolim1t** [comment]
> Just tried, for me the following flow worked (edit in systemd folder requires `sudo`):
> 
>     1. Create a file `/lib/systemd/system/specter.service` with the following content (replace `User=stepan` to your username):
> 
> 
> ```
> [Unit]
> Description=Specter Desktop Service
> After=multi-user.target
> Conflicts=getty@tty1.service
> 
> [Service]
> User=stepan
> Type=simple
> ExecStart=/usr/bin/python3 -m cryptoadvance.specter server
> StandardInput=tty-force
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
>     1. Reload systemd with `sudo systemctl daemon-reload`
> 
>     2. Enable service to run on boot with `sudo systemctl enable specter.service` (optional)
> 
>     3. Start service with `sudo systemctl start specter.service`
> 
> 
> To stop run `sudo systemctl stop specter.service`, to restart `sudo systemctl restart specter.service`
> 
> btw you can do the same for bitcoind if you want to, so both Specter and bitcoind will start on system boot.

you can also use docker and docker-compose and use `restart: on-failure` and it will restart this on reboot as long as docker service is running. I have a [project](https://github.com/lncm/docker-specter-desktop) which packages it up and has example files.  Also the team has also created their [own fork](https://github.com/cryptoadvance/docker-specter-desktop) of it too..

**Comment by stepansnigirev** [comment]
I opened an issue on the docs for daemon https://github.com/cryptoadvance/specter-desktop/issues/630
I will close this issue, we can continue there.
