### ISSUE TITLE
ledger nano s import to specter desktop - wrong derivation path probably

### ISSUE THREAD

**Issue by ashjkl159** [cryptoadvance/specter-desktop#602]
I wanted to migrate from Ledger live app to Specter desktop with full node. I found xpubs and derivation path of my ledger wallet, no fingerprint. When trying to set up new device in specter desktop, was only able to put xpub (with derivation path and no fingerprint got errors). Despite that when creating specter wallet with this ledger I could see all my coins in there. I created a new deposit address in this new specter wallet and send there some bitcoins. When i tried to send some bitcoins out of that specter wallet with ledger nano s, I got errors. I could see incoming funds in specter wallet but I do not see those incoming funds in my ledger live where I can easily send bitcoins out of my wallet. Looks like wrong derivation path? Are my bitcoins in this newly created address lost please?

**Comment by ben-kaufman** [comment]
Hi, when you don't add the fingerprint Specter will not be able to send the funds and the wallet will be watch only.
I'm not sure about how to view it in Ledger Live, but I presume you might need to make sure you are using the same address type (Nested Segwit or Native Segwit) on both Ledger Live and Specter.

If you want to spend from Specter, you should go to the device page, click add more keys and then add keys by connecting with the Ledger device via USB. You might also need to recreate the wallet with the new key on Specter after doing that (by going through the same steps you did to create the wallet initially), but it might work with the existing wallet immediately.

**Comment by ashjkl159** [comment]
thanks, yes, so originally i created watch only wallet by mistake. in this wallet i created deposit address and send there some bitcoins and seems that bitcoins are gone now as I see them in this watch only wallet but i cannot spend it (sign it with leder). Am I rite?
Otherwise i successfully added all other keys via USB and recreated wallet, so from now on, I should be ok. thanks for help anyway

**Comment by stepansnigirev** [comment]
We may be able to help you to recover the funds.
If you share the watch wallet export file with us we may be able to figure out correct derivation path (probably better in DM on telegram or by mail, as disclosing xpubs publicly is bad for privacy)

**Comment by ashjkl159** [comment]
That would be much appreciated. Could you give me email maybe with PGP key please?

**Comment by stepansnigirev** [comment]
snigirev.stepan@gmail.com
gpg key is available here: https://stepansnigirev.com/stepan-gpg.asc
same key on the keyserver: http://keys.gnupg.net/pks/lookup?op=get&search=0x8C3D2C48560E81AC
