### ISSUE TITLE
Failed to connect link

### ISSUE THREAD

**Issue by statusquont** [cryptoadvance/specter-desktop#604]
Specter Desktop v0.9.2 installed on a Windows machine.
myNodeBTC v0.2.18 running with TOR services enabled in a VM VirtualBox.

I have encountered several issues that may be worth raising, so I'll create multiple GitHub issues for each one so that can be tracked separately. Hopefully that's the preferred method and isn't considered spamming. Apologies in advance is it's poor form.

First issue is when trying to setup the desktop to connect to Core on myNode, in the Bitcoin Core Setting screen, after testing a connection is a link "Check e.g. [this article](http://localhost:25441)" which tries to open http://localhost:25441 which fails to load. 

![SPECTE~2](https://user-images.githubusercontent.com/15948511/99147217-49c93000-2690-11eb-87db-e4da20cd713f.jpg)

In addition, the "404" screen doesn't give you any way to get back to Specter. The user is now stuck in the embedded Electron browser displaying the error and can't get back to the main Specter UI without shutting down the application and restarting it. It seems like whatever URL that link should be pointing at would ideally open in the users default browser, not within Electron, so they don't get locked in.

![Specter_mnFUKTUaVe](https://user-images.githubusercontent.com/15948511/99147219-4f267a80-2690-11eb-819e-78aa5bd920b2.png)

I had a similar experience earlier (but can't figure out how to reproduce it) where some link opened to I believe a Stack Exchange URL? Again, this opened in the embedded Electron browser and there wasn't any way to get back to the Specter app without restarting it.

**Comment by ben-kaufman** [comment]
Hi, do you have Tor installed and running, you need that to access websites over tor with Specter. You can check this out on setting it up:
https://www.keepitsimplebitcoin.com/how-to-install-tor/
https://github.com/Fonta1n3/FullyNoded/blob/master/Docs/Tor/Tor.md#windows-10

**Comment by k9ert** [comment]
I'm not sure why "this article" points to localhost. In my test it loads directly the article in electron which is not cool because you don't know how to get back to specter. So this should definitely be opened in a browser.

**Comment by k9ert** [comment]
Should be fixed!
