### ISSUE TITLE
Test results: Connectable

### ISSUE THREAD

**Issue by statusquont** [cryptoadvance/specter-desktop#605]
I think the language around the connection test results could be made much clearer.

```
Test results: 

Connectable  X
```

Looking at that could be interpreted in several ways. 

1. There were no results since after the : is blank.
2. Test result came back as "connectable"

You really have to decipher that, oh, that X graphic means it's not connectable. 

Something more explicit like:

"Test results: Connection failed."
"Test results: Connection succeeded" 

And if it failed, display the error message(s), like "Process finished with code -1Error message: Failed to connect!:

![SPECTE~2](https://user-images.githubusercontent.com/15948511/99147293-e5f33700-2690-11eb-8eff-fdb1d898d5cb.jpg)

**Comment by k9ert** [comment]
I'm not sure i understand your points. I guess you had some struggle discovering the Tests-results but the error-message is shown as well.
Maybe you can make a proposal on how it should be displayed.
