### ISSUE TITLE
Can't connect, tried 3 different plausible connection settings

### ISSUE THREAD

**Issue by statusquont** [cryptoadvance/specter-desktop#606]
I am struggling to figure out the right connection settings spell to cast to make the magic happen.

Specter Desktop v0.9.2 installed on a Windows machine.
myNodeBTC v0.2.18 running with TOR services enabled in a VM VirtualBox.

Trying to connect via TOR.onion addresses with 3 plausible connection variations, none of which seem to work and all give the same error message: "Process finished with code -1Error message: Failed to connect!"

I'm not sure if it would be possible, but if you could make that error more explicit that might help, a few possible examples:

1. Failed to reach host
2. Username and/or password incorrect
3. Onion service not responding (if that's even a thing??)

If you could make the error more verbose like that it would clue the user into where to start looking to diagnose the issue and resolve it. 

Here's the 3 possible parameters I pulled off myNode that at least made a little bit of sense to me.

1. Using all settings from the /bitcoind page of myNode
![btc-rpc-connect](https://user-images.githubusercontent.com/15948511/99147934-c6aad880-2695-11eb-94b2-b0bd17b1f8f8.png)

2. Using the RPC username/password from /bitcoind page, and using the Bitcoin API (REST) onion address and port
![btc-rpc-connect2](https://user-images.githubusercontent.com/15948511/99147935-c7436f00-2695-11eb-9435-17b5603b604a.png)

3. Using the RPC username/password from /bitcoind page, and using the Specter Desktop onion address and port
![btc-rpc-connect3](https://user-images.githubusercontent.com/15948511/99147933-c579ab80-2695-11eb-8cf4-0c9a665cae40.png)

My instinct tells me that Option #2 should be correct, but that still fails to work. 

It's not clear if I need to turn on Tor within the Desktop (Windows) app?
Does Specter app need to be installed on myNode? I would think I should just be able to connect the remote app to Bitcoin Core running on myNode.
If Specter app is installed on myNode, does that need to have it's Tor enabled? It's currently showing as "Tor service is down..."

![firefox_GFTX75PjRQ](https://user-images.githubusercontent.com/15948511/99148221-995f2a00-2697-11eb-8ee5-057ea4851617.png)

Kind of at a loss with all the permutations, and none working.

**Comment by BTCBellyButton** [comment]
Did you open the port 25441 on your node firewall?
`sudo ufw status`
to check if it is open.

**Comment by k9ert** [comment]
I'm closing this issue for now. Please also have a look at:
https://github.com/cryptoadvance/specter-desktop/blob/master/docs/connect-your-node.md
