### ISSUE TITLE
Right mouse click menu not enabled on Linux/Ubuntu

### ISSUE THREAD

**Issue by kolmansoifer** [cryptoadvance/specter-desktop#618]
When copying and pasting on Ubuntu, Ctrl buttons work but the right click menu isn't accessible.

**Comment by kolmansoifer** [comment]
Just checked and OSX has the same issue.

**Comment by stepansnigirev** [comment]
Related to https://github.com/cryptoadvance/specter-desktop/issues/578
@ben-kaufman

**Comment by ben-kaufman** [comment]
I think that's a duplicate of #578 so we can close it here and continue the discussion there.
