### ISSUE TITLE
Required password or pin to launch

### ISSUE THREAD

**Issue by kolmansoifer** [cryptoadvance/specter-desktop#619]
Any thoughts on requiring a password or pin to launch Specter?

**Comment by stepansnigirev** [comment]
Raspiblitz? "Password or PIN" is a bitcoin-rpc password. If Core is not running or Specter is not configured properly there might be no way to login using this method.

To change access mode to no authentication you need to edit `~/.specter/config.json` file and change `"auth": "rpcpasswordaspin"` to `"auth": "none"`.

If you want authentication to access Specter I recommend using "Multiple users" - basically it's a login-password authentication, you don't really need to have multiple users. (default login & password are admin admin)

**Comment by stepansnigirev** [comment]
Maybe I misunderstood the questsion. Authentication is already supported in the settings - authentication.
"Multiple users" is what I would recommend, and you don't need to have multiple users, can use it for simple authentication.
But you could share your specter instance with your friends if you want to.

**Comment by kolmansoifer** [comment]
Ah ha!  Thanks for showing me this.
Best to you all.
KS
