### ISSUE TITLE
Aquired 2 of 3 signatures but unable to broadcast transaction. Cobo, Coldcard, Seedpicker (Buidl)

### ISSUE THREAD

**Issue by flyingfaders** [cryptoadvance/specter-desktop#620]
From the chat in Telegram with @mflaxman & @stepansnigirev 
Specter Version: 0.9.2

Workflow is as follows: 

Create Multisig 2-3

1. Cobo Valut
2. Cold Card
3. Seedpicker via https://github.com/buidl-bitcoin/buidl-python

**Workflow:** 

- Create unsigned transaction in Specter
- Download RAW PSBT as base64
- Copy PSBT to air gapped machine running buidl
- Run Buidl’s “send” command and follow prompts
- Copy Signed PSBT to broadcast to USB stick and upload to Specter
- Specter adds a “tick” symbol next to “Seedpicker” in the “Sign transaction with your:”  section
- Sign transaction with Cobo (now ticked)
- No option to broadcast with 2 signatures acquired 

I've tried deleting a recreating the wallet in Specter. And tried various orders of signing but always get the same result. Was able to sign / broadcast transactions with Cobo & Coldcard: [TX details](https://mempool.space/testnet/tx/8e0312a2b8b8ad2a7f56daf698002587c12a5f70dd26b77eee3214a0c0dbfadb) so I'm not sure where I'm going wrong...

Output of buidl: 

(₿) send
Paste partially signed bitcoin transaction (PSBT) in base64 form: cHNidP8BAH0CAAAAATNqZh5AEw2EegORn8k389HylQF5CJspjgCM0jB4CW6jAAAAAAD+////Aj5SAAAAAAAAFgAU39dKqHlCLz40TqZOjG0KutvIFegDKgAAAAAAACIAIIK6/oC0L2eFV6S1/rb4iITlfS80w9VBLiD93ReZZL15AAAAAAABAH0CAAAAAdv628CgFDLufrcm3XBfKsGHJQCY9tpWfyqtuLiiEgOOAQAAAAD+////AgB9AAAAAAAAIgAgnL8VhoJqZxzLUSEks/da4RScIaCV509kWnDTL5jFxUN7QwAAAAAAABYAFBZtqZB+GD/LhKC5ICzoth15UHd/AAAAAAEBKwB9AAAAAAAAIgAgnL8VhoJqZxzLUSEks/da4RScIaCV509kWnDTL5jFxUMBBWlSIQKeMSvD5EHXPyag4GCRAdbJtz0Z8CeMoDYgF1NoF/dTXiEC3JGQ7QRs6JeIVPkNtExENfYuc/IKPsm0XagAVd7YNokhA+u7xNhU8U5iYG9At2QnGR1lKsN2QMSon1dFtotCz+HBU64iBgKeMSvD5EHXPyag4GCRAdbJtz0Z8CeMoDYgF1NoF/dTXhyqWasBMAAAgAEAAIAAAACAAgAAgAEAAAACAAAAIgYC3JGQ7QRs6JeIVPkNtExENfYuc/IKPsm0XagAVd7YNokcKYlWJjAAAIABAACAAAAAgAIAAIABAAAAAgAAACIGA+u7xNhU8U5iYG9At2QnGR1lKsN2QMSon1dFtotCz+HBHK+dukUwAACAAQAAgAAAAIACAACAAQAAAAIAAAAAAAEBaVIhAiMY0fXIbWxLV2tq9WtSjk+8mBSoqpxBBsawUK5cgFNEIQNJ3VECqHL2lJg0BAR507dLg6iqoL5gFvOs8Eo0MynW4SEDf486TB01L1ETX9G7shr5mhiPcV8TICiv/Uj7FyTaqIVTriICAiMY0fXIbWxLV2tq9WtSjk+8mBSoqpxBBsawUK5cgFNEHKpZqwEwAACAAQAAgAAAAIACAACAAQAAAAAAAAAiAgNJ3VECqHL2lJg0BAR507dLg6iqoL5gFvOs8Eo0MynW4RyvnbpFMAAAgAEAAIAAAACAAgAAgAEAAAAAAAAAIgIDf486TB01L1ETX9G7shr5mhiPcV8TICiv/Uj7FyTaqIUcKYlWJjAAAIABAACAAAAAgAIAAIABAAAAAAAAAAA=

Use Mainnet? [y/N]: N

Units to diplay [BTC/sats]: BTC

PSBT sends 0.00021054 BTC to tb1qmlt542regghnudzw5e8gcmg2htdus90gp2n586 with a fee of 0.00000191 BTC (0.6% of spend)

In Depth Transaction View? [y/N]: y

DETAILED VIEW
TXID: c9faeef53121c5c10bf90e32b72e92cc19f76328e206bab94099573df5ac6630

1 Input(s):
  input #0
    quorum: 2-of-3
    root_xfp_hexes: ['aa59ab01', '29895626', 'af9dba45']
    prev_txhash: a36e097830d28c008e299b08790195f2d1f337c99f91037a840d13401e666a33
    prev_idx: 0
    n_sequence: 4294967294
    sats: 32000
    addr: tb1qnjl3tp5zdfn3ej63yyjt8a66uy2fcgdqjhn57ez6wrfjlxx9c4psj76sps
    witness_script: OP_2 029e312bc3e441d73f26a0e0609101d6c9b73d19f0278ca0362017536817f7535e 02dc9190ed046ce8978854f90db44c4435f62e73f20a3ec9b45da80055ded83689 03ebbbc4d854f14e62606f40b76427191d652ac37640c4a89f5745b68b42cfe1c1 OP_3 OP_CHECKMULTISIG 
    msig_digest: b0b4bd8c0d716c63af2bee994c7c84759a46f8b2618806c01db6d5d1cf733bc4

2 Output(s):
  output #0
    sats: 21054
    addr_type: P2WPKH
    addr: tb1qmlt542regghnudzw5e8gcmg2htdus90gp2n586
    is_change: False
  output #1
    sats: 10755
    addr_type: 
    addr: tb1qs2a0aq959anc24aykhltd7ygsnjh6te5c025zt3qlhw30xtyh4ushp47cp
    is_change: True

Sign this transaction? [Y/n]: Y

24 word BIP39 seed phrase: REMOVED

Signed PSBT to broadcast:

cHNidP8BAH0CAAAAATNqZh5AEw2EegORn8k389HylQF5CJspjgCM0jB4CW6jAAAAAAD+////Aj5SAAAAAAAAFgAU39dKqHlCLz40TqZOjG0KutvIFegDKgAAAAAAACIAIIK6/oC0L2eFV6S1/rb4iITlfS80w9VBLiD93ReZZL15AAAAAAABAH0CAAAAAdv628CgFDLufrcm3XBfKsGHJQCY9tpWfyqtuLiiEgOOAQAAAAD+////AgB9AAAAAAAAIgAgnL8VhoJqZxzLUSEks/da4RScIaCV509kWnDTL5jFxUN7QwAAAAAAABYAFBZtqZB+GD/LhKC5ICzoth15UHd/AAAAACICAtyRkO0EbOiXiFT5DbRMRDX2LnPyCj7JtF2oAFXe2DaJSDBFAiEA5buXFqE8fhMDqkxWHIURm1eHgd3lylJHl+9RD60no2oCIEjWLMzaE9XnCufclPKQN9NfAof64/tr6BZgWTTukGZEAQEFaVIhAp4xK8PkQdc/JqDgYJEB1sm3PRnwJ4ygNiAXU2gX91NeIQLckZDtBGzol4hU+Q20TEQ19i5z8go+ybRdqABV3tg2iSED67vE2FTxTmJgb0C3ZCcZHWUqw3ZAxKifV0W2i0LP4cFTriIGAp4xK8PkQdc/JqDgYJEB1sm3PRnwJ4ygNiAXU2gX91NeHKpZqwEwAACAAQAAgAAAAIACAACAAQAAAAIAAAAiBgLckZDtBGzol4hU+Q20TEQ19i5z8go+ybRdqABV3tg2iRwpiVYmMAAAgAEAAIAAAACAAgAAgAEAAAACAAAAIgYD67vE2FTxTmJgb0C3ZCcZHWUqw3ZAxKifV0W2i0LP4cEcr526RTAAAIABAACAAAAAgAIAAIABAAAAAgAAAAAAAQFpUiECIxjR9chtbEtXa2r1a1KOT7yYFKiqnEEGxrBQrlyAU0QhA0ndUQKocvaUmDQEBHnTt0uDqKqgvmAW86zwSjQzKdbhIQN/jzpMHTUvURNf0buyGvmaGI9xXxMgKK/9SPsXJNqohVOuIgICIxjR9chtbEtXa2r1a1KOT7yYFKiqnEEGxrBQrlyAU0QcqlmrATAAAIABAACAAAAAgAIAAIABAAAAAAAAACICA0ndUQKocvaUmDQEBHnTt0uDqKqgvmAW86zwSjQzKdbhHK+dukUwAACAAQAAgAAAAIACAACAAQAAAAAAAAAiAgN/jzpMHTUvURNf0buyGvmaGI9xXxMgKK/9SPsXJNqohRwpiVYmMAAAgAEAAIAAAACAAgAAgAEAAAAAAAAAAA==

Specter signing page
![Specter Send Screen](https://user-images.githubusercontent.com/67905545/99468637-138ff700-2995-11eb-973f-d8fedf67e581.png)

**Comment by mflaxman** [comment]
Thanks @flyingfaders!

What version is your bitcoin core? I can see that is a v0.2.1 "insane" PSBT, which Specter-Desktop and buidl (now) support (more [here](https://github.com/cryptoadvance/specter-desktop/issues/593)). I was wondering if perhaps your bitcoin-core node is older and does not?

Do you see any relevant info in the console log on that page? There may be a useful clue there.

**Comment by stepansnigirev** [comment]
I tried to verify the signature in this PSBT transaction and it doesn't seem to be valid.
@mflaxman please check how you are signing.

According to [these lines](https://github.com/buidl-bitcoin/buidl-python/blob/main/buidl/psbt.py#L350-L351) you sign as legacy if non witness utxo is present. Better to check script type instead - according to the specs non_witness_utxo may be present even for setwit inputs, and witness_utxo may be missing as well.

See for example our implementation in Specter-DIY: https://github.com/diybitcoinhardware/embit/blob/master/src/embit/psbt.py#L148-L159

**Comment by flyingfaders** [comment]
Thanks for the comments. I'm running 0.20.1. I've  tried spinning up a different instance of Specter on a backup Bitcoin Node I run and had the same issue after recreating the wallet there too. But I could successfully sign with the Seedpicker key by setting up a multisig wallet in Electrum on my airgapped machine: [here's the tx](https://mempool.space/testnet/tx/3b8168a3e833eb936f237bf99c58dfde85d02f806e7efcd4c6d62b474adf647b)

**Comment by mflaxman** [comment]
Thanks @stepansnigirev for digging around and the suggested fix, I appreciate it!

I pushed a fix to buidl that may solve this problem and passes existing tests, but unfortunately @flyingfaders I can't test your specific signing setup without your seed (and I assume you chose to REMOVE it for good reason). @flyingfaders, could you try pulling the changes from this branch and signing the transaction again?
https://github.com/buidl-bitcoin/buidl-python/tree/bugfix-invalidsig

I've filed a github issue on buidl for this [here](https://github.com/buidl-bitcoin/buidl-python/issues/23), it might make sense to close the issue on specter-desktop since it appears to not be a specter-desktop issue.

**Comment by mflaxman** [comment]
FYI: buidl is now fixed and deployed.

Thank you both for the help!
