### ISSUE TITLE
Any reason for new wallets to use SLIP132 version bytes going forward?

### ISSUE THREAD

**Issue by mflaxman** [cryptoadvance/specter-desktop#628]
I originally wrote my [seedpicker](https://seedpicker.net/calculator/last-word.html) implementations ([golang](https://github.com/mflaxman/human-rng-golang) as well as in python in [GUI](https://github.com/mflaxman/multiwallet), [CLI](https://github.com/buidl-bitcoin/buidl-python/), and [Electrum](https://github.com/mflaxman/human-rng-electrum) formats) to use SLIP132 because that was the Electrum standard, but now that Specter-Desktop has gotten so much better than Electrum, I wonder if SLIP132 support still makes sense?

The main benefit I can see is that SLIP132 encoding does inform Specter-Desktop of the script type (`p2wsh` vs `p2wpkh` for example), but it seems like SLIP132 adds a lot complexity for this very simple purpose.

Would Specter-Desktop want to make a standard for exporting public keys from hardware wallets? Then we could retire SLIP132 for new wallet creation.

I'm thinking something like this but very open to other ideas:
`[f7d04090/48h/1h/0h/1h]tpubDF7FTuPECTePtSLgeKZsbMif6c91sq1q7gis9sTVMu1Y8CTfpSew1SYsv5k7vwHUojmrmoLSnZzfvQ6h1VNg2j7J84WSD14u3yyfkzbGB5x-p2wsh`
or
`[xfphex/path]xpub-scripttype`

--
It does [lead to confusion](https://benma.github.io/2020/11/05/multisig-xpubs-verification.html), and also this part of the setup people will "set-it-and-forget-it" so whatever people use today they will likely still be using for many years/decades to come.

Sorry if this is the wrong place to post this.

**Comment by ChristopherA** [comment]
I’d like to have a better understanding of the requirements to support this for interoperability with multiple wallets.

We are working on something related to this in our UR & QR UR research at: https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-015-account.md

/cc @craigraw @wolfmcnally @gorazdko @fonta1n3

**Comment by mflaxman** [comment]
Thanks for chiming in @ChristopherA!

I don't want to invent a standard, I just want to use one that everyone else does.

My use-case is that I'm trying to generate a BIP39 seed with [multiwallet](https://github.com/mflaxman/multiwallet/) using the seedpicker algo and then export the public key to Specter-Desktop (as coordinator of my multisig). I've written versions of this a few times but this time I stopped myself and thought "why am I bothering with SLIP132 encoding here? It's not adding anything."
![Screen Shot 2020-11-18 at 4 36 39 PM](https://user-images.githubusercontent.com/448644/99596623-400b3980-29bc-11eb-9566-2fc74d36f7bb.png)

**Comment by craigraw** [comment]
Thanks for the cc @ChristopherA.

Regarding SLIP32, I think there is a general movement away from it and towards using output descriptors to define wallets - certainly that's the direction the Core wallet is moving in. 

@mflaxman rather than a suffix with the script type, the specification for [output descriptors](https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md) already supports defining the script type as follows:
```
wsh([f7d04090/48h/1h/0h/1h]tpubDF7FTuPECTePtSLgeKZsbMif6c91sq1q7gis9sTVMu1Y8CTfpSew1SYsv5k7vwHUojmrmoLSnZzfvQ6h1VNg2j7J84WSD14u3yyfkzbGB5x)
```

The [crypto-account](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-015-account.md) specification @ChristopherA linked to above uses this to allow hardware wallets to supply a set of output descriptors with different script types for a particular BIP44 account. This allows the script type to be defined in Specter (implicitly or explicitly) and the correct xpub to be extracted from the set when pairing the hardware wallet, making for a simpler user experience. It seems this could be useful for seedpicker as well.

**Comment by Fonta1n3** [comment]
Agree with @craigraw here, output descriptors make slip0132 obsolete.

**Comment by stepansnigirev** [comment]
In Specter we support both canonical xpubs and slip132 as well. So you can use the syntax `[fgp/derivation]xpub` for keys.
We determine the purpose of the key from the derivation path - if it's `m/49'/coin'/account'` it's considered nested segwit single-sig, native segwit for `84'`, `m/48'/coin'/account'/purpose'` for multisig where `purpose=1` for nested, `2` for native. All other derivation paths can be used for any purpose.

For single-sig you can also create the wallet import json and directly import it to Specter from "new wallet" menu.
Example:
```
{ "label": "hot1", "blockheight": 0, "descriptor": "wpkh([73c5da0a\/84h\/1h\/0h]tpubDC8msFGeGuwnKG9Upg7DM2b4DaRqg3CUZa5g8v2SRQ6K4NSkxUgd7HsL2XVWbVm39yBA4LAxysQAm397zwQSQoQgewGiYZqrA9DsP4zbQ1M\/0\/*)#evh9fu0w" }
``` 
As you see descriptor here is the receiving descriptor for Bitcoin Core. We derive change descriptor by replacing `/0/*` to `/1/*`

**Comment by mflaxman** [comment]
> @mflaxman rather than a suffix with the script type, the specification for [output descriptors](https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md) already supports defining the script type as follows:
> 
> ```
> wsh([f7d04090/48h/1h/0h/1h]tpubDF7FTuPECTePtSLgeKZsbMif6c91sq1q7gis9sTVMu1Y8CTfpSew1SYsv5k7vwHUojmrmoLSnZzfvQ6h1VNg2j7J84WSD14u3yyfkzbGB5x)
> ```

@craigraw this example would work great for my use-case. @stepansnigirev would you accept a PR that allowed this to be entered into Specter-Desktop? Here's the error it currently throws:
![Uploading Screen Shot 2020-11-19 at 10.54.48 AM.png…]()

I'm not sure it needs a whole serialization format, we're talking about a tiny amount of data.

**Comment by stepansnigirev** [comment]
Try without wsh wrapper: `[f7d04090/48h/1h/0h/1h]tpubDF7FTuPECTePtSLgeKZsbMif6c91sq1q7gis9sTVMu1Y8CTfpSew1SYsv5k7vwHUojmrmoLSnZzfvQ6h1VNg2j7J84WSD14u3yyfkzbGB5x`

It will figure out the purpose from the derivation path.

`wsh(xpub)` is not a valid descriptor and can cause confusion, so I would better avoid that. What's the problem with importing xpub with derivation if it sets correct purpose automatically?

**Comment by mflaxman** [comment]
> What's the problem with importing xpub with derivation if it sets correct purpose automatically?

@stepansnigirev are you using `purpose` like this for any other reasons except that it's often how existing multisig has been done? Linking a script type to a (part of the) path seems unrelated to me and it could be limiting. In the future we might see paths used only as paths, and that would be difficult to do in the way you're describing.

For example, I'd like to see a scheme where a semi-trusted service (think Casa/Unchained) can give out an xpub to `1` key in a HODLer's say `2-of-3`. The HODLer uses software to "blind" the service's BIP32 path using a passphrase that is given to an heir. Then if the HODLer dies, the heir presents the passphrase to the semi-trusted service, who can use it to derive the path needed to use their xpriv (the one corresponding to the original xpub they originally handed out) to cosign. That way you get complete privacy in your lifetime and your heirs still get (at least 1 key to) your bitcoin when you die.

There's also no need for the service to be a professional company, it could be a bitcoiner that you trust (who uses their existing hardware wallet to secure 1 key in _many_ friend/family member quorums).

Here's a rough sketch of what that would look like in code:
https://gist.github.com/mflaxman/d72d25ad00941cea8241b6667cf008a8

**Comment by stepansnigirev** [comment]
I don't like purposes in general, I think that keys can be used in any types of script, I would even use the same xpub for all single-sig script types, but bip49, bip84 and agreement on m/48 multisig path by hardware wallets put certain limitation on the key usage. For example with BitBox you can't get any other xpub except these specified paths, in all other hardware wallets you will see a warning that derivation path is unusual.
So I am using the purpose here to avoid user mistakes and warnings in the hardware wallets, for all custom derivation paths I don't want to have any specific "purpose". 

In the next release (and already in master) the user will be able to label the xpubs - it should make managing keys easier.

**Comment by mflaxman** [comment]
> for all custom derivation paths I don't want to have any specific "purpose".

So if you have a custom derivation path (like in the gist, check that out as it would be an awesome feature for DIY to support!), what's the preferred way to get xfp, path, xpub, and script-type to Specter-Desktop from the hardware wallet? It sounds like right now my *only* option is to use SLIP132 for the script type?

**Comment by stepansnigirev** [comment]
In master you can specify a custom derivation path in the device wizard and Specter will fetch it from the hardware wallet.
Then if the path is something custom you can use it in any wallet type.

In DIY you can display an xpub with *any* derivation path - there is a menu for that.

**Comment by k9ert** [comment]
When i got that right, this issue can be closed. Feel free to reopen it again!
