### ISSUE TITLE
Encrypt and backup wallet labels somewhere defined

### ISSUE THREAD

**Issue by nolim1t** [cryptoadvance/specter-desktop#629]
First of all thanks for the awesome project (which actually made me create [this one](https://github.com/lncm/docker-specter-desktop) to allow for server side installs - namely to embedded devices). Makes multi device and multi sig easy with multiple hardware wallets (especially Coldcard).

But would like to request that there should be a way of backing up (and encrypting) wallet labels somewhere for safekeeping. Not sure if it does this already.

**Comment by ben-kaufman** [comment]
Hi, thanks for your interest and for making this docker setup, really great!

We already export and allow importing of wallet labels as part of the full backup format under the Settings -> General tab.
Would be nice to allow encryption and decryption from Specter but will take us time to add this feature so for now any separate file encryption software could be used with the downloaded files. I'm not sure if that's what you meant but do you think an export of only the labels data separate from the rest of the info would be useful to have as well?

**Comment by nolim1t** [comment]
Thanks, will try that.
