### ISSUE TITLE
Extracting keys of Ledger Nano S stuck on 'Detecting'

### ISSUE THREAD

**Issue by SteliosRammos** [cryptoadvance/specter-desktop#655]
Hi there, I am running Specter Desktop v0.9.2 and am trying to connect my Ledger Nano S which is running the latest firmware. 

It seems Specter is unable to extract the keys as the UI is just stuck there. Any idea why that may be?

**Comment by stepansnigirev** [comment]
Hi! Yes, Ledger changed certain values in usb descriptors in the latest firmware so Specter does not detect it.
We already have a fix, and we are doing a release today that will bring compatibility with ledger back.

**Comment by leossleo** [comment]
> Oi! Sim, o Ledger alterou certos valores nos descritores usb no firmware mais recente para que o Spectre não o detecte. Já temos uma correção e estamos fazendo um lançamento hoje que trará de volta a compatibilidade com o ledger.

Still not working
