### ISSUE TITLE
Transaction history shows all the UTXOs not only the ones owned by the wallet

### ISSUE THREAD

**Issue by BTCBellyButton** [cryptoadvance/specter-desktop#656]
I created a new wallet pointing to the Wasabi wallet I use.
After a CoinJoin, the transactions history in Specter shows ALL the outputs of that transaction instead of just the ones actually owned by the wallet.
So with an anonymity set of 95 you see 95 rows + N other rows from the same transaction.

**Comment by stepansnigirev** [comment]
#657 may fix this, we release today so when the release is out please check if it helps.

**Comment by stepansnigirev** [comment]
Release is out, can you check if you still see all the outputs?

**Comment by BTCBellyButton** [comment]
It is not fixed. It shows all the outputs.   :(

**Comment by BTCBellyButton** [comment]
I just updated to 0.10.4, deleted and re-imported the wasabi wallet and unfortunately I still see all the UTXOs of the coin joins.
Also the balance it's much higher than it should be.

**Comment by stepansnigirev** [comment]
I'll try to reproduce it. What is your Bitcoin Core version?

**Comment by BTCBellyButton** [comment]
v0.20.1

**Comment by BTCBellyButton** [comment]
After re-scanning completed now the balance is correct, but I see lines after lines from the same transaction.

![image](https://user-images.githubusercontent.com/68573637/101436587-0f8c3080-38d4-11eb-8519-4b7587c76316.png)

**Comment by BTCBellyButton** [comment]
I just noticed there's no derivation path in the device settings.
I'm gonna try redoing it from scratch.

![image](https://user-images.githubusercontent.com/68573637/101436836-8e816900-38d4-11eb-82a8-c90ab299ad45.png)

**Comment by stepansnigirev** [comment]
This makes sense, because Core thinks that you are sending money to these addresses. As one of the inputs is yours Core considers all outputs to be destination addresses, and therefore shows all of them.
I think we could group all outputs of the transaction to a single entry, and show "to many" in the address column. And you could see details of the transaction when you click on it.

Re derivation path, I don't know how you imported it, if you just pasted the zpub then we don't know the derivation path and therefore it's empty.

**Comment by BTCBellyButton** [comment]
I don't remember. How I did it, But I just made anew device and new wallet with it.
![image](https://user-images.githubusercontent.com/68573637/101437733-77dc1180-38d6-11eb-8171-ebcf132ad234.png)


Same result. So the missing derivation path doesn't have anything to do with the problem.

![image](https://user-images.githubusercontent.com/68573637/101437680-5d099d00-38d6-11eb-8225-cf78cf1595d5.png)

**Comment by BTCBellyButton** [comment]
I'll try to sum it up here.

The wallet re-created based on the device with no derivation path, after scanning shows the correct balance, and ONLY its own 9 current UTXOs. So the UTXO tab seems to work correctly now.

The History tab shows multiple lines for each coin-join transaction so as, you suggested, grouping would be great.
Only thing they are A LOT of lines and it takes quite a bit of time switching to the wallet history tab. 
On my wasabi wallet the transaction history is about 200 lines but it shows only the transactions for Fees, Sends and Receives not the actual coinjoins.

Here I got to the last page...   
![image](https://user-images.githubusercontent.com/68573637/101440343-2040a480-38dc-11eb-8388-c3b9e07b673d.png)
