### ISSUE TITLE
Only change address visible on Trezor when consolidating (sending to myself)

### ISSUE THREAD

**Issue by DriftwoodPalace** [cryptoadvance/specter-desktop#660]
Hi,

I've been thinking of consolidating some of my funds by combining multiple UTXOs to one or two. But when trying it with Specter and a Trezor One I encountered an issue (I think). When I check the receiving address on the device it shows the wrong address (it shows the change address). Maybe this is because I'm sending to myself?

So, for example. Two scenarios:
1. Sending 0.2 btc to myself by splitting it in two, 0.1 btc to `address 1` and 0.1 btc to `address 2`. I'll use `address 1` as the Recipient address. But when I select "show on device" `address 2` shows up (the change address). 
2. Sending 0.2 btc to myself by combining multiple UTXOs in to one address. Again I'll use `address 1` as the Recipient address. This time when I check the address it shows the `miner fee address` on the device.

Is this expected behavior? I guess it's OK because it would show the address if it was to someone else then myself. But kind of defeats the purpose of showing the address on the device.

Thanks for a great product and your hard work!

**Comment by stepansnigirev** [comment]
For me when I send to myself I only see the fees, so please double-check the addresses, not sure why this is happening but please be very careful.

![photo_2020-11-21_11-33-25](https://user-images.githubusercontent.com/1706012/99875195-fa35b780-2bed-11eb-8ef0-c97096354311.jpg)

**Comment by DriftwoodPalace** [comment]
Hm weird, that I haven't experienced. I however are running an old firmware on my Trezor (1.8.0 ), might be why. It's miner fee or change address if that exists that shows up

I tried with some test amounts and there wasn't any issues (and you can control the outputs on the screen). But yea, you would like to confirm them on the device, even if sending to yourself I guess. Otherwise it kind of defeats some of the purpose with a HW-wallet.

**Comment by stepansnigirev** [comment]
I think Trezor hides all addresses that belong to the same wallet.
It would be better if they could show the address and just mark it as "change" or "to self", but that's what they decided to do...
