### ISSUE TITLE
Fiat price amounts: missing in a few places. 

### ISSUE THREAD

**Issue by s-5Q2X8mgeGR** [cryptoadvance/specter-desktop#664]
Great with the new fiat price feature. 

Fiat price missing in a few places: 

- Create new transaction tab: Calculate estimated fee 
![image](https://user-images.githubusercontent.com/71570725/99883969-eceaee00-2c2a-11eb-8dee-6a00ffea5c38.png)

After having created new transaction, click _Show Transaction_ details: 
- Total fee 
![image](https://user-images.githubusercontent.com/71570725/99884004-27ed2180-2c2b-11eb-9ecb-6f8df9357bd2.png)
- Amount on Input(s)
![image](https://user-images.githubusercontent.com/71570725/99884013-3f2c0f00-2c2b-11eb-92ca-7318a86e018a.png)
- Amount on Output(s)
![image](https://user-images.githubusercontent.com/71570725/99884019-47844a00-2c2b-11eb-9266-c3596c6e05c8.png)

Also, it's missing on coin selection subtab. But, not really space for it. IMO, if detect not mobile sized screens, just make the Send screen tab full width. But probably not good to spend ressources to do these microimprovements to the coin selection (and create tx screen in general) before do a full redesign at some point (IMO, the Specter coin selection section is terrible; bitcoin core's coin selection popup gives a much better overview. I should stop being lazy and propose a redesign :)) 

Lastly, I think hiding the toggle to enable fiat value in settings as the only option to enable it is OK, but adding ability to, the first time, enable fiat conversion with the top right is a better and more accessible option. 

See image as example: 

![image](https://user-images.githubusercontent.com/71570725/99884114-e5781480-2c2b-11eb-950b-a78888896890.png)

Allow user to simply click this (probably could be worded in better, shorter way), see modal to Enable price, and then select manual/automatic. Then user needn't find it inside settings. Would wager that most users find having fiat conversions inside the wallet app to be useful, thus hiding the enabling of the feature to settings, instead of more front and center, just means less users will find it.

**Comment by ben-kaufman** [comment]
Fixed in #691
