### ISSUE TITLE
When creating transaction, allow Amount to Recipient input as Fiat value. 

### ISSUE THREAD

**Issue by s-5Q2X8mgeGR** [cryptoadvance/specter-desktop#665]
Now that it's possible for Specter Desktop to have a fiat price source, it would be neat to allow input amount for recipient when creating a transaction to also be input as fiat amount. 

Design wise, it's just two input fields, on same horizontal line: 

![image](https://user-images.githubusercontent.com/71570725/99884152-2f60fa80-2c2c-11eb-8412-e2b5da0131c9.png)
![image](https://user-images.githubusercontent.com/71570725/99884155-3a1b8f80-2c2c-11eb-8eaf-3831ab5989d0.png)

Adding this gives two benefits to the user: 
- When the user wants to send BTC amounts worth X fiat (eg., sending 100 USD to someone), they needn't do the calculation outside the wallet app. 
- If user enters an amount in the BTC field, the fiat field automatically updates, and vice versa—helps confirm to the user that the amount they entered in BTC is actually the amount in fiat they assume it to be. 

Minor details: 
- This feature perhaps *only* show up (maybe greyed out, with text explaining:) if user has enabled the fiat price feature. 
- If the user then has fiat price feature enabled and is using manual prices, not automatic, perhaps should have small text "BTC(FiatSymbol): (Value)" -- so it's pointed out to the user that the app is calculating via their manually set exchange rate, which may be outdated.

**Comment by k9ert** [comment]
With a long enough time horizon, unit of account is changing faster than we're able to implement that feature ...
