### ISSUE TITLE
Speed up (RBF) on transaction that spends all input(s), bad error message 

### ISSUE THREAD

**Issue by s-5Q2X8mgeGR** [cryptoadvance/specter-desktop#667]
If you try to speed up a transaction that had spent the entire input(s), this is the error message:

![image](https://user-images.githubusercontent.com/71570725/99884818-2fafc480-2c31-11eb-9867-a6286aa8cea6.png)

Bitcoin core gives a better, although still not that good, error message: 

![image](https://user-images.githubusercontent.com/71570725/99884858-78677d80-2c31-11eb-9d04-524d7a8b22fd.png)

Assuming Specter desktop can derive that it is not possible to RBF as the entire input(s) were spent and there's no change, either
- improve the error message
- or simply grey out the Speed up button, with a tooltip/small message displayed on error to educate/inform the user that Speed Up is not possible when the entire input(s) were spent and there's no change.

**Comment by ben-kaufman** [comment]
Should now give a proper error message ("Cannot RBF a transaction with no change output") with #744 so closing this for now
