### ISSUE TITLE
Add instructions on how to verify the release

### ISSUE THREAD

**Issue by s-tikhomirov** [cryptoadvance/specter-desktop#668]
Currently, the releases page says:

> sha256.signed.txt file contains sha256 hashes of all binary files and signed with @stepansnigirev's GPG key.
You can get public key from here: https://stepansnigirev.com/ss-specter-release.asc.
It is also available via keys.gnupg.net or keys.openpgp.org.
Fingerprint of the key is 6F16 E354 F833 93D6 E52E C25F 36ED 357A B24B 915F, short id: 36ed357ab24b915f

but doesn't specify how exactly one can use this information to verify the release.

**Comment by stepansnigirev** [comment]
Good point, I will add the doc.

**Comment by k9ert** [comment]
Fixed. This is now described on https://specter.solutions
