### ISSUE TITLE
Broken image for device listing in v0.10.0 under raspiblitz v1.6.1

### ISSUE THREAD

**Issue by shawnyeager** [cryptoadvance/specter-desktop#670]
In the left nav bar:

<img width="241" alt="Screen Shot 2020-11-21 at 9 08 42 PM" src="https://user-images.githubusercontent.com/980297/99886556-12640180-2c03-11eb-988e-da383a24ab59.png">

As well as here under device Settings:

<img width="558" alt="Screen Shot 2020-11-21 at 9 10 20 PM" src="https://user-images.githubusercontent.com/980297/99886582-4c350800-2c03-11eb-8dd1-7effd50c968d.png">

**Comment by stepansnigirev** [comment]
Does it happen for other devices as well or only for Coldcard?

**Comment by shawnyeager** [comment]
Restarting the service resolved the problem. Thanks.
