### ISSUE TITLE
Currency symbol display for USD

### ISSUE THREAD

**Issue by shawnyeager** [cryptoadvance/specter-desktop#672]
$ symbol should precede the amount. 👍 

<img width="305" alt="Screen Shot 2020-11-21 at 9 26 25 PM" src="https://user-images.githubusercontent.com/980297/99886874-8acbc200-2c05-11eb-9731-b72721eccf58.png">

As well as for the `Total balance:`

**Comment by figgyfigs** [comment]
I was taking a look at this. Indeed the $ sign goes before the number. I wasn't too sure about the euro or pound symbols but doing some research it looks like the pound sign goes before as well and the euro sign goes after. Does that sound right? If so I will make the changes

**Comment by shawnyeager** [comment]
I'm no currency expert, but I can confirm that for USD and GBP (£) the symbol precedes the number.

**Comment by maxidev** [comment]
I believe that this issue should be closed as it is fixed on #799

**Comment by ben-kaufman** [comment]
Yes I think we can close this, thanks. (Please reopen if still relevant)
