### ISSUE TITLE
How do I delete a wallet?

### ISSUE THREAD

**Issue by s-tikhomirov** [cryptoadvance/specter-desktop#675]
Testing things out, I created a bunch of devices and wallets and now want to delete / forget them. I can't forget a device that is used in a wallet. But how do I delete a wallet? I don't see an obvious red button for wallets like in the device menu.

**Comment by BTCBellyButton** [comment]
![image](https://user-images.githubusercontent.com/68573637/99888536-34fe1680-2c13-11eb-8284-c6f6683e39cf.png)

**Comment by s-tikhomirov** [comment]
Thanks @BTCBellyButton ! Maybe worth giving a hint on where to find this in the error message that says that a device can't be forgotten before its wallets are deleted.
