### ISSUE TITLE
Scan to Verify Address - what does it mean?

### ISSUE THREAD

**Issue by s-tikhomirov** [cryptoadvance/specter-desktop#677]
I created a new multisig wallet and press "Verify address via QR code" and see this window:

![Screenshot from 2020-11-21 22-37-21](https://user-images.githubusercontent.com/7126627/99888085-2aab3f00-2c4a-11eb-974a-b3741ee04878.png)

I don't understand what this means. "Specter can verify this address if you scan it"... with what? Specter is _already_ showing me this QR code. How does it verify itself? And what is "my device" in this case?

**Comment by ben-kaufman** [comment]
That should only appear if your multisig has a Specter DIY... This just means you can scan the QR on your Specter DIY device to verify the address.

**Comment by s-tikhomirov** [comment]
So there are actually two issues here:

1. I don't have a Specter DIY, so this window shouldn't have appeared in the first place;
1. Even if I had, the wording looks unclear to me.

**Comment by k9ert** [comment]
Yeah, that's true the wording could be improved. The first issue is also solvable over at:
https://github.com/cryptoadvance/specter-diy

If you're not so much into DIY, check the news and you might be able to buy a device!

**Comment by stepansnigirev** [comment]
Closed with https://github.com/cryptoadvance/specter-desktop/pull/714
This option is not available for Cobo any more.
