### ISSUE TITLE
Default wallet not available in Bitcoin Core after creating a new wallet in Specter

### ISSUE THREAD

**Issue by s-tikhomirov** [cryptoadvance/specter-desktop#678]
I have a Bitcoin Core (testnet) instance with some coins. I launch Specter that connects to it. I then import Bitcoin Core as a new device and create a new single-signature wallet. After that, my existing wallet is no longer available in Bitcoin Core CLI:

```
$ bitcoin-cli getwalletinfo
error code: -19
error message:
Wallet file not specified (must request wallet RPC through /wallet/<filename> uri-path).
Try adding "-rpcwallet=<filename>" option to bitcoin-cli command line.
```

What arguments (filename?) do I provide to `getwalletinfo` to continue using my old wallet from outside of Specter? More generally, where does Specter create its Core wallets?

**Comment by stepansnigirev** [comment]
Empty string is the name of the default wallet.

bitcoin-cli -rpcwallet= getwalletinfo

**Comment by s-tikhomirov** [comment]
> you can see this folder in your wallets dir

Where can I find this dir? Probably not in `~/.bitcoin`?..

**Comment by stepansnigirev** [comment]
`~/.bitcoin/wallets/speter<randomid>`

**Comment by k9ert** [comment]
Did that solved your issue?

**Comment by k9ert** [comment]
Please reopen if necessary!
