### ISSUE TITLE
Grand Total

### ISSUE THREAD

**Issue by BTCBellyButton** [cryptoadvance/specter-desktop#679]
It'd be nice to have the grand total of all the wallets somewhere.

**Comment by ben-kaufman** [comment]
There already is actually, in the sidebar next to "Wallets" right under the Bitcoin symbol and info, it's "Wallets Overview"
 
<img width="241" alt="Screen Shot 2020-11-21 at 23 15 04" src="https://user-images.githubusercontent.com/10667901/99888787-8b894600-2c4f-11eb-810c-139129d94431.png">

**Comment by BTCBellyButton** [comment]
Cool! I didn't notice. I thought it was just part of the description "Wallets".
Thanks!
