### ISSUE TITLE
Ledger still not working with latest Bitcoin app

### ISSUE THREAD

**Issue by rsdrsd** [cryptoadvance/specter-desktop#681]
Specter still won't retrieve addresses from the Ledger Nano S, unless the update. I installed version 0.10 in which it should be fixed, but it's still unresponsive.

**Comment by ben-kaufman** [comment]
Hi, please try with https://github.com/cryptoadvance/specter-desktop/releases/tag/v0.10.1

**Comment by k9ert** [comment]
Did that worked for you?

**Comment by rsdrsd** [comment]
Sorry for the delay, but the latest version is working for me on windows.
