### ISSUE TITLE
Backup files naming: use wallet current name

### ISSUE THREAD

**Issue by BTCBellyButton** [cryptoadvance/specter-desktop#684]
I think it would be better when you export a backup file to name it with the current name instead of the directory's original name given (explicitly or not) at wallet creation time.

For example in my case the following are the tests wallet I am using. I didn't change the default name of some of them at creation time. But I did it later on from the wallet settings. 
So now the directories don't match the Wallet names shown in Specter and the backup files are named after these directories. It is confusing and you have to manually change them at backup time.

![image](https://user-images.githubusercontent.com/68573637/99919353-74476880-2ce2-11eb-815a-0e3f2b6fd788.png)

**Comment by k9ert** [comment]
Seems like the PDF-export is doing it correct but the json-one is doing it wrong.
![image](https://user-images.githubusercontent.com/117085/100610227-9d35b200-330f-11eb-84ea-f4cb218d78eb.png)

**Comment by rajarshimaitra** [comment]
Hi. I am new specter-desktop and willing to scour the project. If this is still an issue I would like to take it up.

**Comment by ben-kaufman** [comment]
Yes I believe that's still active. Thanks!
