### ISSUE TITLE
'Display address on device' does not match

### ISSUE THREAD

**Issue by vayok16680** [cryptoadvance/specter-desktop#685]
Made a 2 of 2 Multisig wallet using 2 KeepKey devices (fully up to date firmware) for testing purposes, using Segwit/Bech32.

On the Receive tab, the 'Display address on device' address fails to match and results in a red warning notification to 'Contact support ...'

**Comment by k9ert** [comment]
Is this a duplicate on #694 ? Can you please check?!

**Comment by stepansnigirev** [comment]
Closed with https://github.com/cryptoadvance/specter-desktop/pull/733
Release with the fix will be available soon.
