### ISSUE TITLE
Specter 10.1 Version Unknown in UX home screen on Windows 10 app

### ISSUE THREAD

**Issue by joe-rodgers** [cryptoadvance/specter-desktop#693]
Specter Desktop 10.1 on Windows 10 shows Specter Version: Unknown in the main window.

I've provided a screenshot for reference, please see the bottom left of the screenshot. 

![Specter_XHZ0KZopje](https://user-images.githubusercontent.com/25499388/100017801-13329a00-2da1-11eb-9770-6dd043442c19.png)

**Comment by stepansnigirev** [comment]
Please try deleting the file in your user folder:
~/.specter/specter-binaries/specterd

**Comment by joe-rodgers** [comment]
that worked
