### ISSUE TITLE
Support scanning a user specified derivation path

### ISSUE THREAD

**Issue by lucasmoten** [cryptoadvance/specter-desktop#695]
Intent is to facilitate usage of Specter as a possible recovery tool for CasaHODL, and Unchained Capital.

When currently adding a device, the options presented to the user require one of the following
1. Know the fingerprint, derivation path, and xpub
2. Scan a QR code
3. Have a premade file 
4. Scan the USB

There is an option to specify account number, but this influences only a portion of the scanned paths which are
- 49'/0'/0'
- 84'/0'/0'
- 48'/0'/0'/1'
- 49'/0'/0'/2'
- 49'/1'/0'
- 84'/1'/0'
- 48'/1'/0'/1'
- 49'/1'/0'/2'

In the case of Casa, they use unhardened paths off of 49/0/0. Recovery information that clients get yields the derivation path and xpub, but not the fingerprint, preventing manual entry in the text box without using another tool (whether thats HWI or Electrum, or whatever) to discern it.

 Unchained Capital uses 45'/0'/d'/r for its base derivation paths, where `d` represents a device number, and `r` a rotation number (e.g. m/45'/0'/0'/1) with the last bit unhardened.  This isn't part of the default scan set either.  

Ideally it would be great if the scan process also had an advanced option so the user could specify any derivation path.  My current workaround for this is to do so at the command line using HWI directly to interrogate the device for it and then manually assemble the [ fingerprint / derivation / path ] format.

**Comment by yunier2002** [comment]
Agree with this, we need a way to add other services multisig with custom derivation paths.

**Comment by ben-kaufman** [comment]
Hi. It is already possible to use any derivation path you would like to by first adding the xpub for that derivation path (when adding device (you have a table of derivations and xpubs, click edit at its top right, then you'll have a new row at the bottom with a button to add custom derivation path)

After you have imported the xpub for that derivation path, you can create a wallet and select to use that xpub in the keys list in the wallet creation screen. Then you can also check the rescan for funds checkbox and it should detect funds on the wallet with this custom derivation path

**Comment by lucasmoten** [comment]
Excellent. I was able to verify that as you described with Specter 0.10.1+.  

I think when I first encountered the problem months ago I must have been on an older version as the interface for this was dramatically different as well.  I reviewed the release notes going back which reveals this was addressed in #514 in 0.9.1 which was cut in early November.

Thanks for following up on this.
