### ISSUE TITLE
Store pending transaction

### ISSUE THREAD

**Issue by Sjors** [cryptoadvance/specter-desktop#7]
If you navigate away from the send screen while signing on a device, then you can't resume the transaction.

**Comment by stepansnigirev** [comment]
Good idea. 
I think the best way would be to store it in the wallet and when the user navigates to `/send/` notify him that there is an unfinished transaction and allow to either load it and continue with it or to create a new one.

**Comment by kdmukai** [comment]
My in-progress implementation just auto-loads the pending psbt whenever you navigate back to `send/` and presents it to the user, ready to sign. The UI has an added "cancel transaction" button at the bottom that clears the pending psbt.

Also I figured it would be much simpler to only allow one pending psbt at a time.

**Comment by stepansnigirev** [comment]
I think having a single pending psbt transaction is ok for now.
Would it make sense to add "export" and "import" buttons?
Maybe something like a textarea where you can enter a base64-encoded PSBT?
And similar for export - to show base64-encoded PSBT that you could copy and send over email / save in the text file for example.

**Comment by kdmukai** [comment]
Agreed. Er, concept ACK, right?

**Comment by ben-kaufman** [comment]
Hi, I'd be happy to pick up this issue. I was thinking of saving unfinished transactions in an array in the wallet (either manually or automatically if the user navigates out of the send screen). The user will be able to return to any saved PSBT and pick up from where he left off with the signing process. When a PSBT is saved we'll lock the UTXO with `lockunspent` and release it if the PSBT is discarded. As we now add manual coin selection we'll need to either disable/ hide locked UTXO or ask the user about discarding the pending PSBT using the coin. We'll need a similar process also if the user tries to spend more than the "unlocked" balance.

**Comment by stepansnigirev** [comment]
Assigned you to this issue :)
