### ISSUE TITLE
Screen: Pop-up "New device was added successfully!"

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#704]
Please change wording here to:

"Create wallet" -> "Create single key wallet"
"Create multsig" -> "Create multisignature wallet" 

![image](https://user-images.githubusercontent.com/47259243/100448093-0fa95680-30b2-11eb-9136-4f9f08f98edf.png)

**Comment by rajarshimaitra** [comment]
Is this issue persisting? Willing to take it, but it seems the current Pop up have different only first two items.

**Comment by ben-kaufman** [comment]
I think you could do it, just checked and it's still. as in the image, maybe you've checked a different place?

**Comment by rajarshimaitra** [comment]
I am seeing this when adding a dummy core hot device.
![specter1](https://user-images.githubusercontent.com/36541669/102857075-cb5d6c00-444d-11eb-9081-f46953785389.png)

**Comment by ben-kaufman** [comment]
Maybe you have only a single device added (then you need to add another one before you can make a multisig)?

**Comment by rajarshimaitra** [comment]
Got it. Thanks..
