### ISSUE TITLE
Signet uses the wrong address prefix

### ISSUE THREAD

**Issue by Sjors** [cryptoadvance/specter-desktop#706]
There was a somewhat last minute change to the bech32 prefix for Signet, making it the same as testnet (tb1...).

I couldn't find where the prefix is set in the code, but if I make `def address` in `descriptor.py` use "testnet" instead of "signet" it behaves.

**Comment by k9ert** [comment]
Can you check my PR on embit? Is it simple as that?

**Comment by Sjors** [comment]
This indeed behaves now.
