### ISSUE TITLE
Use descriptor wallets for Bitcoin Core v0.21.0

### ISSUE THREAD

**Issue by Sjors** [cryptoadvance/specter-desktop#707]
Coming soon(tm). I have some ugly WIP code to support it, but anyone should feel free to make a PR earlier.

I suggest checking the Bitcoin Core version and if it's 0.21 or later, leverage the following:

* `createwallet` takes a new `descriptors` argument, set it to `true`
* use `importdescriptors` instead of `importmulti`. It's the same syntax except:
  * you can drop `keypool`
   * you have to set `"active": True` for both receive and change
   * you have to set `"internal": True` for change
   * Nice benefit: the New Address button in Bitcoin Core GUI will work
* you can probably ditch all the keypool refill logic, as Bitcoin Core will just expand the descriptors as needed
* use `balance = self.rpc.getbalances()["mine"]` (instead of "watch-only")

**Comment by stepansnigirev** [comment]
What's the default address gap in core?

**Comment by Sjors** [comment]
The default gap is 1000, and can be configured with `-keypool` or (1 off) by setting a higher range during the descriptor import. If you set it to 1 million things get unacceptably slow, at least the last time I tried.

**Comment by ben-kaufman** [comment]
Closed with #737
