### ISSUE TITLE
UX: Search functions

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#725]
Hi guys :)
So working with the woocommerce webshop & BTCpay integration is quite interesting.
Two txs failed because of low fees - so they were flagged as "failed" in woocommerce.

While trying to label these customers addresses I realized we do not have a good search function in the app.
I using now the browser window, but could we add a search function?

The best would be one window (maybe transactions) where you could search txs, addresses, amounts and also do the labeling. Maybe also download a csv file.

Cheers, Moritz

**Comment by k9ert** [comment]
Should be fixed with #760 and #758. As it is part of the new release, i'm closing it here.
