### ISSUE TITLE
Python 3.9 upgrade issue

### ISSUE THREAD

**Issue by holuan** [cryptoadvance/specter-desktop#741]
OK, i might be doing something stupid..

I am running Arch Linux. There was recently an upgrade to python 3.9.

After that upgrade - my specter desktop stooped executing.

When i try to run:

python -m cryptoadvance.specter server

i get:

/usr/bin/python: Error while finding module specification for 'cryptoadvance.specter' (ModuleNotFoundError: No module named 'cryptoadvance')

When i try to reinstall using pip, i get the following error:

defaulting to user installation because normal site-packages is not writeable
Collecting cryptoadvance.specter
  Using cached cryptoadvance.specter-0.8.1-py3-none-any.whl (1.3 MB)
Collecting Flask-Login==0.5.0
  Using cached Flask_Login-0.5.0-py2.py3-none-any.whl (16 kB)
ERROR: Could not find a version that satisfies the requirement hwi==1.1.2 (from cryptoadvance.specter) (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for hwi==1.1.2 (from cryptoadvance.specter)

Am I doing something stupid?

**Comment by holuan** [comment]
curl https://bootstrap.pypa.io/get-pip.py | python 

fixed it. Surprise surprise i was doing something stupid :)

**Comment by stepansnigirev** [comment]
I didn't expect it would work on 3.9 because HWI doesn't support 3.9, so we had to use the same versions range...
I am really surprised that it worked for you :)

https://github.com/bitcoin-core/HWI/blob/master/setup.py#L150
