### ISSUE TITLE
Price Settings Error

### ISSUE THREAD

**Issue by MauiLiam** [cryptoadvance/specter-desktop#762]
Love Specter! I just got an error when attempting to set a Price Setting to pull Kraken Spot price data over TOR.  After poking around other places, I noticed my TOR was not activated. So I thought that was it - activated TOR and still am getting the error. Not sure if you prefer these small issues noted here, or in the Telegram group.  I'm a Github newbie so please let me know best practice.  Thanks

![Specter_Desktop](https://user-images.githubusercontent.com/55666499/101557505-452b2b00-3961-11eb-8532-ff2e84a9738b.jpg)

**Comment by ben-kaufman** [comment]
Hi, this seems not to be an issue with Specter, but looks like the price provider API - Spotbit - is down. Cc @ChristopherA

**Comment by shannona** [comment]
I've restarted the server. Debugging to see if we can find the cause of the crash.

**Comment by shannona** [comment]
We had an out-of-memory error. We've upped the swap on the server and will hopefully be setting up some monitoring next week to better note if a problem like this occurs.

**Comment by MauiLiam** [comment]
Right on - I see you're in Hawaii nei.  Thanks for the update.

**Comment by ben-kaufman** [comment]
Thanks @shannona !

Closing this issue then.
