### ISSUE TITLE
Failed connecting to the node

### ISSUE THREAD

**Issue by alherrando** [cryptoadvance/specter-desktop#767]
I tried to connect to the external drive path directory "D:\" where I have the bitcoin blockchain but returns an error message. 
Could there be another directory path I missed?
thanks
![Captura](https://user-images.githubusercontent.com/75807118/101882636-73de1700-3b96-11eb-8f8c-0e7952ca15a8.PNG)

**Comment by ben-kaufman** [comment]
Hi, can you confirm that:
1. the `bitcoin.conf` file has a line `server=1` (if not, add it and restart)
2. The Bitcoin core folder is at the root of the D:\ dirve? If not set it to the exact folder it's at (i.e. whichever folder the `bitcoin.conf` is at).

**Comment by alherrando** [comment]
> Hi, can you confirm that:
> 
> 1. the `bitcoin.conf` file has a line `server=1` (if not, add it and restart)
> 2. The Bitcoin core folder is at the root of the D:\ dirve? If not set it to the exact folder it's at (i.e. whichever folder the `bitcoin.conf` is at).

thanks for your help! I see the file in the root of the D:\ drive, but how do I open it to see the line you comment?
Thanks!

**Comment by ben-kaufman** [comment]
You could open it with any text editor.

Here's a video guid for setting it up https://www.youtube.com/watch?v=4koKF2MDXtk

**Comment by alherrando** [comment]
> You could open it with any text editor.
> 
> Here's a video guid for setting it up https://www.youtube.com/watch?v=4koKF2MDXtk

Great, it worked! thanks
