### ISSUE TITLE
Support for uppercase schema and amount parameter in QR codes.

### ISSUE THREAD

**Issue by mutatrum** [cryptoadvance/specter-desktop#771]
Uppercase schema and addresses are easier to scan as they generate smaller QR codes due to more efficient encodings. Spected Desktop currently fails to recognize uppercase schema and the amount parameters.

See https://github.com/btcpayserver/btcpayserver/issues/2110#issuecomment-743751851.

**Comment by k9ert** [comment]
I agree that the schema/amount is not parsed properly. However uppercase has already been solved in #499 , no?!
Or do you mean that specter should create QR-codes based on uppercase bech32-addresses?

**Comment by mutatrum** [comment]
The issue raised is specifically for reading QR codes, not generating.

**Comment by ben-kaufman** [comment]
Fixed with #837
