### ISSUE TITLE
Specter-0.10.4.AppImage only works when started from terminal

### ISSUE THREAD

**Issue by unruhschuh** [cryptoadvance/specter-desktop#775]
If I run the app image via a .desktop file, I get the error message "Failed to load: http://localhost:25441".
```
[Desktop Entry]
Version=0.10.4
Terminal=false
Type=Application
Name=Specter
Exec=/home/me/bin/Specter-0.10.4.AppImage
Path=/home/me/bin
```

If I run it via ./Specter-0.10.4.AppImage in the terminal it works.

**Comment by k9ert** [comment]
Why don't you use the AppImage directly? Clicking on it directly works on my ubuntu 20.04. (using the [v0.11.0-pre2](https://github.com/cryptoadvance/specter-desktop/releases/tag/v0.11.0-pre2))
Any reason to create the exra-indirection?
I'm not sure why you wan

**Comment by unruhschuh** [comment]
Running it via double-click from the file manager (in my case Dolphin (KDE)) doesn't work either and leads to the same error message as running it via .desktop file.

As to why I want to do it this way: This is how most apps are started on the desktop, so I guess it should work for specter as well.

**Comment by k9ert** [comment]
Did you find a solution for your issue? I guess you're using a KDE based OS. Which is it?
Does it work if you start via terminal?

**Comment by unruhschuh** [comment]
I haven't used it in a while. I tried it today and it works, but I'm using gnome now. I was using KDE on Ubuntu 20.04.2 LTS back then.

**Comment by k9ert** [comment]
Ah, ok. I'd say we probably will never fix thais as KDE is rarely used nowadays. Closing it for now.
