### ISSUE TITLE
Signing messages and Verifying messages

### ISSUE THREAD

**Issue by wombat26** [cryptoadvance/specter-desktop#777]
Hello guys, I wonder if you have thought about adding the feature to sign messages with addresses and also verify messages, something similar as Bitcoin Core has.

Thanks for all the work that you have been doing, Specter works like magic to me. 

<img width="689" alt="Screenshot 2020-12-13 at 15 44 48" src="https://user-images.githubusercontent.com/45880001/102016756-607ba900-3d5a-11eb-923d-2f7ef6bbb436.png">
<img width="694" alt="Screenshot 2020-12-13 at 15 44 54" src="https://user-images.githubusercontent.com/45880001/102016757-62456c80-3d5a-11eb-9cdc-ac3060753105.png">

**Comment by ben-kaufman** [comment]
Hi, so currently we support message signing with HWI devices. Would also make sense to support this for the hot wallet though. Message verification would also be nice, but not sure where to put that in the UI. Any ideas?

**Comment by real-or-random** [comment]
For me, "Message was signed successfully!" is displayed even where was an error (on Trezor).

Also, bitbox02 has the button for message signing but this device does not support message signing at all. (Hm ideally, HWI would export the support matrix in code https://hwi.readthedocs.io/en/latest/devices/index.html#support-matrix...)

**Comment by benma** [comment]
> Also, bitbox02 has the button for message signing but this device does not support message signing at all.

BitBox02 supports message signing, also through HWI (on master, I think it's not released in an official release yet):

https://github.com/bitcoin-core/HWI/blob/7dcd7bd57cc311cb73c48ea2335dd6be75842067/hwilib/devices/bitbox02.py#L789

**Comment by mandelbit** [comment]
Can messages be signed with multisig wallets using Specter?

Where is the message signing in the Specter Desktop UI?

**Comment by k9ert** [comment]
Message signing with multisig is not possible however i think that's not a restriction of specter (not 100% sure, though).
Message signing with single-sig-wallets is possible but not very UIUX-friendly. See a description here:
https://github.com/k9ert/specter-desktop/blob/message_signatures/docs/sign-message.md

**Comment by lclc** [comment]
BIP322 would allow signing with multisig, but it has pretty much 0 adoption (not even Core implemented it). So no, there is no common standard for message signing with multisig.

Thanks for the link @k9ert.

**Comment by k9ert** [comment]
Closing as this is done.
