### ISSUE TITLE
Can't connect to the node with certain symbols in the password

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-desktop#784]
For example if % is in the password

**Comment by brmdbr** [comment]
File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\requests\auth.py", line 63, in _basic_auth_str
    password = password.encode('latin1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\ufffd' in position 5: ordinal not in range(256)

**Comment by Clamenda** [comment]
Had the same issue with one or several of these characters: /()_

**Comment by maxidev** [comment]
To reproduce this I need to set the bitcoin-core RPC / password with some special character like %, right?

**Comment by Clamenda** [comment]
Yes, but I didn't check which special character it was or if there are several causing the issue. It most be at least one of these 4:
/
(
)
_

**Comment by maxidev** [comment]
Could not reproduce using the password shown on screenshot, (with % and ')' ) and Bitcoin core
![image](https://user-images.githubusercontent.com/5783552/104230000-c035a480-542b-11eb-8f62-991561b47560.png)

**Comment by brmdbr** [comment]
It does a request with the password in the path, any url-breaking chars will break it I think,

**Comment by brmdbr** [comment]
Try: & ? =

**Comment by maxidev** [comment]
Could reproduce it with & ? = chars, erroror:
[2021-01-12 14:57:04,680] ERROR in specter: Caught an exception of type <class 'requests.exceptions.InvalidURL'> while test_rpc: Failed to parse: http://bitcoin:%test_pas)sw&o=r?d@localhost:8332
