### ISSUE TITLE
Enhancement: add "verify address on the device" button

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-desktop#79]
HWI has a method to display address on the device. It works for single key wallets, for multisig it is not available yet, but I think it makes sense to implement this feature. Kinda critical for hardware wallets.

**Comment by kdmukai** [comment]
The KeepKey (and presumably Trezor) is able to verify multisig addrs, at least on Electrum's implementation.

**Comment by stepansnigirev** [comment]
Yes, Trezor and KeepKey can display multisig addresses, but it is not implemented in HWI.
We are also missing change verification on Trezor when using HWI.

**Comment by stepansnigirev** [comment]
Here is the pull request that will enable this feature:
https://github.com/bitcoin-core/HWI/pull/279
