### ISSUE TITLE
Labeling Issue

### ISSUE THREAD

**Issue by IsaacJ1** [cryptoadvance/specter-desktop#806]
I recently imported a few HW wallets to Specter. Each of those wallets as single sig have addresses starting with "bc1". I downloaded a PDF wallet backup, and noticed that below the name I gave the wallet it says "Nested Seqwit". Unless I am mistaken, this should read "Native Seqwit" as they are bech32 starting with bc1.

**Comment by ben-kaufman** [comment]
Hi, yes this is a bug. PR #800 should fix this
