### ISSUE TITLE
Runtime error: ImportError: cannot import name 'ExtendedKey'

### ISSUE THREAD

**Issue by instagibbs** [cryptoadvance/specter-desktop#808]
```
python3 -m cryptoadvance.specter server 
...
  File "/pathtovirtualenv/python3.6/site-packages/cryptoadvance/specter/devices/hwi/trezor.py", line 43, in <module>
    from hwilib.serializations import (
ImportError: cannot import name 'ExtendedKey'
```
Installed it via `pip3 install cryptoadvance.specter`

python 3.6.9

**Comment by ben-kaufman** [comment]
Hi, my best guess is that you have an HWI version installed on your system and it's not the one Specter requires.
Have you tried installing it in a clean virtual env?

**Comment by instagibbs** [comment]
yep, like keys I should make sure to never reuse virtualenvs ;)
