### ISSUE TITLE
Export wallet QR generation fails when wallet name contains Apostrophe `'`

### ISSUE THREAD

**Issue by amfathi** [cryptoadvance/specter-desktop#811]
I'm trying to export a wallet with name `Fathi's Wallet` and the QR generated was almost empty.

here is the screenshot:

<img width="569" alt="Screenshot 2020-12-27 at 9 58 06 PM" src="https://user-images.githubusercontent.com/22002954/103179679-b25e1c00-488e-11eb-83a1-3ad0d13ca2ee.png">

here is the QR code content:

`{ "label": "Fathi\`

Workaround is to change the wallet name to some doesn't contain `apostrophe` like `FathisWallet`

**Comment by ben-kaufman** [comment]
Fixed with v1.2.2
