### ISSUE TITLE
Not finding the Docker image for running tests

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#83]
Running `pytest` and seeing:

```
No such image: registry.gitlab.com/cryptoadvance/specter-desktop/python-bitcoind:latest
```

**Comment by kdmukai** [comment]
Making progress:

```
docker pull registry.gitlab.com/cryptoadvance/specter-desktop/python-bitcoind:master
```

**Comment by stepansnigirev** [comment]
@k9ert you should know something about our docker stuff ;)

**Comment by kdmukai** [comment]
I have the docker image now and can `docker run -it` it. But stuck there. With the container running I tried the `python3 -m cryptoadvance.specter bitcoind` but that didn't seem to go anywhere. Can't figure how to get bitcoind to run inside the container. 

I'm sure I'm just missing something really obvious. Only really started using Docker in Dec so still a lot to learn.

**Comment by k9ert** [comment]
Sorry for the late reply. So here is a description of how that should work. When you don't have downloaded the image, starting the bitcoind should look like this:
```
➜  specter-desktop git:(master) ✗ . ./.env/bin/activate
(.env) ➜  specter-desktop git:(master) ✗ python3 -m cryptoadvance.specter bitcoind
    --> starting or detecting container
    --> Image with tag latest does not exist!
    --> Try to download first with docker pull registry.gitlab.com/cryptoadvance/specter-desktop/python-bitcoind:latest
(.env) ➜  specter-desktop git:(master) ✗ 
```
So after you do the docker pull-command, the same command should look like this:

```
(.env) ➜  specter-desktop git:(master) ✗ python3 -m cryptoadvance.specter bitcoind                                           
    --> starting or detecting container
    --> containerImage: ['registry.gitlab.com/cryptoadvance/specter-desktop/python-bitcoind:latest', 'registry.gitlab.com/k9ert/specter-desktop/python-bitcoind:latest']
    -->            url: http://bitcoin:secret@172.17.0.2:18443/wallet/
    --> user, password: bitcoin, secret
    -->     host, port: localhost, 18443
    -->    bitcoin-cli: bitcoin-cli -regtest -rpcuser=bitcoin -rpcpassword=secret getblockchaininfo 
    --> Now, mining a block every 15 seconds. Avoid it via --no-mining
    --> 01234
```

If that is not how it looks at your side, maybe you get a stacktrace when you Ctrl-C? You can also check whether your docker is properly running like this:

```
(.env) ➜  specter-desktop git:(master) ✗ docker run -it registry.gitlab.com/cryptoadvance/specter-desktop/python-bitcoind:latest echo hello world
hello world
(.env) ➜  specter-desktop git:(master) ✗ 

```
Sorry again for the late reply!

**Comment by k9ert** [comment]
Assuming that this is fixed. Please reopen if it's still an issue!
