### ISSUE TITLE
Fresh mac install: autodetect failed

### ISSUE THREAD

**Issue by LaserHodl** [cryptoadvance/specter-desktop#833]
After a brand new install of Bitcoin Core and Specter, I run into an unexpected issue.

* macOS: Catalina `10.15.7` 
* Bitcoin Core: `0.20.1`
* Specter: `0.10.4`

After Bitcoin Core has fully synced, I open Specter and test the connection and get: 

```
Process finished with code -1Error message: autodetect failed
```

Is installing the Bitcoin Core dmg on Mac not sufficient for Specter?
Is there some way I can test the connection to Bitcoin Core by hand?

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/76824110/103445282-e6d32e80-4c26-11eb-98ec-de52d445b425.png">
<img width="862" alt="image" src="https://user-images.githubusercontent.com/76824110/103445311-44677b00-4c27-11eb-964d-0e59976b7ed3.png">

**Comment by ben-kaufman** [comment]
Hi, have you added in the bitcoin.conf file server=1 ?
If not try to add that and restart.

**Comment by LaserHodl** [comment]
The Bitcoin Core dmg does not appear to include a `bicoin.conf` - 

```
Application Support/Bitcoin » pwd
/Users/user/Library/Application Support/Bitcoin

Application Support/Bitcoin » ls -la
total 333856
drwxr-xr-x    11 user  staff        352 Jan  1 11:47 .
drwx------+   79 user  staff       2528 Jan  1 11:39 ..
-rw-r--r--@    1 user  staff       6148 Jan  1 11:45 .DS_Store
-rw-------     1 user  staff          0 Dec 31 16:57 .lock
-rw-------     1 user  staff         37 Dec 31 16:57 banlist.dat
-rw-------     1 user  staff          5 Dec 31 16:57 bitcoind.pid
drwx------    29 user  staff        928 Jan  1 09:44 blocks
drwx------  2517 user  staff      80544 Jan  1 11:45 chainstate
-rw-------@    1 user  staff  166136600 Jan  1 11:47 debug.log
-rw-------     1 user  staff    3138694 Jan  1 11:47 peers.dat
drwxr-xr-x     7 user  staff        224 Jan  1 11:39 wallets
```

This might imply that the Bitcoin Core dmg is not sufficient, and in fact Bitcoin needs to be installed with `brew` or the like in order to get the `bitcoind` daemon and server config files...

What do you think?

**Comment by LaserHodl** [comment]
Ok, looks like you were right.

Opening the preferences in Bitcoin-Qt shows a "Open Configuration File" - <img width="728" alt="image" src="https://user-images.githubusercontent.com/76824110/103445461-31ee4100-4c29-11eb-900d-a8bc50169afa.png">

That appears to just create a new blank `bitcoin.conf`. I added `server=1` and saved: <img width="572" alt="image" src="https://user-images.githubusercontent.com/76824110/103445460-2c90f680-4c29-11eb-9c75-4fb9517c8b61.png">

After restarting Bitcoin Core and Specter Desktop, it appears to be able to successfully find the node. <img width="1264" alt="image" src="https://user-images.githubusercontent.com/76824110/103445481-606c1c00-4c29-11eb-92b2-34fb2906cbbc.png">

Thanks for your help @ben-kaufman!

**Comment by LaserHodl** [comment]
Suggestion: seems like it would be pretty easy for Specter to search the Bitcoin Core data directory path for a `bitcoin.conf` containing `server=1` and if it doesn't find it either alert the user to create it or, and potentially better, do it for them and trigger a restart of Bitcoin Core and then Specter Desktop.
