### ISSUE TITLE
Ledger multisig "unverified inputs"

### ISSUE THREAD

**Issue by djpnewton** [cryptoadvance/specter-desktop#834]
When signing a multisig tx with ledger it gives me a warning "unverifed inputs" and tells me to update the wallet software I am using

**Comment by BTCBellyButton** [comment]
That's unfortunately normal with the very bad (=0) multisig support by Ledger...
Also Ledger won't show you the receiving address in a multisig configuration...so no way to be sure the address is correct (99.9% of the time it will be correct unless some kind of malware infected your computer).
Not sure if Specter developers can mitigate the Ledger's problem in some way...

**Comment by djpnewton** [comment]
It seems like electrum managed to work around (or fix?) the issue: https://github.com/spesmilo/electrum/issues/6230

**Comment by k9ert** [comment]
When i get that right, you've addressed the issue in #885. Please reopen if necessary.

**Comment by IanMichaelHarper** [comment]
I get this error when using a singlesig Ledger Nano S, spending 1 UTXO to multiple outputs
