### ISSUE TITLE
Can't always view History/UTXO screens

### ISSUE THREAD

**Issue by statusquont** [cryptoadvance/specter-desktop#835]
It seems like there is a scenario in which the option to access the History and UTXO buttons are not visible -- possibly if the balance of a wallet is zero? The wallet does actually a history though. Even if I emptied the wallet it would still be nice to be able to edit labels for UTXO's so I can keep a record of everything. Right now it seems as if this isn't possible.

![sp2](https://user-images.githubusercontent.com/15948511/103483797-036b9400-4dea-11eb-8fce-c7630c17d600.png)
![sp1](https://user-images.githubusercontent.com/15948511/103483905-d4095700-4dea-11eb-9580-d5acdfffc858.png)
![sp3](https://user-images.githubusercontent.com/15948511/103483799-04042a80-4dea-11eb-9437-e2d1c8fcf82f.png)

**Comment by statusquont** [comment]
After further review, it might not be the zero-balance. I sent some funds in, and the balance showed the correct >0 value, but I still didn't see the History/UTXO buttons. The tx only had 1 confirmation, fwiw. I then manually edited the URL in the browser to view the UTXO page for that wallet in question, and it did load just fine, and I was able to modify the UTXO label. Then, when I returned to the default view for that wallet, it did show the two buttons as I expected. So now I'm really unsure why they weren't available initially.

**Comment by ben-kaufman** [comment]
Hi, can you please check if that's still an issue with the pre-release?

https://github.com/cryptoadvance/specter-desktop/releases/tag/v0.11.0-pre6

**Comment by ben-kaufman** [comment]
Hi, this should be solved with v1.0.0, can you please try and confirm @statusquont?

**Comment by statusquont** [comment]
I'm using Specter on myNodeBTC and they haven't pushed the latest version yet. I'm not sure how to do a manual upgrade of individual software packages. If you want to close the issue anyways, please do feel free.

**Comment by ben-kaufman** [comment]
I think this can be closed now. Please reopen if still relevant.
