### ISSUE TITLE
[REQUEST] Homebrew support?

### ISSUE THREAD

**Issue by LaserHodl** [cryptoadvance/specter-desktop#836]
Wouldn't it be really nice for brand new users to be able to do something like:

```
brew install tor bitcoin specter
```

That would open the door to scripts that automated launching the three configured correctly.

Let me know if this feature request belongs in Discussions instead.

**Comment by sirpesto** [comment]
I made the pull request for adding specter to brew. 
https://github.com/Homebrew/homebrew-cask/pull/104820

**Comment by sirpesto** [comment]
The process threw an error on `livecheck` because [early releases](https://github.com/cryptoadvance/specter-desktop/releases?after=workshop%2Fstep12) are called `workshop/stepXX` and they are parsing it as bigger versions than the current version scheme. I will remove `livecheck` for now until the naming scheme is resolved. But we can update the specter cask manually in the meantime.


```brew livecheck specter --debug
git config --get homebrew.devcmdrun

Cask:             specter
Livecheckable?:   Yes

URL:              https://github.com/cryptoadvance/specter-desktop/
URL (processed):  https://github.com/cryptoadvance/specter-desktop.git
Strategy:         Git

Matched Versions:
0.0.1-alpha, 1.2.1, 0.0.2, 0.1.0, 0.1.1, 0.1.2, 0.10.0, 0.10.0-pre1, 0.10.0-pre2, 0.10.0-pre3, 0.10.0-pre4, 0.10.0-pre5, 0.10.1, 0.10.1-pre1, 0.10.2, 0.10.4, 0.11.0-pre1, 0.11.0-pre2, 0.11.0-pre3, 0.11.0-pre4, 0.11.0-pre5, 0.11.0-pre6, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.4.3, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3-pre1, 0.7.3-pre2, 0.7.3-pre3, 0.8.0, 0.8.1, 0.8.1-pre2, 0.8.2-pre1, 0.8.2-pre2, 0.8.2-pre3, 0.9.1, 0.9.2, 1.0.0, 1.1.0, 1.1.0-pre1, 1.1.0-pre2, 1.1.1-pre1, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.3.0-pre1, 1.3.0-pre2, 1.3.0-pre3, 1.3.0-pre4, 1.3.0-pre5, 1.3.0-pre6, 1.3.0-pre7, 1.3.0-pre8, 1.3.0-pre9, 1.3.1, 1.3.1-pre2, 07, 08, 11, 12
specter : 1.3.1 ==> 12

**Comment by sirpesto** [comment]
This should solve the issue.
https://github.com/Homebrew/homebrew-cask/pull/104820/commits/2cea2a20bf421c6d03f4401fdf3f06d81e8fb673

**Comment by ben-kaufman** [comment]
Thanks @sirpesto ! Tried it and works great!

**Comment by sirpesto** [comment]
@ben-kaufman pr is merged, issue can be closed. :)
