### ISSUE TITLE
Fetching transactions takes a long time [v0.11.0-pre4]

### ISSUE THREAD

**Issue by BTCBellyButton** [cryptoadvance/specter-desktop#838]
I'm testing the v0.11.0-pre4. Very cool improvement!
I also went to see how the transactions grouping is working and it's great for most of the regular wallet with not too many transactions but when the number of transactions is high, the fetching is extremely slow.

![image](https://user-images.githubusercontent.com/68573637/103488498-9f89a100-4dd2-11eb-8771-f239809c3b2a.png)

![image](https://user-images.githubusercontent.com/68573637/103488488-8e409480-4dd2-11eb-861a-6ba0fcb46da6.png)

Also navigating through the pages is very slow:
![image](https://user-images.githubusercontent.com/68573637/103488622-b8468680-4dd3-11eb-8ec6-068135d0dea3.png)

Running specterd on remote linux 20.04.1 LTS
RAM 15.6GB
Intel Core i7-4700MQ CPU @ 2.40GHz x 8

**Comment by ben-kaufman** [comment]
Ho, could you please try out #839 and see if that helps?

**Comment by BTCBellyButton** [comment]
Is it included in the new release? I'll be testing that as soon as possible!

**Comment by ben-kaufman** [comment]
Yes that's in the new release, let me know if that works

**Comment by BTCBellyButton** [comment]
As fast as Lightning!   :D

Great job guys!!!   Thanks!
