### ISSUE TITLE
"download specter backup files" no longer works for me in 0.10.4

### ISSUE THREAD

**Issue by riannom** [cryptoadvance/specter-desktop#840]
for some reason, the "download specter backup files" no longer works for me in 0.10.4.  I was able to do it before in 0.10.3 I believe.
It fails with "failed - network error" in the downloads in Chrome.

Thanks for any help!

**Comment by ben-kaufman** [comment]
Hi, any luck on v1.0.0?

**Comment by riannom** [comment]
hi ben,
strangely it's still broken for me on 1.0.0.  upgraded, rebooted pi, no luck.  same exact symptoms, "failed - network error" in downloads in Chrome.  love the rest of the improvements in 1.0.0 though!

**Comment by riannom** [comment]
interestingly enough, it works for me on Firefox so maybe it's something that changed for me in Chrome (extension, firewall, etc.).  I don't think anything major has changed on my end but i'll poke around more to see what's going on.

**Comment by riannom** [comment]
Super weird.  I tried different computers using Chrome and still the same problem.  On both of the computers I can download other files off specter like device multisig import files, multisig backup pdfs but just not the specter_backup.zip file.  Both computers can download the backup zip file using Firefox oddly enough.

**Comment by k9ert** [comment]
I assume this is solved with #1005 . Please reopen if necessary.
