### ISSUE TITLE
Failed connecting to the node

### ISSUE THREAD

**Issue by harryhorss** [cryptoadvance/specter-desktop#845]
Bitcoin Core config: RPC Username and Password is set with setting server=1 

Running v0.10.4 with bitcoin core and upon first start up NODE auto detection has failed in the original pregenerated AppData location. I switched the location to the correct place and still getting error (I'm running bitcoin core that is fully synced with the data/blocks being hosted on an external HDD under E:\. )

Error on start for auto sync failure: "Wallets are unavailable if Specter is not connected to Bitcoin Core!"
Bitcoin Core unavailable click to sync

After entering the details manually for my node, it continues providing the red error at the top: Failed connecting to the node

I've attempted entering numerous things into host field none redeeming any results: localhost, my public IP and my static internal IP and the same error occurs: **Failed connecting to the node**

If you've run into the issue I'd love to know how you got around it!

I've tested it on the new version v1.0.0 and also throwing the same error. QR code sync option does not respond when I click it
[Image of my client and node info to confirm](https://i.imgur.com/bqT5dfQ.png)
Cheers

**Comment by harryhorss** [comment]
I've relocated to linux and will try running this through umbrel which should hopefully resolve the issue. I am unable to further troubleshoot on windows

**Comment by stepansnigirev** [comment]
Sorry for a late reply...
You could try disabling autodetect and providing rpcuser and password in the Specter config page.
Another thing to try is to open localhost:8332 in the browser and check if it's reachable.
