### ISSUE TITLE
No Transaction History showing in 3/5 multisig after upgrading to 1.0

### ISSUE THREAD

**Issue by MauiLiam** [cryptoadvance/specter-desktop#850]
Hi guys - just upgraded to 1.0.  All my wallets and devices showed up fine, but my 3/5 multisig shows no transaction history.  I went and re scanned the block chain - still nothing.  The next address is showing address 6 which is correct.  And when it shows the past addresses, all looks good.  But after re scan - no transaction history showing.
<img width="876" alt="Specter_Desktop" src="https://user-images.githubusercontent.com/55666499/103955626-d3263d00-50ea-11eb-93fb-b148c693b373.png">

**Comment by stepansnigirev** [comment]
Can you check if this wallet has balance in Bitcoin Core?
If you are using Bitcoin-QT then you can just switch to the wallet and see, if you are using bitcoind then you can make a `getbalances` cli call.

**Comment by MauiLiam** [comment]
Hi Stepan - there is no balance in this wallet.  This was a test wallet.  What's interesting is that when I re created the multisig wallet in Specter from scratch by re assembling the five hardware devices, then the entire transaction history shows up perfectly.  
![Specter_Desktop](https://user-images.githubusercontent.com/55666499/104048746-dae7ef00-5187-11eb-9cef-d07eba99e310.jpg)

**Comment by MauiLiam** [comment]
Ahhh - in Bitcoin core, the transactions and wallet are there.  I noticed in the original 3/5 wallet that is not showing up there's this weirdness in bitcoin core:  (I've not seen this before?)
![Bitcoin_Core_-_specterc776103da708037a_elima_multisig](https://user-images.githubusercontent.com/55666499/104049825-aecd6d80-5189-11eb-9702-1cc5f656d6f0.jpg)
