### ISSUE TITLE
2-of-3 multisig history all showing "Unconfirmed" after 1.0

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#851]
History had previously shown correct confirmation counts prior to v1.0. Tried a wallet rescan via the UI but still shows everything as "Unconfirmed". Individual transactions are all listed as expected (aside from being displayed as unconfirmed). If I click into a transaction it says "Mine at block: undefined" but all other info is correct (tx id, size, Block hash, Block time, Inputs/Outputs).

Wallet is in an isolated user login within Specter.

Seeing this same issue in all my 2/3 multisig wallets.

Connection to my node running on the same machine has no complaints. Full node, no pruning, indexing enabled.

**Comment by moneymanolis** [comment]
Same issue after upgrade to v1.0 , single sig, using specterd on Linux, tested with version 0.10.2 again and the issue disappears, not sure whether there were any relevant changes on that end but my Core version is v0.19.0.1.

**Comment by moneymanolis** [comment]
Cross checked with pip install on Mac using regtest, confirmations show up correctly.

**Comment by kdmukai** [comment]
I'm also on v0.19.0.1. Running on raspbian.

**Comment by ben-kaufman** [comment]
Can confirm the issue is with Core v0.19.0.1, will try to see why and fix it. Meanwhile, you could upgrade Core to v0.20 and that should work.

**Comment by ben-kaufman** [comment]
Found the issue. It appears that Bitcoin Core v0.19 doesn't return the blockheight as part of the gettransaction command, which currently breaks Specter blockheight caching and tx details display. I fixed both in #851, which should make this work.

**Comment by ben-kaufman** [comment]
@kdmukai @moneymanolis if you could test it and confirm that would be very helpful.

**Comment by moneymanolis** [comment]
Will do!

**Comment by moneymanolis** [comment]
Fix works here. Confirmations are displayed now.

**Comment by kdmukai** [comment]
Fix looking good!

Sorry for the delay (it's taken a while to get my dev setup in my M1 MacBook in proper working order).
