### ISSUE TITLE
Specter desktop stuck on startup Mac OS

### ISSUE THREAD

**Issue by ohnoh1** [cryptoadvance/specter-desktop#856]
tried to install with app & PIP, either way get stuck on startup

for app, stuck on Pacman screen "Launching Specter Desktop"

from cmd line, stuck on "initializing HWI"

left desktop running for several hours without change

using Mac OS Big Sur 11.1 with Specter v1.0.0 & v0.10.4

**Comment by ben-kaufman** [comment]
Hi, I think I've seen such an issue when a Ledger was connected to the computer while trying to start Specter, maybe that's the case?

**Comment by ohnoh1** [comment]
Thanks, no Ledger connected. Intend to use airgapped HW wallet

**Comment by ben-kaufman** [comment]
Hi, sorry for the late response. Is this still an issue? I checked on Big Sur myself but seems to work fine... Can you maybe share a screenshot from the command line run? Or is it really just `Initializing HWI` and nothing else?

**Comment by ohnoh1** [comment]
No worries. I ran it on a clean install of Big Sur and it worked, maybe its a conflict with another program/process.

**Comment by ben-kaufman** [comment]
ok thanks, so I'll close this for now.
