### ISSUE TITLE
Wallet Error

### ISSUE THREAD

**Issue by mcsnubbs** [cryptoadvance/specter-desktop#86]
I was able to use the software without issue until my node finished syncing, at which point it returned this browser error

cryptoadvance.specter.rpc.RpcError
cryptoadvance.specter.rpc.RpcError: Server responded with error code 500: {"result":null,"error":{"code":-18,"message":"Requested wallet does not exist or is not loaded"},"id":0}

Opening/closing wallets in CORE does not seem to effect it. Any ideas?

**Comment by stepansnigirev** [comment]
Can you try deleting wallets folder in `~/.specter` folder?
I think somehow Bitcoin Core forgot about one of the wallets and specter can't load it now. I will try to fix this issue tomorrow.

**Comment by mcsnubbs** [comment]
Thank you - ill give it a shot. Tried uninstalling specter/reinstalling but for some reason it says the package isnt available

**Comment by mcsnubbs** [comment]
Removing the wallet file worked. However, after recreating the wallet (multisig), it shows 0 balance although one of the addresses contained by this multisig has valid UTXOs. I’m currently connected to a core client which is synced. Does it need to rescan for valid UTXO’s or is that happening in the background/needs time?

**Comment by stepansnigirev** [comment]
Yes, you need to rescan - you can go to settings of the wallet and start rescan. You can set the start block there, so no need to rescan everything.

**Comment by mcsnubbs** [comment]
I get the following error when I go to wallet settings in Specter:

AttributeError
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by stepansnigirev** [comment]
Ah... Interesting... I will try to fix it.
Meanwhile you can rescan using command line.

**Comment by stepansnigirev** [comment]
Should be fixed now, if it's not please reopen the issue.
