### ISSUE TITLE
Wrong input address in PSBT preview

### ISSUE THREAD

**Issue by MyNameIsOka** [cryptoadvance/specter-desktop#864]
I noticed just now that an unsigned transaction for a multi-sig wallet in Specter showed the wrong input address.

The transaction I created consisted of 1 input and 1 output.
The input correctly showed that output #0 will be used for the transaction, but the shown address was actually from output #1.
The created PSBT was correctly shown in the hardware devices with the address of output #0.

So this seems to just be something visual in Specter.

**Comment by ben-kaufman** [comment]
Hi, thanks for reporting, you're right. It was so far implemented to take just the first vout instead of the one corresponding to the input. Fixed it in #865

**Comment by MyNameIsOka** [comment]
Awesome, thank you!
