### ISSUE TITLE
Show change addresses

### ISSUE THREAD

**Issue by djpnewton** [cryptoadvance/specter-desktop#874]
Specter Desktop allows one to see their receive addresses but not their change addresses.

It would be nice to be able to see the change addresses so we can confirm the change address shown on a hardware wallet (see #834)

**Comment by ben-kaufman** [comment]
Hi, the next version of Specter will include an Addresses tab where you can see the change addresses as well. However, this is NOT secure and there is hardly any point in using it for verification. An attacker that swapped the addresses sent to the device could as easily swap it on you laptop. You shouldn't trust the computer when using hardware wallets. Rather, change verification should be done by the hardware wallet itself on signing. Ledger doesn't support that for multisig, but verifying on Specter won't make this more secure, the best thing is to not use Ledger for multisig.

**Comment by djpnewton** [comment]
Yeah I realize it's not secure. I think multisig change verification risks should be better documented ( see #875) as I don't think they are well known (I am just learning about them myself)

**Comment by ben-kaufman** [comment]
Ok I see, so I think this issue can be closed though since showing change addresses is already merged in master, and we can discuss the doc of this in #875
