### ISSUE TITLE
PDF backup should include Zpubs as well?

### ISSUE THREAD

**Issue by mmikeww** [cryptoadvance/specter-desktop#876]
`Wallet -> Settings -> Export -> Save Backup PDF`

This saves all the info to your computer, but it saves each cosigner's xpub key. Should this file also include the Zpub key as well? For easier verification when cross referencing against other hwwallets which may show that format instead. And also even in specter itself when you click on the respective Device from the left menu, which shows the Zpub

**Comment by ben-kaufman** [comment]
Hi, Zpub option for the PDF was merged already in #849 so will be available from the next release

**Comment by mmikeww** [comment]
perfect, closing this
