### ISSUE TITLE
UX Feedback: "Add Keys" and "Purpose"

### ISSUE THREAD

**Issue by D4nte** [cryptoadvance/specter-desktop#881]
I am trying to add and name new account for ledger nano s.

1. Click on "Devices > Ledger Nano S" in side bar
2. Click "Add more keys"
3. Click "Edit"
4. Click "Add custom derivation"
5. Enter derivation path and "purpose"
6. Click "Add"
7. Click "get via USB" to import the xpubs
8. Click Done (see screenshot below)
9. At this point it looks good. I see no way to "finalize" the work so I click back to "Devices > Ledger Nano S".
10. expected: new key is visible. Actual: All changes were reverted (see screenshot)

Edit: I now understand that on step #9 I should click on "Add Keys". This is really unclear (I went trough the process 10 times yesterday and today before realizing that).

I suggest to either change the colour of "Add Keys" to Blue so that it is highlighted as a finalise button.
Or, you could number the steps: 1. edit, 2. Get via USB, 3. Add keys

Also, the "Purpose" is a free text field that can be edited by the user. I tried to use this text as a way to label my keys.
But actually, "Purpose" is the type of addresses to be used with this account (segwit native vs segwit nested). This is also very confusing.

I would suggest to rename it to "Address Type".
Also, I would suggest to not make it an editable free text field as you do not let the user choose it when using ledger nano s.
If there are situations where the user can select what address type they want then put a dropdown list instead.

Looks good once account is added:
![specter-upload-keys](https://user-images.githubusercontent.com/300805/104856289-fad89900-5965-11eb-9f35-f0b135f90fef.png)

Actually no, it disappeared:
![ledger nano s](https://user-images.githubusercontent.com/300805/104856286-f90ed580-5965-11eb-9c43-c5c81484e53f.png)

**Comment by D4nte** [comment]
After more thoughts on the matter, I'd like to propose some improvements.

To import new xpub keys from a device, the user must follow this sequence:
- Specify derivation paths
- Import extended public keys from ledger
- Save the public keys against the device to later create wallets from them

Currently, there are a number of confusing elements with the current screen.

In the device landing screen I can see 5 keys. From this screen I can delete individual keys.
It also shows the wallets using this device. However, it does not show which key is used for which wallet. Knowing that a wallet uses a unique derivation path, it would make sense to put the wallet names and links directly in the table. Today, if I click `remove` I am uncertain whether I am removing a path related to an existing wallet.

**Suggestion**: In the device landing page, add wallet names/link in the table to correlate them to the derivation path they use.

Then, if I click `add more keys`, the new screen is pre-filled with 4 keys.
Some of these keys were already imported, it is confusing that they are displayed in the "add key" flow.
Also confusing that only some of the already imported keys are displayed, not all of them.

I understand these are the default keys that should be used for single sig/multi sig (segwit or nested).

**Suggestion**: The `add keys` screen should only displays derivation paths which are **not** yet imported.

Then, you have 3 buttons:
- edit
- get via usb
- add keys

If you click `Add keys` then you get an error: `xpubs name must not be empty`.
If `Add Keys` is not a valid action then the button should not be displayed.

**Suggestion**: Do not display or grey out the `Add keys` button until all paths have their xpub loaded.

If you click `Get via USB`, it loads the xpubs from the device. Once done, you can click again on `Get via USB` even though all xpubs are loaded.

**Suggestion**: Do not display or grey out the `Get via USB` button if all displayed paths have their xpub loaded.

The `Add account` button allows you to add 4 new derivation paths: Single Sig nested, single sig segwit, multi sig nested, multi sig segwit. It adds all 4 of them. Is that what a user would like to do? I don't believe so.

As a user, I want to create a new wallet from my ledger. I want to setup a new segwit multi-sig wallet.
When going through the `Add new wallet` flow, I realize that I already used all the ledger keys I imported.
So I go to the device flow: `Ledger Nano S > Add more keys`.

I then have to click
1. `Edit`
2. `Add account`
3. Select the **right** number (by default, `0` is proposed even if I already have loaded all the keys for account 0)
4. `Add account`. This adds 4 new keys to the table.
5. I now need to go and `remove` the keys I don't intend to use. Maybe I only use multisig and don't want to encumber by device setup screen with useless single sig derivation paths.
6. `Done`
7. `Get via USB`
8. `Add Keys`

Step 3 is non-intuitive: I have to think/check for which account number I haven't yet loaded a segwit multi sig key.
Step 5 is cumbersome and should not be necessary.

**Suggestion**: Do not preload default keys of account 0 in Add Keys screen

**Suggestion**: Replace the `Add account` and `Add custom derivation` buttons with a single (`Add path`?) button. This button should propose the following option:
- drop down list to choose between `single sig nested`, `single sig segwit`, `multi sig ..`
  - This should default to the latest unload path
- Advance option to pass a custom path

I hope this helps.

**Comment by alevchuk** [comment]
This part of the UI is confusing indeed. Also the title "Upload Keys" is confusing (i suppose it means download from hardware wallet to Specter; yet it reads like "upload to hardware wallet").

**Comment by ben-kaufman** [comment]
Hi, so regarding the purpose being overwritten, this is a bug I fixed in #887 

Regarding deleting keys, you won't be able to delete a key used in a wallet, Specter will give an error popup with which wallets it's used in, does that sound good enough in that regard?

Regarding the Add Account option, I do think it's convenient to have the option to add all the standard keys of a certain account with one button, since adding paths one by one is quite annoying imo. I do like the idea of having dropdown for default paths etc.

So I guess we need to put there some more work to improve that. Would be very helpful if you'd like to help with sketching out the suggestions visually on the UI screenshots or something if you have some design experience, would make it much easier for me it implement when I can look at how it should be eventually.

**Comment by k9ert** [comment]
Please have a look at the new UI which is currently in pre-release and will shortly be released as `v2`. Closing this for now.
