### ISSUE TITLE
"Here we only show and General keys. Follow the standards."

### ISSUE THREAD

**Issue by D4nte** [cryptoadvance/specter-desktop#882]
Looks like the `purposes` array can be empty as when I go through to add a new wallet for my ledger wallet, I can see "Here we only show and General keys. Follow the standards."
This is when either "segwit" or "nested segwit" are selected.

https://github.com/cryptoadvance/specter-desktop/blob/e4e85b285f89942913ff59944df5340829015716/src/cryptoadvance/specter/templates/wallet/new_wallet/new_wallet_keys.jinja#L177

**Comment by ben-kaufman** [comment]
Should be fixed in v1.2.2
