### ISSUE TITLE
API to create unsigned transaction

### ISSUE THREAD

**Issue by nicolasburtey** [cryptoadvance/specter-desktop#895]
I've started using specterd for a community wallet (for the [Bitcoin Beach](https://twitter.com/Bitcoinbeach) community, the wallet will soon be open sourced) and we are starting to use specterd + bitcoind to store the majority of the funds in a multisig where the keys are shared within the community.

When there is a rebalancing need, I would like to automatically create a transaction in specterd so that the different parties could log in on the specterd server and add their signature.

Right now (AFAIU) a manual intervention is necessary to first create the transaction. That would be great to be able to automate the transaction initiation step with an API. (like a `bitcoind.createpsbt()` but with specter)

Having an API like this would enable the use of specterd for more complex multisig set up that is used by "multi parties".

**Comment by ben-kaufman** [comment]
Hi, thanks for the suggestion, I think that'd make sense to have. We currently have a WIP PR to add an API for Specter, so probably after that is done we could add this functionality as well.

**Comment by nicolasburtey** [comment]
Awesome. 

Just to make sure the use case is clear: we can easily have the past transactions/balance by fetching the api from bitcoin core directly. What would be helpful is to expose functionality that Specter adds as a coordinator that is not present in bitcoin core

**Comment by nicolasburtey** [comment]
now that the Galoy/Bitcoin Beach wallet is fully open source, here is where this would be useful: https://github.com/GaloyMoney/galoy/blob/c8f3c94486cbb77ccfee3a73c783ca982d5bfd8b/src/SpecterWallet.ts#L119

when there is a rebalancing needed from cold storage (specter) to hot storage (lnd), this would be useful to have a unsigned transaction created programmatically to initiate the coordination process of multi sig among the participants.

**Comment by k9ert** [comment]
Really happy to hear that this helps over at your place! We definitely had some confusion going forward with our API-approach. I reopened the PR some time ago and i'm planning to get that going very soon. 
https://github.com/cryptoadvance/specter-desktop/pull/713

**Comment by k9ert** [comment]
#713 is dead, long live #1232 . Naah, just kidding, hopefully i'll finish that one soon.

**Comment by k9ert** [comment]
Released in v1.5.0
Any feedback highly appreciated
