### ISSUE TITLE
Scanning QR Codes does not work

### ISSUE THREAD

**Issue by anomeitor** [cryptoadvance/specter-desktop#904]
Hi, I am trying to upload the keys of a new device (Specter DIY) but I am unable to scan the QR-Code.  I am using Specter-desktop v. 1.0.0 in a Windows 10 desktop.  I have tried with Chrome v. 88 and Firefox v.84 with no result.  I've also checked that the camera is working through the brower in other sites.   When I click on the "Scan QR code" button, i get no response at all, not even asking me for permission to use the camera (I also configured the browser not to ask for permssion with no success).

I feel like I am missing something silly, but after trying a lot of things I am stuck with this problem, so I decided to open this issue.

**Comment by ben-kaufman** [comment]
Hi, have you tried with the desktop app itself? So you're sure you have the camera properly connected but clicking to scan doesn't open it?

**Comment by anomeitor** [comment]
Thanks Ben for your quick response.  I am trying with the desktop app within the browser (see screenshot below).  Is there another way to run the desktop app?

![image](https://user-images.githubusercontent.com/77966947/105700527-43192d80-5f09-11eb-905d-07ceee28b2bc.png)

**Comment by anomeitor** [comment]
I've just tried with the desktop app, and I have the same problem.  When I click scan QR it does nothing, no error message, just nothing.

**Comment by anomeitor** [comment]
I am going to try with a different webcam.  I´ll have the new one t.omorrow

**Comment by anomeitor** [comment]
I have tried today with a new webcam and no result.  The webcam works perfectly right on Electrum, but I get no reaction at all on specter desktop.  Is there specific log or debug file that I should look at?

**Comment by gogomickey** [comment]
I have the same issue.  However, neither the qr code nor the export to sd card works.   For the QR code specter seems to acknowledge "seeing" the QR code but no info is exported.   With the file there is no acknowledgement of anything happening.   Any ideas?

**Comment by ben-kaufman** [comment]
@anomeitor which OS are you using? Might be that you need to give the app permission to access the camera.

@gogomickey that sounds like a different issue. Where exactly do you take the file/ QR from on the Cobo and where in Specter are you adding it? Also, which Cobo version and is that the BTC Only firmware? (we only support that one).

**Comment by anomeitor** [comment]
I am using Windows 10 pro 64bits.  On the camera privacy settings everything is enabled.  Allow desktop apps is enabled, however specter desktop is not shown in that section (electrum and chrome are shown as enabled).  I haven't found a way to manually add specter in the desktop apps section.  When I run specter in chrome browser it does not work either, despite the camera working correctly in other websites.

**Comment by gogomickey** [comment]
I take the file/QR from the "export wallet" option in the settings and I have my wallet designated as a "Generic Wallet" under the "watch-only Wallet menu. I am trying to add it under "add device" in Specter.  I am using the Cobo Vault essential and am running firmware version 2.3.1 (btc only).  Adding a device worked perfectly for the Ledger and the Cold Card.  

On a different note I love Specter Desktop it has been a game changer for UX.  Keep up the good work.

**Comment by ben-kaufman** [comment]
@anomeitor really strange, maybe try restarting the machine? Haven't seen such issue before so hard to say.

@gogomickey I just noticed that the Cobo files aren't compatible with the Specter format, so that won't work currently. However, scanning the QR code should work well. What happens exactly after you scan it, just nothing?

**Comment by anomeitor** [comment]
I have restarted several times with no luck.  Is there some log or debug file I could look at?

**Comment by gogomickey** [comment]
Yes.  I had a feeling the .txt file that Cobo exports was part of the problem.   I have opened an issue with them.   The QR code seems to be recognized by the camera but no info is exported.   Now, I use Specter as part of mynode so I'm always accessing the camera "remotely" through another machine.  Either through the Web GUI within my network or through tor. I'm operating an instance of Specter on my desktop to interface with the instance on mynode.   I understand the difficulty in getting the QR codes to scan remotely over Tor but I figure it should work through the Web GUI "locally" within the same network.   Thanks for the help.

**Comment by anomeitor** [comment]
As an alternative while we work out the camera and QR issue, is there an alternative way to export the xpubs from the specter DIY to the specter desktop?  Maybe using the SD Card?

**Comment by ben-kaufman** [comment]
Only via USB I think. Or you could scan with some QR scanner website and paste the result in Specter setup (I think you'll need to select the device type as "Other" to have paste option, but then you can change it to Specter DIY from the settings)

**Comment by anomeitor** [comment]
> scan with some QR scanner website

Good idea, but not in a website (xpub!!).  Do you know any QR scanner that is trustworthy (opensource, pgp signed, etc)

**Comment by stepansnigirev** [comment]
Maybe you can open Specter web interface in the browser and scan there?
While Specter App is running navigate to http://localhost:25441 and you'll see Specter web interface that is exactly the same as in the app.

**Comment by anomeitor** [comment]
I tried first with the web interface, and then as Ben suggested I tried the desktop App.   The strangest thing about the web interface not working is that other websites work perfectly fine with the camera.

**Comment by stepansnigirev** [comment]
The most well-known QR scanning app is zbar: http://zbar.sourceforge.net/
I don't think they pgp-sign the releases though... It may be available in the windows store as well.
Can you open the developer console and check the error messages there when you try to scan in the browser?

I'll work on SD card support on DIY in one of the next releases, but it will take some time.

**Comment by anomeitor** [comment]
> I'll work on SD card support on DIY in one of the next releases, but it will take some time.

Great news. Thanks!  It suprised me a bit that you had SD card support for Coldcard but not for Specter DIY.

**Comment by k9ert** [comment]
Is this still an issue for you? Which version are you on currently?

**Comment by k9ert** [comment]
Just stumbled over #705 which might be another reason why the QR-scanning does not work for you. Can you please check?

**Comment by k9ert** [comment]
closing it for now.
