### ISSUE TITLE
I can't add cobo vault devices by importing files, but scanning the QR code is fine.

### ISSUE THREAD

**Issue by caixiao-QA** [cryptoadvance/specter-desktop#906]
cobo vault version:2.3.5
specter version:1.0.0(testnet)

I can't add cobo vault devices by importing files, but scanning the QR code is fine.

QRcode:
![1](https://user-images.githubusercontent.com/37337093/105794189-77eaba80-5fc5-11eb-9c82-304b3bcbf2e2.png)

pubkey file:
[p2wpkh-pubkey.txt](https://github.com/cryptoadvance/specter-desktop/files/5870916/p2wpkh-pubkey.txt)

**Comment by ben-kaufman** [comment]
Hi, looks like Cobo export is in some format we don't support. I didn't notice that until now, not sure if they changed it or if I forgot to check that... Anyway we probably should support it (or ask them to change the format). If you don't mind, I'll close this issue and open another one instead to describe what should be implemented (#910)
