### ISSUE TITLE
"Send max" is shorting the amount by 1 sat

### ISSUE THREAD

**Issue by mmikeww** [cryptoadvance/specter-desktop#907]
"Available Funds: 0.04985 BTC"

Click "send max" uses 0.04984999

I manually type in 0.04985 and the txn works

Maybe a floating point error?

**Comment by mmikeww** [comment]
FWIW other times "send max" worked correctly and didn't short it

**Comment by ben-kaufman** [comment]
Hi, I think we now reduce 1 satoshi from the max send as sometimes it's needed for the fees. I see why it's confusing though, I'll try to see if there's a better way...

**Comment by djpnewton** [comment]
Is this to cover a possible floating point inaccuracy of the JS when calculating the maximum spendable amount? Or something else?
