### ISSUE TITLE
Support Cobo Vault import xpub with microSD

### ISSUE THREAD

**Issue by ben-kaufman** [cryptoadvance/specter-desktop#910]
Seems like the format Cobo uses isn't compatible with what we currently support.

Here are example files from Cobo to test with:
[Cobo export xpub.zip](https://github.com/cryptoadvance/specter-desktop/files/5878901/Cobo.export.xpub.zip)

**Comment by ChristopherA** [comment]
I encourage you to discuss interoperability standard issues in the Airgap Wallet Community so we can all benefit.

**Comment by ben-kaufman** [comment]
@ChristopherA  Is there an active discussion there already on the file export formats or should I open one?

**Comment by ChristopherA** [comment]
> @ChristopherA Is there an active discussion there already on the file export formats or should I open one?

@wolfmcnally just completed first alpha  implementation of the UR crypto-hdkey export, but it needs more testing.

it looks something like: 

![EC2C391B-921D-4821-A0D9-7EE256054F62](https://user-images.githubusercontent.com/69103/106332849-6828db80-623c-11eb-8a63-bd441899f8fb.png)

which renders to

`ur:crypto-hdkey/onaxhdclaxylahbdjshedknlckwzbblfjprtghwddegefersesioeetdtsasuejeiylerfeewzaahdcxuedtbwdkmtkkkiatktsrmnoysfwsmednfsvtjspkmncycwuedsdlqdptlacsknadahtaadehoyaoadamtaaddyotadlocsdyykadykaeykaoykaocymhaycmmtaxaxaycywkoelkseceroglvl`

and is equivalent to: 

`[90081696/48h/1h/0h/2h] tpubD6NzVbkrYhZ4YYucCR8FWtDFKF3nPv2pcvKvgBJsQDWtEGuwsH8eXTqshGM1fGPrg1UyvpRZ9NiRAeSUUksGKyp8xZ3ZdegJ6EU9hC7gBJk`

you might ask “why not just share in the the partial descriptor / base64 form?” 

Four reasons:

* though it may look larger in text, in a QR it is more compact to take advantage of QR compression.
* the UR form is completely self describing, so you can append meta data (such as label, key birthdate, holder of key information, etc.) 
* This UR can embedded inside other URs, such as a much larger descriptor. Currently rendering large multisig descriptors (what we call Account Maps) can exceed QR size limits. URs natively support animation when they get too large. 
* everything is composable, and you can have metadata at multiple levels. Any level can be encrypted or secret shared, allowing for say an xprv to be socially recoverable. 

I hope that we’ll be posting live demos, reference code, and some UX discussion for how to use in multisig scenarios next week.
