### ISSUE TITLE
1.1 download links are broken on github releases page

### ISSUE THREAD

**Issue by mmikeww** [cryptoadvance/specter-desktop#922]
1.1 download links are broken on github releases page

the binary executables

**Comment by ben-kaufman** [comment]
Hi, yes the release isn't ready yet, the automated builds are currently running, but it'll take a few more minutes

**Comment by mmikeww** [comment]
ok now all of the links work, except the Desktop client on Windows

looks like its linking to a 1.0 filename instead of 1.1

**Comment by k9ert** [comment]
Thank you! fixed.

**Comment by ben-kaufman** [comment]
Out now, should be fine, closing :)
