### ISSUE TITLE
Version update fails to start on Windows - old specterd doesn't close properly

### ISSUE THREAD

**Issue by mmikeww** [cryptoadvance/specter-desktop#923]
I get this error upon startup:

"Specter Desktop encounter an error:
Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error."

I don't know how to check renderer console. Instead, I use the menu for `View -> Toggle Developer Tools` then click `Console` and I see "Uncaught SyntaxError: Unexpected identifier   splash.html:4"

Windows Specter Desktop. Close reopen and same thing happens

**Comment by ben-kaufman** [comment]
Hi, can you please try to restart the computer and retry?

**Comment by mmikeww** [comment]
interesting, yes rebooting worked

**Comment by ben-kaufman** [comment]
Yes quite strange, we had another user reporting the same issue. I'll keep this open for now and just change the title a bit and will try to see if I can reproduce that.

**Comment by hodlnym** [comment]
Restarting probably isn't necessary - it would be enough just to kill all stuck specterd.exe instances from previous run(s).

I'm pretty sure this is the same problem as described in #772, I've just tried it and the behavior stays the same in both v1.0 and v1.1

**Comment by k9ert** [comment]
Closing this as a duplicate of #772
