### ISSUE TITLE
Zpubs are shown, but SLIP132 toggle is off

### ISSUE THREAD

**Issue by mmikeww** [cryptoadvance/specter-desktop#924]
multisig wallet -> settings -> wallet info -> scroll to bottom click "Show key details" 

on the first open, by default, Specter is showing Zpubs, but the SLIP-132 toggle button above is defaulted to off

so either that toggle should be turned on by default, or Specter should display xpubs instead of Zpubs

**Comment by ben-kaufman** [comment]
HI, you're right, very annoying mistake, fixed in #925 now
