### ISSUE TITLE
Typo: Sign messsage with Bitbox

### ISSUE THREAD

**Issue by frandani82** [cryptoadvance/specter-desktop#926]
There is a typo with the BitBox02 on the button "Sign message on device".

<img width="384" alt="Bildschirmfoto 2021-01-31 um 17 12 22" src="https://user-images.githubusercontent.com/43323145/106390207-8979fb00-63e7-11eb-83ad-735b20822e06.png">

**Comment by ben-kaufman** [comment]
Thanks, already fixed in v1.1.0 with #879
