### ISSUE TITLE
Transaction/UTXO table corrupted?

### ISSUE THREAD

**Issue by instagibbs** [cryptoadvance/specter-desktop#935]
Upgraded specter, and now I have no amount/time/confirmation on my transaction page, and I have no transaction details(throws error `Failed to load transaction details...` and banner error `ReferenceError: numberWithCommas is not defined`), and UTXO page missing with similar things missing.

Simple restarts of process doesn't help, I expect I scrambled the internal db somehow.

Just filing this in case there are some clues to help figure out why.

**Comment by instagibbs** [comment]
Actually this seems to be the case for a freshly synced wallet as well.

Specter version 1.1.0, Linux. Let me know if you need any more details.

**Comment by ben-kaufman** [comment]
I've got one more report about that from @moneymanolis on Linux with the packaged app but not on Mac when both connected to the same node (right @moneymanolis?). Couldn't yet reproduce this, but I will try to check. Are you using Specter from the browser? If so which one? (and if you can check the console and screenshot if it has any errors that'll be really helpful too)

**Comment by instagibbs** [comment]
Using from Chrome. 

```
105(index):1570 Uncaught ReferenceError: numberWithCommas is not defined
    at HTMLElement.connectedCallback ((index):1570)
    at fetchTxItems ((index):2407)
```

good call though, desktop app works fine, so I'll run with that for now

**Comment by moneymanolis** [comment]
> I've got one more report about that from @moneymanolis on Linux with the packaged app but not on Mac when both connected to the same node (right @moneymanolis?). Couldn't yet reproduce this, but I will try to check. Are you using Specter from the browser? If so which one? (and if you can check the console and screenshot if it has any errors that'll be really helpful too)

Yes, except, I used the python module on the Mac. Will check whether the same issue exists with the Linux App Image, too, and also report the browser error.

**Comment by moneymanolis** [comment]
Issue doesn't exist anymore after restart.

**Comment by ben-kaufman** [comment]
@instagibbs can you please check if that works after restart for you too? Sounds like some caching issue where it haven't cleared the cache after update.

**Comment by instagibbs** [comment]
>Simple restarts of process doesn't help, I expect I scrambled the internal db somehow.

I wrote this, but it seems to be working, at least off the appimage then through the browser.

**Comment by k9ert** [comment]
Closing.
