### ISSUE TITLE
ERROR: signing multi sig transaction 2 of 3

### ISSUE THREAD

**Issue by imacfan** [cryptoadvance/specter-desktop#946]
Created a 2 of 3 multi-sig few months back:

Current setup of same quorum:
1. Ledger v- 1.4.7
2. ColdCold 1 - v  3.2.2
3. Coldcard 2 - v 3.2.2

Now, after upgrading to ColdCard firmware to v 3.2.2, I am trying to sign a transaction using Specter.
Ledger signs just fine.

But when I sign using ColdCard I get "**Failure Invalid PSBT multisig.py:953**"
Seems I am stuck. Please suggest how can this be resolved

Thanks!

**Comment by ben-kaufman** [comment]
Hi, yes it seems that after the recent ColdCard firmware update, you have to delete the multisig from the ColdCard and import it again from Specter into the coldcard (from the wallet settings tab)

**Comment by imacfan** [comment]
I imported it fresh.
Now I tried to delete it. it says: 
>>>>"Yikes"<<<<<
"menu.py:198  activate"
menu.py:53 activte
multisig.py 1212 MS_wallet_dele
multisig.py:426 delete
AssertionError:

**Comment by ben-kaufman** [comment]
On the coldcard itself? When exactly? When you're deleting, reimporting, or trying to sign?

**Comment by imacfan** [comment]
> On the coldcard itself? When exactly? When you're deleting, reimporting, or trying to sign?

ok.. seems I had couple of existing MultiSigs which were 3of5 but had same ColdCard as part of quorum. Had to delete them all.. and re-import 2of3. Now, it has signed the transaction. Still in middle of it, will report once transaction is fully signed

**Comment by imacfan** [comment]
Transaction signed!
