### ISSUE TITLE
Data Backup does not restore Bitcoin Core hot wallet.

### ISSUE THREAD

**Issue by LaserHodl** [cryptoadvance/specter-desktop#948]
Using a brand new Specter `1.0.0` (via getumbrel.com), I loaded the data backup files from my other node and it appeared to successfully restore all devices and wallet onto the node.

When attempting a simple roundtrip transaction using a 2-of-3, I discovered the following issue.

When signing with the newly restored hot wallet, the following error was surfaced:

```
Failed to sign PSBT: Request error: Requested wallet does not exist or is not loaded.
```

My best guess is that Specter restores the metadata, but does not check for hot wallets within, and therefor does not reinitialize those wallets inside Bitcoin Core. This causes the wallet to feel restored, but otherwords be orphaned.

**Comment by LaserHodl** [comment]
I was able to verify that on the new node that no hot wallet has been initiated in Bitcoin Core.

The original node has a `specter..._hotstorage` folder in the Bitcoin Core data dir containing the initialized hot wallet, including the `wallet.dat` binary file. The new node does not have this folder at all.

This makes me think that my guess above was correct:

> Specter restores the metadata, but does not check for hot wallets within, and therefor does not reinitialize those wallets inside Bitcoin Core. This causes the wallet to feel restored, but otherwords be orphaned.

**Comment by LaserHodl** [comment]
As a short-term workaround for other Umbrel users that run into this: you can manually backup/restore the `wallet.dat` file.

### Steps 1/2 - Backup `wallet.dat`

Start by SSHing into your node and storing the Specter UID into the bash variable `$SPECTERUID` - 

```
$ ssh umbrel@umbrel-local # password: moneyprintergobrrr
$ SPECTERUID="$(cat /home/umbrel/umbrel/app-data/specter-desktop/data/config.json | jq .uid -r)"
$ echo $SPECTERUID
c1c7fc19e553fb0e
```

Now find the correlating hot wallet inside the Bitcoin data directory:

``` 
$ HOTWALLETDIR="~/umbrel/umbrel/bitcoin/specter`echo $SPECTERUID`_hotstorage/umbrel_hot_wallet"
$ cd $HOTWALLETDIR
$ ls -l
total 4800
drwx------ 2 umbrel umbrel    4096 Feb 15 21:11 database
-rw------- 1 umbrel umbrel       0 Feb 15 21:11 db.log
-rw------- 1 umbrel umbrel 4911104 Feb 15 21:13 wallet.dat

$ echo $(pwd)/wallet.dat
echo $(pwd)/wallet.da
/home/umbrel/umbrel/bitcoin/specterc1c7fc19e553fb0e_hotstorage/umbrel_hot_wallet/wallet.dat
```

Copy the full `wallet.dat` path into your clipboard, switch back to your daily driver latpop, and copy the `wallet.dat` to your home folder using `rsync` - 

```
$ exit
$ rsync umbrel@umbrel-local:/home/umbrel/umbrel/bitcoin/specterc1c7fc19e553fb0e_hotstorage/umbrel_hot_wallet/wallet.dat .
``

Now store the `wallet.dat` somewhere safe.


### Steps 2/2 - Restore `wallet.dat`

Start by copying the `wallet.dat` to the home directory of your new node using `rsync`, and then SSHing in - 

```
$ rsync ~/wallet.dat umbrel@umbrel2-local:/home/umbrel/wallet.dat
$ ssh umbrel@umbrel2-local # password: moneyprintergobrrr
```

Now move the `wallet.dat` into the correct location using the local Specter UID `

```
$ SPECTERUID="$(cat /home/umbrel/umbrel/app-data/specter-desktop/data/config.json | jq .uid -r)"
$ HOTWALLETDIR="~/umbrel/umbrel/bitcoin/specter`echo $SPECTERUID`_hotstorage/umbrel_hot_wallet"
$ mkdir -p $HOTWALLETDIR
$ mv ~/wallet.dat $HOTWALLETDIR
```

Cheers.

**Comment by ben-kaufman** [comment]
Hi, yeah that's a good point. We should definitely add better support for backup of the hot wallet. We don't save the mnemonic itself, so you might need to go to the wallet screen, click add more keys, and re-add the keys with the mnemonic, but we should at least create a new wallet on the bitcoin core when you restore a hot wallet type.

**Comment by kdmukai** [comment]
@ben-kaufman would it make sense to make the mnemonic entry screen part of the import flow if there's a hot wallet involved? Maybe also revisit whatever language is around the wallet backups to make it clear that if you don't have your mnemonic phrase, this "backup" you're about to download ain't doing sh*t.

If this all makes sense, assign this one to me.

**Comment by ben-kaufman** [comment]
Thanks, yes that'd definitely make sense. The whole backup and flow of the hot wallet functionality could be improved quite a bit, so would be great if you could do that.

**Comment by kdmukai** [comment]
Initial progress. @ben-kaufman @k9ert any concerns with updating the wallet backup `account_map` format to include device type and label?

https://github.com/kdmukai/specter-desktop/blob/2417839b824c41434bf5b53eb26f897ca71e421c/src/cryptoadvance/specter/wallet.py#L926

```
{
  "label": "Keith_s test _Hot_!",
  "blockheight": 0,
  "descriptor": "...",
  "devices": [
    {
      "type": "bitcoincore",
      "label": "My Core Hot Wallet"
    },
    {
      "type": "keepkey",
      "label": "Muh KeepKey"
    }
  ]
}
```
_There's a note in `helpers.py` that Account Map is used by "Fully Noded, Gordian, Sparrow etc." My changes are adding to the json but not changing any of the existing fields. Hopefully that doesn't impact their portability to those projects. If we don't want to mess with `account_map`, then I'll have to create a third backup option: Account Map, Electrum, and Specter-Desktop native._

With that in place I'm able to identify and label unknown devices to a new Specter instance. The next step will be to require mnemonic entry if you're importing a hot wallet.

<img width="841" alt="Screen Shot 2021-03-07 at 9 26 08 AM" src="https://user-images.githubusercontent.com/934746/110245396-80210880-7f28-11eb-9963-a52db9a75dc4.png">

**Comment by ben-kaufman** [comment]
As long as the extra fields to the format are optional I don't see any issues adding them. Not sure if you should require adding the mnemonic for the hot wallet import, I think just warning that otherwise it'll be watch only is fine.

**Comment by LaserHodl** [comment]
@ben-kaufman you suggesting they import, and then, seeing the warning, go into settings and add the mnemonic, passphrase, and derivation paths by hand?

**Comment by LaserHodl** [comment]
I just attempted to "add keys" to a fresh import of a hot wallet and can confirm that it fails:

> Wallet does not exist.

I'm guessing the add keys code path assumes a wallet has been initialized in Core *already*.

That'll have to be addressed to achieve the feature we are describing here.

**Comment by LaserHodl** [comment]
Ok, verified again. 

The *only* way to restore an existing hot wallet from fresh Specter that loaded `specter-backup.zip` as a means of restoring is to manually hand copy the `wallet.dat` into the correct path, as I detailed in the workaround above. 

Hope that's useful.

**Comment by LaserHodl** [comment]
Update: I did a test transaction using the `wallet.dat` I hand-restored. While it was able to sign the transaction Ok, it failed to broadcast with the following error:

```
Server failed to broadcast transactions! Failed to broadcast transaction: transaction is invalid missing-inputs
```

Looks like this workaround is not actually sufficient, and a more direct line of support is needed within Specter.

Thank you guys for all your help here.

**Comment by LaserHodl** [comment]
Ok, figured it out. It looks like manually copying over the `wallet.dat` does not set the 25th word. Here's what I had to do:

1. Manually copy over the `wallet.dat`
2. Click on the wallet and then click "Add more keys"
3. Add the 24 word mnemonic, and then in Advanced add the 25th word

This makes sense, the `wallet.dat` is not supposed to contain the 25th word. It does make me think that Specter will have to account for this (and is today holding that in memory somewhere). Users need to be able to properly restore this detail of the wallet as well when importing `specter-backup.zip` into a brand new Specter Desktop.

**Comment by LaserHodl** [comment]
Nice - I was able to restore the hot wallet without the `wallet.dat` using the mnemonic, 25th word, and encryption password directly. Here's what you do.

# Restoring Hot Wallet in Specter, by hand

After SSHing into the machine, grab the Specter session ID and create a new hot wallet at the correct path, entering the encryption password (for the `wallet.dat` that will be created) when prompted:

```bash
$ SPECTERUID="$(cat /home/umbrel/umbrel/app-data/specter-desktop/data/config.json | jq .uid -r)"

$ /home/umbrel/umbrel/bin/bitcoin-cli createwallet "specter`echo $SPECTERUID`_hotstorage/umbrel_hot_wallet/" false false "`read -p 'Enter encryption password: ' pw; echo $pw`" false false true
```

Now that the hot wallet has been initiated, select it in the Web UI and:

1. Hit the gear (configure) in the top right.
2. Select "Add more keys."
3. Input the 24 word mnemonic.
4. Select "Advanced" and input the 25th word and encryption password.

I have tested that this works end-to-end on a multisig vault.

Cheers.

**Comment by ben-kaufman** [comment]
Thanks for posting @LaserHodl! Anyway, I believe now @kdmukai is working on it, and so hopefully it'll be resolvd with the next version.
