### ISSUE TITLE
unexpected token in json at position 0

### ISSUE THREAD

**Issue by gongyj0948** [cryptoadvance/specter-desktop#949]
When I tried to connect to a hardware wallet with Specter, It returns a red banner on the top, said "unexpected token in JSON at position 0".  Is this a common issue?

**Comment by ben-kaufman** [comment]
Hi, which Specter version? Did you modify anything on the HWI Bridge settings?

**Comment by gongyj0948** [comment]
I'm currently using specter 1.1.0, both on the umbrel node and desktop. It happened in the prior version as well. 

it looks like this on desktop
![Screen Shot 2021-02-16 at 2 22 11 PM](https://user-images.githubusercontent.com/29460794/108111200-5e87dc00-7062-11eb-8c71-21ac170e95ce.png)

it looks like this on the web app 

![Screen Shot 2021-02-16 at 2 24 26 PM](https://user-images.githubusercontent.com/29460794/108111448-ae66a300-7062-11eb-87bb-b2fa80391498.png)

**Comment by ben-kaufman** [comment]
On the desktop, did you configure the connection to be to Umbrel like shown here?  https://github.com/cryptoadvance/specter-desktop/blob/master/docs/tor.md#configure-specter-desktop-for-remote-instance

**Comment by gongyj0948** [comment]
Yes, but still not working.

**Comment by ben-kaufman** [comment]
Ok I see, In the top field where it says "hwi bridge url" you should put http://127.0.0.1:25441/hwi/api
Can you try that please?

**Comment by gongyj0948** [comment]
Hi Ben,
I tried to put http://127.0.0.1:25441/hwi/api, as well as umbrel.local:25441/hwi/api and localhost:25441/hwi/api, oddly I run into something like this.
![Screen Shot 2021-02-19 at 10 35 16 AM](https://user-images.githubusercontent.com/29460794/108525528-2bca2780-729e-11eb-9c7c-7d0f12bdb113.png)

I'm not tech-savvy. I've been testing Specter for months but always run into issues. Here's what I make up of this. I think you guys did a wonderful job putting this together, just have some thoughts I want to share. 
> after install from both umbrel and desktop, you have at least 5 PLACES to configure.  JSON-RPC configuration on the web app, on desktop, HWI bridge on the web app, on desktop, and preferences in a separated place. 

> Each of them has many different combinations of configurations, make it hard to finger where is the issue located. 

> Both web app and desktop version have identical UI. I'm still confusing which is the bridge, which is the server. 

I'm going to leave this project for a while, will check back sometime in the future.  Hope you guys keep up the excellent work on pioneering the multisig.

**Comment by ben-kaufman** [comment]
Ok thanks, sorry for the issues...
