### ISSUE TITLE
Addresses: Used column is incorrect. New Receiving Address is actually a used address. On Pruned Node

### ISSUE THREAD

**Issue by statusquont** [cryptoadvance/specter-desktop#962]
I installed a new local instance of prunednode.today along with Specter. I added a device and a corresponding wallet.

When viewing the Addresses tab, some of the addresses are showing Used=No, which is incorrect. The balance for the affected addresses is 0, which is correct. But they are actually used addresses, the sats have just been sent to other UTXO's resulting in a zero balance.

A related issue is that on the Receive tab, it's giving me a new Address at index 44 which seems to be the highest index after the last known address with a balance > 0. Unfortunately, that address was also used before (and as mentioned above has since been zero'd out). So in this particular case, the correct next (unused) address is actually at index 45.

I'm not sure if this is expected behavior when using a pruned node or not? But if it's possible to fix this, it seems like an important one to help prevent people from reusing addresses on accident.

**Comment by ben-kaufman** [comment]
Hi, I believe this should be resolved with v1.2.2, can you please recheck and update?

**Comment by statusquont** [comment]
I tried to recreate this issue again by pointing my local Specter back at my local pruned node (instead of the remote full node), and re-added the device and the wallet, and rescanned. But now no transactions are showing at all and the next receive index is back to zero. 

Just to make sure, I compared and verified that it's using the same exact device key and wallet xpub as the remote Specter instance that comes with myNode (that one IS showing all transactions correctly)

So I can't really confirm it has been resolved in 1.2.2 since I have no transactions showing anymore for some reason. Wish I could recreate it again for you to verify. I'll poke around some more to see if maybe I missed something.

**Comment by statusquont** [comment]
Following-up, I do actually see this is resolved on the full-node instance. The Used column is correct now, and the next Receive address is at the correct index. 

Sorry, I think I may be confusing myself by running 2 Specter instances and trying to consolidate into 1. I'll stop now! :)
