### ISSUE TITLE
White background (no styles) after linux upgrade

### ISSUE THREAD

**Issue by alevchuk** [cryptoadvance/specter-desktop#966]
Specter-1.1.2.AppImage
Specter-1.1.0.AppImage

Specter was working fine on Linux Fedora 33 (Workstation Edition)

i think there was an OS update and now Specter UI is in this broken state: white background (see screenshot), no buttons, Unknown  version
![Screenshot from 2021-02-20 09-03-57](https://user-images.githubusercontent.com/64738/108603339-4236b880-735c-11eb-831c-731e5d0c30f0.png)

**Comment by alevchuk** [comment]
On CLI it just prints: `child process exited with code 255`

Also, saw the same simptom on Mac (let restart resolved it). On Linux restarting does not help.

**Comment by ben-kaufman** [comment]
Hi @alevchuk, I would assume the reasons for the mac and Linux were different. If restart solved it on Mac, it is most likely an old Specter process was still running, holding the port from the new process to use, which would make it fail and exit. Maybe that was the case?

On Fedora, I would guess the OS may not be compatible, as I don't recall anyone trying Specter on there.
Can you try running the `specterd` and share the logs? This should show the full logs for why it fails to run.
https://github.com/cryptoadvance/specter-desktop/releases/download/v1.2.2/specterd-v1.2.2-x86_64-linux-gnu.zip

**Comment by alevchuk** [comment]
yep, old process already running
```
  File "socketserver.py", line 466, in server_bind
OSError: [Errno 98] Address already in use
```

killed it and everything works now

i wonder why the UI doesn't just connect to the old process

**Comment by ben-kaufman** [comment]
Strange, it should... at least it does when I tested on Mac. I'll try to recheck though

**Comment by alevchuk** [comment]
Sounds good. I’d be happy if the UI just said what connection error it is
(rejected or timeout).

**Comment by k9ert** [comment]
Looks like this is solved. The white-background is solved as well? Please don't hesitate to reopen if it's not.
