### ISSUE TITLE
Testnet / broke Specter trying to delete multisig wallet while Rescanning Testnet chain

### ISSUE THREAD

**Issue by daprovik** [cryptoadvance/specter-desktop#977]
"Server error!
Exception: Request error: Requested wallet does not exist or is not loaded"

I was unable to get back to main page on Specter. Tried rebooting Specter, same error. Had to uninstall and reinstall.

**Comment by ben-kaufman** [comment]
Strange, that should never block specter like that... which version?

**Comment by daprovik** [comment]
> Strange, that should never block specter like that... which version?

v.1.2.2

**Comment by ben-kaufman** [comment]
Ok thanks, very strange, I tried switching networks, making wallets on each etc. but could not replicate the issue. Which OS are you on?

**Comment by daprovik** [comment]
Microsoft Windows 10 Home

**Comment by k9ert** [comment]
If this is still reproducible, please reopen the issue. We did a lot in that area of the code so hopefully it's gone.
