### ISSUE TITLE
Use-case: Remote Full Node. Local Pruned Node. Toggle Specter to use different node as needed

### ISSUE THREAD

**Issue by statusquont** [cryptoadvance/specter-desktop#978]
I'm not sure if this is a really dumb idea on my part, or just something that hasn't been considered as a use case and therefore isn't (currently) possible.

I have myNodeBTC as the primary node with full 373GB blockchain download. 
On my laptop I have Specter that connects to the remote node and is configured as the HWI interface.

I was trying to setup a pruned node on my laptop to use when away from the primary node.

My thought was that while I'm home I would just use the primary node and everything works as expected. But then, as a backup and when away from the home base for a while, I could just point Specter to the local pruned node instead. I wouldn't need to bring my RaspberryPi with me, I'd maintain all transaction history, all labels, etc.

The problem that I discovered is that the wallets I added to Specter when connected to myNode are not found in Core on the local pruned node.

```
Error Details:
Request error: Wallet file verification failed. Failed to load database path
```

Is there a better way to accomplish this? So that I have just one Specter app that I use to manage all my transactions and labels and wallets. But I can toggle it (by just changing node connection settings) to use whichever Core node is ideal in a given situation.

It's not like I'm adding a bunch of wallets all of the time. So this should be for the most part a one time setup, and then perhaps an occasional update.

**Comment by ben-kaufman** [comment]
Hi, since Specter uses the Bitcoin Core for indexing wallet transactions, this might be a bit problematic to have... Maybe we could have that later in the future if we allow backup of transactions full data necessary for import, then you won't need rescan and create the wallet on another node will be fast. But until we have that I think this is a bit problematic

**Comment by statusquont** [comment]
Do you think it would be possible (in theory) to backup my wallet files from Core on myNode, and then copy them over to the pruned Core node on my laptop?

That way both nodes would have the same wallets and then I could toggle Specter to point at one or the other based on the situation?

Or is it more complex than I'm making it out to be?

**Comment by ben-kaufman** [comment]
It's a bit more complicated. You need to know how to export and import the wallet in such a case. That's doable, but without automation needs lot of CLI...

**Comment by statusquont** [comment]
Noted. OK, punt on this for now. Thanks for thinking about it.
