### ISSUE TITLE
wallets: cannot create/import multisig wallet w/ Umbrel

### ISSUE THREAD

**Issue by weisjohn** [cryptoadvance/specter-desktop#980]
*Steps to Reproduce:*

Create a Wallet:
0. Connect Specter to Umbrel via Tor
1. Add devices
2. click "Add New Wallet"
3. Select multisig, choose devices, choose name
4. Observe error: `ERROR: Failed to create wallet...`

<img width="368" alt="Screen Shot 2021-02-22 at 5 36 27 PM" src="https://user-images.githubusercontent.com/12034/108779240-92687300-7534-11eb-8268-1612e6c36adc.png">

Import a Wallet:
0. Connect Specter to Umbrel via Tor
1. Add devices.
2. click "Add New Wallet"
3. Click "Import from wallet software"
4. Select .json file exported from other Specter
5. Observe error: `Failed to create wallet: RpcError('Request error: Compiled without sqlite support (required for descriptor wallets)')`

<img width="991" alt="Screen Shot 2021-02-22 at 5 32 54 PM" src="https://user-images.githubusercontent.com/12034/108778909-1c640c00-7534-11eb-85a8-2fc42a38b9a5.png">

Info:
Version: Specter Desktop v1.2.2
Bitcoin Core: v0.21.0

**Comment by CmdrPenetrant** [comment]
I am having the same issue creating a multisig wallet while connected to an umbrel node. 

**ERROR: Failed to create wallet...**

**Comment by ben-kaufman** [comment]
Hi, thanks for reporting, seems like Umberl has Bitcoin Core v0.21 without the SQLite Specter is expecting it to have.
I will check with Umbrel team if they could add that, and will make sure that in case it is not there, Specter will default to not use the feature like with older Bitcoin Core versions.

**Comment by nolim1t** [comment]
This will be resolved as soon as the referenced issue is closed,

**Comment by nolim1t** [comment]
Hi,

This has been resolved as of `v0.21.0+build21` (see https://hub.docker.com/r/lncm/bitcoind/tags) 

You can fetch it from `v0.21.0-arm64v8-build21` if you are using arm64

**Comment by nolim1t** [comment]
I've added a PR on the umbrel repository to update its bitcoind with the latest compiled in switches.

I don't use your setup however, I use a similar setup where I create a new wallet from an existing container and it seems to be working.

**Comment by weisjohn** [comment]
Confirmed this is ready to mark as fixed in both a Specter Desktop GUI connected to an Umbrel via Tor and as a Umbrel-delivered Specter app

**Comment by ben-kaufman** [comment]
Closing as fixed in the latest Umbrel release.
