### ISSUE TITLE
Rescan and UTXO rescan not working.

### ISSUE THREAD

**Issue by miguelmiramar** [cryptoadvance/specter-desktop#986]
Hello,

when I create a new device and a wallet and I select to rescan in order to get the transactions and funds.
- With UTXO it takes several hours, and in my experience never completes.
- Complete rescan takes as well long time, what makes sense in this case but funds ends up being 0 and no history
of transactions shows up.

I know for sure that there are funds.
I would appreciate if someone could help me.

**_Linux desktop with Bitcoincore 0.21(non prune mode) + Specter 1.2.2,_** 

Regards.

**Comment by ben-kaufman** [comment]
Hi, UTXO rescan should not take more than 3 minutes. If it does there must be something wrong with that. Are you sure the addresses in the addresses tab correspond to those you have funds on? (sometimes people pick the wrong address type)

**Comment by miguelmiramar** [comment]
Thanks ben-kaufman,

in fact in the address tab lists around 200 addresses and none of them are the ones that has for example the receiving funds activity(the ones showed in the hardware wallet native application). At this point I'm lost, why the wallet in Specter is not showing the address that has had activity in the hardware wallet?

The wallet in Specter is created as a segwit single key as the hadware wallet as well.

Do I'm missing something obvious?

Regards.

**Comment by ben-kaufman** [comment]
Hi, if the address type is correct (both on the native hww app and specter addresses start with bc1), another possible option could be that you used an account on the hardware wallet which is not the default. Which hww is this? Can you try to check which derivation path is used there?

**Comment by miguelmiramar** [comment]
hello, the addresses are indeed in different formats, in specter starts bc1 but in the hww (ledger nano s) starts with a number.

not sure yet which type of derivation path is using the hww, is there a way to select different derivation path formats in Specter? Beause to me sounds that that is the issue as you mentioned.

Regards.

**Comment by miguelmiramar** [comment]
If i am correct the derivation path type in the hww is "49'/0'/0'/0/8" .

Regards.

**Comment by miguelmiramar** [comment]
I think I isolated the problem(besides my initial confusion of derivation paths), it happens when creating a new wallet, even if I don't select the rescan option(or selecting only UTXO) does a complete scan that takes around several hours  and in my case never ended successfully(error message of wallet not found), although the wallet is created(but showing zero funds). After that and doing a rescan for only UTXO works and shows the correct funds and history.

Thanks and regards.
