### ISSUE TITLE
"Speed up!" RBF feature usable on non-change txs. 

### ISSUE THREAD

**Issue by s-5Q2X8mgeGR** [cryptoadvance/specter-desktop#988]
While the current "Speed up!" RBF feature is great, it'd be neat to have ability to RBF tx's that do not have any change. 

The user can already do this today with Specter UI, but must manually "hack" around it. Example: 
- Create PSBT for transaction, feerate 10. 
- Save PSBT. 
- Delete the transaction inside Specter. 
- Recreate the exact same transaction (or, at a minimum, with at least 1 of the same inputs), with higher feerate (optionally, do this as many times as one wants) 
- Sign and broadcast the first transaction with the lowest feerate
- Later on, if the tx with lowest feerate hasn't been confirmed and the user wishes to bump the tx, sign & broadcast the identical (or, again, at a minimum reusing 1 of the inputs) tx with a higher feerate

The flow for this could be much easier for a user. Update the "Speed up!" flow to support tx's with non-change by showing the following if no change: 
- If only 1 output: "Text explaining the extra sats for the fees will be taken from the output" 
- If several outputs: "Select which output to take the extra sats for the fees."

Support for adding more/specific inputs to this new, RBF-ing tx seems unnecessary.

**Comment by ben-kaufman** [comment]
Fixed with #998 - now full edit of the transaction is also possible.
