### ISSUE TITLE
BitBox02: Adding devices shows "The user aborted the request" error

### ISSUE THREAD

**Issue by jstrnbrg** [cryptoadvance/specter-desktop#999]
When trying to add a BitBox02 as a device I get a "The user aborted the request" error. However, afterwards I can still continue and successfully add the BitBox02 as a signing device.

Steps to reproduce:
1. Launch Specter, BitBox01 plugged in, click "Add new device", select BitBox02
2. Enter device name
3. Click "Get via USB"
4. BitBox02 asks for device password, I enter and confirm it, BitBox02 unlocks
==> At that point Specter shows "The user aborted the request" error

However, I can then click "Get via USB" again, which successfully extracts the wallet xPUBs and clicking "Add device" successfully saves it. So the issue just is this intermediate error that Specter shows for some reason.

Details:
- Mac OS 10.15.6 
- Specter 1.2.2
- BitBox02 firmware v9.4

**Comment by Agnus-Castus** [comment]
I have the same error message. But while trying to sign a transaction. 
Maybe it is because i have Imported the wallet from an other specter installation. 

Specter: v1.3.0-pre3

**Comment by ben-kaufman** [comment]
I saw that happening once while the BitBox02 was awaiting for password. Was the Bitcoin unlocked/ locked/ or prompting password while the issue occurred?

**Comment by Agnus-Castus** [comment]
It was unlocked.

**Comment by btchodler** [comment]
Same problem here.

When I'm connecting the bitbox, I can unlock the device with my password, but short after that the error message "The user aborted the request" is up there. Also when I want to sign a tx or verify an address 

Specter v1.3.0
BitBox02 firmware: v9.5.0

**Comment by benma** [comment]
@ben-kaufman the HWI enumerate call prompts an unlock on the device since https://github.com/bitcoin-core/HWI/pull/404, and the error only happens in this condition. Is this a problem for Specter? Ideally the call just waits until the BitBox02 is ready and `enumerate()` returns.

The abort error is a HTML DOM error: `DOMException: The operation was aborted`, not an error explicitly thrown by the BitBox or Specter. Looks like an async error? 

If the device is already unlocked, it proceeds without an error.

**Comment by benma** [comment]
The issue seems to be coming from a 5s timeout in HWI enumerate()

```
async enumerate(passphrase="", useTimeout){
        return await this.fetch("enumerate", {
            passphrase
        }, (useTimeout ? 5000 : 0));
    }
```

Since some wallets using HWI rely on the fingerprint being available in the enumerate() call, the BitBox02 prompts an unlock during enumerate(), which takes longer than 5s.

**Comment by My1** [comment]
@benma but it apparently throws this even if unlocked for some reason.

**Comment by kayth1** [comment]
Works well with this version: https://github.com/ben-kaufman/specter-desktop/releases/tag/v1.3.2-dev

**Comment by k9ert** [comment]
https://github.com/cryptoadvance/specter-desktop/pull/1090 has been merged. So we only need a release in order to close this.
A more recent pre-release is available here:
https://github.com/cryptoadvance/specter-desktop/releases/tag/v1.3.1-pre2

**Comment by jstrnbrg** [comment]
@k9ert Unfortunately can't test as [no Mac OS version available ](https://github.com/cryptoadvance/specter-desktop/releases/tag/v1.3.1-pre2)

**Comment by benma** [comment]
I don't get the user abort error any more, but also the pairing code doesn't show up for me now.

**Comment by ben-kaufman** [comment]
Hi @jstrnbrg , sorry I forgot to upload the macOS version, just did and it's there now.

**Comment by jstrnbrg** [comment]
Tested, not getting the error message with this pre-release version anymore. Thanks!

**Comment by cercatrova21** [comment]
Tested, everything is working now with BitBox02.

version 1.3.1

**Comment by k9ert** [comment]
Great, as we have now released the fix, i'll close. Please reopen if this is still an issue somehow.
